Repository apple/swift-nio, pull requests merged in 2018-04, with the labels that each got.

#264 Don't re-arm timerfd each epoll_wait
  Sources/NIO/Selector.swift
  Tests/NIOTests/EventLoopTest+XCTest.swift
  Tests/NIOTests/EventLoopTest.swift
Labels: patch-version-bump-only

#259 Fixed a few minor typos and some force unwraps
  Sources/NIO/Bootstrap.swift
  Sources/NIO/ByteBuffer-core.swift
  Sources/NIO/Codec.swift
  Sources/NIO/CompositeError.swift
  Sources/NIO/EventLoop.swift
  Sources/NIO/EventLoopFuture.swift
  Sources/NIO/FileRegion.swift
  Sources/NIO/LinuxCPUSet.swift
  Sources/NIO/MarkedCircularBuffer.swift
  Sources/NIO/PendingDatagramWritesManager.swift
  Sources/NIO/Selector.swift
  Sources/NIO/Thread.swift
  Sources/NIOChatServer/main.swift
  Sources/NIOHTTP1Server/main.swift
  Sources/NIOWebSocketServer/main.swift
Labels: patch-version-bump-only

#263 alloc counter test: better recursive malloc
  IntegrationTests/tests_04_performance/test_01_allocation_counts_for_http1.sh
  IntegrationTests/tests_04_performance/test_01_resources/template/HookedFunctions/Sources/HookedFunctions/src/hooked-functions.c
Labels: patch-version-bump-only

#261 improve integration tests verbose mode
  IntegrationTests/run-tests.sh
Labels: patch-version-bump-only

#272 Don't accidentally fail leak detection tests.
  Tests/NIOTests/ChannelTests.swift
Labels: patch-version-bump-only

#267 use @convention(c) for malloc/realloc/free in ByteBuffer
  Sources/NIO/ByteBuffer-core.swift
  Tests/NIOTests/ByteBufferTest.swift
  Tests/NIOTests/CodecTest.swift
Labels: patch-version-bump-only

#275 Just store NIOAny in the pending array.
  Sources/NIOHTTP1/HTTPDecoder.swift
Labels: patch-version-bump-only

#280 Wait for test cleanup.
  Tests/NIOTests/EchoServerClientTest.swift
Labels: patch-version-bump-only

#269 Add EventLoopFuture fold function
  Sources/NIO/EventLoopFuture.swift
  Tests/NIOTests/EventLoopFutureTest+XCTest.swift
  Tests/NIOTests/EventLoopFutureTest.swift
Labels: needs-minor-version-bump

#284 Remove unsafe cross-thread communication from lifecycle test
  Tests/NIOTests/ChannelTests.swift
Labels: patch-version-bump-only

#290 Make Scheduled's constructor public.
  Sources/NIO/EventLoop.swift
Labels: needs-minor-version-bump

#268 Add support for automatic HTTP error reporting.
  IntegrationTests/tests_01_http/test_12_headers_too_large.sh
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOHTTP1/HTTPPipelineSetup.swift
  Sources/NIOHTTP1/HTTPServerProtocolErrorHandler.swift
  Sources/NIOHTTP1Server/main.swift
  Tests/LinuxMain.swift
  Tests/NIOHTTP1Tests/HTTPServerProtocolErrorHandlerTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPServerProtocolErrorHandlerTest.swift
  Tests/NIOHTTP1Tests/HTTPUpgradeTests.swift
Labels: needs-minor-version-bump

#289 Don't race waiting for a nil reference.
  Tests/NIOTests/ChannelTests.swift
Labels: patch-version-bump-only

#266 [TO BE DISCUSSED] make generic/closure ByteBuffer methods inlineable
  Sources/NIO/ByteBuffer-aux.swift
  Sources/NIO/ByteBuffer-core.swift
Labels: discussion, patch-version-bump-only

#240 Add EventLoopFuture reduction primitives
  Sources/NIO/EventLoopFuture.swift
  Tests/NIOTests/EventLoopFutureTest+XCTest.swift
  Tests/NIOTests/EventLoopFutureTest.swift
Labels: needs-minor-version-bump

#295 Enable our one disabled integration test.
  IntegrationTests/tests_01_http/test_14_strict_mode_assertion.sh
Labels: patch-version-bump-only

#296 Stop calling read(...) if we were not able to fill the whole buffer.
  Sources/NIO/SocketChannel.swift
  Tests/NIOTests/ChannelTests.swift
Labels: patch-version-bump-only

#297 TailChannelHandler does not need to implement _ChannelOutboundHandler
  Sources/NIO/ChannelPipeline.swift
Labels: patch-version-bump-only

#260 workaround ab (ApacheBench) in keep-alive mode
  IntegrationTests/tests_01_http/test_18_close_with_no_keepalive.sh
  IntegrationTests/tests_01_http/test_22_http_1.0_keep_alive.sh
  Sources/NIOHTTP1Server/main.swift
Labels: patch-version-bump-only

#301 Restore unary initializer for HTTPHeaders
  Sources/NIOHTTP1/HTTPTypes.swift
Labels: patch-version-bump-only

#310 Don't call to user code before reconciling Channel state.
  Sources/NIO/BaseSocketChannel.swift
  Tests/NIOTests/SocketChannelTest+XCTest.swift
  Tests/NIOTests/SocketChannelTest.swift
Labels: patch-version-bump-only

#298 Fix up HTTP message framing edge cases.
  Sources/NIOHTTP1/HTTPDecoder.swift
  Tests/LinuxMain.swift
  Tests/NIOHTTP1Tests/HTTPDecoderLengthTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPDecoderLengthTest.swift
Labels: patch-version-bump-only

#312 Remove PendingWriteStateManager.chunks
  Sources/NIO/PendingWritesManager.swift
Labels: patch-version-bump-only

#286 eagerly process input EOF/connection resets (fixes #277)
  IntegrationTests/tests_01_http/defines.sh
  IntegrationTests/tests_01_http/test_19_connection_drop_while_waiting_for_response_uds.sh
  IntegrationTests/tests_01_http/test_20_connection_drop_while_waiting_for_response_tcp.sh
  IntegrationTests/tests_01_http/test_21_connection_reset_tcp.sh
  Sources/NIO/BaseSocket.swift
  Sources/NIO/BaseSocketChannel.swift
  Sources/NIO/Bootstrap.swift
  Sources/NIO/Channel.swift
  Sources/NIO/EventLoop.swift
  Sources/NIO/Linux.swift
  Sources/NIO/Selector.swift
  Sources/NIO/SocketChannel.swift
  Sources/NIOHTTP1Server/main.swift
  Tests/NIOTests/AcceptBackoffHandlerTest.swift
  Tests/NIOTests/ChannelTests+XCTest.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/EventLoopTest.swift
  Tests/NIOTests/SelectorTest.swift
  Tests/NIOTests/SocketChannelTest.swift
Labels: patch-version-bump-only

#318 add 'info' mode for integration tests
  IntegrationTests/run-single-test.sh
  IntegrationTests/run-tests.sh
  IntegrationTests/test_functions.sh
  IntegrationTests/tests_04_performance/test_01_allocation_counts_for_http1.sh
Labels: patch-version-bump-only

#316 reduce allocations & test we don't regress
  IntegrationTests/tests_04_performance/test_01_allocation_counts_for_http1.sh
  IntegrationTests/tests_04_performance/test_01_resources/template/Sources/SwiftBootstrap/SwiftMain.swift
  Sources/NIO/ByteBuffer-int.swift
Labels: patch-version-bump-only

#321 Allow ChannelCore implementors to unwrap NIOAny.
  Sources/NIO/Channel.swift
  Sources/NIO/NIOAny.swift
  Tests/LinuxMain.swift
  Tests/NIOTests/CustomChannelTests+XCTest.swift
  Tests/NIOTests/CustomChannelTests.swift
Labels: needs-minor-version-bump

#329 Synchronous connection failures must close channels.
  Sources/NIO/BaseSocketChannel.swift
  Tests/NIOTests/ChannelTests+XCTest.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/SocketChannelTest.swift
Labels: patch-version-bump-only

#256 non-blocking versions of file open/stat
  Sources/NIO/BlockingIOThreadPool.swift
  Sources/NIO/NonBlockingFileIO.swift
  Sources/NIOHTTP1Server/main.swift
  Tests/NIOTests/NonBlockingFileIOTest+XCTest.swift
  Tests/NIOTests/NonBlockingFileIOTest.swift
Labels: needs-minor-version-bump

#324 Make all members of HTTP{Request|Response}Head mutable.
  Sources/NIOHTTP1/HTTPTypes.swift
Labels: needs-minor-version-bump

#334 Make sure we create correct socket family.
  Tests/NIOTests/EventLoopTest.swift
Labels: patch-version-bump-only

#285 Support for initializing off the system file descriptors
  Sources/NIO/BaseSocketChannel.swift
  Sources/NIO/Bootstrap.swift
  Sources/NIO/Channel.swift
  Sources/NIO/DeadChannel.swift
  Sources/NIO/Embedded.swift
  Sources/NIO/ServerSocket.swift
  Sources/NIO/Socket.swift
  Sources/NIO/SocketChannel.swift
  Tests/NIOTests/CustomChannelTests.swift
  Tests/NIOTests/SocketChannelTest+XCTest.swift
  Tests/NIOTests/SocketChannelTest.swift
Labels: needs-minor-version-bump

#330 Ensure correct ordering of promise notification when connect is still…
  Sources/NIO/BaseSocketChannel.swift
  Tests/NIOTests/SocketChannelTest+XCTest.swift
  Tests/NIOTests/SocketChannelTest.swift
Labels: patch-version-bump-only

#339 better descriptions for HTTP{Response,Request}Head and HTTPVersion
  Sources/NIOHTTP1/HTTPTypes.swift
Labels: patch-version-bump-only

#340 Add WebSocketUpgrader to channel config
  Sources/NIOWebSocketServer/main.swift
Labels: patch-version-bump-only

#344 canonical form for headers: fast path for 0 headers
  Sources/NIOHTTP1/HTTPTypes.swift
Labels: patch-version-bump-only

#338 Prevent spurious test failure in testShuttingDownFailsRegistration
  Tests/NIOTests/EventLoopTest.swift
Labels: patch-version-bump-only

#346 Ensure localAddress / remoteAddress are still accessible in channelIn…
  Sources/NIO/BaseSocketChannel.swift
  Sources/NIO/ChannelPipeline.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/SocketChannelTest+XCTest.swift
  Tests/NIOTests/SocketChannelTest.swift
Labels: patch-version-bump-only

#348 fix recursive channelReads in pipelining handler
  Sources/NIOHTTP1/HTTPServerPipelineHandler.swift
  Tests/NIOHTTP1Tests/HTTPServerPipelineHandlerTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPServerPipelineHandlerTest.swift
Labels: patch-version-bump-only

#351 shrink HTTP{Request,Response}Head by CoW boxing them
  Sources/NIOHTTP1/HTTPTypes.swift
  Tests/NIOHTTP1Tests/HTTPTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPTest.swift
Labels: patch-version-bump-only

#356 Fix warning during compiling tests.
  Tests/NIOTests/SelectorTest.swift
Labels: patch-version-bump-only

#365 Remove unnecessary if let usage in writeAndFlush
  Sources/NIO/ChannelPipeline.swift
Labels: patch-version-bump-only

#363 Not cause a CoW when calling ByteBuffer.discardReadBytes() while it wa…
  Sources/NIO/ByteBuffer-core.swift
  Tests/NIOTests/ByteBufferTest+XCTest.swift
  Tests/NIOTests/ByteBufferTest.swift
Labels: patch-version-bump-only

#366 add other memory allocation functions
  dev/malloc-aggregation.d
Labels: patch-version-bump-only

#368 Avoid delivering websocket frames twice on EOF.
  Sources/NIOWebSocket/WebSocketFrameDecoder.swift
  Tests/NIOWebSocketTests/WebSocketFrameDecoderTest+XCTest.swift
  Tests/NIOWebSocketTests/WebSocketFrameDecoderTest.swift
Labels: patch-version-bump-only

#367 make BB.debugDescription print xxd -r -p compatible format
  Sources/NIO/ByteBuffer-core.swift
  Tests/NIOTests/ByteBufferTest+XCTest.swift
  Tests/NIOTests/ByteBufferTest.swift
Labels: patch-version-bump-only
