Repository apple/swift-nio, pull requests merged in 2018-05, with the labels that each got.

#357 extend docker setup to multiple version of ubuntu and swift
  README.md
  docker/Dockerfile
  docker/docker-compose.1404.403.yaml
  docker/docker-compose.1404.41.yaml
  docker/docker-compose.1604.403.yaml
  docker/docker-compose.1604.41.yaml
  docker/docker-compose.yaml
Labels: patch-version-bump-only

#373 Add UnsafeEmbeddedAtomic and use it.
  IntegrationTests/tests_04_performance/test_01_allocation_counts_for_http1.sh
  IntegrationTests/tests_04_performance/test_01_resources/template/Sources/SwiftBootstrap/SwiftMain.swift
  Sources/NIO/EventLoopFuture.swift
  Sources/NIOConcurrencyHelpers/atomics.swift
Labels: needs-minor-version-bump

#371 Refactored UInt32 and UInt64 methods nextPowerOf2
  Sources/NIO/ByteBuffer-int.swift
Labels: patch-version-bump-only

#375 expose sanity script through docker compose
  docker/docker-compose.yaml
Labels: patch-version-bump-only

#376 Track Future allocations in CI.
  docker/docker-compose.1404.41.yaml
  docker/docker-compose.1604.41.yaml
Labels: patch-version-bump-only

#251 Add http-parser license and authors
  Sources/CNIOHTTPParser/AUTHORS
  Sources/CNIOHTTPParser/LICENSE-MIT
  Sources/CNIOHTTPParser/update_and_patch_http_parser.sh
Labels: patch-version-bump-only

#374 fix some Swift 4.2 warnings
  Sources/NIO/ByteBuffer-core.swift
  Sources/NIO/CircularBuffer.swift
  Sources/NIO/MarkedCircularBuffer.swift
  Sources/NIOPriorityQueue/Heap.swift
  Sources/NIOPriorityQueue/PriorityQueue.swift
  Tests/NIOTests/ByteBufferTest+XCTest.swift
  Tests/NIOTests/ByteBufferTest.swift
Labels: patch-version-bump-only

#379 fix one more register/bind race
  Tests/NIOTests/SocketChannelTest.swift
Labels: patch-version-bump-only

#384 fix Swift 4.2 compile error
  Sources/NIO/PriorityQueue.swift
Labels: patch-version-bump-only

#387 don't crash if close is called when close fails
  Sources/NIO/BaseSocket.swift
  Sources/NIO/BaseSocketChannel.swift
  Tests/NIOTests/ChannelTests+XCTest.swift
  Tests/NIOTests/ChannelTests.swift
Labels: patch-version-bump-only

#389 fix event loop hop between registration and activation of accepted ch…
  IntegrationTests/tests_01_http/test_23_repeated_reqs_with_half_closure.sh
  Sources/NIO/BaseSocketChannel.swift
  Sources/NIO/SocketChannel.swift
  Tests/NIOTests/EventLoopTest.swift
Labels: patch-version-bump-only

#383 Add support for compiling and running NIO on Raspberry Pi 32-bit
  Sources/NIO/ByteBuffer-core.swift
  Sources/NIO/ChannelHandlers.swift
  Sources/NIO/EventLoop.swift
  Sources/NIO/Selector.swift
  Sources/NIOConcurrencyHelpers/atomics.swift
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOHTTP1Server/main.swift
Labels: patch-version-bump-only

#388 implement lazy selector registration
  Sources/NIO/BaseSocketChannel.swift
  Sources/NIO/EventLoop.swift
  Tests/NIOTests/ChannelTests+XCTest.swift
  Tests/NIOTests/ChannelTests.swift
Labels: patch-version-bump-only

#390 lower allocation limits
  docker/docker-compose.1404.41.yaml
  docker/docker-compose.1604.41.yaml
Labels: patch-version-bump-only

#391 let the stdlib enumerate the Sequence elements
  Sources/NIO/ByteBuffer-core.swift
  Tests/NIOTests/ByteBufferTest.swift
Labels: patch-version-bump-only

#395 Make hopTo(eventLoop:) public.
  Sources/NIO/EventLoopFuture.swift
Labels: 🔼 needs-minor-version-bump

#299 Reuse detected keepalive of http_parser as long as possible
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOHTTP1/HTTPTypes.swift
  Tests/NIOHTTP1Tests/HTTPHeadersTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPHeadersTest.swift
Labels: patch-version-bump-only

#407 fewer warnings for 4.2 in 4.2 mode
  Sources/NIO/ByteBuffer-core.swift
Labels: patch-version-bump-only

#399 Channel quiescing support
  Sources/NIO/Bootstrap.swift
  Sources/NIO/Channel.swift
  Sources/NIO/CircularBuffer.swift
  Sources/NIOHTTP1/HTTPServerPipelineHandler.swift
  Sources/NIOHTTP1/HTTPTypes.swift
  Tests/LinuxMain.swift
  Tests/NIOHTTP1Tests/HTTPServerPipelineHandlerTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPServerPipelineHandlerTest.swift
  Tests/NIOTests/CircularBufferTests+XCTest.swift
  Tests/NIOTests/CircularBufferTests.swift
  Tests/NIOTests/IntegerTypesTest+XCTest.swift
  Tests/NIOTests/IntegerTypesTest.swift
Labels: 🔼 needs-minor-version-bump

#408 Make removeHandlers public.
  Sources/NIO/Channel.swift
  Sources/NIO/ChannelPipeline.swift
Labels: 🔼 needs-minor-version-bump

#416 Link to swift-nio-http2.
  README.md
Labels: patch-version-bump-only

#423 explain why typealias is complicated
  Sources/NIO/CircularBuffer.swift
  Sources/NIO/MarkedCircularBuffer.swift
Labels: patch-version-bump-only

#415 retain Channel from ChannelPipeline until destroyed
  Sources/NIO/ChannelPipeline.swift
Labels: patch-version-bump-only

#413 don't just drop Channels on the floor if registration fails
  Sources/NIO/BaseSocketChannel.swift
  Sources/NIO/Bootstrap.swift
  Tests/NIOTests/ChannelTests+XCTest.swift
  Tests/NIOTests/ChannelTests.swift
  docker/docker-compose.1404.41.yaml
  docker/docker-compose.1604.41.yaml
Labels: patch-version-bump-only

#427 Ensure HTTPDecoder will not run into re-entrance issues and correctly…
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOHTTP1/HTTPUpgradeHandler.swift
  Tests/NIOHTTP1Tests/HTTPUpgradeTests+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPUpgradeTests.swift
Labels: patch-version-bump-only

#431 Correctly account for writes of all datagrams.
  Sources/CNIODarwin/shim.c
  Tests/NIOTests/DatagramChannelTests+XCTest.swift
  Tests/NIOTests/DatagramChannelTests.swift
Labels: patch-version-bump-only

#437 Don't provide promises when we don't care about results.
  Sources/NIO/Bootstrap.swift
Labels: patch-version-bump-only

#438 Change initializer to public for HTTPRequestDecoder
  Sources/NIOHTTP1/HTTPDecoder.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
Labels: 🔼 needs-minor-version-bump

#441 raise Ubuntu 16.04 allocation limit by 1 allocation
  docker/docker-compose.1604.41.yaml
Labels: patch-version-bump-only

#442 fix testUpgradeWithUpgradePayloadInlineWithRequestWorks race
  Tests/NIOHTTP1Tests/HTTPUpgradeTests.swift
Labels: patch-version-bump-only

#443 Rename numThreads to numberOfThreads parameter.
  IntegrationTests/tests_04_performance/test_01_resources/template/Sources/SwiftBootstrap/SwiftMain.swift
  Sources/NIO/Bootstrap.swift
  Sources/NIO/EventLoop.swift
  Sources/NIOChatClient/main.swift
  Sources/NIOChatServer/main.swift
  Sources/NIOEchoClient/main.swift
  Sources/NIOEchoServer/main.swift
  Sources/NIOHTTP1Server/main.swift
  Sources/NIOPerformanceTester/main.swift
  Sources/NIOWebSocketServer/main.swift
  Tests/NIOHTTP1Tests/HTTPServerClientTest.swift
  Tests/NIOHTTP1Tests/HTTPUpgradeTests.swift
  Tests/NIOTests/AcceptBackoffHandlerTest.swift
  Tests/NIOTests/BootstrapTest.swift
  Tests/NIOTests/ChannelNotificationTest.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/DatagramChannelTests.swift
  Tests/NIOTests/EchoServerClientTest.swift
  Tests/NIOTests/EventLoopFutureTest.swift
  Tests/NIOTests/EventLoopTest.swift
  Tests/NIOTests/FileRegionTest.swift
  Tests/NIOTests/GetAddrInfoResolverTest.swift
  Tests/NIOTests/IdleStateHandlerTest.swift
  Tests/NIOTests/NonBlockingFileIOTest.swift
  Tests/NIOTests/SelectorTest.swift
  Tests/NIOTests/SocketChannelTest.swift
Labels: hygiene, 🔼 needs-minor-version-bump

#445 make _UInt24 and _UInt56 printable
  Sources/NIO/IntegerTypes.swift
  Tests/NIOTests/IntegerTypesTest+XCTest.swift
  Tests/NIOTests/IntegerTypesTest.swift
Labels: 🔼 needs-minor-version-bump

#454 ByteBuffer: simplify ensureAvailableCapacity
  Sources/NIO/ByteBuffer-core.swift
  Tests/NIOTests/ByteBufferTest+XCTest.swift
  Tests/NIOTests/ByteBufferTest.swift
Labels: patch-version-bump-only

#411 introduce ByteBufferView
  Sources/NIO/ByteBuffer-views.swift
  Tests/NIOTests/ByteBufferTest+XCTest.swift
  Tests/NIOTests/ByteBufferTest.swift
Labels: 🔼 needs-minor-version-bump

#453 Widen assertion on readEOF.
  Sources/NIO/BaseSocketChannel.swift
Labels: patch-version-bump-only
