Repository apple/swift-nio, pull requests merged in 2018-03, with the labels that each got.

#56 Update README to consistently use plurals
  README.md
Labels: patch-version-bump-only

#53 Fix typo for Bootstrap’s resolver parameter
  Sources/NIO/Bootstrap.swift
Labels: patch-version-bump-only

#49 Create PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: patch-version-bump-only

#58 fix: typos in README
  README.md
Labels: patch-version-bump-only

#57 add NIOFoundationCompat lib to package products
  Package.swift
Labels: patch-version-bump-only

#45 Fix flaky upgrade test.
  Tests/NIOHTTP1Tests/HTTPUpgradeTests.swift
Labels: patch-version-bump-only

#65 Add ChannelDuplexHandler protocol
  Sources/NIO/ChannelHandlers.swift
  Sources/NIO/TypeAssistedChannelHandler.swift
  Sources/NIOHTTP1/HTTPResponseCompressor.swift
  Tests/NIOTests/TypeAssistedChannelHandlerTests.swift
Labels: needs-minor-version-bump

#63 fix EventLoop-hopping thens (#51)
  Sources/NIO/EventLoopFuture.swift
  Tests/NIOTests/EventLoopFutureTest+XCTest.swift
  Tests/NIOTests/EventLoopFutureTest.swift
Labels: patch-version-bump-only

#70 Update test generation script to append newline character.
  scripts/generate_linux_tests.rb
Labels: patch-version-bump-only

#69 typo: ChannnelDuplexHandler should be ChannelDuplexHandler
  Sources/NIO/ChannelHandlers.swift
  Sources/NIO/TypeAssistedChannelHandler.swift
  Sources/NIOHTTP1/HTTPResponseCompressor.swift
  Tests/NIOTests/TypeAssistedChannelHandlerTests.swift
Labels: needs-minor-version-bump

#47 Support enumerating network interfaces.
  Sources/NIO/BaseSocket.swift
  Sources/NIO/Interfaces.swift
  Sources/NIO/System.swift
  Sources/NIO/Utilities.swift
  Tests/NIOTests/UtilitiesTest+XCTest.swift
  Tests/NIOTests/UtilitiesTest.swift
Labels: needs-minor-version-bump

#79 base variadic ChannelPipeline.addHandlers off of an array accepting version
  Sources/NIO/ChannelPipeline.swift
  Sources/NIOHTTP1/HTTPDecoder.swift
Labels: needs-minor-version-bump

#92 Correctly validate delayed upgrade.
  Tests/NIOHTTP1Tests/HTTPUpgradeTests.swift
Labels: patch-version-bump-only

#91 Rename PriorityQueue's T to Element, and iterator to Iterator
  Sources/NIOPriorityQueue/PriorityQueue.swift
Labels: needs-minor-version-bump

#98 Correctly update cached addresses for accepted Channels.
  Sources/NIO/SocketChannel.swift
  Tests/NIOTests/ChannelTests+XCTest.swift
  Tests/NIOTests/ChannelTests.swift
Labels: bug, patch-version-bump-only

#82 write/set(integer:) should like read/getInteger have an option as: ar…
  Sources/NIO/ByteBuffer-int.swift
  Tests/NIOTests/ByteBufferTest+XCTest.swift
  Tests/NIOTests/ByteBufferTest.swift
Labels: needs-minor-version-bump

#76 [Cleanup] Small code clean up in HTTP1Server.
  Sources/NIOHTTP1Server/main.swift
Labels: patch-version-bump-only

#66 Some random Swiftyness
  Sources/NIOChatServer/main.swift
Labels: patch-version-bump-only

#90 docker cleanup
  README.md
  docker/Dockerfile.xenial
  docker/docker-compose.yaml
Labels: needs-minor-version-bump

#84 make ChannelPipeline.init public
  Sources/NIO/ChannelPipeline.swift
Labels: needs-minor-version-bump

#99 Use one Box to store both, the local and remote address.
  Sources/NIO/SocketChannel.swift
Labels: patch-version-bump-only

#103 Prefer to use ctx.remoteAddress over ctx.channel.remoteAddress
  Sources/NIOChatServer/main.swift
Labels: patch-version-bump-only

#102 Declare ThreadSpecificVariable public
  Sources/NIO/Thread.swift
Labels: needs-minor-version-bump

#104 Ensure channels don't get stuck completely unregistered.
  Sources/NIO/SocketChannel.swift
  Tests/NIOTests/ChannelTests+XCTest.swift
  Tests/NIOTests/ChannelTests.swift
Labels: patch-version-bump-only

#113 Make clear generate_linux_tests must be run
  CONTRIBUTING.md
Labels: patch-version-bump-only

#117 Add READMEs for the various sample applications
  Sources/NIOChatClient/README.md
  Sources/NIOChatServer/README.md
  Sources/NIOEchoClient/README.md
  Sources/NIOEchoServer/README.md
  Sources/NIOHTTP1Server/README.md
Labels: patch-version-bump-only

#118 Ensure that handlers added with first:true are in proper order.
  Sources/NIO/ChannelPipeline.swift
  Tests/NIOTests/ChannelPipelineTest+XCTest.swift
  Tests/NIOTests/ChannelPipelineTest.swift
Labels: patch-version-bump-only

#123 make isOpen a computed property
  Sources/NIO/BaseSocket.swift
  Sources/NIO/FileHandle.swift
  Tests/NIOTests/BaseObjectsTest.swift
  Tests/NIOTests/ChannelPipelineTest.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/TestUtils.swift
Labels: patch-version-bump-only

#129 Revert "make isOpen a computed property"
  Sources/NIO/BaseSocket.swift
  Sources/NIO/FileHandle.swift
  Tests/NIOTests/BaseObjectsTest.swift
  Tests/NIOTests/ChannelPipelineTest.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/TestUtils.swift
Labels: patch-version-bump-only

#115 Our sample HTTP server should respect HTTP keep-alive.
  IntegrationTests/tests_01_http/test_18_close_with_no_keepalive.sh
  Sources/NIOHTTP1Server/main.swift
Labels: patch-version-bump-only

#133 properly destroy pthread mutex and cond
  Sources/NIOConcurrencyHelpers/lock.swift
Labels: patch-version-bump-only

#135 add license headers for shell scripts
  IntegrationTests/plugin_echo.sh
  IntegrationTests/plugin_junit_xml.sh
  IntegrationTests/run-single-test.sh
  IntegrationTests/run-tests.sh
  IntegrationTests/test_functions.sh
  IntegrationTests/tests_01_http/SKIP_test_12_headers_too_large.sh
  IntegrationTests/tests_01_http/SKIP_test_13_http_pipelining.sh
  IntegrationTests/tests_01_http/SKIP_test_14_strict_mode_assertion.sh
  IntegrationTests/tests_01_http/defines.sh
  IntegrationTests/tests_01_http/test_01_get_file.sh
  IntegrationTests/tests_01_http/test_02_get_random_bytes.sh
  IntegrationTests/tests_01_http/test_03_post_random_bytes.sh
  IntegrationTests/tests_01_http/test_04_keep_alive_works.sh
  IntegrationTests/tests_01_http/test_05_repeated_reqs_work.sh
  IntegrationTests/tests_01_http/test_06_http_1.0.sh
  IntegrationTests/tests_01_http/test_07_headers_work.sh
  IntegrationTests/tests_01_http/test_08_survive_signals.sh
  IntegrationTests/tests_01_http/test_09_curl_happy_with_trailers.sh
  IntegrationTests/tests_01_http/test_10_connection_drop_in_body_ok.sh
  IntegrationTests/tests_01_http/test_11_res_body_streaming.sh
  IntegrationTests/tests_01_http/test_15_post_in_chunked_encoding.sh
  IntegrationTests/tests_01_http/test_16_tcp_client_ip.sh
  IntegrationTests/tests_01_http/test_17_serve_massive_sparse_file.sh
  IntegrationTests/tests_01_http/test_18_close_with_no_keepalive.sh
  IntegrationTests/tests_02_syscall_wrappers/defines.sh
  IntegrationTests/tests_02_syscall_wrappers/test_01_syscall_wrapper_fast.sh
  IntegrationTests/tests_02_syscall_wrappers/test_02_blacklisted_errnos.sh
  IntegrationTests/tests_03_linker_things/defines.sh
  IntegrationTests/tests_03_linker_things/test_01_check_we_do_not_link_Foundation.sh
  Sources/CNIOHTTPParser/update_and_patch_http_parser.sh
  scripts/generate_docs.sh
  scripts/integration_tests.sh
Labels: patch-version-bump-only

#131 improve license header checking
  scripts/sanity.sh
Labels: patch-version-bump-only

#94 Nest HTTPHeaderIterator inside HTTPHeader, un-erase makeIterator()
  Sources/NIOHTTP1/HTTPTypes.swift
Labels: patch-version-bump-only

#124 use accept4 and SOCK_NONBLOCK on Linux
  Sources/CNIOLinux/include/c_nio_linux.h
  Sources/CNIOLinux/shim.c
  Sources/NIO/BaseSocket.swift
  Sources/NIO/Linux.swift
  Sources/NIO/ServerSocket.swift
  Sources/NIO/Socket.swift
  Sources/NIO/SocketChannel.swift
Labels: patch-version-bump-only

#128 Add support for adding handlers at arbitrary pipeline locations
  Sources/NIO/ChannelPipeline.swift
  Tests/NIOTests/ChannelPipelineTest+XCTest.swift
  Tests/NIOTests/ChannelPipelineTest.swift
Labels: needs-minor-version-bump

#125 Don't close ServerSocketChannel when accept fails with ECONNABORTED /…
  Sources/NIO/ServerSocket.swift
  Sources/NIO/SocketChannel.swift
  Tests/NIOTests/SocketChannelTest+XCTest.swift
  Tests/NIOTests/SocketChannelTest.swift
Labels: patch-version-bump-only

#62 Add channel handler for server side pipelining.
  IntegrationTests/tests_01_http/test_13_http_pipelining.sh
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOHTTP1/HTTPServerPipelineHandler.swift
  Sources/NIOHTTP1Server/main.swift
  Tests/LinuxMain.swift
  Tests/NIOHTTP1Tests/HTTPServerPipelineHandlerTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPServerPipelineHandlerTest.swift
Labels: needs-minor-version-bump

#109 Add initial websocket codec.
  NOTICE.txt
  Package.swift
  Sources/CNIOSHA1/c_nio_sha1.c
  Sources/CNIOSHA1/include/c_nio_sha1.h
  Sources/CNIOSHA1/update_and_patch_sha1.sh
  Sources/NIOWebSocket/Base64.swift
  Sources/NIOWebSocket/SHA1.swift
  Sources/NIOWebSocket/WebSocketErrorCodes.swift
  Sources/NIOWebSocket/WebSocketFrame.swift
  Sources/NIOWebSocket/WebSocketFrameDecoder.swift
  Sources/NIOWebSocket/WebSocketFrameEncoder.swift
  Sources/NIOWebSocket/WebSocketOpcode.swift
  Sources/NIOWebSocket/WebSocketUpgrader.swift
  Sources/NIOWebSocketServer/main.swift
  Tests/LinuxMain.swift
  Tests/NIOWebSocketTests/Base64Test+XCTest.swift
  Tests/NIOWebSocketTests/Base64Test.swift
  Tests/NIOWebSocketTests/EndToEndTests+XCTest.swift
  Tests/NIOWebSocketTests/EndToEndTests.swift
  Tests/NIOWebSocketTests/WebSocketFrameDecoderTest+XCTest.swift
  Tests/NIOWebSocketTests/WebSocketFrameDecoderTest.swift
  Tests/NIOWebSocketTests/WebSocketFrameEncoderTest+XCTest.swift
  Tests/NIOWebSocketTests/WebSocketFrameEncoderTest.swift
  scripts/sanity.sh
Labels: needs-minor-version-bump

#154 don't use _Nonnull for clang 3.6 (#147)
  Sources/CNIOAtomics/include/c-atomics.h
Labels: patch-version-bump-only

#155 Add support for getting a handler of a given type.
  Sources/NIO/ChannelPipeline.swift
  Tests/NIOTests/ChannelPipelineTest+XCTest.swift
  Tests/NIOTests/ChannelPipelineTest.swift
Labels: needs-minor-version-bump

#144 Let Upgrade handler remove other HTTP handlers.
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOHTTP1/HTTPUpgradeHandler.swift
  Tests/NIOHTTP1Tests/HTTPUpgradeTests.swift
Labels: needs-minor-version-bump

#120 Add support to obtain the current EventLoop
  Sources/NIO/EventLoop.swift
  Tests/NIOTests/EventLoopTest+XCTest.swift
  Tests/NIOTests/EventLoopTest.swift
Labels: needs-minor-version-bump

#159 Add new, better helper method for configuring HTTP servers.
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOHTTP1/HTTPPipelineSetup.swift
  Sources/NIOHTTP1Server/main.swift
  Sources/NIOWebSocketServer/main.swift
  Tests/NIOHTTP1Tests/HTTPServerClientTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPServerClientTest.swift
  Tests/NIOHTTP1Tests/HTTPUpgradeTests+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPUpgradeTests.swift
  Tests/NIOWebSocketTests/EndToEndTests.swift
Labels: needs-minor-version-bump

#164 channelRead should never be triggered if autoRead is false.
  Sources/NIO/Selector.swift
  Sources/NIO/SocketChannel.swift
  Tests/NIOTests/ChannelTests+XCTest.swift
  Tests/NIOTests/ChannelTests.swift
Labels: patch-version-bump-only

#169 Add missing docs to EventLoopPromise and EventLoopFuture
  Sources/NIO/EventLoopFuture.swift
Labels: patch-version-bump-only

#126 Add handler that provides some backoff for accepts if these failed be…
  Sources/NIO/ChannelHandlers.swift
  Tests/LinuxMain.swift
  Tests/NIOTests/AcceptBackoffHandlerTest+XCTest.swift
  Tests/NIOTests/AcceptBackoffHandlerTest.swift
  Tests/NIOTests/SocketChannelTest.swift
  Tests/NIOTests/TestUtils.swift
Labels: needs-minor-version-bump

#167 port numbers sin[6]_port are in network byte order
  Sources/NIO/SocketAddresses.swift
  Tests/NIOTests/EchoServerClientTest+XCTest.swift
  Tests/NIOTests/EchoServerClientTest.swift
  Tests/NIOTests/HappyEyeballsTest.swift
  Tests/NIOTests/SocketAddressTest.swift
Labels: patch-version-bump-only

#171 Don't close DatagramChannel when recvfrom fails with ECONNREFUSED / E…
  Sources/NIO/Socket.swift
  Sources/NIO/SocketChannel.swift
  Tests/NIOTests/DatagramChannelTests+XCTest.swift
  Tests/NIOTests/DatagramChannelTests.swift
Labels: patch-version-bump-only

#174 Also verify that fireErrorCaught(...) was called for "recoverable" er…
  Tests/NIOTests/SocketChannelTest.swift
Labels: patch-version-bump-only

#177 Support hopping event loops with EventLoopFuture
  Sources/NIO/Bootstrap.swift
  Sources/NIO/EventLoopFuture.swift
  Tests/NIOTests/EventLoopFutureTest+XCTest.swift
  Tests/NIOTests/EventLoopFutureTest.swift
Labels: needs-minor-version-bump

#158 Make HTTPResponseStatus factory method public
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOHTTP1/HTTPTypes.swift
Labels: needs-minor-version-bump

#179 Suppress compiler warnings in release mode.
  Sources/NIO/EventLoopFuture.swift
  Sources/NIO/Utilities.swift
Labels: patch-version-bump-only

#188 Fix possible endless loop when shutdown SelectableEventLoop
  Sources/NIO/EventLoop.swift
  Tests/NIOTests/EventLoopTest+XCTest.swift
  Tests/NIOTests/EventLoopTest.swift
Labels: patch-version-bump-only

#190 Correctly shutdown EventLoopGroup during tests.
  Tests/NIOTests/EventLoopFutureTest.swift
Labels: patch-version-bump-only

#189 Make EmbeddedEventLoop behave more like the regular one.
  Sources/NIO/Embedded.swift
  Tests/NIOTests/EmbeddedEventLoopTest+XCTest.swift
  Tests/NIOTests/EmbeddedEventLoopTest.swift
Labels: patch-version-bump-only

#181 Ensure we always update the promise before calling fire* methods and …
  Sources/NIO/SocketChannel.swift
  Tests/LinuxMain.swift
  Tests/NIOTests/ChannelNotificationTest+XCTest.swift
  Tests/NIOTests/ChannelNotificationTest.swift
  Tests/NIOTests/EchoServerClientTest.swift
Labels: patch-version-bump-only

#194 Correctly expose backward-compat shim for header iterator.
  Sources/NIOHTTP1/HTTPTypes.swift
Labels: patch-version-bump-only

#192 Re-use same ContiguousArray for tasks copy operations.
  Sources/NIO/EventLoop.swift
Labels: patch-version-bump-only

#193 Fix warnings in tests.
  Tests/NIOTests/ChannelNotificationTest.swift
  Tests/NIOTests/EmbeddedEventLoopTest.swift
Labels: patch-version-bump-only

#142 Add docs to explain inbound/outbound
  Sources/NIO/ChannelHandler.swift
Labels: patch-version-bump-only

#195 Ensure fireChannelActive(...) is always called before fireChannelRead(...)
  Sources/NIO/SocketChannel.swift
  Tests/NIOTests/ChannelNotificationTest+XCTest.swift
  Tests/NIOTests/ChannelNotificationTest.swift
Labels: patch-version-bump-only

#197 Better docs for threading guarantees of futures
  Sources/NIO/EventLoopFuture.swift
Labels: patch-version-bump-only

#200 Ensure we wait for the promise to succeed.
  Tests/NIOTests/ChannelNotificationTest.swift
Labels: patch-version-bump-only

#191 HappyEyeballs should tolerate uncancellable tasks.
  Sources/NIO/HappyEyeballs.swift
  Tests/NIOTests/HappyEyeballsTest+XCTest.swift
  Tests/NIOTests/HappyEyeballsTest.swift
Labels: patch-version-bump-only

#205 If connectSocket() completes directly we need to mark channel as active
  Sources/NIO/SocketChannel.swift
  Tests/NIOTests/SocketChannelTest+XCTest.swift
  Tests/NIOTests/SocketChannelTest.swift
Labels: patch-version-bump-only

#210 Guard against the case when a Selectable is deregistered during Selec…
  Sources/NIO/Linux.swift
  Sources/NIO/Selector.swift
  Tests/LinuxMain.swift
  Tests/NIOTests/SelectorTest+XCTest.swift
  Tests/NIOTests/SelectorTest.swift
Labels: patch-version-bump-only

#207 Add some docs to note on which message types a bootstrapped Channel w…
  Sources/NIO/Bootstrap.swift
Labels: patch-version-bump-only

#218 Remove unsafe assert on Linux
  Sources/NIO/Selector.swift
  Tests/NIOTests/SelectorTest+XCTest.swift
  Tests/NIOTests/SelectorTest.swift
Labels: patch-version-bump-only

#219 Changed EventLoop{Future,Promise}<()> occurances to EventLoop{Future,Promise}<Void> (#211)
  Sources/NIO/Bootstrap.swift
  Sources/NIO/DeadChannel.swift
  Sources/NIO/NonBlockingFileIO.swift
  Sources/NIO/PendingWritesManager.swift
  Sources/NIOHTTP1/HTTPEncoder.swift
  Sources/NIOHTTP1Server/main.swift
  Tests/NIOHTTP1Tests/HTTPTest.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/DatagramChannelTests.swift
  Tests/NIOTests/EchoServerClientTest.swift
  Tests/NIOTests/EventLoopFutureTest.swift
  Tests/NIOTests/FileRegionTest.swift
  Tests/NIOTests/PendingDatagramWritesManagerTests.swift
Labels: patch-version-bump-only

#217 Not retry calling close(...) when EINTR is reported.
  Sources/NIO/System.swift
Labels: patch-version-bump-only

#223 Annotate global constants that refer to C functions with @convention(c)
  Sources/NIO/System.swift
Labels: patch-version-bump-only

#225 Dissallow access and removal of Head and Tail ChannelHandlers
  Sources/NIO/ChannelPipeline.swift
  Tests/NIOTests/ChannelPipelineTest+XCTest.swift
  Tests/NIOTests/ChannelPipelineTest.swift
Labels: bug, patch-version-bump-only

#226 Correctly fail EventLoopFuture for unsupported operations on ServerSo…
  Sources/NIO/SocketChannel.swift
  Tests/NIOTests/SocketChannelTest+XCTest.swift
  Tests/NIOTests/SocketChannelTest.swift
Labels: patch-version-bump-only

#229 Fixes build issue on 4.1
  Sources/NIO/System.swift
  Sources/NIOWebSocketServer/main.swift
Labels: patch-version-bump-only

#231 Take closeFuture into account when closing EventLoopGroup
  Sources/NIO/Selector.swift
  Tests/NIOTests/EventLoopTest+XCTest.swift
  Tests/NIOTests/EventLoopTest.swift
Labels: patch-version-bump-only

#235 Remove one pair of lock() / unlock() during EventLoop run.
  Sources/NIO/EventLoop.swift
Labels: patch-version-bump-only

#234 Remove busywork left over from flush promises.
  Sources/NIO/BaseSocketChannel.swift
  Sources/NIO/PendingDatagramWritesManager.swift
  Sources/NIO/SocketChannel.swift
Labels: patch-version-bump-only

#241 Update EmbeddedChannel state before notify connect and close promise.
  Sources/NIO/Embedded.swift
  Tests/NIOTests/EmbeddedChannelTest+XCTest.swift
  Tests/NIOTests/EmbeddedChannelTest.swift
Labels: patch-version-bump-only

#245 bring PriorityQueue/Heap implementations inline
  Package.swift
  Sources/NIO/Embedded.swift
  Sources/NIO/EventLoop.swift
  Sources/NIO/Heap.swift
  Sources/NIO/PriorityQueue.swift
  Tests/LinuxMain.swift
  Tests/NIOTests/HeapTests+XCTest.swift
  Tests/NIOTests/HeapTests.swift
  Tests/NIOTests/PriorityQueueTests+XCTest.swift
  Tests/NIOTests/PriorityQueueTests.swift
Labels: patch-version-bump-only

#236 Refactors generate_linux_tests script
  scripts/generate_linux_tests.rb
Labels: patch-version-bump-only

#221 Set hints for getaddrinfo to restrict results
  Sources/NIO/Bootstrap.swift
  Sources/NIO/GetaddrinfoResolver.swift
  Sources/NIO/System.swift
  Tests/LinuxMain.swift
  Tests/NIOTests/GetAddrInfoResolverTest+XCTest.swift
  Tests/NIOTests/GetAddrInfoResolverTest.swift
Labels: patch-version-bump-only

#252 add an allocation counting integration test
  IntegrationTests/run-tests.sh
  IntegrationTests/test_functions.sh
  IntegrationTests/tests_04_performance/defines.sh
  IntegrationTests/tests_04_performance/test_01_allocation_counts_for_http1.sh
  IntegrationTests/tests_04_performance/test_01_resources/README.md
  IntegrationTests/tests_04_performance/test_01_resources/template/AtomicCounter/Package.swift
  IntegrationTests/tests_04_performance/test_01_resources/template/AtomicCounter/Sources/AtomicCounter/include/atomic-counter.h
  IntegrationTests/tests_04_performance/test_01_resources/template/AtomicCounter/Sources/AtomicCounter/src/atomic-counter.c
  IntegrationTests/tests_04_performance/test_01_resources/template/HookedFree/Package.swift
  IntegrationTests/tests_04_performance/test_01_resources/template/HookedFree/Sources/HookedFree/include/hooked-free.h
  IntegrationTests/tests_04_performance/test_01_resources/template/HookedFree/Sources/HookedFree/src/hooked-free.c
  IntegrationTests/tests_04_performance/test_01_resources/template/Package.swift
  IntegrationTests/tests_04_performance/test_01_resources/template/Sources/SwiftBootstrap/SwiftMain.swift
  IntegrationTests/tests_04_performance/test_01_resources/template/Sources/bootstrap/main.c
Labels: patch-version-bump-only

#255 add a simple leak detector
  IntegrationTests/run-tests.sh
  IntegrationTests/tests_04_performance/test_01_allocation_counts_for_http1.sh
  IntegrationTests/tests_04_performance/test_01_resources/README.md
  IntegrationTests/tests_04_performance/test_01_resources/template/AtomicCounter/Sources/AtomicCounter/include/atomic-counter.h
  IntegrationTests/tests_04_performance/test_01_resources/template/AtomicCounter/Sources/AtomicCounter/src/atomic-counter.c
  IntegrationTests/tests_04_performance/test_01_resources/template/HookedFree/Sources/HookedFree/src/hooked-free.c
  IntegrationTests/tests_04_performance/test_01_resources/template/HookedFunctions/Package.swift
  IntegrationTests/tests_04_performance/test_01_resources/template/HookedFunctions/Sources/HookedFunctions/include/hooked-functions.h
  IntegrationTests/tests_04_performance/test_01_resources/template/HookedFunctions/Sources/HookedFunctions/src/hooked-functions.c
  IntegrationTests/tests_04_performance/test_01_resources/template/Package.swift
  IntegrationTests/tests_04_performance/test_01_resources/template/Sources/SwiftBootstrap/SwiftMain.swift
  IntegrationTests/tests_04_performance/test_01_resources/template/Sources/bootstrap/main.c
Labels: patch-version-bump-only

#220 make Channel lifecycle statemachine explicit
  Sources/NIO/BaseSocketChannel.swift
  Sources/NIO/Channel.swift
  Sources/NIO/ChannelPipeline.swift
  Sources/NIO/Selector.swift
  Sources/NIO/SocketChannel.swift
  Tests/NIOTests/ChannelTests+XCTest.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/DatagramChannelTests.swift
Labels: needs-minor-version-bump

#262 make allocation counter test fail on error in subshell
  IntegrationTests/tests_04_performance/test_01_allocation_counts_for_http1.sh
Labels: patch-version-bump-only

#258 just set 127.0.0.1 as localhost's IPv4 address
  IntegrationTests/tests_01_http/defines.sh
Labels: patch-version-bump-only
