Repository apple/swift-nio, pull requests merged in 2019-03, with the labels that each got.

#844 Allow delaying HTTP upgrade decisions.
  Sources/NIOHTTP1/HTTPUpgradeHandler.swift
  Sources/NIOWebSocket/WebSocketUpgrader.swift
  Sources/NIOWebSocketServer/main.swift
  Tests/NIOHTTP1Tests/HTTPUpgradeTests+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPUpgradeTests.swift
  Tests/NIOWebSocketTests/EndToEndTests+XCTest.swift
  Tests/NIOWebSocketTests/EndToEndTests.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#859 slight improvements to the allocation tests
  IntegrationTests/tests_04_performance/test_01_resources/template/AtomicCounter/Package.swift
  IntegrationTests/tests_04_performance/test_01_resources/template/HookedFunctions/Package.swift
  IntegrationTests/tests_04_performance/test_01_resources/template/Package.swift
  IntegrationTests/tests_04_performance/test_01_resources/template/Sources/SwiftBootstrap/SwiftMain.swift
  docker/docker-compose.1804.50.yaml
Labels: patch-version-bump-only

#327 Add 418 status code
  Sources/NIOHTTP1/HTTPTypes.swift
Labels: ⚠️ needs-major-version-bump

#861 prepare tests for throwing readIn/Outbound
  Sources/NIO/Embedded.swift
  Tests/NIOHTTP1Tests/HTTPDecoderLengthTest.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
  Tests/NIOHTTP1Tests/HTTPRequestEncoderTest.swift
  Tests/NIOHTTP1Tests/HTTPResponseCompressorTest.swift
  Tests/NIOHTTP1Tests/HTTPResponseEncoderTest.swift
  Tests/NIOHTTP1Tests/HTTPServerProtocolErrorHandlerTest.swift
  Tests/NIOHTTP1Tests/HTTPUpgradeTests.swift
  Tests/NIOTLSTests/ApplicationProtocolNegotiationHandlerTests.swift
  Tests/NIOTLSTests/SNIHandlerTests.swift
  Tests/NIOTests/ChannelPipelineTest.swift
  Tests/NIOTests/CodecTest.swift
  Tests/NIOTests/EmbeddedChannelTest.swift
  Tests/NIOWebSocketTests/EndToEndTests.swift
  Tests/NIOWebSocketTests/WebSocketFrameDecoderTest.swift
  Tests/NIOWebSocketTests/WebSocketFrameEncoderTest.swift
Labels: ⚠️ needs-major-version-bump

#865 remove HTTPResponseCompressor
  Package.swift
  Sources/CNIOZlib/empty.c
  Sources/CNIOZlib/include/CNIOZlib.h
  Sources/NIOHTTP1/HTTPResponseCompressor.swift
  Tests/LinuxMain.swift
  Tests/NIOHTTP1Tests/HTTPResponseCompressorTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPResponseCompressorTest.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#866 convert NIOWebSocketUpgradeError from enum to struct
  Sources/NIOWebSocket/WebSocketUpgrader.swift
  Tests/NIOWebSocketTests/EndToEndTests.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#800 conform ByteBufferView to Foundation's ContiguousBytes protocol & withContiguousStorageIfAvailable
  Sources/NIO/ByteBuffer-views.swift
  Sources/NIOFoundationCompat/ByteBuffer-foundation.swift
  Tests/NIOTests/ByteBufferTest+XCTest.swift
  Tests/NIOTests/ByteBufferTest.swift
Labels: ⚠️ needs-major-version-bump

#867 fail unhandled outbound user events
  Sources/NIO/BaseSocketChannel.swift
  Sources/NIO/Embedded.swift
  Tests/NIOTests/ChannelTests+XCTest.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/DatagramChannelTests+XCTest.swift
  Tests/NIOTests/DatagramChannelTests.swift
  Tests/NIOTests/EmbeddedChannelTest+XCTest.swift
  Tests/NIOTests/EmbeddedChannelTest.swift
  Tests/NIOTests/SocketChannelTest+XCTest.swift
  Tests/NIOTests/SocketChannelTest.swift
Labels: ⚠️ needs-major-version-bump

#868 improve and simplify MessageToByteEncoder
  Sources/NIO/Codec.swift
  Sources/_NIO1APIShims/NIO1APIShims.swift
  Tests/NIOTests/CodecTest.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#323 [2.0 change] Hard-fail on invalid write types in core channels.
  Sources/NIO/Channel.swift
  Sources/NIO/SocketChannel.swift
  Tests/NIOTests/ChannelTests+XCTest.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/EmbeddedChannelTest.swift
Labels: ⚠️ needs-major-version-bump

#751 Conform NIOAny to CustomStringConvertible
  Sources/NIO/AddressedEnvelope.swift
  Sources/NIO/ByteBuffer-core.swift
  Sources/NIO/FileHandle.swift
  Sources/NIO/FileRegion.swift
  Sources/NIO/IOData.swift
  Sources/NIO/NIOAny.swift
  Tests/LinuxMain.swift
  Tests/NIOTests/NIOAnyDebugTest+XCTest.swift
  Tests/NIOTests/NIOAnyDebugTest.swift
Labels: 🔼 needs-minor-version-bump

#784 Drop HTTPHeaders Sequence conformance in favor of RandomAccessCollection
  Sources/NIOHTTP1/HTTPTypes.swift
  Tests/NIOHTTP1Tests/HTTPHeadersTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPHeadersTest.swift
Labels: 🔼 needs-minor-version-bump

#743 Support using recvmmsg to perform gathering reads.
  Package.swift
  Sources/NIO/ChannelOption.swift
  Sources/NIO/DatagramVectorReadManager.swift
  Sources/NIO/SocketChannel.swift
  Sources/NIOUDPEchoServer/main.swift
  Tests/NIOTests/DatagramChannelTests+XCTest.swift
  Tests/NIOTests/DatagramChannelTests.swift
Labels: 🔼 needs-minor-version-bump

#602 EmbeddedChannel: use tryAs() not forceAs()
  Sources/NIO/Embedded.swift
  Tests/NIOTests/EmbeddedChannelTest+XCTest.swift
  Tests/NIOTests/EmbeddedChannelTest.swift
Labels: 🔼 needs-minor-version-bump

#870 fix NIOAny.tryAsOther
  Sources/NIO/NIOAny.swift
  Tests/NIOTests/EmbeddedChannelTest+XCTest.swift
  Tests/NIOTests/EmbeddedChannelTest.swift
Labels: patch-version-bump-only

#871 DEVELOPMENT-SNAPSHOT-2019-03-04-a
  docker/docker-compose.1804.50.yaml
Labels: patch-version-bump-only

#869 ByteBuffer get* now respects reader/writer indexes
  Sources/NIO/ByteBuffer-aux.swift
  Sources/NIO/ByteBuffer-core.swift
  Sources/NIO/ByteBuffer-int.swift
  Sources/NIO/DatagramVectorReadManager.swift
  Sources/NIOFoundationCompat/ByteBuffer-foundation.swift
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOHTTP1/HTTPTypes.swift
  Tests/NIOTests/ByteBufferTest+XCTest.swift
  Tests/NIOTests/ByteBufferTest.swift
  Tests/NIOTests/CodecTest.swift
Labels: ⚠️ needs-major-version-bump

#875 B2MD: Stop parsing loop correctly on EOF
  Sources/NIO/Codec.swift
  Tests/NIOTests/CodecTest+XCTest.swift
  Tests/NIOTests/CodecTest.swift
Labels: patch-version-bump-only

#814 new http parser
  Sources/NIO/Codec.swift
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOHTTP1/HTTPPipelineSetup.swift
  Sources/NIOUDPEchoServer/main.swift
  Tests/NIOHTTP1Tests/HTTPDecoderLengthTest.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
  Tests/NIOHTTP1Tests/HTTPServerProtocolErrorHandlerTest.swift
  Tests/NIOHTTP1Tests/HTTPTest.swift
  Tests/NIOHTTP1Tests/HTTPUpgradeTests.swift
  Tests/NIOWebSocketTests/EndToEndTests.swift
  docker/docker-compose.1804.50.yaml
Labels: ⚠️ needs-major-version-bump

#876 Make `NIOAny` log the contents of its storage when encountering fatal unwrapping errors.
  Sources/NIO/NIOAny.swift
Labels: patch-version-bump-only

#857 HTTP/1 headers simplification & cleanup
  IntegrationTests/tests_01_http/test_07_headers_work.sh
  Sources/NIOHTTP1/ByteCollectionUtils.swift
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOHTTP1/HTTPTypes.swift
  Sources/NIOHTTP1/HTTPUpgradeHandler.swift
  Sources/NIOWebSocket/WebSocketUpgrader.swift
  Sources/_NIO1APIShims/NIO1APIShims.swift
  Tests/NIOHTTP1Tests/HTTPHeadersTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPHeadersTest.swift
  docker/docker-compose.1804.50.yaml
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#878 ByteBuffer.viewBytes now returns an Optional
  Sources/NIO/ByteBuffer-views.swift
  Tests/NIOTests/ByteBufferTest.swift
Labels: ⚠️ needs-major-version-bump

#879 [nio-1.13] Make `NIOAny` log the contents of its storage when encountering fatal unwrapping errors.
  Sources/NIO/NIOAny.swift
Labels: patch-version-bump-only

#846 ELF: make everything inlinable
  Sources/NIO/EventLoop.swift
  Sources/NIO/EventLoopFuture.swift
Labels: patch-version-bump-only

#880 Selector: make sure timerfd is level triggered
  Sources/NIO/Selector.swift
  Tests/NIOTests/SelectorTest+XCTest.swift
  Tests/NIOTests/SelectorTest.swift
Labels: patch-version-bump-only

#888 update documentation that EventLoopIterator is no longer optional
  Sources/NIO/EventLoop.swift
Labels: ⚠️ needs-major-version-bump

#886 remove overloading from scheduleRepeatedTask
  Sources/NIO/EventLoop.swift
  Sources/_NIO1APIShims/NIO1APIShims.swift
  Tests/NIOTests/EventLoopTest+XCTest.swift
  Tests/NIOTests/EventLoopTest.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#887 NIONetworkInterface: Return if multicast is supported
  Sources/NIO/Channel.swift
  Sources/NIO/Interfaces.swift
  Sources/NIO/SocketChannel.swift
  Tests/NIOTests/MulticastTest.swift
  Tests/NIOTests/NIOAnyDebugTest.swift
  Tests/NIOTests/SocketOptionProviderTest.swift
Labels: ⚠️ needs-major-version-bump

#889 disable NIO1APIShim's warning
  Sources/_NIO1APIShims/NIO1APIShims.swift
  docker/docker-compose.1804.50.yaml
Labels: ⚠️ needs-major-version-bump

#881 [1.13] Selector: make sure timerfd is level triggered
  Sources/NIO/Selector.swift
  Tests/NIOTests/SelectorTest+XCTest.swift
  Tests/NIOTests/SelectorTest.swift
Labels: patch-version-bump-only

#890 MarkedCircularBuffer: don't used indices incorrectly
  Sources/NIO/MarkedCircularBuffer.swift
Labels: patch-version-bump-only

#885 remove WebSocketFrameDecoder inline error handling
  Package.swift
  Sources/NIOWebSocket/WebSocketFrameDecoder.swift
  Sources/NIOWebSocket/WebSocketUpgrader.swift
  Sources/_NIO1APIShims/NIO1APIShims.swift
  Tests/NIOWebSocketTests/WebSocketFrameDecoderTest+XCTest.swift
  Tests/NIOWebSocketTests/WebSocketFrameDecoderTest.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#897 README.md: Update prerequisites
  README.md
Labels: patch-version-bump-only

#895 ByteBuffer docs: gets are safe
  Sources/NIO/ByteBuffer-core.swift
Labels: patch-version-bump-only

#899 HTTPDecoder: remove rawURI
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOHTTP1/HTTPTypes.swift
Labels: patch-version-bump-only

#901 migration guide: swift-nio-ssl has converged
  docs/migration-guide-NIO1-to-NIO2.md
Labels: patch-version-bump-only

#896 ByteBuffer: improve and simplify get* implementations
  Sources/NIO/ByteBuffer-aux.swift
  Sources/NIO/ByteBuffer-core.swift
  Sources/NIO/ByteBuffer-int.swift
  Sources/NIO/ByteBuffer-views.swift
  Sources/NIOFoundationCompat/ByteBuffer-foundation.swift
  Tests/NIOTests/ByteBufferTest.swift
Labels: patch-version-bump-only

#892 remove deprecated methods
  Sources/NIO/EventLoop.swift
Labels: ⚠️ needs-major-version-bump

#903 B2MH: helpful message if re-added to pipeline
  Sources/NIO/Codec.swift
Labels: patch-version-bump-only

#905 Update migration guide with now-converging repos.
  docs/migration-guide-NIO1-to-NIO2.md
Labels: patch-version-bump-only

#906 CircularBuffer: better opaque indices
  Sources/NIO/ByteBuffer-int.swift
  Sources/NIO/CircularBuffer.swift
  Sources/NIO/MarkedCircularBuffer.swift
  Sources/NIO/PendingDatagramWritesManager.swift
  Sources/NIO/PendingWritesManager.swift
  Sources/_NIO1APIShims/NIO1APIShims.swift
  Tests/NIOTests/CircularBufferTests+XCTest.swift
  Tests/NIOTests/CircularBufferTests.swift
  Tests/NIOTests/MarkedCircularBufferTests.swift
Labels: ⚠️ needs-major-version-bump

#900 conform ByteBufferView to DataProtocol
  Sources/NIOFoundationCompat/ByteBuffer-foundation.swift
  Tests/NIOTests/ByteBufferTest+XCTest.swift
  Tests/NIOTests/ByteBufferTest.swift
Labels: 🔼 needs-minor-version-bump

#907 B2MD: check that EOF events are forwarded
  Tests/NIOTests/CodecTest+XCTest.swift
  Tests/NIOTests/CodecTest.swift
Labels: patch-version-bump-only

#908 make HTTPMethod.hasRequestBody internal
  Sources/NIOHTTP1/HTTPTypes.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#909 CircularBuffer: debug-only index validation
  Sources/NIO/CircularBuffer.swift
  Sources/NIO/IntegerTypes.swift
  Tests/NIOTests/CircularBufferTests.swift
Labels: patch-version-bump-only

#910 less confusion for Jazzy
  Sources/NIO/Embedded.swift
  Sources/NIO/EventLoop.swift
  Sources/NIO/Heap.swift
  Sources/NIO/PriorityQueue.swift
  Sources/NIO/SocketChannel.swift
  Sources/NIO/SocketOptionProvider.swift
Labels: patch-version-bump-only

#917 EmbeddedChannel: remove mystery bools
  Sources/NIO/Embedded.swift
  Tests/NIOHTTP1Tests/HTTPDecoderLengthTest.swift
  Tests/NIOHTTP1Tests/HTTPHeadersTest.swift
  Tests/NIOHTTP1Tests/HTTPRequestEncoderTest.swift
  Tests/NIOHTTP1Tests/HTTPResponseEncoderTest.swift
  Tests/NIOHTTP1Tests/HTTPUpgradeTests.swift
  Tests/NIOTLSTests/ApplicationProtocolNegotiationHandlerTests.swift
  Tests/NIOTLSTests/SNIHandlerTests.swift
  Tests/NIOTests/ChannelPipelineTest.swift
  Tests/NIOTests/CodecTest.swift
  Tests/NIOTests/EmbeddedChannelTest.swift
  Tests/NIOTests/IdleStateHandlerTest.swift
  Tests/NIOWebSocketTests/EndToEndTests.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#914 CircBuffer: docs: add that indices are no longer Strideable
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: patch-version-bump-only

#913 Scheduled: Don't hold onto cancellationTask
  Sources/NIO/EventLoop.swift
  Tests/NIOTests/EmbeddedEventLoopTest+XCTest.swift
  Tests/NIOTests/EmbeddedEventLoopTest.swift
  Tests/NIOTests/EventLoopTest+XCTest.swift
  Tests/NIOTests/EventLoopTest.swift
  Tests/NIOTests/TestUtils.swift
Labels: patch-version-bump-only

#918 remove unused CompositeError
  Sources/NIO/CompositeError.swift
  Tests/LinuxMain.swift
  Tests/NIOTests/CompositeErrorTests+XCTest.swift
  Tests/NIOTests/CompositeErrorTests.swift
Labels: ⚠️ needs-major-version-bump

#919 improve documentation
  Sources/NIO/ChannelHandlers.swift
  Sources/NIO/CircularBuffer.swift
  Sources/NIO/Codec.swift
  Sources/NIO/Embedded.swift
  Sources/NIO/PriorityQueue.swift
  Sources/NIO/ServerSocket.swift
  Sources/NIOConcurrencyHelpers/atomics.swift
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOHTTP1/HTTPUpgradeHandler.swift
  Sources/NIOTLS/ApplicationProtocolNegotiationHandler.swift
  Sources/NIOTLS/SNIHandler.swift
  Tests/NIOTests/AcceptBackoffHandlerTest.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/CodecTest.swift
  Tests/NIOTests/EmbeddedEventLoopTest.swift
  Tests/NIOTests/EventLoopTest.swift
  Tests/NIOTests/HappyEyeballsTest.swift
  Tests/NIOTests/IntegerTypesTest.swift
  Tests/NIOTests/RecvByteBufAllocatorTest.swift
  Tests/NIOTests/SocketChannelTest.swift
  Tests/NIOWebSocketTests/WebSocketFrameDecoderTest.swift
  Tests/NIOWebSocketTests/WebSocketFrameEncoderTest.swift
Labels: patch-version-bump-only

#920 DEVELOPMENT-SNAPSHOT-2019-03-10-a
  docker/docker-compose.1804.50.yaml
Labels: patch-version-bump-only

#921 update contributors
  .mailmap
  CONTRIBUTORS.txt
Labels: patch-version-bump-only

#933 UDP Echo Client Example.
  Package.swift
  Sources/NIOUDPEchoClient/README.md
  Sources/NIOUDPEchoClient/main.swift
Labels: patch-version-bump-only

#932 API docs: repo switcher
  scripts/generate_docs.sh
Labels: patch-version-bump-only

#937 Update style in TCP Client and HTTP1Server examples.
  Sources/NIOEchoClient/main.swift
  Sources/NIOHTTP1Server/main.swift
Labels: patch-version-bump-only
