Repository apple/swift-nio, pull requests merged in 2019-02, with the labels that each got.

#798 Update my name in Contributors list
  .mailmap
  CONTRIBUTORS.txt
Labels: patch-version-bump-only

#801 enable HTTP1 error handling by default
  IntegrationTests/tests_04_performance/test_01_resources/template/Sources/SwiftBootstrap/SwiftMain.swift
  Sources/NIOHTTP1/HTTPPipelineSetup.swift
Labels: ⚠️ needs-major-version-bump

#802 standardize `ELF.cascade*` collection of methods
  IntegrationTests/tests_04_performance/test_01_resources/template/Sources/SwiftBootstrap/SwiftMain.swift
  Sources/NIO/BaseSocketChannel.swift
  Sources/NIO/Bootstrap.swift
  Sources/NIO/ChannelPipeline.swift
  Sources/NIO/EventLoop.swift
  Sources/NIO/EventLoopFuture.swift
  Sources/NIO/PendingDatagramWritesManager.swift
  Sources/NIO/PendingWritesManager.swift
  Sources/NIOHTTP1/HTTPEncoder.swift
  Sources/NIOHTTP1/HTTPResponseCompressor.swift
  Sources/NIOHTTP1/HTTPServerPipelineHandler.swift
  Sources/NIOPerformanceTester/main.swift
  Sources/_NIO1APIShims/NIO1APIShims.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/EventLoopTest.swift
  Tests/NIOTests/MulticastTest.swift
  Tests/NIOTests/SelectorTest.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#806 Remove useless comment
  Sources/NIOEchoServer/main.swift
Labels: patch-version-bump-only

#803 Rename `ELF.andAll(_:eventLoop:)` to `andAllSucceed(_:on:)` and add `ELF.andAllComplete`
  Sources/NIO/ChannelPipeline.swift
  Sources/NIO/EventLoopFuture.swift
  Sources/NIO/Selector.swift
  Sources/NIOHTTP1/HTTPUpgradeHandler.swift
  Sources/_NIO1APIShims/NIO1APIShims.swift
  Tests/NIOHTTP1Tests/HTTPTest.swift
  Tests/NIOHTTP1Tests/HTTPUpgradeTests.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/DatagramChannelTests.swift
  Tests/NIOTests/EventLoopFutureTest.swift
  Tests/NIOTests/SelectorTest.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#808 Remove outdated documentation
  Sources/NIO/EventLoopFuture.swift
Labels: patch-version-bump-only

#807 Avoid race condition in Posix.accept() on macOS
  Sources/NIO/System.swift
  Tests/NIOTests/SocketChannelTest+XCTest.swift
  Tests/NIOTests/SocketChannelTest.swift
Labels: patch-version-bump-only

#811 Add TCP_INFO/TCP_CONNECTION_INFO queries.
  Sources/NIO/SocketOptionProvider.swift
  Tests/NIOTests/SocketOptionProviderTest+XCTest.swift
  Tests/NIOTests/SocketOptionProviderTest.swift
Labels: 🔼 needs-minor-version-bump

#767 better ChannelHandler removal API
  Sources/NIO/Channel.swift
  Sources/NIO/ChannelHandler.swift
  Sources/NIO/ChannelPipeline.swift
  Sources/NIO/Codec.swift
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOHTTP1/HTTPEncoder.swift
  Sources/NIOHTTP1/HTTPPipelineSetup.swift
  Sources/NIOHTTP1/HTTPServerPipelineHandler.swift
  Sources/NIOHTTP1/HTTPServerProtocolErrorHandler.swift
  Sources/NIOHTTP1/HTTPUpgradeHandler.swift
  Sources/NIOTLS/ApplicationProtocolNegotiationHandler.swift
  Sources/NIOWebSocketServer/main.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
  Tests/NIOTests/AcceptBackoffHandlerTest.swift
  Tests/NIOTests/ChannelPipelineTest+XCTest.swift
  Tests/NIOTests/ChannelPipelineTest.swift
  Tests/NIOTests/CodecTest+XCTest.swift
  Tests/NIOTests/CodecTest.swift
  Tests/NIOTests/TestUtils.swift
  Tests/NIOWebSocketTests/WebSocketFrameDecoderTest.swift
  docker/docker-compose.1804.50.yaml
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#812 ByteBuffer: rename set(<type>:, ...) to set<Type>(...)
  IntegrationTests/tests_04_performance/test_01_resources/template/Sources/SwiftBootstrap/SwiftMain.swift
  Package.swift
  Sources/NIO/ByteBuffer-aux.swift
  Sources/NIO/ByteBuffer-core.swift
  Sources/NIO/ByteBuffer-int.swift
  Sources/NIO/Codec.swift
  Sources/NIOChatClient/main.swift
  Sources/NIOChatServer/main.swift
  Sources/NIOEchoClient/main.swift
  Sources/NIOFoundationCompat/ByteBuffer-foundation.swift
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOHTTP1/HTTPEncoder.swift
  Sources/NIOHTTP1/HTTPResponseCompressor.swift
  Sources/NIOHTTP1/HTTPTypes.swift
  Sources/NIOHTTP1Server/main.swift
  Sources/NIOMulticastChat/main.swift
  Sources/NIOPerformanceTester/main.swift
  Sources/NIOWebSocket/WebSocketErrorCodes.swift
  Sources/NIOWebSocket/WebSocketFrameEncoder.swift
  Sources/NIOWebSocketServer/main.swift
  Sources/_NIO1APIShims/NIO1APIShims.swift
  Tests/NIOHTTP1Tests/ByteBufferUtilsTest.swift
  Tests/NIOHTTP1Tests/HTTPDecoderLengthTest.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
  Tests/NIOHTTP1Tests/HTTPHeadersTest.swift
  Tests/NIOHTTP1Tests/HTTPRequestEncoderTest.swift
  Tests/NIOHTTP1Tests/HTTPResponseCompressorTest.swift
  Tests/NIOHTTP1Tests/HTTPServerClientTest.swift
  Tests/NIOHTTP1Tests/HTTPServerProtocolErrorHandlerTest.swift
  Tests/NIOHTTP1Tests/HTTPTest.swift
  Tests/NIOHTTP1Tests/HTTPUpgradeTests.swift
  Tests/NIOTLSTests/SNIHandlerTests.swift
  Tests/NIOTests/BaseObjectsTest.swift
  Tests/NIOTests/ByteBufferTest.swift
  Tests/NIOTests/ChannelNotificationTest.swift
  Tests/NIOTests/ChannelPipelineTest.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/CodecTest.swift
  Tests/NIOTests/DatagramChannelTests.swift
  Tests/NIOTests/EchoServerClientTest.swift
  Tests/NIOTests/EmbeddedChannelTest.swift
  Tests/NIOTests/EventLoopTest.swift
  Tests/NIOTests/FileRegionTest.swift
  Tests/NIOTests/IdleStateHandlerTest.swift
  Tests/NIOTests/MulticastTest.swift
  Tests/NIOTests/NonBlockingFileIOTest.swift
  Tests/NIOTests/PendingDatagramWritesManagerTests.swift
  Tests/NIOTests/SelectorTest.swift
  Tests/NIOTests/SocketChannelTest.swift
  Tests/NIOTests/TestUtils.swift
  Tests/NIOWebSocketTests/EndToEndTests.swift
  Tests/NIOWebSocketTests/WebSocketFrameDecoderTest.swift
  Tests/NIOWebSocketTests/WebSocketFrameEncoderTest.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#815 make all removals go through the RemovableChannelHandler API
  Sources/NIO/ChannelHandlers.swift
  Sources/NIO/ChannelPipeline.swift
  Sources/NIOHTTP1/HTTPDecoder.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
  Tests/NIOTests/ChannelPipelineTest+XCTest.swift
  Tests/NIOTests/ChannelPipelineTest.swift
  Tests/NIOWebSocketTests/WebSocketFrameDecoderTest.swift
Labels: ⚠️ needs-major-version-bump

#809 Update ELF parameter labels to be more Swifty
  Sources/NIO/Bootstrap.swift
  Sources/NIO/EventLoopFuture.swift
  Sources/_NIO1APIShims/NIO1APIShims.swift
  Tests/NIOTests/EventLoopFutureTest.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#821 update to 5.0-DEVELOPMENT-SNAPSHOT-2019-02-06-a
  docker/docker-compose.1804.50.yaml
Labels: patch-version-bump-only

#824 Accept dictionary literals for HTTPHeaders
  Sources/NIOHTTP1/HTTPTypes.swift
  Tests/NIOHTTP1Tests/HTTPHeadersTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPHeadersTest.swift
Labels: 🔼 needs-minor-version-bump

#822 remove extension public/internal modifiers
  Sources/NIO/BlockingIOThreadPool.swift
  Sources/NIO/ByteBuffer-views.swift
  Sources/NIO/Channel.swift
  Sources/NIO/EventLoopFuture.swift
  Sources/NIO/LinuxCPUSet.swift
  Sources/NIO/MulticastChannel.swift
  Sources/NIO/PriorityQueue.swift
  Sources/NIO/Selector.swift
  Sources/NIO/SocketOptionProvider.swift
  Sources/NIOHTTP1/HTTPPipelineSetup.swift
  Sources/NIOHTTP1/HTTPResponseCompressor.swift
  Sources/NIOHTTP1/HTTPTypes.swift
  Sources/NIOWebSocket/Base64.swift
  Sources/NIOWebSocket/WebSocketErrorCodes.swift
  Sources/NIOWebSocket/WebSocketFrameDecoder.swift
  Sources/NIOWebSocket/WebSocketOpcode.swift
  Tests/NIOTLSTests/SNIHandlerTests.swift
  Tests/NIOTests/TestUtils.swift
Labels: patch-version-bump-only

#819 Thread's == was public by accident
  Sources/NIO/Thread.swift
Labels: ⚠️ needs-major-version-bump

#820 rename Channel._unsafe to Channel._channelCore
  Sources/NIO/BaseSocketChannel.swift
  Sources/NIO/Channel.swift
  Sources/NIO/ChannelPipeline.swift
  Sources/NIO/DeadChannel.swift
  Sources/NIO/Embedded.swift
  Sources/_NIO1APIShims/NIO1APIShims.swift
  Tests/NIOTests/AcceptBackoffHandlerTest.swift
  Tests/NIOTests/ChannelOptionStorageTest.swift
  Tests/NIOTests/EmbeddedChannelTest.swift
  docs/public-api-changes-NIO1-to-NIO2.md
  docs/public-api.md
Labels: ⚠️ needs-major-version-bump

#823 require ChannelOptions to be Equatable
  Sources/NIO/Bootstrap.swift
  Sources/NIO/ChannelOption.swift
  Tests/NIOTests/ChannelTests.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#818 rename FileHandle to NIOFileHandle
  Sources/NIO/EventLoop.swift
  Sources/NIO/FileHandle.swift
  Sources/NIO/FileRegion.swift
  Sources/NIO/LinuxCPUSet.swift
  Sources/NIO/NonBlockingFileIO.swift
  Sources/NIO/Thread.swift
  Sources/_NIO1APIShims/NIO1APIShims.swift
  Tests/NIOHTTP1Tests/HTTPServerClientTest.swift
  Tests/NIOTests/BaseObjectsTest.swift
  Tests/NIOTests/ChannelPipelineTest.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/EmbeddedChannelTest.swift
  Tests/NIOTests/EventLoopTest.swift
  Tests/NIOTests/FileRegionTest.swift
  Tests/NIOTests/NonBlockingFileIOTest.swift
  Tests/NIOTests/TestUtils.swift
  Tests/NIOTests/ThreadTest.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#828 simplify ChannelOptions
  Sources/NIO/BaseSocketChannel.swift
  Sources/NIO/Bootstrap.swift
  Sources/NIO/Channel.swift
  Sources/NIO/ChannelOption.swift
  Sources/NIO/DeadChannel.swift
  Sources/NIO/Embedded.swift
  Sources/NIO/SocketChannel.swift
  Sources/_NIO1APIShims/NIO1APIShims.swift
  Tests/NIOTests/AcceptBackoffHandlerTest.swift
  Tests/NIOTests/ChannelOptionStorageTest.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/DatagramChannelTests.swift
  Tests/NIOTests/SelectorTest.swift
  Tests/NIOTests/SocketChannelTest.swift
  Tests/NIOTests/TestUtils.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#826 opaque indices for (Marked)CircularBuffer
  Sources/NIO/CircularBuffer.swift
  Sources/NIO/MarkedCircularBuffer.swift
  Sources/NIO/PendingDatagramWritesManager.swift
  Sources/NIO/PendingWritesManager.swift
  Sources/_NIO1APIShims/NIO1APIShims.swift
  Tests/NIOTests/CircularBufferTests.swift
  Tests/NIOTests/MarkedCircularBufferTests.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#830 Clean up some broken shims.
  Sources/_NIO1APIShims/NIO1APIShims.swift
Labels: patch-version-bump-only

#817 ChannelPipeline: addHandler and removeHandler instead of add/remove
  IntegrationTests/tests_04_performance/test_01_resources/template/Sources/SwiftBootstrap/SwiftMain.swift
  Sources/NIO/Bootstrap.swift
  Sources/NIO/ChannelPipeline.swift
  Sources/NIO/Embedded.swift
  Sources/NIOChatClient/main.swift
  Sources/NIOChatServer/main.swift
  Sources/NIOEchoClient/main.swift
  Sources/NIOEchoServer/main.swift
  Sources/NIOHTTP1/HTTPPipelineSetup.swift
  Sources/NIOHTTP1/HTTPUpgradeHandler.swift
  Sources/NIOHTTP1Server/main.swift
  Sources/NIOMulticastChat/main.swift
  Sources/NIOPerformanceTester/main.swift
  Sources/NIOTLS/ApplicationProtocolNegotiationHandler.swift
  Sources/NIOTLS/SNIHandler.swift
  Sources/NIOWebSocket/WebSocketUpgrader.swift
  Sources/NIOWebSocketServer/main.swift
  Sources/_NIO1APIShims/NIO1APIShims.swift
  Tests/NIOHTTP1Tests/HTTPDecoderLengthTest.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
  Tests/NIOHTTP1Tests/HTTPRequestEncoderTest.swift
  Tests/NIOHTTP1Tests/HTTPResponseCompressorTest.swift
  Tests/NIOHTTP1Tests/HTTPResponseEncoderTest.swift
  Tests/NIOHTTP1Tests/HTTPServerClientTest.swift
  Tests/NIOHTTP1Tests/HTTPServerPipelineHandlerTest.swift
  Tests/NIOHTTP1Tests/HTTPServerProtocolErrorHandlerTest.swift
  Tests/NIOHTTP1Tests/HTTPTest.swift
  Tests/NIOHTTP1Tests/HTTPUpgradeTests.swift
  Tests/NIOTLSTests/ApplicationProtocolNegotiationHandlerTests.swift
  Tests/NIOTLSTests/SNIHandlerTests.swift
  Tests/NIOTests/AcceptBackoffHandlerTest.swift
  Tests/NIOTests/ChannelNotificationTest.swift
  Tests/NIOTests/ChannelPipelineTest+XCTest.swift
  Tests/NIOTests/ChannelPipelineTest.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/CodecTest.swift
  Tests/NIOTests/DatagramChannelTests.swift
  Tests/NIOTests/EchoServerClientTest.swift
  Tests/NIOTests/EmbeddedChannelTest.swift
  Tests/NIOTests/EventLoopTest.swift
  Tests/NIOTests/FileRegionTest.swift
  Tests/NIOTests/HappyEyeballsTest.swift
  Tests/NIOTests/IdleStateHandlerTest.swift
  Tests/NIOTests/MulticastTest.swift
  Tests/NIOTests/SelectorTest.swift
  Tests/NIOTests/SocketChannelTest.swift
  Tests/NIOWebSocketTests/EndToEndTests.swift
  Tests/NIOWebSocketTests/WebSocketFrameDecoderTest.swift
  Tests/NIOWebSocketTests/WebSocketFrameEncoderTest.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#831 improve B2MD EOF handling
  Sources/NIO/Codec.swift
  Sources/NIOChatServer/main.swift
  Sources/NIOTLS/SNIHandler.swift
  Sources/NIOWebSocket/WebSocketFrameDecoder.swift
  Tests/NIOTests/CodecTest+XCTest.swift
  Tests/NIOTests/CodecTest.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#832 update to 5.0-DEVELOPMENT-SNAPSHOT-2019-02-20-a
  docker/docker-compose.1804.50.yaml
Labels: patch-version-bump-only

#827 make ChannelOptions.Storage public
  Sources/NIO/Bootstrap.swift
  Sources/NIO/ChannelOption.swift
  Tests/NIOTests/ChannelOptionStorageTest.swift
Labels: 🔼 needs-minor-version-bump

#834 introduce WriteObservingByteToMessageDecoder
  Sources/NIO/Codec.swift
  Tests/NIOTests/CodecTest+XCTest.swift
  Tests/NIOTests/CodecTest.swift
Labels: ⚠️ needs-major-version-bump

#838 address #186: rename BlockingIOThreadPool to NIOThreadPool
  Sources/NIO/NIOThreadPool.swift
  Sources/NIO/NonBlockingFileIO.swift
  Sources/NIOHTTP1Server/main.swift
  Sources/_NIO1APIShims/NIO1APIShims.swift
  Tests/NIOTests/BlockingIOThreadPoolTest.swift
  Tests/NIOTests/NonBlockingFileIOTest.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#837 B2MD: Don't deliver data after error
  Sources/NIO/Codec.swift
  Tests/NIOTests/CodecTest+XCTest.swift
  Tests/NIOTests/CodecTest.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: patch-version-bump-only

#842 rename ctx to context
  IntegrationTests/tests_04_performance/test_01_resources/template/Sources/SwiftBootstrap/SwiftMain.swift
  Sources/NIO/Bootstrap.swift
  Sources/NIO/ChannelHandler.swift
  Sources/NIO/ChannelHandlers.swift
  Sources/NIO/ChannelPipeline.swift
  Sources/NIO/Codec.swift
  Sources/NIO/Embedded.swift
  Sources/NIO/NIOAny.swift
  Sources/NIOChatClient/main.swift
  Sources/NIOChatServer/main.swift
  Sources/NIOEchoClient/main.swift
  Sources/NIOEchoServer/main.swift
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOHTTP1/HTTPEncoder.swift
  Sources/NIOHTTP1/HTTPResponseCompressor.swift
  Sources/NIOHTTP1/HTTPServerPipelineHandler.swift
  Sources/NIOHTTP1/HTTPServerProtocolErrorHandler.swift
  Sources/NIOHTTP1/HTTPUpgradeHandler.swift
  Sources/NIOHTTP1Server/main.swift
  Sources/NIOMulticastChat/main.swift
  Sources/NIOPerformanceTester/main.swift
  Sources/NIOTLS/ApplicationProtocolNegotiationHandler.swift
  Sources/NIOTLS/SNIHandler.swift
  Sources/NIOWebSocket/WebSocketFrameDecoder.swift
  Sources/NIOWebSocket/WebSocketFrameEncoder.swift
  Sources/NIOWebSocket/WebSocketProtocolErrorHandler.swift
  Sources/NIOWebSocket/WebSocketUpgrader.swift
  Sources/NIOWebSocketServer/main.swift
  Sources/_NIO1APIShims/NIO1APIShims.swift
  Tests/NIOHTTP1Tests/HTTPDecoderLengthTest.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
  Tests/NIOHTTP1Tests/HTTPServerClientTest.swift
  Tests/NIOHTTP1Tests/HTTPServerPipelineHandlerTest.swift
  Tests/NIOHTTP1Tests/HTTPServerProtocolErrorHandlerTest.swift
  Tests/NIOHTTP1Tests/HTTPTest.swift
  Tests/NIOHTTP1Tests/HTTPUpgradeTests.swift
  Tests/NIOTLSTests/ApplicationProtocolNegotiationHandlerTests.swift
  Tests/NIOTests/AcceptBackoffHandlerTest.swift
  Tests/NIOTests/ChannelNotificationTest.swift
  Tests/NIOTests/ChannelPipelineTest.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/CodecTest.swift
  Tests/NIOTests/DatagramChannelTests.swift
  Tests/NIOTests/EchoServerClientTest.swift
  Tests/NIOTests/EmbeddedChannelTest.swift
  Tests/NIOTests/EventLoopTest.swift
  Tests/NIOTests/HappyEyeballsTest.swift
  Tests/NIOTests/IdleStateHandlerTest.swift
  Tests/NIOTests/MulticastTest.swift
  Tests/NIOTests/SelectorTest.swift
  Tests/NIOTests/SocketChannelTest.swift
  Tests/NIOTests/TestUtils.swift
  Tests/NIOWebSocketTests/EndToEndTests.swift
  Tests/NIOWebSocketTests/WebSocketFrameDecoderTest.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#833 make localAddress and remoteAddress testable in EmbeddedChannel
  Sources/NIO/Embedded.swift
  Tests/NIOTests/EmbeddedChannelTest+XCTest.swift
  Tests/NIOTests/EmbeddedChannelTest.swift
Labels: 🔼 needs-minor-version-bump

#843 ELF: fix andAll*
  Sources/NIO/EventLoopFuture.swift
  Tests/NIOTests/EventLoopTest+XCTest.swift
  Tests/NIOTests/EventLoopTest.swift
Labels: patch-version-bump-only

#845 update http_parser
  Sources/CNIOHTTPParser/c_nio_http_parser.c
  Sources/CNIOHTTPParser/include/c_nio_http_parser.h
  Sources/CNIOHTTPParser/update_and_patch_http_parser.sh
  Sources/NIOHTTP1/HTTPEncoder.swift
  Sources/NIOHTTP1/HTTPTypes.swift
Labels: patch-version-bump-only

#157 don't leak pthread_keys
  Sources/NIO/Thread.swift
  Tests/NIOTests/ThreadTest+XCTest.swift
  Tests/NIOTests/ThreadTest.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#852 integration tests: debug mode which doesn't delete tmp
  IntegrationTests/run-tests.sh
Labels: patch-version-bump-only

#847 NIO 1 to 2 migration guide
  docs/migration-guide-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#850 fix new Swift 5 warnings for NIO 1
  Sources/NIO/BaseSocket.swift
  Sources/NIO/ByteBuffer-core.swift
  Sources/NIO/IntegerTypes.swift
  Tests/NIOTests/ChannelPipelineTest.swift
Labels: patch-version-bump-only

#853 B2MD: actually call decoderRemoved
  Sources/NIO/Codec.swift
  Tests/NIOTests/CodecTest+XCTest.swift
  Tests/NIOTests/CodecTest.swift
Labels: patch-version-bump-only

#854 B2MD: fast-path to reduce allocations
  IntegrationTests/tests_04_performance/test_01_resources/template/Sources/SwiftBootstrap/SwiftMain.swift
  Sources/NIO/Codec.swift
Labels: patch-version-bump-only

#856 fix/improve some NIO1APIShims
  Sources/_NIO1APIShims/NIO1APIShims.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: patch-version-bump-only

#855 EmbeddedChannel: expose EmbeddedEventLoop
  Sources/NIO/Embedded.swift
  Tests/NIOHTTP1Tests/HTTPDecoderLengthTest.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
  Tests/NIOHTTP1Tests/HTTPServerProtocolErrorHandlerTest.swift
  Tests/NIOTests/ChannelPipelineTest.swift
  Tests/NIOTests/CodecTest.swift
Labels: 🔼 needs-minor-version-bump

#851 improve ChannelPipeline debug print
  Sources/NIO/ChannelPipeline.swift
  Tests/NIOTests/ChannelPipelineTest+XCTest.swift
  Tests/NIOTests/ChannelPipelineTest.swift
Labels: patch-version-bump-only
