Repository apple/swift-nio, pull requests merged in 2019-01, with the labels that each got.

#719 [Gardening] Use multiline string literals instead of concatenation
  Sources/NIO/ByteBuffer-core.swift
  Tests/NIOTests/ByteBufferTest.swift
Labels: patch-version-bump-only

#723 Update list_topsorted_dependencies script.
  scripts/list_topsorted_dependencies.sh
Labels: patch-version-bump-only

#724 use the Swift 5.0 snapshot from 2018-12-28
  docker/docker-compose.1804.50.yaml
Labels: patch-version-bump-only

#716 Fix: BlockingIOThreadPool not releasing the latest WorkItem
  Sources/NIO/BlockingIOThreadPool.swift
  Tests/NIOTests/BlockingIOThreadPoolTest+XCTest.swift
  Tests/NIOTests/BlockingIOThreadPoolTest.swift
Labels: patch-version-bump-only

#728 override content encoding header value in compressor
  Sources/NIOHTTP1/HTTPResponseCompressor.swift
  Tests/NIOHTTP1Tests/HTTPResponseCompressorTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPResponseCompressorTest.swift
Labels: patch-version-bump-only

#718 [NIOHTTP1Server] Use fixed default string to write in response and do not hardcode content length
  IntegrationTests/tests_01_http/test_23_repeated_reqs_with_half_closure.sh
  Sources/NIOHTTP1Server/main.swift
Labels: patch-version-bump-only

#730 [FORWARD_PORT] Fix: BlockingIOThreadPool not releasing the latest WorkItem (#716)
  Sources/NIO/BlockingIOThreadPool.swift
  Tests/NIOTests/BlockingIOThreadPoolTest+XCTest.swift
  Tests/NIOTests/BlockingIOThreadPoolTest.swift
Labels: patch-version-bump-only

#710 re-enable allocation test for Swift 5 (fixes #685)
  IntegrationTests/tests_04_performance/test_01_allocation_counts_for_http1.sh
  IntegrationTests/tests_04_performance/test_01_resources/template/Sources/SwiftBootstrap/SwiftMain.swift
Labels: patch-version-bump-only

#732 better DispatchData support
  IntegrationTests/tests_04_performance/test_01_resources/template/Sources/SwiftBootstrap/SwiftMain.swift
  Sources/NIO/ByteBuffer-aux.swift
  Sources/NIO/ByteBuffer-core.swift
  Tests/NIOTests/ByteBufferTest+XCTest.swift
  Tests/NIOTests/ByteBufferTest.swift
Labels: 🔼 needs-minor-version-bump

#731 Fix encoding header
  Sources/NIOHTTP1/HTTPResponseCompressor.swift
  Tests/NIOHTTP1Tests/HTTPResponseCompressorTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPResponseCompressorTest.swift
Labels: patch-version-bump-only

#737 use automatic Equatable conformances
  Sources/NIO/ByteBuffer-core.swift
  Sources/NIO/EventLoop.swift
  Sources/NIO/IO.swift
  Sources/NIO/IOData.swift
  Sources/NIO/IntegerTypes.swift
  Sources/NIO/LinuxCPUSet.swift
  Sources/NIOHTTP1/HTTPTypes.swift
  Sources/NIOTLS/ApplicationProtocolNegotiationHandler.swift
  Sources/NIOTLS/SNIHandler.swift
  Sources/NIOTLS/TLSEvents.swift
  Sources/NIOWebSocket/WebSocketErrorCodes.swift
  Sources/NIOWebSocket/WebSocketFrame.swift
  Tests/NIOTests/HappyEyeballsTest.swift
Labels: ⚠️ needs-major-version-bump

#738 remove backports of newer Swift functionality
  Sources/NIO/ByteBuffer-core.swift
  Sources/NIO/CircularBuffer.swift
  Sources/NIO/MarkedCircularBuffer.swift
  Sources/NIOConcurrencyHelpers/lock.swift
  Sources/NIOHTTP1/ByteCollectionUtils.swift
  Tests/NIOTests/HappyEyeballsTest.swift
Labels: ⚠️ needs-major-version-bump

#740 [NIO 1.12] remove bogus 'is active' assertion in channelRead0
  Sources/NIO/BaseSocketChannel.swift
  Tests/NIOTests/ChannelPipelineTest+XCTest.swift
  Tests/NIOTests/ChannelPipelineTest.swift
Labels: patch-version-bump-only

#739 remove bogus 'is active' assertion in channelRead0
  Sources/NIO/BaseSocketChannel.swift
  Tests/NIOTests/ChannelPipelineTest+XCTest.swift
  Tests/NIOTests/ChannelPipelineTest.swift
Labels: patch-version-bump-only

#754 Docs: move defer shutdown next to EventLoop creation
  Sources/NIO/Bootstrap.swift
Labels: patch-version-bump-only

#757 make ELF.cascade accept an optional promise
  Sources/NIO/BaseSocketChannel.swift
  Sources/NIO/ChannelPipeline.swift
  Sources/NIO/EventLoopFuture.swift
  Sources/NIOHTTP1/HTTPResponseCompressor.swift
  Sources/NIOHTTP1/HTTPServerPipelineHandler.swift
Labels: 🔼 needs-minor-version-bump

#752 Actually remove promise logging info.
  Sources/NIO/EventLoop.swift
Labels: patch-version-bump-only

#673 RFC: declare public API
  README.md
  docs/public-api.md
Labels: ⚠️ needs-major-version-bump

#745 Fix broken test for byte delivery.
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
Labels: patch-version-bump-only

#759 actually enable warnings as errors
  docker/docker-compose.1804.50.yaml
Labels: patch-version-bump-only

#765 define NIO_CI_BUILD in the CI builds
  docker/docker-compose.1804.50.yaml
  docker/docker-compose.yaml
Labels: patch-version-bump-only

#758 provide _NIO1APIShims
  Package.swift
  Sources/_NIO1APIShims/NIO1APIShims.swift
Labels: ⚠️ needs-major-version-bump

#760 rename ELF.then to ELF.flatMap
  IntegrationTests/tests_04_performance/test_01_resources/template/Sources/SwiftBootstrap/SwiftMain.swift
  Sources/NIO/Bootstrap.swift
  Sources/NIO/ChannelPipeline.swift
  Sources/NIO/EventLoop.swift
  Sources/NIO/EventLoopFuture.swift
  Sources/NIO/NonBlockingFileIO.swift
  Sources/NIO/Selector.swift
  Sources/NIO/SocketChannel.swift
  Sources/NIOChatServer/main.swift
  Sources/NIOEchoServer/main.swift
  Sources/NIOHTTP1/HTTPServerPipelineHandler.swift
  Sources/NIOHTTP1/HTTPUpgradeHandler.swift
  Sources/NIOHTTP1Server/main.swift
  Sources/NIOMulticastChat/main.swift
  Sources/NIOPerformanceTester/main.swift
  Sources/NIOWebSocket/WebSocketUpgrader.swift
  Sources/NIOWebSocketServer/main.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
  Tests/NIOHTTP1Tests/HTTPServerClientTest.swift
  Tests/NIOHTTP1Tests/HTTPServerProtocolErrorHandlerTest.swift
  Tests/NIOHTTP1Tests/HTTPTest.swift
  Tests/NIOHTTP1Tests/HTTPUpgradeTests.swift
  Tests/NIOTests/AcceptBackoffHandlerTest.swift
  Tests/NIOTests/ChannelNotificationTest.swift
  Tests/NIOTests/ChannelPipelineTest.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/CodecTest.swift
  Tests/NIOTests/DatagramChannelTests.swift
  Tests/NIOTests/EchoServerClientTest.swift
  Tests/NIOTests/EventLoopFutureTest+XCTest.swift
  Tests/NIOTests/EventLoopFutureTest.swift
  Tests/NIOTests/EventLoopTest.swift
  Tests/NIOTests/FileRegionTest.swift
  Tests/NIOTests/HappyEyeballsTest.swift
  Tests/NIOTests/IdleStateHandlerTest.swift
  Tests/NIOTests/MulticastTest.swift
  Tests/NIOTests/SocketChannelTest.swift
  Tests/NIOTests/SocketOptionProviderTest.swift
  Tests/NIOWebSocketTests/WebSocketFrameDecoderTest.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#768 provide NIO1 API shim for ELF.then*
  Sources/_NIO1APIShims/NIO1APIShims.swift
Labels: patch-version-bump-only

#766 Allow setting of RemoveAfterUpgradeStrategy
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOHTTP1/HTTPPipelineSetup.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
Labels: 🔼 needs-minor-version-bump

#762 [1.12 backport] speed up getBytes
  Sources/NIO/ByteBuffer-aux.swift
Labels: patch-version-bump-only

#771 NIO1 API Shims: Forgotten deprecation warning
  Sources/_NIO1APIShims/NIO1APIShims.swift
Labels: patch-version-bump-only

#744 Allow to set RemoveAfterUpgradeStrategy on HTTPResponseDecoder
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOHTTP1/HTTPPipelineSetup.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
Labels: 🔼 needs-minor-version-bump

#775 fixed small typo
  README.md
Labels: patch-version-bump-only

#776 remove ELP.succeed/fail's labels
  IntegrationTests/tests_04_performance/test_01_resources/template/Sources/SwiftBootstrap/SwiftMain.swift
  Sources/NIO/BaseSocketChannel.swift
  Sources/NIO/BlockingIOThreadPool.swift
  Sources/NIO/Bootstrap.swift
  Sources/NIO/Channel.swift
  Sources/NIO/ChannelPipeline.swift
  Sources/NIO/Codec.swift
  Sources/NIO/DeadChannel.swift
  Sources/NIO/Embedded.swift
  Sources/NIO/EventLoop.swift
  Sources/NIO/EventLoopFuture.swift
  Sources/NIO/GetaddrinfoResolver.swift
  Sources/NIO/HappyEyeballs.swift
  Sources/NIO/NonBlockingFileIO.swift
  Sources/NIO/PendingDatagramWritesManager.swift
  Sources/NIO/PendingWritesManager.swift
  Sources/NIO/Selector.swift
  Sources/NIO/SocketChannel.swift
  Sources/NIOHTTP1/HTTPResponseCompressor.swift
  Sources/NIOHTTP1/HTTPUpgradeHandler.swift
  Sources/NIOMulticastChat/main.swift
  Sources/NIOPerformanceTester/main.swift
  Sources/_NIO1APIShims/NIO1APIShims.swift
  Tests/NIOHTTP1Tests/HTTPTest.swift
  Tests/NIOHTTP1Tests/HTTPUpgradeTests.swift
  Tests/NIOTLSTests/ApplicationProtocolNegotiationHandlerTests.swift
  Tests/NIOTLSTests/SNIHandlerTests.swift
  Tests/NIOTests/AcceptBackoffHandlerTest.swift
  Tests/NIOTests/BootstrapTest.swift
  Tests/NIOTests/ChannelNotificationTest.swift
  Tests/NIOTests/ChannelOptionStorageTest.swift
  Tests/NIOTests/ChannelPipelineTest.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/CodecTest.swift
  Tests/NIOTests/CustomChannelTests.swift
  Tests/NIOTests/DatagramChannelTests.swift
  Tests/NIOTests/EchoServerClientTest.swift
  Tests/NIOTests/EmbeddedChannelTest.swift
  Tests/NIOTests/EventLoopFutureTest.swift
  Tests/NIOTests/EventLoopTest.swift
  Tests/NIOTests/HappyEyeballsTest.swift
  Tests/NIOTests/MulticastTest.swift
  Tests/NIOTests/NonBlockingFileIOTest.swift
  Tests/NIOTests/SelectorTest.swift
  Tests/NIOTests/SocketChannelTest.swift
  Tests/NIOTests/TestUtils.swift
  Tests/NIOWebSocketTests/EndToEndTests.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#777 rename ELF.mapIfError to ELF.recover
  IntegrationTests/tests_04_performance/test_01_resources/template/Sources/SwiftBootstrap/SwiftMain.swift
  Sources/NIO/EventLoop.swift
  Sources/NIO/EventLoopFuture.swift
  Sources/NIO/HappyEyeballs.swift
  Sources/_NIO1APIShims/NIO1APIShims.swift
  Tests/NIOHTTP1Tests/HTTPServerClientTest.swift
  Tests/NIOTests/EchoServerClientTest.swift
  Tests/NIOTests/EmbeddedEventLoopTest.swift
  Tests/NIOTests/EventLoopFutureTest.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#778 provide ELF.flatMapResult
  Sources/NIO/EventLoop.swift
  Sources/NIO/EventLoopFuture.swift
  Tests/NIOTests/EventLoopFutureTest+XCTest.swift
  Tests/NIOTests/EventLoopFutureTest.swift
Labels: ⚠️ needs-major-version-bump

#773 Add `whenAllComplete` EventLoopFuture method
  Sources/NIO/EventLoopFuture.swift
  Tests/NIOTests/EventLoopFutureTest+XCTest.swift
  Tests/NIOTests/EventLoopFutureTest.swift
Labels: 🔼 needs-minor-version-bump

#782 alloc tests: hook posix_memalign & reallocf
  IntegrationTests/tests_04_performance/test_01_resources/template/HookedFunctions/Sources/HookedFunctions/include/hooked-functions.h
  IntegrationTests/tests_04_performance/test_01_resources/template/HookedFunctions/Sources/HookedFunctions/src/hooked-functions.c
  IntegrationTests/tests_04_performance/test_01_resources/template/Sources/bootstrap/main.c
Labels: patch-version-bump-only

#770 Add deadlines as an alternative to timeouts
  Sources/NIO/ChannelHandlers.swift
  Sources/NIO/Embedded.swift
  Sources/NIO/EventLoop.swift
  Sources/NIO/NonBlockingFileIO.swift
  Sources/NIO/Selector.swift
  Sources/NIOWebSocketServer/main.swift
  Tests/NIOHTTP1Tests/HTTPDecoderLengthTest.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
  Tests/NIOHTTP1Tests/HTTPUpgradeTests.swift
  Tests/NIOTests/AcceptBackoffHandlerTest.swift
  Tests/NIOTests/EventLoopTest.swift
  Tests/NIOTests/SocketChannelTest.swift
  Tests/NIOTests/TestUtils.swift
Labels: ⚠️ needs-major-version-bump

#780 CI: use DEVELOPMENT-SNAPSHOT-2019-01-23-a
  Sources/NIOHTTP1/HTTPEncoder.swift
  docker/docker-compose.1804.50.yaml
Labels: patch-version-bump-only

#785 malloc-aggregation.d: don't forget posix_memalign
  dev/malloc-aggregation.d
Labels: patch-version-bump-only

#791 README: update requirements
  README.md
Labels: ⚠️ needs-major-version-bump

#792 address Norman's B2MD feedback
  Sources/NIO/Codec.swift
Labels: patch-version-bump-only

#750 rename HTTPProtocolUpgrader to HTTPServerProtocolUpgrader
  .gitignore
  Sources/NIOHTTP1/HTTPPipelineSetup.swift
  Sources/NIOHTTP1/HTTPUpgradeHandler.swift
  Sources/NIOWebSocket/WebSocketUpgrader.swift
  Sources/_NIO1APIShims/NIO1APIShims.swift
  Tests/NIOHTTP1Tests/HTTPUpgradeTests.swift
  Tests/NIOWebSocketTests/EndToEndTests.swift
  docs/public-api-changes-NIO1-to-NIO2.md
Labels: ⚠️ needs-major-version-bump

#794 Make use of dropFirst(_:) in example code
  Sources/NIOChatClient/main.swift
  Sources/NIOEchoClient/main.swift
  Sources/NIOEchoServer/main.swift
  Sources/NIOHTTP1Server/main.swift
Labels: patch-version-bump-only

#795 fix #657
  Sources/NIO/System.swift
  Tests/NIOTests/ChannelTests.swift
Labels: patch-version-bump-only
