Repository apple/swift-nio, pull requests merged in 2020-08, with the labels that each got.

#1606 Add doc comment about potential of events to arrive out of order.
  Sources/NIO/ChannelPipeline.swift
Labels: needs-no-version-bump

#1609 Define public EventLoopGroupProvider type
  Sources/NIO/EventLoop.swift
  Tests/NIOTests/EventLoopTest+XCTest.swift
  Tests/NIOTests/EventLoopTest.swift
Labels: 🔼 needs-minor-version-bump

#1610 Deprecate and replace `ByteBuffer.clear(minimumCapacity: _Capacity)`
  Sources/NIO/ByteBuffer-core.swift
Labels: 🔼 needs-minor-version-bump

#1614 Reduce refcounting in Heap by removing configurability
  Sources/NIO/Embedded.swift
  Sources/NIO/Heap.swift
  Sources/NIO/PriorityQueue.swift
  Sources/NIO/SelectableEventLoop.swift
  Tests/NIOTests/HeapTests.swift
  Tests/NIOTests/PriorityQueueTests+XCTest.swift
  Tests/NIOTests/PriorityQueueTests.swift
Labels: patch-version-bump-only

#1615 Support writing ContiguousBytes and DataProtocol to ByteBuffers
  Sources/NIOFoundationCompat/ByteBuffer-foundation.swift
  Tests/LinuxMain.swift
  Tests/NIOFoundationCompatTests/ByteBufferDataProtocolTests+XCTest.swift
  Tests/NIOFoundationCompatTests/ByteBufferDataProtocolTests.swift
Labels: 🔼 needs-minor-version-bump

#1598 Recover from EINVAL even if the error is untyped
  Sources/NIO/FileDescriptor.swift
  Sources/NIO/SocketChannel.swift
  Sources/NIO/SocketProtocols.swift
  Sources/NIO/System.swift
  Tests/NIOTests/SocketChannelTest.swift
Labels: bug

#1621 Linux: make `Epoll` available on Android
  Sources/NIO/Linux.swift
Labels: patch-version-bump-only

#1613 Minor build_podspecs.sh usage tweak.
  scripts/build_podspecs.sh
Labels: needs-no-version-bump

#1622 Replace NIONetworkInterface with NIONetworkDevice.
  Sources/NIO/Channel.swift
  Sources/NIO/Interfaces.swift
  Sources/NIO/MulticastChannel.swift
  Sources/NIO/SocketChannel.swift
  Sources/NIO/Utilities.swift
  Sources/NIOMulticastChat/main.swift
  Tests/NIOTests/DatagramChannelTests.swift
  Tests/NIOTests/MulticastTest+XCTest.swift
  Tests/NIOTests/MulticastTest.swift
  Tests/NIOTests/SocketOptionProviderTest.swift
  Tests/NIOTests/TestUtils.swift
  Tests/NIOTests/UtilitiesTest+XCTest.swift
  Tests/NIOTests/UtilitiesTest.swift
Labels: 🔼 needs-minor-version-bump

#1624 Better handle writability changes in triggerWriteOperations
  Sources/NIO/PendingDatagramWritesManager.swift
  Sources/NIO/PendingWritesManager.swift
  Tests/NIOTests/ChannelTests+XCTest.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/DatagramChannelTests+XCTest.swift
  Tests/NIOTests/DatagramChannelTests.swift
Labels: patch-version-bump-only

#1625 Add @inlinable to all BBV methods.
  Sources/NIO/ByteBuffer-views.swift
Labels: patch-version-bump-only
