Repository apple/swift-nio, pull requests merged in 2020-09, with the labels that each got.

#1628 Correct typo in `_ChannelOutboundHandler` docs
  Sources/NIO/ChannelHandler.swift
Labels: patch-version-bump-only

#1627 Remove incorrect assertion in MarkedCircularBuffer.popFirst
  Sources/NIO/MarkedCircularBuffer.swift
  Tests/NIOTests/MarkedCircularBufferTests+XCTest.swift
  Tests/NIOTests/MarkedCircularBufferTests.swift
Labels: patch-version-bump-only

#1630 Note that certain NIOFileHandle.init overloads are blocking
  Sources/NIO/FileHandle.swift
Labels: needs-no-version-bump

#1636 NIO: repair the build after e3508b0d0
  Sources/NIO/BSDSocketAPI.swift
  Sources/NIO/BSDSocketAPIPosix.swift
  Sources/NIO/BSDSocketAPIWindows.swift
Labels: patch-version-bump-only

#1634 NIO: remove unnecessary `@discardableResult`
  Sources/NIO/BSDSocketAPIWindows.swift
Labels: patch-version-bump-only

#1635 NIO: remove `poll` from the `_BSDSocketProtocol` protocol
  Sources/NIO/BSDSocketAPI.swift
  Sources/NIO/BSDSocketAPIWindows.swift
Labels: patch-version-bump-only

#1633 NIO: fix `close(socket:)`
  Sources/NIO/BSDSocketAPIWindows.swift
Labels: patch-version-bump-only

#1631 Swift 5.3-RELEASE is out, let's use it.
  docker/docker-compose.1604.53.yaml
Labels: needs-no-version-bump

#1639 CNIOWindows: preprocess away WinSock support code
  Sources/CNIOWindows/WSAStartup.c
Labels: patch-version-bump-only

#1638 build: add `CNIOWindows` to Package.swift
  Package.swift
Labels: 🔼 needs-minor-version-bump

#1641 Increases default initial size for `AdaptiveRecvByteBufferAllocator`
  Sources/NIO/RecvByteBufferAllocator.swift
  Tests/NIOTests/SALChannelTests.swift
Labels: patch-version-bump-only

#1637 Cleanup unix socket pathname on server socket close or bind
  Sources/NIO/BaseSocket.swift
  Sources/NIO/Bootstrap.swift
  Sources/NIO/ServerSocket.swift
  Sources/NIO/SocketAddresses.swift
  Sources/NIO/System.swift
  Tests/NIOTests/EchoServerClientTest+XCTest.swift
  Tests/NIOTests/EchoServerClientTest.swift
Labels: 🔼 needs-minor-version-bump

#1645 CNIOWindows: add stubs for `sendmmsg` and `recvmmsg`
  Sources/CNIOWindows/include/CNIOWindows.h
  Sources/CNIOWindows/shim.c
Labels: patch-version-bump-only

#1646 CNIOWindows: correct declaration
  Sources/CNIOWindows/shim.c
Labels: patch-version-bump-only

#1642 Scheduling tasks Int.max ns into future results in an obtuse fatal error (#1056)
  Sources/NIO/EventLoop.swift
  Sources/NIO/Selector.swift
  Tests/NIOTests/EventLoopTest+XCTest.swift
  Tests/NIOTests/EventLoopTest.swift
Labels: patch-version-bump-only

#1651 We use main as our development branch now.
  CONTRIBUTING.md
  IntegrationTests/allocation-counter-tests-framework/run-allocation-counter.sh
  IntegrationTests/allocation-counter-tests-framework/template/HookedFunctionsDoHook/Package.swift
  IntegrationTests/allocation-counter-tests-framework/template/HookedFunctionsDoNotHook/Package.swift
  README.md
  docker/Dockerfile
  docs/debugging-allocations.md
  docs/migration-guide-NIO1-to-NIO2.md
  docs/optimization-tips.md
  scripts/check_no_api_breakages.sh
  scripts/generate_linux_tests.rb
Labels: needs-no-version-bump

#1652 NIO: add import for the C library for Windows
  Sources/NIO/ByteBuffer-core.swift
Labels: patch-version-bump-only

#1629 Distinguish capacity and no. of addressable bytes. (#1485)
  Sources/NIO/ByteBuffer-core.swift
  Tests/NIOTests/ByteBufferTest.swift
  Tests/NIOTests/NIOAnyDebugTest.swift
Labels: 🔼 needs-minor-version-bump

#1657 NIO: make BSDSocketAPI build on Windows
  Sources/NIO/BSDSocketAPI.swift
Labels: patch-version-bump-only

#1660 NIO: invalid sockets are not `-1` but `INVALID_SOCKET`
  Sources/NIO/BaseSocket.swift
Labels: patch-version-bump-only

#1659 NIO: improvements to Windows BSD API
  Sources/NIO/BSDSocketAPIWindows.swift
Labels: patch-version-bump-only

#1658 NIO: shave off parts of System
  Sources/NIO/System.swift
Labels: patch-version-bump-only

#1661 NIO: implement address resolution for Windows
  Sources/NIO/SocketAddresses.swift
Labels: patch-version-bump-only

#1662 Provide a convenience API for dispatching blocking work
  Sources/NIO/DispathQueue+WithFuture.swift
  Sources/NIO/EventLoopFuture.swift
  Tests/LinuxMain.swift
  Tests/NIOTests/DispatchQueue+WithFutureTest+XCTest.swift
  Tests/NIOTests/DispatchQueue+WithFutureTest.swift
  Tests/NIOTests/EventLoopFutureTest+XCTest.swift
  Tests/NIOTests/EventLoopFutureTest.swift
Labels: 🔼 needs-minor-version-bump

#1663 Minor cleanups of Windows compatability code.
  Sources/NIO/BSDSocketAPI.swift
  Sources/NIO/BaseSocket.swift
  Sources/NIO/SocketProtocols.swift
Labels: patch-version-bump-only
