Repository apple/swift-nio, pull requests merged in 2020-10, with the labels that each got.

#1665 Print the usage if no args are provided to the build_podspecs script
  scripts/build_podspecs.sh
Labels: needs-no-version-bump

#1666 NIOUDPEchoServer use AddressedEnvelope as InboundIn and OutboundOut
  Sources/NIOUDPEchoServer/main.swift
Labels: needs-no-version-bump

#1667 NIO: correct return value for messaging on Windows
  Sources/NIO/BSDSocketAPIWindows.swift
Labels: patch-version-bump-only

#1664 HTTPObjectAggregator implementation
  Sources/NIOHTTP1/HTTPTypes.swift
  Sources/NIOHTTP1/NIOHTTPObjectAggregator.swift
  Tests/LinuxMain.swift
  Tests/NIOHTTP1Tests/NIOHTTPObjectAggregatorTest+XCTest.swift
  Tests/NIOHTTP1Tests/NIOHTTPObjectAggregatorTest.swift
Labels: 🔼 needs-minor-version-bump

#1672 Fix incorrect new names for deprecated APIs
  Sources/NIO/Bootstrap.swift
Labels: patch-version-bump-only

#1669 NIO: carve away more of `System.swift` on Windows
  Sources/NIO/System.swift
Labels: patch-version-bump-only

#1668 NIO: silence error on Windows
  Sources/NIO/BaseSocket.swift
  Sources/NIO/SocketProtocols.swift
Labels: patch-version-bump-only

#1675 NIO: expose `LINGER` as a public type on Windows
  Sources/NIO/BSDSocketAPIWindows.swift
Labels: patch-version-bump-only

#1677 NIO: reflow some comments (NFC)
  Sources/NIO/BSDSocketAPI.swift
Labels: needs-no-version-bump

#1678 NIO: extract control message handling into a separate protocol
  Sources/CNIOWindows/include/CNIOWindows.h
  Sources/CNIOWindows/shim.c
  Sources/NIO/BSDSocketAPI.swift
  Sources/NIO/BSDSocketAPIPosix.swift
  Sources/NIO/BSDSocketAPIWindows.swift
  Sources/NIO/ControlMessage.swift
  Sources/NIO/System.swift
  Tests/NIOTests/SystemTest.swift
Labels: patch-version-bump-only

#1674 NIO: implement `sendmsg` and `recvmsg` on Windows
  Sources/NIO/BSDSocketAPI.swift
  Sources/NIO/BSDSocketAPIPosix.swift
  Sources/NIO/BSDSocketAPIWindows.swift
  Sources/NIO/Socket.swift
Labels: patch-version-bump-only

#1679 Add watchOS deployment to PodSpec build script
  README.md
  scripts/build_podspecs.sh
Labels: needs-no-version-bump

#1647 NIO: implement network interface enumeration for Windows
  Sources/NIO/Interfaces.swift
  Sources/NIO/MulticastChannel.swift
  Sources/NIO/SocketChannel.swift
  Sources/NIO/Utilities.swift
Labels: patch-version-bump-only
