Repository apple/swift-nio, pull requests merged in 2020-07, with the labels that each got.

#1584 fix incorrect case when removing an element from a circular buffer
  Sources/NIO/CircularBuffer.swift
Labels: patch-version-bump-only

#1473 Move DatagramChannel over to using recvmsg.
  Sources/NIO/BSDSocketAPI.swift
  Sources/NIO/BSDSocketAPIPosix.swift
  Sources/NIO/BSDSocketAPIWindows.swift
  Sources/NIO/PipePair.swift
  Sources/NIO/Socket.swift
  Sources/NIO/SocketChannel.swift
  Sources/NIO/SocketProtocols.swift
  Sources/NIO/System.swift
  Tests/NIOTests/DatagramChannelTests+XCTest.swift
  Tests/NIOTests/DatagramChannelTests.swift
Labels: patch-version-bump-only

#1588 Improve pointer hygeine in SocketAddresses.swift
  Sources/NIO/SocketAddresses.swift
Labels: patch-version-bump-only

#1587 Use sendmsg rather than sendto to send UDP data.
  Sources/NIO/BSDSocketAPI.swift
  Sources/NIO/BSDSocketAPIPosix.swift
  Sources/NIO/BSDSocketAPIWindows.swift
  Sources/NIO/PipePair.swift
  Sources/NIO/Socket.swift
  Sources/NIO/SocketChannel.swift
  Sources/NIO/SocketProtocols.swift
  Sources/NIO/System.swift
Labels: patch-version-bump-only

#1591 Allow Metadata to be constructed and set on AddressedEnvelope
  Sources/NIO/AddressedEnvelope.swift
Labels: 🔼 needs-minor-version-bump

#1593 Plumb metadata through PendingDatagramWritesManager.
  Sources/NIO/PendingDatagramWritesManager.swift
  Sources/NIO/SocketChannel.swift
  Tests/NIOTests/PendingDatagramWritesManagerTests.swift
Labels: patch-version-bump-only

#1594 Setup allocation test to send and receive ECN data.
  IntegrationTests/tests_04_performance/test_01_resources/test_1000_udp_reqs.swift
Labels: needs-no-version-bump

#1597 Don't install Jazzy on Xenial
  docker/Dockerfile
  docker/docker-compose.1604.53.yaml
Labels: needs-no-version-bump

#1604 Don't use deadbeef for dead pointers.
  Sources/NIO/ControlMessage.swift
Labels: patch-version-bump-only

#1605 Avoid including non-modular headers.
  Sources/CNIODarwin/include/CNIODarwin.h
  Sources/CNIODarwin/shim.c
  Sources/NIO/ControlMessage.swift
  Sources/NIO/System.swift
Labels: patch-version-bump-only
