Repository apple/swift-nio, pull requests merged in 2021-06, with the labels that each got.

#1865 Fix spelling of detach
  Sources/NIOAsyncAwaitDemo/main.swift
  Sources/_NIOConcurrency/AsyncAwaitSupport.swift
Labels: needs-no-version-bump

#1863 Add performance test for web socket client random request key
  Sources/NIOPerformanceTester/main.swift
Labels: needs-no-version-bump

#1822 http_parser: update vendored copy
  Sources/CNIOHTTPParser/c_nio_http_parser.c
  Sources/CNIOHTTPParser/include/c_nio_http_parser.h
Labels: patch-version-bump-only

#1845 add Swift 5.5 job
  Sources/NIOAsyncAwaitDemo/main.swift
  Sources/_NIOConcurrency/AsyncAwaitSupport.swift
  dev/update-alloc-limits-to-last-completed-ci-build
  docker/docker-compose.2004.55.yaml
Labels: needs-no-version-bump

#1866 Work around awkward SO_TIMESTAMP definition.
  Sources/CNIOLinux/include/CNIOLinux.h
  Sources/CNIOLinux/shim.c
  Sources/NIO/System.swift
Labels: patch-version-bump-only

#1868 Made the extern to const in CNIODarwin
  Sources/CNIODarwin/include/CNIODarwin.h
  Sources/CNIODarwin/shim.c
Labels: patch-version-bump-only

#1869 Made the externs const in CNIOLinux
  Sources/CNIOLinux/include/CNIOLinux.h
  Sources/CNIOLinux/shim.c
Labels: patch-version-bump-only

#1862 Improving performance of base64 encoding by about 10%
  Sources/NIOWebSocket/Base64.swift
Labels: patch-version-bump-only

#1872 Update _NIOConcurrency for Swift 5.5 latest changes
  Sources/_NIOConcurrency/AsyncAwaitSupport.swift
  Sources/_NIOConcurrency/Helpers.swift
Labels: needs-no-version-bump

#1873 #1714 Update Codec.swift
  Sources/NIO/Codec.swift
Labels: needs-no-version-bump

#1876 Concurrency features are runtime-specific.
  Sources/_NIOConcurrency/AsyncAwaitSupport.swift
Labels: needs-no-version-bump

#1877 Fix tests for 32-bit platforms, tested for Android armv7
  Sources/NIO/IntegerTypes.swift
  Sources/NIO/RecvByteBufferAllocator.swift
  Tests/NIOTests/RecvByteBufAllocatorTest.swift
  Tests/NIOTests/SystemTest.swift
Labels: patch-version-bump-only

#1879 Add async implementation of EventLoopGroup.shutdownGracefully to _NIOConcurrency
  Sources/NIOAsyncAwaitDemo/main.swift
  Sources/_NIOConcurrency/AsyncAwaitSupport.swift
Labels: needs-no-version-bump

#1860 Make Swift 5.2 the minimum requirement
  CONTRIBUTING.md
  Package.swift
  README.md
  dev/update-alloc-limits-to-last-completed-ci-build
  docker/Dockerfile
  docker/docker-compose.1804.50.yaml
  docker/docker-compose.1804.51.yaml
  docker/docker-compose.1804.52.yaml
  docs/migration-guide-NIO1-to-NIO2.md
  scripts/build_podspecs.sh
  scripts/check_no_api_breakages.sh
Labels: 🔼 needs-minor-version-bump

#1881 docs: formatting comments with double slash
  Sources/NIO/ChannelHandlers.swift
  Sources/NIO/SocketChannel.swift
Labels: needs-no-version-bump

#1886 Adds Equatable and ExpressibleByArrayLiteral conformance to ByteBufferView
  Sources/NIO/ByteBuffer-views.swift
  Tests/NIOTests/ByteBufferTest+XCTest.swift
  Tests/NIOTests/ByteBufferTest.swift
Labels: 🔼 needs-minor-version-bump
