Repository apple/swift-nio, pull requests merged in 2021-04, with the labels that each got.

#1791 fix #if AsyncAwait check
  Sources/_NIOConcurrency/Helpers.swift
Labels: patch-version-bump-only

#1793 Add custom cleanup hook to allow PipeChannel to properly deregister during halfclose
  Sources/NIO/BaseStreamSocketChannel.swift
  Sources/NIO/PipeChannel.swift
Labels: patch-version-bump-only

#1794 Add 'promise' versions of EventLoopFuture.{and,when}All{succeed,complete}
  Sources/NIO/EventLoopFuture.swift
  Tests/NIOTests/EventLoopFutureTest.swift
Labels: 🔼 needs-minor-version-bump

#1796 Update documentation related to allocation troubleshooting on Linux and the ability to run unit tests in parallel
  README.md
  docs/debugging-allocations.md
Labels: needs-no-version-bump

#1798 Create `EmbeddedChannel` with multiple handlers
  Sources/NIO/Embedded.swift
  Tests/NIOTests/EmbeddedChannelTest+XCTest.swift
  Tests/NIOTests/EmbeddedChannelTest.swift
Labels: 🔼 needs-minor-version-bump

#1795 Split Selector into separate files per backend.
  Sources/NIO/EventLoop.swift
  Sources/NIO/Selector.swift
  Sources/NIO/SelectorEpoll.swift
  Sources/NIO/SelectorGeneric.swift
  Sources/NIO/SelectorKqueue.swift
  Tests/NIOTests/SyscallAbstractionLayer.swift
Labels: patch-version-bump-only

#1797 Fix bug in eventfd(initval: Int32, flags: Int32)
  Sources/NIO/Linux.swift
Labels: patch-version-bump-only

#1799 Add sequenceIdentifier to Registrations to handle outdated events
  Sources/NIO/BaseSocket.swift
  Sources/NIO/EventLoop.swift
  Sources/NIO/PipeChannel.swift
  Sources/NIO/SelectableEventLoop.swift
  Sources/NIO/SelectorEpoll.swift
  Sources/NIO/SelectorGeneric.swift
  Sources/NIO/SelectorKqueue.swift
  Sources/NIO/SocketChannel.swift
  Tests/NIOTests/SALChannelTests.swift
  Tests/NIOTests/SelectorTest.swift
  Tests/NIOTests/SyscallAbstractionLayer.swift
Labels: patch-version-bump-only

#1803 Change redundant 'public' access modifiers
  Sources/NIO/Linux.swift
  Sources/NIO/System.swift
Labels: patch-version-bump-only

#1806 support qemu: qemu returns ENOPROTOOPT for unknown socket opts
  Tests/NIOTests/SystemTest.swift
Labels: needs-no-version-bump

#1809 Wrap concurrency code with @available(macOS 9999, etc)
  Sources/NIOAsyncAwaitDemo/AsyncChannelIO.swift
  Sources/NIOAsyncAwaitDemo/main.swift
  Sources/_NIOConcurrency/AsyncAwaitSupport.swift
Labels: needs-no-version-bump

#1810 fix compilation on Ubuntu 14.04 and other old Linuxes
  Sources/NIO/Linux.swift
Labels: patch-version-bump-only

#1812 alloc-limits-from-test-output: support more formats
  dev/alloc-limits-from-test-output
Labels: needs-no-version-bump

#1813 Fix crash: Create ByteBuffer Slice from ByteBuffer Slice after 16MB
  Sources/NIO/ByteBuffer-core.swift
  Tests/NIOTests/ByteBufferTest+XCTest.swift
  Tests/NIOTests/ByteBufferTest.swift
Labels: patch-version-bump-only

#1814 implement CircularBuffer.first: to prevent allocs
  Sources/NIO/CircularBuffer.swift
  Tests/NIOTests/CircularBufferTests+XCTest.swift
  Tests/NIOTests/CircularBufferTests.swift
  docker/docker-compose.1604.52.yaml
  docker/docker-compose.1604.53.yaml
  docker/docker-compose.1804.50.yaml
  docker/docker-compose.1804.51.yaml
  docker/docker-compose.2004.54.yaml
  docker/docker-compose.2004.main.yaml
  docs/workarounds.md
Labels: patch-version-bump-only

#1801 refactor registration IDs
  Sources/NIO/BaseSocket.swift
  Sources/NIO/EventLoop.swift
  Sources/NIO/IntegerBitPacking.swift
  Sources/NIO/PipeChannel.swift
  Sources/NIO/SelectableEventLoop.swift
  Sources/NIO/SelectorEpoll.swift
  Sources/NIO/SelectorGeneric.swift
  Sources/NIO/SelectorKqueue.swift
  Sources/NIO/SocketChannel.swift
  Tests/NIOTests/IntegerBitPackingTests+XCTest.swift
  Tests/NIOTests/IntegerBitPackingTests.swift
  Tests/NIOTests/SALChannelTests.swift
  Tests/NIOTests/SelectorTest.swift
  Tests/NIOTests/StreamChannelsTest.swift
  Tests/NIOTests/SyscallAbstractionLayer.swift
Labels: patch-version-bump-only

#1815 Selectors: make file descriptors CInts everywhere
  Sources/NIO/Linux.swift
  Sources/NIO/PipePair.swift
  Sources/NIO/SelectorEpoll.swift
  Sources/NIO/SelectorGeneric.swift
  Sources/NIO/SelectorKqueue.swift
  Sources/NIO/Socket.swift
  Sources/NIO/SocketProtocols.swift
Labels: patch-version-bump-only

#1817 script to download & apply alloc limits from Jenkins
  dev/update-alloc-limits-to-last-completed-ci-build
Labels: needs-no-version-bump

#1816 Less allocs during `flatMapErrorThrowing` and `flatMapThrowing`
  Sources/NIO/EventLoopFuture.swift
  docker/docker-compose.1604.52.yaml
  docker/docker-compose.1604.53.yaml
  docker/docker-compose.1804.50.yaml
  docker/docker-compose.1804.51.yaml
  docker/docker-compose.2004.54.yaml
  docker/docker-compose.2004.main.yaml
Labels: patch-version-bump-only

#1818 Reducing allocations in future chains
  Sources/NIO/EventLoopFuture.swift
  docker/docker-compose.1604.52.yaml
  docker/docker-compose.1604.53.yaml
  docker/docker-compose.1804.50.yaml
  docker/docker-compose.1804.51.yaml
  docker/docker-compose.2004.54.yaml
  docker/docker-compose.2004.main.yaml
Labels: patch-version-bump-only

#1819 Implement reserveCapacity for CircularBuffer.
  Sources/NIO/CircularBuffer.swift
  Tests/NIOTests/CircularBufferTests+XCTest.swift
  Tests/NIOTests/CircularBufferTests.swift
Labels: patch-version-bump-only

#1821 CI: print out version info
  docker/docker-compose.yaml
Labels: needs-no-version-bump

#1826 Stop measuring alloc counts on 5.0
  dev/update-alloc-limits-to-last-completed-ci-build
  docker/docker-compose.1604.53.yaml
  docker/docker-compose.1804.50.yaml
Labels: needs-no-version-bump

#1820 Reduce selector wakeups.
  Sources/NIO/SelectableEventLoop.swift
  Sources/NIO/SelectorEpoll.swift
  Sources/NIO/SelectorGeneric.swift
  Sources/NIO/SelectorKqueue.swift
  Tests/LinuxMain.swift
  Tests/NIOTests/SALEventLoopTests+XCTest.swift
  Tests/NIOTests/SALEventLoopTests.swift
  Tests/NIOTests/SelectorTest.swift
  Tests/NIOTests/SyscallAbstractionLayer.swift
Labels: patch-version-bump-only

#1804 Added second implementation of liburing as discussed in #1761.
  Sources/CNIOLinux/include/CNIOLinux.h
  Sources/CNIOLinux/include/liburing_nio.h
  Sources/CNIOLinux/liburing_shims.c
  Sources/NIO/BaseSocketChannel.swift
  Sources/NIO/LinuxUring.swift
  Sources/NIO/SelectorEpoll.swift
  Sources/NIO/SelectorGeneric.swift
  Sources/NIO/SelectorUring.swift
  Tests/NIOTests/StreamChannelsTest.swift
  docs/debugging-allocations.md
  docs/io_uring.md
Labels: 🔼 needs-minor-version-bump

#1833 bring back accidental commented benchmark
  Sources/NIOPerformanceTester/ByteToMessageDecoderDecodeManySmallsBenchmark.swift
Labels: needs-no-version-bump

#1835 ByteBufferTests: some extra tests around withUnsafeMutableReadableBytes
  Tests/NIOTests/ByteBufferTest+XCTest.swift
  Tests/NIOTests/ByteBufferTest.swift
Labels: needs-no-version-bump

#1838 update version support (new floor: Ubuntu 18.04)
  README.md
Labels: needs-no-version-bump

#1837 ByteBuffer: more random tests
  Tests/NIOTests/ByteBufferTest+XCTest.swift
  Tests/NIOTests/ByteBufferTest.swift
Labels: needs-no-version-bump

#1823 WebSocket Frame Aggregator
  Sources/NIOWebSocket/NIOWebSocketFrameAggregator.swift
  Tests/LinuxMain.swift
  Tests/NIOWebSocketTests/NIOWebSocketFrameAggregatorTests+XCTest.swift
  Tests/NIOWebSocketTests/NIOWebSocketFrameAggregatorTests.swift
Labels: 🔼 needs-minor-version-bump
