Repository apple/swift-nio, pull requests merged in 2021-01, with the labels that each got.

#1712 Remove error handling for adding/removing handlers functions
  Sources/NIO/ChannelPipeline.swift
Labels: patch-version-bump-only

#1713 Clean up typo in method argument.
  Sources/NIO/ChannelPipeline.swift
Labels: patch-version-bump-only

#1718 Only use ascii characters in perf test names.
  Sources/NIOPerformanceTester/main.swift
Labels: needs-no-version-bump

#1719 Remove CNIOAtomics and CNIOSHA1 as dependency
  Package.swift
Labels: patch-version-bump-only

#1703 Specialise succeeded Void futures so we allocate less
  Sources/NIO/EventLoop.swift
  Sources/NIO/SelectableEventLoop.swift
  Tests/NIOTests/EventLoopTest+XCTest.swift
  Tests/NIOTests/EventLoopTest.swift
  docker/docker-compose.1604.52.yaml
  docker/docker-compose.1604.53.yaml
  docker/docker-compose.1804.50.yaml
  docker/docker-compose.1804.51.yaml
Labels: 🔼 needs-minor-version-bump

#1723 Add static vars for common HTTP versions
  IntegrationTests/tests_04_performance/test_01_resources/shared.swift
  Sources/NIO/SingleStepByteToMessageDecoder.swift
  Sources/NIOCrashTester/CrashTests+HTTP.swift
  Sources/NIOHTTP1/HTTPServerProtocolErrorHandler.swift
  Sources/NIOHTTP1/HTTPServerUpgradeHandler.swift
  Sources/NIOHTTP1/HTTPTypes.swift
  Sources/NIOHTTP1/NIOHTTPObjectAggregator.swift
  Sources/NIOHTTP1Client/main.swift
  Sources/NIOPerformanceTester/main.swift
  Sources/NIOTestUtils/NIOHTTP1TestServer.swift
  Sources/NIOWebSocketClient/main.swift
  Sources/NIOWebSocketServer/main.swift
  Tests/NIOHTTP1Tests/HTTPClientUpgradeTests.swift
  Tests/NIOHTTP1Tests/HTTPDecoderLengthTest.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
  Tests/NIOHTTP1Tests/HTTPHeadersTest.swift
  Tests/NIOHTTP1Tests/HTTPRequestEncoderTest.swift
  Tests/NIOHTTP1Tests/HTTPResponseEncoderTest.swift
  Tests/NIOHTTP1Tests/HTTPServerClientTest.swift
  Tests/NIOHTTP1Tests/HTTPServerPipelineHandlerTest.swift
  Tests/NIOHTTP1Tests/HTTPServerProtocolErrorHandlerTest.swift
  Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift
  Tests/NIOHTTP1Tests/HTTPTest.swift
  Tests/NIOHTTP1Tests/NIOHTTPObjectAggregatorTest.swift
  Tests/NIOTestUtilsTests/NIOHTTP1TestServerTest.swift
  Tests/NIOWebSocketTests/WebSocketClientEndToEndTests.swift
Labels: patch-version-bump-only

#1728 Use welcoming language
  Sources/CNIOSHA1/c_nio_sha1.c
  Sources/NIOHTTP1/HTTPEncoder.swift
  Sources/NIOTLS/SNIHandler.swift
  Tests/NIOHTTP1Tests/HTTPClientUpgradeTests.swift
  Tests/NIOTests/SocketOptionProviderTest.swift
  docker/docker-compose.yaml
  scripts/soundness.sh
Labels: needs-no-version-bump

#1731 Replace unwelcoming language in sha1
  Sources/CNIOSHA1/c_nio_sha1.c
  Sources/CNIOSHA1/include/CNIOSHA1.h
  Sources/CNIOSHA1/update_and_patch_sha1.sh
Labels: needs-no-version-bump

#1729 B2MD: Fix default memory reclamation strategy to match its documentation
  Sources/NIO/Codec.swift
  Tests/NIOTests/CodecTest.swift
  Tests/NIOTests/SingleStepByteToMessageDecoderTest.swift
Labels: patch-version-bump-only

#1732 Remove last occurrences of sanity
  Sources/CNIOSHA1/update_and_patch_sha1.sh
  docker/docker-compose.yaml
  scripts/soundness.sh
Labels: needs-no-version-bump

#1734 [Android] fix compile error for swift-nio-ssl
  Sources/NIO/ChannelOption.swift
Labels: patch-version-bump-only

#1739 align all functions to make micro benchmarks more stable
  docker/docker-compose.yaml
Labels: needs-no-version-bump

#1733 B2MD: Don't try to reclaim if continuing to parse
  Sources/NIO/Codec.swift
  Sources/NIOPerformanceTester/ByteToMessageDecoderDecodeManySmallsBenchmark.swift
  Sources/NIOPerformanceTester/main.swift
  Tests/NIOTests/CodecTest+XCTest.swift
  Tests/NIOTests/CodecTest.swift
Labels: patch-version-bump-only
