Repository apple/swift-nio, pull requests merged in 2021-07, with the labels that each got.

#1889 ByteBuffer: unconditionally use zero-copy for JSON Decoding
  Sources/NIOFoundationCompat/Codable+ByteBuffer.swift
Labels: patch-version-bump-only

#1888 Feature: Datagram Packet Info
  Package.swift
  Sources/CNIODarwin/include/CNIODarwin.h
  Sources/CNIODarwin/shim.c
  Sources/CNIOLinux/include/CNIOLinux.h
  Sources/CNIOLinux/shim.c
  Sources/NIO/AddressedEnvelope.swift
  Sources/NIO/BSDSocketAPI.swift
  Sources/NIO/ChannelOption.swift
  Sources/NIO/ControlMessage.swift
  Sources/NIO/DatagramVectorReadManager.swift
  Sources/NIO/SocketChannel.swift
  Sources/NIO/System.swift
  Tests/NIOTests/DatagramChannelTests+XCTest.swift
  Tests/NIOTests/DatagramChannelTests.swift
Labels: 🔼 needs-minor-version-bump

#1895 Extract basic data structures to NIOCore.
  Package.swift
  Sources/NIO/ExportCore.swift
  Sources/NIOCore/ByteBuffer-aux.swift
  Sources/NIOCore/ByteBuffer-conversions.swift
  Sources/NIOCore/ByteBuffer-core.swift
  Sources/NIOCore/ByteBuffer-int.swift
  Sources/NIOCore/ByteBuffer-views.swift
  Sources/NIOCore/CircularBuffer.swift
  Sources/NIOCore/IntegerBitPacking.swift
  Sources/NIOCore/IntegerTypes.swift
  Sources/NIOCore/PointerHelpers.swift
  Sources/NIOCore/RecvByteBufferAllocator.swift
  Sources/NIOCore/Utilities.swift
  Tests/NIOTests/ByteBufferTest.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/CircularBufferTests.swift
  Tests/NIOTests/CodecTest.swift
  Tests/NIOTests/IntegerTypesTest.swift
  Tests/NIOTests/PendingDatagramWritesManagerTests.swift
Labels: 🔼 needs-minor-version-bump

#1900 Avoid EventLoopFuture.wait knowing about specific implementations.
  Sources/NIO/Embedded.swift
  Sources/NIO/EventLoop.swift
  Sources/NIO/EventLoopFuture.swift
  Sources/NIO/SelectableEventLoop.swift
Labels: 🔼 needs-minor-version-bump

#1899 Enable all EventLoops to track promise creation.
  Sources/NIO/Embedded.swift
  Sources/NIO/EventLoop.swift
  Sources/NIO/EventLoopFuture.swift
  Sources/NIO/SelectableEventLoop.swift
Labels: 🔼 needs-minor-version-bump

#1903 Provide a fallback date for new files.
  scripts/generate_linux_tests.rb
Labels: needs-no-version-bump

#1904 Avoid syncShutdownGracefully knowing about MTELG.
  Sources/NIO/Embedded.swift
  Sources/NIO/EventLoop.swift
  Tests/NIOTests/EventLoopTest.swift
Labels: 🔼 needs-minor-version-bump

#1905 Better default for safe loop shutdown.
  Sources/NIO/EventLoop.swift
  Tests/NIOTests/EventLoopTest.swift
Labels: 🔼 needs-minor-version-bump

#1898 Extract EventLoop protocols and EventLoopFuture to Core
  Sources/NIO/BaseSocketChannel.swift
  Sources/NIO/DeadChannel.swift
  Sources/NIO/MultiThreadedEventLoopGroup.swift
  Sources/NIO/SelectableEventLoop.swift
  Sources/NIOCore/DispatchQueue+WithFuture.swift
  Sources/NIOCore/EventLoop.swift
  Sources/NIOCore/EventLoopFuture.swift
  Tests/NIOTests/EventLoopFutureTest.swift
  Tests/NIOTests/EventLoopTest.swift
Labels: 🔼 needs-minor-version-bump

#1882 docs: link to the SSWG's `perf` guide
  docs/advanced-performance-analysis.md
Labels: needs-no-version-bump

#1887 GetaddrinfoResolver: don't block EventLoops
  Sources/NIO/GetaddrinfoResolver.swift
  Sources/NIO/SocketAddresses.swift
Labels: patch-version-bump-only

#1908 Add more synchronous pipeline operations.
  Sources/NIO/BaseSocketChannel.swift
  Sources/NIO/BaseStreamSocketChannel.swift
  Sources/NIO/ChannelPipeline.swift
  Sources/NIO/Embedded.swift
  Sources/NIO/SocketChannel.swift
  Tests/NIOTests/ChannelPipelineTest+XCTest.swift
  Tests/NIOTests/ChannelPipelineTest.swift
Labels: 🔼 needs-minor-version-bump

#1907 Move SocketAddress and NIOBSDSocket to NIOCore
  IntegrationTests/tests_02_syscall_wrappers/defines.sh
  Sources/NIO/BSDSocketAPICommon.swift
  Sources/NIO/BSDSocketAPIPosix.swift
  Sources/NIO/BSDSocketAPIWindows.swift
  Sources/NIO/BaseSocket.swift
  Sources/NIO/IO.swift
  Sources/NIO/Interfaces.swift
  Sources/NIO/System.swift
  Sources/NIOCore/BSDSocketAPI.swift
  Sources/NIOCore/IO.swift
  Sources/NIOCore/SocketAddresses.swift
  Sources/NIOCore/Utilities.swift
  Tests/NIOTests/HappyEyeballsTest.swift
  Tests/NIOTests/SocketAddressTest+XCTest.swift
  Tests/NIOTests/SocketAddressTest.swift
  Tests/NIOTests/TestUtils.swift
Labels: 🔼 needs-minor-version-bump

#1902 ByteBuffer.writeLengthPrefixed
  Sources/NIOCore/ByteBuffer-lengthPrefix.swift
  Tests/LinuxMain.swift
  Tests/NIOTests/ByteBufferLengthPrefixTests+XCTest.swift
  Tests/NIOTests/ByteBufferLengthPrefixTests.swift
Labels: 🔼 needs-minor-version-bump

#1913 Remove extra whitespace when generating license header for linux tests
  Tests/NIOTests/ByteBufferLengthPrefixTests+XCTest.swift
  scripts/generate_linux_tests.rb
Labels: needs-no-version-bump

#1916 Create ChannelCore.removeHandlers(pipeline:) and use it
  Sources/NIO/BaseSocketChannel.swift
  Sources/NIO/Channel.swift
  Sources/NIO/Embedded.swift
Labels: 🔼 needs-minor-version-bump

#1906 issue-1891: API Addition for JSONSerialization in NIOFoundationCompat
  Sources/NIOFoundationCompat/JSONSerialization+ByteBuffer.swift
  Tests/LinuxMain.swift
  Tests/NIOFoundationCompatTests/JSONSerialization+ByteBufferTest+XCTest.swift
  Tests/NIOFoundationCompatTests/JSONSerialization+ByteBufferTest.swift
Labels: 🔼 needs-minor-version-bump

#1918 Fix the missing socket options for 32-bit.
  Package.swift
  Sources/NIO/System.swift
  Sources/NIOCore/BSDSocketAPI.swift
Labels: patch-version-bump-only

#1919 Add ChannelCore.tryUnwrapAs
  Sources/NIO/Channel.swift
  Sources/NIO/Embedded.swift
Labels: 🔼 needs-minor-version-bump
