Repository apple/swift-nio, pull requests merged in 2021-08, with the labels that each got.

#1920 Move Channel abstractions to NIOCore.
  Sources/NIO/BaseStreamSocketChannel.swift
  Sources/NIO/Bootstrap.swift
  Sources/NIO/Embedded.swift
  Sources/NIO/FileDescriptor.swift
  Sources/NIO/NetworkDevices.swift
  Sources/NIO/SelectableChannel.swift
  Sources/NIO/SocketChannel.swift
  Sources/NIO/Utilities.swift
  Sources/NIOCore/AddressedEnvelope.swift
  Sources/NIOCore/Channel.swift
  Sources/NIOCore/ChannelHandler.swift
  Sources/NIOCore/ChannelInvoker.swift
  Sources/NIOCore/ChannelOption.swift
  Sources/NIOCore/ChannelPipeline.swift
  Sources/NIOCore/DeadChannel.swift
  Sources/NIOCore/FileDescriptor.swift
  Sources/NIOCore/FileHandle.swift
  Sources/NIOCore/FileRegion.swift
  Sources/NIOCore/IO.swift
  Sources/NIOCore/IOData.swift
  Sources/NIOCore/Interfaces.swift
  Sources/NIOCore/NIOAny.swift
  Sources/NIOCore/SystemCallHelpers.swift
  Sources/NIOCore/TypeAssistedChannelHandler.swift
  Tests/NIOTestUtilsTests/ByteToMessageDecoderVerifierTest.swift
  Tests/NIOTests/BaseObjectsTest.swift
  Tests/NIOTests/ChannelPipelineTest.swift
  Tests/NIOTests/ChannelTests.swift
  Tests/NIOTests/PendingDatagramWritesManagerTests.swift
Labels: 🔼 needs-minor-version-bump

#1922 Move UniversalBootstrap to NIOCore.
  Sources/NIOCore/ConvenienceOptionSupport.swift
  Sources/NIOCore/UniversalBootstrapSupport.swift
Labels: 🔼 needs-minor-version-bump

#1911 _NIOConcurrency: Rename completeWithAsync(_:) to completeWithTask(_:) and return task
  Sources/_NIOConcurrency/AsyncAwaitSupport.swift
Labels: needs-no-version-bump

#1924 Copy Android constants needed by Channel over to NIOCore too
  Sources/NIOCore/BSDSocketAPI.swift
Labels: patch-version-bump-only

#1923 Move Marked Circular Buffer to NIOCore
  Sources/NIOCore/MarkedCircularBuffer.swift
Labels: 🔼 needs-minor-version-bump

#1926 Backport: add setters to complete implementations of MutableCollection (#1925)
  Sources/NIO/CircularBuffer.swift
  Sources/NIO/MarkedCircularBuffer.swift
  Tests/NIOTests/CircularBufferTests+XCTest.swift
  Tests/NIOTests/CircularBufferTests.swift
  Tests/NIOTests/MarkedCircularBufferTests+XCTest.swift
  Tests/NIOTests/MarkedCircularBufferTests.swift
Labels: patch-version-bump-only

#1927 Move the Codecs to NIOCore
  Sources/NIOCore/Codec.swift
  Sources/NIOCore/SingleStepByteToMessageDecoder.swift
  Tests/NIOTests/SingleStepByteToMessageDecoderTest.swift
  Tests/NIOWebSocketTests/WebSocketServerEndToEndTests.swift
Labels: 🔼 needs-minor-version-bump

#1929 Move the first-party ChannelHandlers to NIOCore.
  Sources/NIOCore/ChannelHandlers.swift
  Sources/NIOCore/NIOCloseOnErrorHandler.swift
Labels: 🔼 needs-minor-version-bump

#1930 Split and move SocketOptionProvider
  Sources/NIO/BaseSocketChannel+SocketOptionProvider.swift
  Sources/NIOCore/SocketOptionProvider.swift
Labels: 🔼 needs-minor-version-bump

#1931 Move MulticastChannel and NIONetworkDevice to NIOCore
  Sources/NIO/Linux.swift
  Sources/NIO/NetworkDevices.swift
  Sources/NIO/SelectableChannel.swift
  Sources/NIO/System.swift
  Sources/NIO/Utilities.swift
  Sources/NIOCore/Interfaces.swift
  Sources/NIOCore/Linux.swift
  Sources/NIOCore/MulticastChannel.swift
  Sources/NIOCore/SystemCallHelpers.swift
  Sources/NIOCore/Utilities.swift
  Tests/NIOTests/LinuxTest.swift
Labels: 🔼 needs-minor-version-bump

#1932 Extract PriorityQueue to its own module.
  Package.swift
  Sources/NIO/Embedded.swift
  Sources/NIO/SelectableEventLoop.swift
  Sources/_NIODataStructures/Heap.swift
  Sources/_NIODataStructures/PriorityQueue.swift
  Tests/LinuxMain.swift
  Tests/NIODataStructuresTests/HeapTests+XCTest.swift
  Tests/NIODataStructuresTests/HeapTests.swift
  Tests/NIODataStructuresTests/PriorityQueueTests+XCTest.swift
  Tests/NIODataStructuresTests/PriorityQueueTests.swift
Labels: needs-no-version-bump

#1933 Move EmbeddedChannel to its own library.
  Package.swift
  Sources/NIO/Exports.swift
  Sources/NIOEmbedded/Embedded.swift
  Tests/LinuxMain.swift
  Tests/NIOEmbeddedTests/EmbeddedChannelTest+XCTest.swift
  Tests/NIOEmbeddedTests/EmbeddedChannelTest.swift
  Tests/NIOEmbeddedTests/EmbeddedEventLoopTest+XCTest.swift
  Tests/NIOEmbeddedTests/EmbeddedEventLoopTest.swift
  Tests/NIOEmbeddedTests/TestUtils.swift
Labels: 🔼 needs-minor-version-bump

#1937 Re-add NIO as a dependency of our library targets.
  Package.swift
Labels: needs-no-version-bump

#1934 Our readme should be clearer about our products.
  README.md
Labels: needs-no-version-bump

#1940 Mention NIOPosix in README.
  README.md
Labels: needs-no-version-bump

#1943 [Concurrency] `completeWithTask` expects to receive a `@Sendable` closure
  Sources/_NIOConcurrency/AsyncAwaitSupport.swift
Labels: patch-version-bump-only

#1941 Update NIOAsyncAwaitDemo to use correct @available checks (post WWDC '21)
  Sources/NIOAsyncAwaitDemo/AsyncChannelIO.swift
  Sources/NIOAsyncAwaitDemo/main.swift
  Sources/_NIOConcurrency/AsyncAwaitSupport.swift
Labels: needs-no-version-bump

#1945 Minor rewording to clarify the location of the NIO 1 to NIO 2 migration guide
  docs/migration-guide-NIO1-to-NIO2.md
Labels: needs-no-version-bump
