Repository apple/swift-nio, pull requests merged in 2021-05, with the labels that each got.

#1840 dev/lldb-smoker: LLDB smoke test using NIO
  dev/lldb-smoker
Labels: needs-no-version-bump

#1850 Rewrite RecvByteBufferAllocator.
  Sources/NIO/ByteBuffer-int.swift
  Sources/NIO/RecvByteBufferAllocator.swift
  Tests/NIOTests/RecvByteBufAllocatorTest+XCTest.swift
  Tests/NIOTests/RecvByteBufAllocatorTest.swift
Labels: patch-version-bump-only

#1851 fix 5.4. docker setup
  docker/docker-compose.2004.54.yaml
Labels: needs-no-version-bump

#1852 dev/scripts: add missing license headers
  dev/alloc-limits-from-test-output
  dev/lldb-smoker
  dev/update-alloc-limits-to-last-completed-ci-build
  scripts/soundness.sh
Labels: needs-no-version-bump

#1853 Tests should tolerate cpusets.
  Tests/NIOTests/EventLoopTest.swift
Labels: patch-version-bump-only

#1824 Add method to generate a random mask
  Sources/NIOWebSocket/WebSocketFrame.swift
  Tests/LinuxMain.swift
  Tests/NIOWebSocketTests/WebSocketMaskingKeyTests+XCTest.swift
  Tests/NIOWebSocketTests/WebSocketMaskingKeyTests.swift
Labels: 🔼 needs-minor-version-bump

#1855 Random WebSocket Request Key
  Sources/NIOWebSocket/Base64.swift
  Sources/NIOWebSocket/NIOWebSocketClientUpgrader.swift
  Tests/LinuxMain.swift
  Tests/NIOWebSocketTests/NIOWebSocketClientUpgraderTests+XCTest.swift
  Tests/NIOWebSocketTests/NIOWebSocketClientUpgraderTests.swift
Labels: 🔼 needs-minor-version-bump

#1858 Add alloc counter benchmark for result erasing maps.
  IntegrationTests/tests_04_performance/test_01_resources/test_future_erase_result.swift
  docker/docker-compose.1604.52.yaml
  docker/docker-compose.1604.53.yaml
  docker/docker-compose.1804.51.yaml
  docker/docker-compose.2004.54.yaml
  docker/docker-compose.2004.main.yaml
Labels: needs-no-version-bump
