Repository apple/swift-nio, pull requests merged in 2021-11, with the labels that each got.

#1982 Conform EventLoopFuture/Promise to Sendable
  Sources/NIOCore/AsyncAwaitSupport.swift
  Sources/NIOCore/EventLoopFuture.swift
Labels: 🔼 needs-minor-version-bump

#1985 Allow HTTP Server to send multiple informational heads before actual response head
  Sources/NIOHTTP1/HTTPServerPipelineHandler.swift
  Sources/NIOHTTP1/HTTPServerProtocolErrorHandler.swift
  Sources/NIOHTTP1/HTTPTypes.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
  Tests/NIOHTTP1Tests/HTTPServerPipelineHandlerTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPServerPipelineHandlerTest.swift
  Tests/NIOHTTP1Tests/HTTPServerProtocolErrorHandlerTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPServerProtocolErrorHandlerTest.swift
Labels: 🔼 needs-minor-version-bump

#1988 ByteBuffer: reduce unnecessary bounds & under/overflow checks
  Sources/NIOCore/ByteBuffer-core.swift
Labels: patch-version-bump-only

#1990 ByteBuffer: Read and write null terminated strings
  Sources/NIOCore/ByteBuffer-aux.swift
  Tests/NIOPosixTests/ByteBufferTest+XCTest.swift
  Tests/NIOPosixTests/ByteBufferTest.swift
Labels: 🔼 needs-minor-version-bump

#1992 Fix testSchedulingTaskOnSleepingLoopWakesUpOnce
  Tests/NIOPosixTests/SALEventLoopTests.swift
Labels: patch-version-bump-only

#1994 benchmarks: lock performance for 1, 2, 4, 8 threads wanting lock
  Sources/NIOPerformanceTester/LockBenchmark.swift
  Sources/NIOPerformanceTester/main.swift
Labels: needs-no-version-bump

#1995 disable PTHREAD_MUTEX_ERRORCHECK in release mode
  Sources/NIOConcurrencyHelpers/lock.swift
Labels: patch-version-bump-only
