Repository apple/swift-nio, pull requests merged in 2021-03, with the labels that each got.

#1771 Make stackdiff-dtrace.py a little more tolerant
  dev/stackdiff-dtrace.py
Labels: needs-no-version-bump

#1773 fix doc generation script
  scripts/generate_docs.sh
Labels: needs-no-version-bump

#1760 Add assertion helpers for NIOHTTP1TestServer
  Sources/NIOTestUtils/NIOHTTP1TestServer.swift
  Tests/NIOTestUtilsTests/NIOHTTP1TestServerTest+XCTest.swift
  Tests/NIOTestUtilsTests/NIOHTTP1TestServerTest.swift
Labels: 🔼 needs-minor-version-bump

#1762 Add synchronous helpers for HTTP1 pipeline setup
  Sources/NIO/ChannelPipeline.swift
  Sources/NIOHTTP1/HTTPPipelineSetup.swift
  docker/docker-compose.1604.52.yaml
  docker/docker-compose.1604.53.yaml
  docker/docker-compose.1804.50.yaml
  docker/docker-compose.1804.51.yaml
  docker/docker-compose.2004.54.yaml
Labels: 🔼 needs-minor-version-bump

#1757 README updates
  README.md
Labels: needs-no-version-bump

#1736 Add a security policy
  SECURITY.md
Labels: needs-no-version-bump

#1774 more readme updates
  README.md
Labels: needs-no-version-bump

#1775 Decrease overhead of internal size table used in AdaptiveRecvByteBufferAllocator
  Sources/NIO/RecvByteBufferAllocator.swift
Labels: patch-version-bump-only

#1777 More relevant email address for reporting SECURITY issues
  SECURITY.md
Labels: needs-no-version-bump

#1776 Make HTTP Parser import implementationOnly
  Sources/NIOHTTP1/HTTPDecoder.swift
Labels: patch-version-bump-only

#1783 Update NIOSSH version in README
  README.md
Labels: needs-no-version-bump

#1782 Support multiple shared files in the allocation counter test framework
  IntegrationTests/allocation-counter-tests-framework/run-allocation-counter.sh
Labels: needs-no-version-bump

#1785 Add allocation counter tests handler add/remove
  IntegrationTests/tests_04_performance/test_01_resources/test_1000_addRemoveHandlers.swift
  docker/docker-compose.1604.52.yaml
  docker/docker-compose.1604.53.yaml
  docker/docker-compose.1804.50.yaml
  docker/docker-compose.1804.51.yaml
  docker/docker-compose.2004.54.yaml
Labels: needs-no-version-bump

#1784 Make ChannelHandler removal cheaper.
  Sources/NIO/ChannelPipeline.swift
  docker/docker-compose.1604.52.yaml
  docker/docker-compose.1604.53.yaml
  docker/docker-compose.1804.50.yaml
  docker/docker-compose.1804.51.yaml
  docker/docker-compose.2004.54.yaml
Labels: patch-version-bump-only

#1786 Sometimes @escaping is a lie.
  Sources/NIO/ChannelPipeline.swift
Labels: patch-version-bump-only

#1787 Better error type for inactive thread pools
  Sources/NIO/NIOThreadPool.swift
  Tests/NIOTests/NonBlockingFileIOTest+XCTest.swift
  Tests/NIOTests/NonBlockingFileIOTest.swift
Labels: 🔼 needs-minor-version-bump

#1752 docker setup for main nightlies
  docker/docker-compose.2004.main.yaml
Labels: needs-no-version-bump

#1790 disable tests on main
  docker/docker-compose.2004.main.yaml
  docker/docker-compose.yaml
Labels: needs-no-version-bump

#1701 async/await support
  Package.swift
  Sources/NIOAsyncAwaitDemo/AsyncChannelIO.swift
  Sources/NIOAsyncAwaitDemo/FullRequestResponse.swift
  Sources/NIOAsyncAwaitDemo/main.swift
  Sources/_NIOConcurrency/AsyncAwaitSupport.swift
  Sources/_NIOConcurrency/Helpers.swift
Labels: needs-no-version-bump
