Repository apple/swift-nio, pull requests merged in 2021-09, with the labels that each got.

#1947 Add missing implementation of subscript(_ bounds:) to StaticString
  Sources/NIO/ContiguousCollection.swift
Labels: patch-version-bump-only

#1950 Fix doc generation and jazzy version
  docker/Dockerfile
  scripts/generate_docs.sh
Labels: needs-no-version-bump

#1951 Add safer abstraction for kqueue filter set.
  Sources/NIOPosix/SelectorKqueue.swift
Labels: patch-version-bump-only

#1942 Add compiler setting for __APPLE_USE_RFC_3542 for CNIODarwin
  scripts/build_podspecs.sh
Labels: needs-no-version-bump

#1953 Add performance and allocation tests for canonical form headers
  IntegrationTests/tests_04_performance/test_01_resources/test_get_100000_headers_canonical_form.swift
  Sources/NIOPerformanceTester/main.swift
  docker/docker-compose.1604.53.yaml
  docker/docker-compose.1804.52.yaml
  docker/docker-compose.2004.54.yaml
  docker/docker-compose.2004.55.yaml
  docker/docker-compose.2004.main.yaml
Labels: patch-version-bump-only

#1952 Improve performance of `HTTPHeaders.subscript(canonicalForm:)`
  Sources/NIOHTTP1/HTTPTypes.swift
Labels: patch-version-bump-only

#1954 Don't count CR or LF as whitespace when trimming canonical header values
  Sources/NIOHTTP1/HTTPTypes.swift
  Tests/NIOHTTP1Tests/HTTPHeadersTest.swift
Labels: patch-version-bump-only

#1956 Work around Xcode 13 GM SDK issues.
  Sources/NIOCore/ByteBuffer-core.swift
  Tests/NIOPosixTests/ByteBufferTest.swift
  Tests/NIOPosixTests/CodecTest.swift
  docker/docker-compose.2004.main.yaml
Labels: patch-version-bump-only

#1959 [NIOSingleStepByteToMessageProcessor] Inline process methods
  Sources/NIOCore/Codec.swift
  Sources/NIOCore/SingleStepByteToMessageDecoder.swift
Labels: patch-version-bump-only

#1958 [NIOSingleStepByteToMessageProcessor] Only reclaim once at the end of the decode loop
  Sources/NIOCore/SingleStepByteToMessageDecoder.swift
  Tests/NIOPosixTests/SingleStepByteToMessageDecoderTest+XCTest.swift
  Tests/NIOPosixTests/SingleStepByteToMessageDecoderTest.swift
Labels: patch-version-bump-only

#1961 Get unit tests running again on nightly builds.
  Sources/NIOCore/SocketAddresses.swift
  Sources/NIOPosix/BaseSocket.swift
  Tests/NIOPosixTests/SocketAddressTest.swift
  Tests/NIOPosixTests/TestUtils.swift
  docker/docker-compose.2004.main.yaml
Labels: patch-version-bump-only

#1965 NIO1 Fix Ruby version in CI
  docker/Dockerfile
  docker/docker-compose.1804.42.yaml
  docker/docker-compose.1804.50.yaml
Labels: needs-no-version-bump

#1964 NIO1 Work around Xcode 13 GM SDK issues
  Sources/NIO/ByteBuffer-core.swift
  Tests/NIOTests/ByteBufferTest.swift
  Tests/NIOTests/CodecTest.swift
Labels: patch-version-bump-only

#1967 Migrate to Swift 5.5 release in CI.
  docker/docker-compose.2004.55.yaml
Labels: needs-no-version-bump

#1966 Only include concurrency features on new OSes
  Sources/NIOAsyncAwaitDemo/AsyncChannelIO.swift
  Sources/NIOAsyncAwaitDemo/main.swift
  Sources/_NIOConcurrency/AsyncAwaitSupport.swift
  Tests/NIOPosixTests/ByteBufferTest.swift
Labels: patch-version-bump-only

#1968 Work around Xcode 13 GM SDK issues. (#1956)
  Sources/NIO/ByteBuffer-core.swift
  Tests/NIOTests/ByteBufferTest.swift
  Tests/NIOTests/CodecTest.swift
  docker/docker-compose.2004.main.yaml
Labels: patch-version-bump-only

#1969 Move AsyncAwait helpers into NIOCore
  Package.swift
  Sources/NIOAsyncAwaitDemo/main.swift
  Sources/NIOCore/AsyncAwaitSupport.swift
  Sources/_NIOConcurrency/Helpers.swift
Labels: 🔼 needs-minor-version-bump

#1970 Readd module _NIOConcurrency to not break adopters
  Package.swift
  Sources/_NIOConcurrency/Empty.swift
Labels: patch-version-bump-only

#1962 Update workarounds list with our recent ones
  docs/workarounds.md
Labels: needs-no-version-bump
