Repository apple/swift-nio, pull requests merged in 2021-12, with the labels that each got.

#1999 relax-precondition
  Sources/NIOPosix/System.swift
Labels: patch-version-bump-only

#2002 Don't tolerate EBADF on close.
  Sources/NIOPosix/System.swift
Labels: patch-version-bump-only

#2003 provide EventLoopGroup.any() which is sticky to the current EventLoop
  Sources/NIOCore/EventLoop.swift
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
  Sources/NIOPosix/SelectableEventLoop.swift
  Tests/NIOPosixTests/EventLoopTest+XCTest.swift
  Tests/NIOPosixTests/EventLoopTest.swift
Labels: 🔼 needs-minor-version-bump

#1998 remove/deprecate the file:line: parameters from flatMap and friends
  Sources/NIOCore/EventLoop+Deprecated.swift
  Sources/NIOCore/EventLoop.swift
  Sources/NIOCore/EventLoopFuture+Deprecated.swift
  Sources/NIOCore/EventLoopFuture.swift
  Sources/NIOCrashTester/CrashTests+EventLoop.swift
  Sources/NIOEmbedded/Embedded.swift
  Sources/NIOPosix/SelectableEventLoop.swift
  Tests/NIOPosixTests/EventLoopFutureTest.swift
  Tests/NIOPosixTests/EventLoopTest.swift
Labels: 🔼 needs-minor-version-bump

#2006 Enable io_uring builds with newer liburing
  Sources/CNIOLinux/include/CNIOLinux.h
  Sources/NIOPosix/LinuxUring.swift
Labels: patch-version-bump-only

#2008 nio-diagnose script
  .github/ISSUE_TEMPLATE.md
  scripts/nio-diagnose
Labels: needs-no-version-bump

#2010 Convert `ScheduledTask` to a struct to reduce allocations for scheduling
  Sources/NIOEmbedded/Embedded.swift
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
  Sources/NIOPosix/SelectableEventLoop.swift
  Sources/_NIODataStructures/Heap.swift
  Sources/_NIODataStructures/PriorityQueue.swift
  docker/docker-compose.1604.53.yaml
  docker/docker-compose.1804.52.yaml
  docker/docker-compose.2004.54.yaml
  docker/docker-compose.2004.55.yaml
  docker/docker-compose.2004.main.yaml
Labels: patch-version-bump-only, performance

#2011 Call the `cancellationTask` of `Scheduled` directly
  Sources/NIOCore/EventLoop.swift
  Sources/NIOEmbedded/Embedded.swift
  Tests/NIOEmbeddedTests/EmbeddedEventLoopTest.swift
  docker/docker-compose.1604.53.yaml
  docker/docker-compose.1804.52.yaml
  docker/docker-compose.2004.54.yaml
  docker/docker-compose.2004.55.yaml
  docker/docker-compose.2004.main.yaml
Labels: patch-version-bump-only, performance

#2013 update docs generation script to match latest source-kitten
  scripts/generate_docs.sh
Labels: needs-no-version-bump

#2015 Add canImport(_Concurrency) for Xcode 13.0
  Sources/NIOCore/AsyncAwaitSupport+OldXcodes.swift
Labels: patch-version-bump-only

#2017 Conform `AddressedEnvelope` conditionally to `Hashable` & `Equatable`
  Package.swift
  Sources/NIOCore/AddressedEnvelope.swift
  Tests/LinuxMain.swift
  Tests/NIOCoreTests/AddressedEnvelopeTests+XCTest.swift
  Tests/NIOCoreTests/AddressedEnvelopeTests.swift
Labels: 🔼 needs-minor-version-bump
