Repository apple/swift-nio, pull requests merged in 2022-10, with the labels that each got.

#2276 Add `withLockVoid(_:)` to `NIOLock`
  Sources/NIOConcurrencyHelpers/NIOLock.swift
Labels: 🔼 needs-minor-version-bump

#2277 Correctly manage Content-Length on HEAD responses
  Sources/NIOHTTP1/HTTPDecoder.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
Labels: patch-version-bump-only

#2278 Fixed compile errors on windows
  Sources/NIOConcurrencyHelpers/NIOLock.swift
  Sources/NIOConcurrencyHelpers/lock.swift
Labels: patch-version-bump-only

#2281 Remove wrong comment about performance
  Sources/NIOConcurrencyHelpers/NIOLock.swift
Labels: needs-no-version-bump

#2284 Get NIO compiling with GM Xcode
  Sources/_NIOBeta/TimeAmount+Duration.swift
  Tests/NIOBetaTests/TimeAmount+DurationTests.swift
Labels: patch-version-bump-only

#2285 Improve diagnostics for depracted `Lock`.
  Sources/NIOConcurrencyHelpers/lock.swift
Labels: patch-version-bump-only

#2287 Improve `NIOAsyncSequenceProducer` docs
  Sources/NIOCore/AsyncSequences/NIOAsyncSequenceProducer.swift
Labels: needs-no-version-bump

#2289 Backport: "Correctly manage Content-Length on HEAD responses (#2277)"
  Sources/NIOHTTP1/HTTPDecoder.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
Labels: patch-version-bump-only

#2290 Mark types explicitly non sendable
  Sources/NIOCore/FileRegion.swift
  Sources/NIOCore/IOData.swift
  Sources/NIOCore/NIOAny.swift
Labels: 🔼 needs-minor-version-bump

#2291 Replace `NIOSendable` with `Sendable`
  Sources/NIOCore/AddressedEnvelope.swift
  Sources/NIOCore/BSDSocketAPI.swift
  Sources/NIOCore/ByteBuffer-core.swift
  Sources/NIOCore/ByteBuffer-int.swift
  Sources/NIOCore/ByteBuffer-views.swift
  Sources/NIOCore/Channel.swift
  Sources/NIOCore/ChannelHandlers.swift
  Sources/NIOCore/ChannelInvoker.swift
  Sources/NIOCore/ChannelOption.swift
  Sources/NIOCore/ChannelPipeline.swift
  Sources/NIOCore/CircularBuffer.swift
  Sources/NIOCore/Codec.swift
  Sources/NIOCore/ConvenienceOptionSupport.swift
  Sources/NIOCore/EventLoop.swift
  Sources/NIOCore/EventLoopFuture.swift
  Sources/NIOCore/FileHandle.swift
  Sources/NIOCore/IntegerTypes.swift
  Sources/NIOCore/MarkedCircularBuffer.swift
  Sources/NIOCore/NIOCloseOnErrorHandler.swift
  Sources/NIOCore/NIOSendable.swift
  Sources/NIOCore/SocketAddresses.swift
  Sources/NIOCore/Utilities.swift
  Sources/NIOFoundationCompat/ByteBuffer-foundation.swift
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOHTTP1/HTTPServerUpgradeHandler.swift
  Sources/NIOHTTP1/HTTPTypes.swift
  Sources/NIOHTTP1/NIOHTTPObjectAggregator.swift
  Sources/NIOPosix/HappyEyeballs.swift
  Sources/NIOPosix/NIOThreadPool.swift
  Sources/NIOPosix/NonBlockingFileIO.swift
  Sources/NIOTLS/ApplicationProtocolNegotiationHandler.swift
  Sources/NIOTLS/SNIHandler.swift
  Sources/NIOTLS/TLSEvents.swift
  Sources/NIOTestUtils/EventCounterHandler.swift
  Sources/NIOWebSocket/WebSocketErrorCodes.swift
  Sources/NIOWebSocket/WebSocketFrame.swift
  Sources/NIOWebSocket/WebSocketOpcode.swift
Labels: 🔼 needs-minor-version-bump

#2293 We only support 5.5.2+
  README.md
Labels: needs-no-version-bump

#2244 Implement additional file operation in NonBlockingFileIO
  Sources/NIOPosix/NonBlockingFileIO.swift
  Sources/NIOPosix/System.swift
  Tests/NIOPosixTests/NonBlockingFileIOTest+XCTest.swift
  Tests/NIOPosixTests/NonBlockingFileIOTest.swift
Labels: 🔼 needs-minor-version-bump

#2296 adds create directory method
  Sources/NIOPosix/NonBlockingFileIO.swift
  Sources/NIOPosix/System.swift
  Tests/NIOPosixTests/NonBlockingFileIOTest+XCTest.swift
  Tests/NIOPosixTests/NonBlockingFileIOTest.swift
Labels: 🔼 needs-minor-version-bump

#2297 Add support for removing channel options
  Sources/NIOCore/ChannelOption.swift
  Tests/NIOCoreTests/ChannelOptionStorageTest+XCTest.swift
  Tests/NIOCoreTests/ChannelOptionStorageTest.swift
Labels: 🔼 needs-minor-version-bump

#2301 Add benchmarks for `NIOAsyncWriter` and `NIOAsyncSequenceProducer`
  IntegrationTests/allocation-counter-tests-framework/template/scaffolding.swift
  IntegrationTests/tests_04_performance/test_01_resources/test_10000000_asyncsequenceproducer.swift
  IntegrationTests/tests_04_performance/test_01_resources/test_1000000_asyncwriter.swift
  Sources/NIOPerformanceTester/NIOAsyncSequenceProducerBenchmark.swift
  Sources/NIOPerformanceTester/NIOAsyncWriterSingleWritesBenchmark.swift
  Sources/NIOPerformanceTester/main.swift
  docker/docker-compose.2004.55.yaml
  docker/docker-compose.2004.56.yaml
  docker/docker-compose.2004.main.yaml
  docker/docker-compose.2204.57.yaml
Labels: needs-no-version-bump

#2303 Don't unconditionally remove the HTTPServerUpgradeHandler
  Sources/NIOHTTP1/HTTPServerUpgradeHandler.swift
  Tests/NIOHTTP1Tests/HTTPServerUpgradeTests+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift
Labels: patch-version-bump-only

#2304 Make `NIOWebSocketServerUpgrader` `Sendable`
  Sources/NIOWebSocket/NIOWebSocketServerUpgrader.swift
Labels: 🔼 needs-minor-version-bump

#2045 Add utilties for reading and writing UUIDs
  Sources/NIOFoundationCompat/ByteBuffer-foundation.swift
  Tests/LinuxMain.swift
  Tests/NIOFoundationCompatTests/ByteBuffer+UUIDTests+XCTest.swift
  Tests/NIOFoundationCompatTests/ByteBuffer+UUIDTests.swift
Labels: 🔼 needs-minor-version-bump
