Repository apple/swift-nio, pull requests merged in 2022-08, with the labels that each got.

#2234 Fix compilation with Swift 5.5.0 and 5.5.1
  Sources/NIOCore/SocketAddresses.swift
  Sources/NIOHTTP1/HTTPTypes.swift
Labels: patch-version-bump-only

#2230 Implement a back-pressure aware `AsyncSequence` source
  Package.swift
  Sources/NIOCore/AsyncSequences/NIOAsyncSequenceProducer.swift
  Sources/NIOCore/AsyncSequences/NIOAsyncSequenceProducerStrategies.swift
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncSequenceProducer+HighLowWatermarkBackPressureStrategyTests.swift
  Tests/NIOCoreTests/AsyncSequences/NIOBackPressuredAsyncSequenceTests.swift
Labels: 🔼 needs-minor-version-bump

#2236 Add availability requirements to NIOAsyncSequenceProducer extension
  Sources/NIOCore/AsyncSequences/NIOAsyncSequenceProducer.swift
Labels: patch-version-bump-only

#2240 Update soundness.sh
  scripts/soundness.sh
Labels: needs-no-version-bump

#2237 Add throwing version of `NIOAsyncSequenceProducer`
  Sources/NIOCore/AsyncSequences/NIOAsyncSequenceProducer.swift
  Sources/NIOCore/AsyncSequences/NIOThrowingAsyncSequenceProducer.swift
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncSequenceTests.swift
  Tests/NIOCoreTests/AsyncSequences/NIOThrowingAsyncSequenceTests.swift
Labels: 🔼 needs-minor-version-bump

#2238 Provide NIOAsyncTestingChannel
  Sources/NIOEmbedded/AsyncTestingChannel.swift
  Sources/NIOEmbedded/Embedded.swift
  Tests/LinuxMain.swift
  Tests/NIOEmbeddedTests/AsyncTestingChannelTests+XCTest.swift
  Tests/NIOEmbeddedTests/AsyncTestingChannelTests.swift
  docker/docker-compose.1804.54.yaml
  docker/docker-compose.2004.55.yaml
  docker/docker-compose.2004.56.yaml
  docker/docker-compose.2004.57.yaml
  docker/docker-compose.2004.main.yaml
Labels: 🔼 needs-minor-version-bump

#2245 Validate missing imports in CI
  docker/docker-compose.2004.main.yaml
  docker/docker-compose.yaml
Labels: needs-no-version-bump

#2246 Conform `NIOTooManyBytesError` to `Hashable`
  Sources/NIOCore/AsyncAwaitSupport.swift
Labels: 🔼 needs-minor-version-bump

#2249 Functions passed to non-`Sendable` `ChannelHandler`s do not need to conform to `Sendable`
  Sources/NIOHTTP1/HTTPServerUpgradeHandler.swift
  Sources/NIOHTTP1/NIOHTTPClientUpgradeHandler.swift
  Sources/NIOTLS/ApplicationProtocolNegotiationHandler.swift
  Sources/NIOTLS/SNIHandler.swift
  Sources/NIOWebSocket/NIOWebSocketClientUpgrader.swift
  Sources/NIOWebSocket/NIOWebSocketServerUpgrader.swift
Labels: 🔼 needs-minor-version-bump

#2253 Add EventLoopFuture.makeCompletedFuture(withResultOf:)
  Sources/NIOCore/EventLoop.swift
  Tests/NIOPosixTests/EventLoopTest+XCTest.swift
  Tests/NIOPosixTests/EventLoopTest.swift
Labels: patch-version-bump-only

#2254 Small changes for the `NIOAsyncSequenceProducer`
  Sources/NIOCore/AsyncSequences/NIOAsyncSequenceProducer.swift
  Sources/NIOCore/AsyncSequences/NIOThrowingAsyncSequenceProducer.swift
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncSequenceProducer+HighLowWatermarkBackPressureStrategyTests.swift
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncSequenceTests.swift
Labels: patch-version-bump-only
