Repository apple/swift-nio, pull requests merged in 2022-07, with the labels that each got.

#2204 Deprecate `NIOAtomics` in favor of `Atomics`
  Package.swift
  Sources/NIOConcurrencyHelpers/NIOAtomic.swift
  Sources/NIOConcurrencyHelpers/atomics.swift
  Sources/NIOEmbedded/AsyncEmbeddedEventLoop.swift
  Sources/NIOPosix/BaseSocketChannel.swift
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
  Sources/NIOPosix/PendingDatagramWritesManager.swift
  Sources/NIOPosix/PendingWritesManager.swift
  Sources/NIOPosix/SelectableEventLoop.swift
  Sources/NIOTestUtils/EventCounterHandler.swift
  Tests/NIOConcurrencyHelpersTests/NIOConcurrencyHelpersTests.swift
  Tests/NIOEmbeddedTests/AsyncEmbeddedEventLoopTests.swift
  Tests/NIOEmbeddedTests/TestUtils.swift
  Tests/NIOPosixTests/AcceptBackoffHandlerTest.swift
  Tests/NIOPosixTests/ChannelPipelineTest.swift
  Tests/NIOPosixTests/EchoServerClientTest.swift
  Tests/NIOPosixTests/EventLoopTest.swift
  Tests/NIOPosixTests/NonBlockingFileIOTest.swift
  Tests/NIOPosixTests/SALChannelTests.swift
  Tests/NIOPosixTests/SelectorTest.swift
  Tests/NIOPosixTests/SocketChannelTest.swift
  Tests/NIOPosixTests/StreamChannelsTest.swift
Labels: 🔼 needs-minor-version-bump

#2209 Adopt `Sendable` for Bootstraps
  Sources/NIOCore/UniversalBootstrapSupport.swift
  Sources/NIOPosix/Bootstrap.swift
Labels: 🔼 needs-minor-version-bump

#2212 Adopt `Sendable` in `NonBlockingFileIO`
  Sources/NIOPosix/NonBlockingFileIO.swift
Labels: 🔼 needs-minor-version-bump

#2215 NIOCore: add missing import on Windows
  Sources/NIOCore/SocketOptionProvider.swift
Labels: patch-version-bump-only

#2213 Adopt `Sendable` for types in `NIOHTTP1`
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOHTTP1/HTTPEncoder.swift
  Sources/NIOHTTP1/HTTPServerPipelineHandler.swift
  Sources/NIOHTTP1/HTTPServerProtocolErrorHandler.swift
  Sources/NIOHTTP1/HTTPServerUpgradeHandler.swift
  Sources/NIOHTTP1/HTTPTypes.swift
  Sources/NIOHTTP1/NIOHTTPClientUpgradeHandler.swift
  Sources/NIOHTTP1/NIOHTTPObjectAggregator.swift
Labels: 🔼 needs-minor-version-bump

#2217 Adopt `Sendable` for Types in `NIOWebSocket`
  Sources/NIOWebSocket/NIOWebSocketClientUpgrader.swift
  Sources/NIOWebSocket/NIOWebSocketFrameAggregator.swift
  Sources/NIOWebSocket/NIOWebSocketServerUpgrader.swift
  Sources/NIOWebSocket/WebSocketErrorCodes.swift
  Sources/NIOWebSocket/WebSocketFrame.swift
  Sources/NIOWebSocket/WebSocketFrameDecoder.swift
  Sources/NIOWebSocket/WebSocketFrameEncoder.swift
  Sources/NIOWebSocket/WebSocketOpcode.swift
  Sources/NIOWebSocket/WebSocketProtocolErrorHandler.swift
Labels: 🔼 needs-minor-version-bump

#2220 Adopt `Sendable` for `NIOChatServer` and `MIOMulticastChat` Examples
  Sources/NIOChatServer/main.swift
  Sources/NIOMulticastChat/main.swift
Labels: needs-no-version-bump

#2219 NIOCore: handle error description on Windows
  Sources/NIOCore/IO.swift
Labels: patch-version-bump-only

#2225 Workaround `Sendable` warning from Swift 5.7
  Tests/NIOHTTP1Tests/HTTPTest.swift
Labels: needs-no-version-bump

#2226 NIOCore: Implemented all three variants of _failEarlyRangeCheck methods for ByteBufferView
  Sources/NIOCore/ByteBuffer-views.swift
Labels: patch-version-bump-only

#2227 Added test for BufferView custom contains function
  Tests/NIOCoreTests/ByteBufferTest+XCTest.swift
  Tests/NIOCoreTests/ByteBufferTest.swift
Labels: needs-no-version-bump

#2224 Enhance and rename AsyncEmbeddedEventLoop
  Sources/NIOEmbedded/AsyncTestingEventLoop.swift
  Tests/LinuxMain.swift
  Tests/NIOEmbeddedTests/AsyncTestingEventLoopTests+XCTest.swift
  Tests/NIOEmbeddedTests/AsyncTestingEventLoopTests.swift
Labels: patch-version-bump-only

#2229 Fix strict concurrency checking diagnostics in `MTELG`
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
Labels: patch-version-bump-only
