Repository apple/swift-nio, pull requests merged in 2022-11, with the labels that each got.

#2305 Add missing `Sendable` requirements
  Sources/NIOWebSocket/NIOWebSocketServerUpgrader.swift
Labels: 🔼 needs-minor-version-bump

#2306 Use #fileID/#filePath instead of #file
  Sources/NIOCore/AsyncAwaitSupport.swift
  Sources/NIOCore/ChannelInvoker.swift
  Sources/NIOCore/EventLoop+Deprecated.swift
  Sources/NIOCore/EventLoop.swift
  Sources/NIOCore/EventLoopFuture+Deprecated.swift
  Sources/NIOCore/EventLoopFuture.swift
  Tests/NIOConcurrencyHelpersTests/NIOConcurrencyHelpersTests.swift
  Tests/NIOCoreTests/AsyncSequenceTests.swift
  Tests/NIOCoreTests/ByteBufferTest.swift
  Tests/NIOCoreTests/RecvByteBufAllocatorTest.swift
  Tests/NIOCoreTests/XCTest+AsyncAwait.swift
  Tests/NIOCoreTests/XCTest+Extensions.swift
  Tests/NIOEmbeddedTests/AsyncTestingChannelTests.swift
  Tests/NIOEmbeddedTests/EmbeddedChannelTest.swift
  Tests/NIOEmbeddedTests/TestUtils.swift
  Tests/NIOEmbeddedTests/XCTest+AsyncAwait.swift
  Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift
  Tests/NIOPosixTests/ChannelNotificationTest.swift
  Tests/NIOPosixTests/ChannelTests.swift
  Tests/NIOPosixTests/CodecTest.swift
  Tests/NIOPosixTests/ControlMessageTests.swift
  Tests/NIOPosixTests/DatagramChannelTests.swift
  Tests/NIOPosixTests/EventLoopFutureTest.swift
  Tests/NIOPosixTests/EventLoopTest.swift
  Tests/NIOPosixTests/MulticastTest.swift
  Tests/NIOPosixTests/PendingDatagramWritesManagerTests.swift
  Tests/NIOPosixTests/SocketOptionProviderTest.swift
  Tests/NIOPosixTests/StreamChannelsTest.swift
  Tests/NIOPosixTests/SyscallAbstractionLayer.swift
  Tests/NIOPosixTests/SystemCallWrapperHelpers.swift
  Tests/NIOPosixTests/TestUtils.swift
  Tests/NIOTestUtilsTests/NIOHTTP1TestServerTest.swift
  Tests/NIOWebSocketTests/WebSocketClientEndToEndTests.swift
Labels: patch-version-bump-only

#2307 Add `NIOAsyncTestingChannel.waitForOut/InboundWrite()`
  Package.swift
  Sources/NIOEmbedded/AsyncTestingChannel.swift
  Sources/NIOEmbedded/Embedded.swift
  Tests/NIOEmbeddedTests/AsyncTestingChannelTests+XCTest.swift
  Tests/NIOEmbeddedTests/AsyncTestingChannelTests.swift
Labels: 🔼 needs-minor-version-bump

#2308 MPTCP support on Linux
  Sources/CNIOLinux/include/CNIOLinux.h
  Sources/NIOCore/BSDSocketAPI.swift
  Sources/NIOCore/SocketOptionProvider.swift
  Sources/NIOPosix/BSDSocketAPIPosix.swift
  Sources/NIOPosix/BSDSocketAPIWindows.swift
  Sources/NIOPosix/BaseSocket.swift
  Sources/NIOPosix/Bootstrap.swift
  Sources/NIOPosix/ServerSocket.swift
  Sources/NIOPosix/Socket.swift
  Sources/NIOPosix/SocketChannel.swift
  Tests/NIOPosixTests/SocketChannelTest+XCTest.swift
  Tests/NIOPosixTests/SocketChannelTest.swift
Labels: 🔼 needs-minor-version-bump

#2314 Fix `testTaskCancel_whenStreaming_andNotSuspended` flakiness
  Tests/NIOCoreTests/AsyncSequences/NIOThrowingAsyncSequenceTests.swift
Labels: needs-no-version-bump

#2313 Fix failing build on MacOS
  Tests/NIOPosixTests/SocketChannelTest.swift
Labels: needs-no-version-bump

#2315 Correctly include netinet/in.h
  Sources/CNIODarwin/shim.c
Labels: patch-version-bump-only

#2318 Make `NIOHTTP1TestServer` Sendable
  Sources/NIOTestUtils/NIOHTTP1TestServer.swift
Labels: 🔼 needs-minor-version-bump

#2317 Add `NIOBSDSocket.ProtocolSubtype`
  IntegrationTests/tests_02_syscall_wrappers/defines.sh
  Sources/NIOCore/IPProtocol.swift
  Sources/NIOPosix/BSDSocketAPICommon.swift
  Sources/NIOPosix/BSDSocketAPIPosix.swift
  Sources/NIOPosix/BSDSocketAPIWindows.swift
  Sources/NIOPosix/BaseSocket.swift
  Sources/NIOPosix/Bootstrap.swift
  Sources/NIOPosix/ServerSocket.swift
  Sources/NIOPosix/Socket.swift
  Sources/NIOPosix/SocketChannel.swift
  Sources/NIOPosix/System.swift
  Tests/NIOPosixTests/BootstrapTest.swift
  Tests/NIOPosixTests/ChannelTests.swift
  Tests/NIOPosixTests/DatagramChannelTests.swift
  Tests/NIOPosixTests/PipeChannelTest.swift
  Tests/NIOPosixTests/SelectorTest.swift
Labels: 🔼 needs-minor-version-bump

#2321 Remove obsolete information from the README
  README.md
Labels: needs-no-version-bump

#2323 cap read+pread POSIX read sizes at Int32.max
  Sources/NIOPosix/NonBlockingFileIO.swift
  Tests/NIOPosixTests/NonBlockingFileIOTest+XCTest.swift
  Tests/NIOPosixTests/NonBlockingFileIOTest.swift
Labels: patch-version-bump-only
