Repository apple/swift-nio, pull requests merged in 2022-02, with the labels that each got.

#2037 Add benchmarks for copying BBV to Array.
  IntegrationTests/tests_04_performance/test_01_resources/test_1000_copying_bytebufferview_to_array.swift
  Sources/NIOPerformanceTester/ByteBufferViewCopyToArrayBenchmark.swift
  Sources/NIOPerformanceTester/main.swift
Labels: needs-no-version-bump

#2038 Add `collect(into:maxBytes:)` to `AsyncSequence`
  NOTICE.txt
  Sources/NIOCore/AsyncAwaitSupport.swift
  Tests/LinuxMain.swift
  Tests/NIOCoreTests/AsyncSequenceTests+XCTest.swift
  Tests/NIOCoreTests/AsyncSequenceTests.swift
  Tests/NIOCoreTests/XCTest+AsyncAwait.swift
Labels: 🔼 needs-minor-version-bump

#2039 Improve the performance of copying BBV
  Sources/NIOCore/ByteBuffer-core.swift
  Sources/NIOCore/ByteBuffer-views.swift
Labels: 🔼 needs-minor-version-bump

#1975 Improve `ByteBuffer.setSubstring(_:at:)` performance
  Sources/NIOCore/ByteBuffer-aux.swift
Labels: patch-version-bump-only

#2044 Implement BBV custom contains function to improve performance.
  Sources/NIOCore/ByteBuffer-views.swift
Labels: patch-version-bump-only

#2047 Add an allocation test for execute which needs to hop threads.
  IntegrationTests/tests_04_performance/test_01_resources/test_execute_hop_10000_tasks.swift
  docker/docker-compose.1604.53.yaml
  docker/docker-compose.1804.52.yaml
  docker/docker-compose.2004.54.yaml
  docker/docker-compose.2004.55.yaml
  docker/docker-compose.2004.56.yaml
  docker/docker-compose.2004.main.yaml
Labels: needs-no-version-bump

#2048 atomics: make add/sub @discardableResult
  IntegrationTests/tests_04_performance/test_01_resources/test_read_10000_chunks_from_file.swift
  Sources/NIOConcurrencyHelpers/atomics.swift
  Tests/NIOConcurrencyHelpersTests/NIOConcurrencyHelpersTests.swift
  Tests/NIOPosixTests/EventLoopTest.swift
  Tests/NIOPosixTests/NonBlockingFileIOTest.swift
  Tests/NIOPosixTests/SelectorTest.swift
  Tests/NIOPosixTests/SocketChannelTest.swift
  Tests/NIOPosixTests/StreamChannelsTest.swift
Labels: patch-version-bump-only

#2049 ELF: provide flatMapWithEventLoop and friends (#1996)
  Sources/NIOCore/EventLoopFuture+WithEventLoop.swift
  Tests/NIOPosixTests/EventLoopFutureTest+XCTest.swift
  Tests/NIOPosixTests/EventLoopFutureTest.swift
Labels: 🔼 needs-minor-version-bump

#2046 [SelectableEventLoop] SR-15872; Save allocations when appending task
  Sources/NIOPosix/SelectableEventLoop.swift
  dev/update-alloc-limits-to-last-completed-ci-build
  docker/docker-compose.1604.53.yaml
  docker/docker-compose.1804.52.yaml
  docker/docker-compose.2004.54.yaml
  docker/docker-compose.2004.55.yaml
  docker/docker-compose.2004.56.yaml
  docker/docker-compose.2004.main.yaml
  docs/workarounds.md
Labels: patch-version-bump-only

#2050 Make all ByteBuffer methods inlinable
  Sources/NIOCore/ByteBuffer-aux.swift
  Sources/NIOCore/ByteBuffer-conversions.swift
  Sources/NIOCore/ByteBuffer-core.swift
  Sources/NIOCore/ByteBuffer-int.swift
  Sources/NIOCore/ByteBuffer-views.swift
Labels: patch-version-bump-only

#2051 Fixed some typos
  Sources/NIOAsyncAwaitDemo/FullRequestResponse.swift
  Sources/NIOConcurrencyHelpers/atomics.swift
  Sources/NIOConcurrencyHelpers/lock.swift
  Sources/NIOCore/Channel.swift
  Sources/NIOCore/Codec.swift
  Sources/NIOCore/DispatchQueue+WithFuture.swift
  Sources/NIOCore/EventLoop.swift
  Sources/NIOCore/EventLoopFuture.swift
  Sources/NIOCore/MarkedCircularBuffer.swift
  Sources/NIOHTTP1/HTTPServerUpgradeHandler.swift
  Sources/NIOHTTP1/NIOHTTPObjectAggregator.swift
  Sources/NIOPosix/SelectorGeneric.swift
  Sources/NIOPosix/SelectorUring.swift
  Sources/NIOWebSocket/NIOWebSocketFrameAggregator.swift
  Tests/NIOEmbeddedTests/EmbeddedChannelTest.swift
  Tests/NIOPosixTests/ByteBufferTest.swift
  Tests/NIOPosixTests/ChannelTests.swift
  Tests/NIOPosixTests/CodecTest.swift
  Tests/NIOPosixTests/EventLoopTest.swift
  Tests/NIOPosixTests/SelectorTest.swift
  Tests/NIOPosixTests/StreamChannelsTest.swift
Labels: needs-no-version-bump
