Repository apple/swift-nio, pull requests merged in 2022-05, with the labels that each got.

#2091 Adopt `Sendable` in `_NIODataStructures`
  Sources/_NIODataStructures/Heap.swift
  Sources/_NIODataStructures/PriorityQueue.swift
Labels: needs-no-version-bump

#2094 Remove build_podspec.sh
  scripts/build_podspecs.sh
  scripts/list_topsorted_dependencies.sh
  scripts/list_transitive_dependencies.py
Labels: needs-no-version-bump

#2095 Reduce the alloc limits for main
  dev/update-alloc-limits-to-last-completed-ci-build
  docker/docker-compose.2004.57.yaml
  docker/docker-compose.2004.main.yaml
Labels: needs-no-version-bump

#2093 Move tests of NIOCore types from NIOPosixTests to NIOCoreTests
  Package.swift
  Tests/NIOCoreTests/BaseObjectsTest+XCTest.swift
  Tests/NIOCoreTests/BaseObjectsTest.swift
  Tests/NIOCoreTests/ByteBufferLengthPrefixTests+XCTest.swift
  Tests/NIOCoreTests/ByteBufferLengthPrefixTests.swift
  Tests/NIOCoreTests/ByteBufferTest+XCTest.swift
  Tests/NIOCoreTests/ByteBufferTest.swift
  Tests/NIOCoreTests/ChannelOptionStorageTest+XCTest.swift
  Tests/NIOCoreTests/ChannelOptionStorageTest.swift
  Tests/NIOCoreTests/CircularBufferTests+XCTest.swift
  Tests/NIOCoreTests/CircularBufferTests.swift
  Tests/NIOCoreTests/CustomChannelTests+XCTest.swift
  Tests/NIOCoreTests/CustomChannelTests.swift
  Tests/NIOCoreTests/DispatchQueue+WithFutureTest+XCTest.swift
  Tests/NIOCoreTests/DispatchQueue+WithFutureTest.swift
  Tests/NIOCoreTests/IOErrorTest+XCTest.swift
  Tests/NIOCoreTests/IOErrorTest.swift
  Tests/NIOCoreTests/IntegerTypesTest+XCTest.swift
  Tests/NIOCoreTests/IntegerTypesTest.swift
  Tests/NIOCoreTests/LinuxTest+XCTest.swift
  Tests/NIOCoreTests/LinuxTest.swift
  Tests/NIOCoreTests/MarkedCircularBufferTests+XCTest.swift
  Tests/NIOCoreTests/MarkedCircularBufferTests.swift
  Tests/NIOCoreTests/NIOAnyDebugTest+XCTest.swift
  Tests/NIOCoreTests/NIOAnyDebugTest.swift
  Tests/NIOCoreTests/NIOCloseOnErrorHandlerTest+XCTest.swift
  Tests/NIOCoreTests/NIOCloseOnErrorHandlerTest.swift
  Tests/NIOCoreTests/RecvByteBufAllocatorTest+XCTest.swift
  Tests/NIOCoreTests/RecvByteBufAllocatorTest.swift
  Tests/NIOCoreTests/SingleStepByteToMessageDecoderTest+XCTest.swift
  Tests/NIOCoreTests/SingleStepByteToMessageDecoderTest.swift
  Tests/NIOCoreTests/TimeAmountTests+XCTest.swift
  Tests/NIOCoreTests/TimeAmountTests.swift
  Tests/NIOCoreTests/TypeAssistedChannelHandlerTests+XCTest.swift
  Tests/NIOCoreTests/TypeAssistedChannelHandlerTests.swift
  Tests/NIOCoreTests/UtilitiesTest+XCTest.swift
  Tests/NIOCoreTests/UtilitiesTest.swift
  Tests/NIOCoreTests/XCTest+Extensions.swift
Labels: needs-no-version-bump

#2083 Define AsyncEmbeddedEventLoop
  Package.swift
  Sources/NIOCore/EventLoop.swift
  Sources/NIOEmbedded/AsyncEmbeddedEventLoop.swift
  Sources/NIOEmbedded/Embedded.swift
  Tests/LinuxMain.swift
  Tests/NIOEmbeddedTests/AsyncEmbeddedEventLoopTests+XCTest.swift
  Tests/NIOEmbeddedTests/AsyncEmbeddedEventLoopTests.swift
  Tests/NIOEmbeddedTests/TestUtils.swift
  Tests/NIOEmbeddedTests/XCTest+AsyncAwait.swift
Labels: 🔼 needs-minor-version-bump

#2096 Adopt `Sendable` for `SocketAddress`, `AddressedEnvelope` and friends
  Sources/NIOCore/AddressedEnvelope.swift
  Sources/NIOCore/SocketAddresses.swift
  Sources/NIOCore/Utilities.swift
Labels: 🔼 needs-minor-version-bump

#2097 Adopt `Sendable` for `CircularBuffer`, `MarkedCircularBuffer` and types in `NIOBSDSocket` namespace
  IntegrationTests/tests_02_syscall_wrappers/defines.sh
  Sources/NIOCore/AsyncAwaitSupport.swift
  Sources/NIOCore/BSDSocketAPI.swift
  Sources/NIOCore/ByteBuffer-core.swift
  Sources/NIOCore/ByteBuffer-int.swift
  Sources/NIOCore/CircularBuffer.swift
  Sources/NIOCore/MarkedCircularBuffer.swift
  Sources/NIOCore/NIOSendable.swift
Labels: 🔼 needs-minor-version-bump

#2098 Adopt `Sendable` for Types in `ChannelOptions` Namespace
  Sources/NIOCore/ChannelOption.swift
  Sources/NIOCore/NIOSendable.swift
Labels: 🔼 needs-minor-version-bump

#2100 Adopt `Sendable` for `SocketOptionProvider`
  Sources/NIOCore/SocketOptionProvider.swift
Labels: 🔼 needs-minor-version-bump

#2102 Adopt `Sendable` for `NIOFileHandle.Mode` and `NIOFileHandle.Flags`
  Sources/NIOCore/FileHandle.swift
  Sources/NIOCore/FileRegion.swift
Labels: 🔼 needs-minor-version-bump

#2103 Adopt `Sendable` for `NIONetworkDevice`
  Sources/NIOCore/Interfaces.swift
Labels: 🔼 needs-minor-version-bump

#2104 Adopt `Sendable` for `Channel`
  Sources/NIOCore/Channel.swift
Labels: 🔼 needs-minor-version-bump

#2109 Deprecate unsafe `ChannelPipeline.context(handler:)` methods
  Sources/NIOCore/AsyncAwaitSupport+OldXcodes.swift
  Sources/NIOCore/AsyncAwaitSupport.swift
Labels: 🔼 needs-minor-version-bump

#2116 Reduce the alloc limits of `1000_tcpconnections` for main
  docker/docker-compose.2004.57.yaml
  docker/docker-compose.2004.main.yaml
Labels: needs-no-version-bump

#2118 Reduce the alloc limits for main
  docker/docker-compose.2004.57.yaml
  docker/docker-compose.2004.main.yaml
Labels: needs-no-version-bump

#2117 NIOPerformanceTester: Add DeadlineNowBenchmark for NIODeadline.now()
  Sources/NIOPerformanceTester/DeadlineNowBenchmark.swift
  Sources/NIOPerformanceTester/main.swift
Labels: needs-no-version-bump

#2115 Introduce internal `UnsafeTransfer` type
  Sources/NIOCore/NIOSendable.swift
Labels: patch-version-bump-only

#2119 wip: Use clock_gettime for NIODeadline.now()
  Sources/CNIOLinux/shim.c
  Sources/NIOCore/EventLoop.swift
Labels: patch-version-bump-only

#2126 readme: Fix API docs link following NIOCore refactoring
  README.md
Labels: needs-no-version-bump

#2101 Adopt `Sendable` in `EventLoop.swift`
  Sources/NIOCore/EventLoop.swift
Labels: 🔼 needs-minor-version-bump

#2107 Adopt `Sendable` for `EventLoopFuture` and `EventLoopPromise`
  Sources/NIOCore/AsyncAwaitSupport.swift
  Sources/NIOCore/EventLoopFuture+WithEventLoop.swift
  Sources/NIOCore/EventLoopFuture.swift
Labels: 🔼 needs-minor-version-bump

#2123 DatagramChannelTests: Handle receiving datagrams out-of-order in ECN tests
  Tests/NIOPosixTests/DatagramChannelTests.swift
Labels: needs-no-version-bump

#2127 build: correct dependencies for `NIOCore`
  Package.swift
Labels: patch-version-bump-only

#2128 _NIODataStructures: repair the build on Windows
  Sources/_NIODataStructures/Heap.swift
Labels: patch-version-bump-only

#2129 NIOCore: add missing import for `IO`
  Sources/NIOCore/IO.swift
Labels: patch-version-bump-only

#2130 NIOCore: adjust for label change on Windows
  Sources/NIOCore/BSDSocketAPI.swift
Labels: patch-version-bump-only

#2131 NIOCore: import `WSAGetLastError`, `GetLastError`
  Sources/NIOCore/BSDSocketAPI.swift
Labels: patch-version-bump-only

#2133 NIOCore: correct typo in error namespace on Windows
  Sources/NIOCore/SocketAddresses.swift
Labels: patch-version-bump-only

#2138 NIOCore: import `INET{,6}_ADDRSTRLEN` constants
  Sources/NIOCore/SocketAddresses.swift
Labels: patch-version-bump-only

#2139 NIOCore: use `errno` accessor on Windows
  Sources/NIOCore/SystemCallHelpers.swift
Labels: patch-version-bump-only

#2132 NIOCore: replace `mode_t` with `CInt`
  Sources/NIOCore/FileHandle.swift
  Sources/NIOCore/SystemCallHelpers.swift
Labels: 🔼 needs-minor-version-bump

#2140 NIOCore: handle structural differences on Windows
  Sources/NIOCore/SocketAddresses.swift
Labels: patch-version-bump-only
