Repository apple/swift-nio, pull requests merged in 2022-04, with the labels that each got.

#2059 Improve the performance of copying CircularBuffer
  Sources/NIOCore/CircularBuffer.swift
  Tests/NIOPosixTests/CircularBufferTests+XCTest.swift
  Tests/NIOPosixTests/CircularBufferTests.swift
Labels: patch-version-bump-only

#2076 Fix doc comment formatting in `SingleStepByteToMessageDecoder.swift`
  Sources/NIOCore/SingleStepByteToMessageDecoder.swift
Labels: needs-no-version-bump

#2075 Remove invalid math in ByteBuffer slice slow path
  Sources/NIOCore/ByteBuffer-core.swift
  Tests/NIOPosixTests/ByteBufferTest+XCTest.swift
  Tests/NIOPosixTests/ByteBufferTest.swift
Labels: patch-version-bump-only

#2080 Drop support for Swift 5.2 and 5.3
  CONTRIBUTING.md
  IntegrationTests/tests_02_syscall_wrappers/defines.sh
  Package.swift
  README.md
  SECURITY.md
  docker/Dockerfile
  docker/docker-compose.1604.53.yaml
  docker/docker-compose.1804.54.yaml
  docker/docker-compose.2004.54.yaml
  scripts/build_podspecs.sh
Labels: 🔼 needs-minor-version-bump

#2082 Script to list transitive dependencies
  dev/stackdiff-dtrace.py
  scripts/build_podspecs.sh
  scripts/list_topsorted_dependencies.sh
  scripts/list_transitive_dependencies.py
  scripts/soundness.sh
Labels: needs-no-version-bump

#2085 Fix warnings, that appeared after requiring Swift 5.4
  Package.swift
Labels: needs-no-version-bump

#2086 BaseSocket: Remove dead code in BaseSocket.bind(to:)
  Sources/NIOPosix/BaseSocket.swift
Labels: patch-version-bump-only

#2090 Adopt `Sendable` in NIOConcurrencyHelpers
  Sources/NIOConcurrencyHelpers/NIOAtomic.swift
  Sources/NIOConcurrencyHelpers/lock.swift
Labels: 🔼 needs-minor-version-bump
