Repository apple/swift-nio, pull requests merged in 2022-12, with the labels that each got.

#2320 Add `RawSocketBootstrap`
  Sources/NIOCore/BSDSocketAPI.swift
  Sources/NIOCore/ChannelOption.swift
  Sources/NIOPosix/BSDSocketAPICommon.swift
  Sources/NIOPosix/RawSocketBootstrap.swift
  Sources/NIOPosix/Socket.swift
  Tests/LinuxMain.swift
  Tests/NIOPosixTests/DatagramChannelTests.swift
  Tests/NIOPosixTests/IPv4Header.swift
  Tests/NIOPosixTests/RawSocketBootstrapTests+XCTest.swift
  Tests/NIOPosixTests/RawSocketBootstrapTests.swift
Labels: 🔼 needs-minor-version-bump

#2324 Add .spi.yml for Swift Package Index DocC support
  .spi.yml
Labels: needs-no-version-bump

#2328 Fix non Darwin/Linux builds
  Tests/NIOPosixTests/IPv4Header.swift
Labels: patch-version-bump-only

#2330 Remove implicit ByteBuffer copy in copyMemory
  Sources/NIOCore/ByteBuffer-core.swift
Labels: patch-version-bump-only

#2331 Make EventLoopFuture.wait() unavailable from async
  Sources/NIOCore/EventLoopFuture.swift
Labels: 🔼 needs-minor-version-bump

#2333 Measure allocations applying WS mask
  IntegrationTests/tests_04_performance/test_01_resources/test_encode_1000_ws_frames.swift
  dev/update-alloc-limits-to-last-completed-ci-build
  docker/docker-compose.2004.55.yaml
  docker/docker-compose.2004.56.yaml
  docker/docker-compose.2004.main.yaml
  docker/docker-compose.2204.57.yaml
Labels: needs-no-version-bump

#2334 add easier async to future conversion
  Sources/NIOCore/AsyncAwaitSupport.swift
  Tests/NIOPosixTests/EventLoopTest+XCTest.swift
  Tests/NIOPosixTests/EventLoopTest.swift
Labels: 🔼 needs-minor-version-bump

#2336 Improve performance of tests
  Tests/NIOConcurrencyHelpersTests/NIOConcurrencyHelpersTests.swift
Labels: needs-no-version-bump
