Repository apple/swift-nio, pull requests merged in 2022-09, with the labels that each got.

#2259 Widen the tolerance on testSystemCallWrapperPerformance in debug mode
  Tests/NIOPosixTests/SystemCallWrapperHelpers.swift
Labels: needs-no-version-bump

#2264 helpful error message when compiling without test discovery on >= 5.5
  Tests/LinuxMain.swift
  scripts/generate_linux_tests.rb
Labels: needs-no-version-bump

#2263 Update HTTP parser to LLHTTP
  NOTICE.txt
  Package.swift
  Package@swift-5.4.swift
  Package@swift-5.5.swift
  Sources/CNIOHTTPParser/AUTHORS
  Sources/CNIOHTTPParser/LICENSE-MIT
  Sources/CNIOHTTPParser/c_nio_http_parser.c
  Sources/CNIOHTTPParser/include/CNIOHTTPParser.h
  Sources/CNIOHTTPParser/include/c_nio_http_parser.h
  Sources/CNIOHTTPParser/update_and_patch_http_parser.sh
  Sources/CNIOLLHTTP/LICENSE-MIT
  Sources/CNIOLLHTTP/c_nio_api.c
  Sources/CNIOLLHTTP/c_nio_http.c
  Sources/CNIOLLHTTP/c_nio_llhttp.c
  Sources/CNIOLLHTTP/include/CNIOLLHTTP.h
  Sources/CNIOLLHTTP/include/c_nio_llhttp.h
  Sources/CNIOLLHTTP/update_and_patch_llhttp.sh
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOHTTP1/HTTPTypes.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
  Tests/NIOHTTP1Tests/HTTPServerPipelineHandlerTest.swift
  docker/docker-compose.1804.54.yaml
  docker/docker-compose.2004.55.yaml
  docker/docker-compose.2004.56.yaml
  docker/docker-compose.2004.57.yaml
  docker/docker-compose.2004.main.yaml
  scripts/soundness.sh
Labels: patch-version-bump-only

#2269 Add support for newer LLHTTP status codes
  Sources/NIOHTTP1/HTTPDecoder.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest+XCTest.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
Labels: patch-version-bump-only

#2265 NIOConcurrency: add NIOLockedValueBox
  Sources/NIOConcurrencyHelpers/LockedValue.swift
  Tests/NIOConcurrencyHelpersTests/NIOConcurrencyHelpersTests+XCTest.swift
  Tests/NIOConcurrencyHelpersTests/NIOConcurrencyHelpersTests.swift
Labels: 🔼 needs-minor-version-bump

#2251 Implement a `NIOAsyncWriter`
  Package.swift
  Package@swift-5.4.swift
  Package@swift-5.5.swift
  Sources/NIOCore/AsyncSequences/NIOAsyncWriter.swift
  Sources/NIOPerformanceTester/Benchmark.swift
  Sources/NIOPerformanceTester/NIOAsyncWriterSingleWritesBenchmark.swift
  Sources/NIOPerformanceTester/main.swift
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncWriterTests.swift
  Tests/NIOCoreTests/XCTest+AsyncAwait.swift
Labels: 🔼 needs-minor-version-bump

#2271 Fixup docs for the `NIOAsyncWriter`
  Sources/NIOConcurrencyHelpers/LockedValue.swift
  Sources/NIOCore/AsyncSequences/NIOAsyncWriter.swift
Labels: needs-no-version-bump

#2266 rename class Lock to struct NIOLock
  IntegrationTests/tests_05_assertions/test_01_syscall_wrapper_fast.sh
  Sources/NIOConcurrencyHelpers/LockedValue.swift
  Sources/NIOConcurrencyHelpers/NIOLock.swift
  Sources/NIOConcurrencyHelpers/lock.swift
  Sources/NIOCore/AsyncSequences/NIOAsyncWriter.swift
  Sources/NIOCore/AsyncSequences/NIOThrowingAsyncSequenceProducer.swift
  Sources/NIOCore/EventLoop.swift
  Sources/NIOEmbedded/AsyncTestingChannel.swift
  Sources/NIOEmbedded/AsyncTestingEventLoop.swift
  Sources/NIOPerformanceTester/LockBenchmark.swift
  Sources/NIOPerformanceTester/main.swift
  Sources/NIOPosix/BaseSocketChannel.swift
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
  Sources/NIOPosix/NIOThreadPool.swift
  Sources/NIOPosix/SelectableEventLoop.swift
  Sources/NIOPosix/SelectorGeneric.swift
  Tests/NIOConcurrencyHelpersTests/NIOConcurrencyHelpersTests.swift
  Tests/NIOEmbeddedTests/AsyncTestingEventLoopTests.swift
  Tests/NIOEmbeddedTests/TestUtils.swift
  Tests/NIOPosixTests/BootstrapTest.swift
  Tests/NIOPosixTests/EventLoopTest.swift
  Tests/NIOPosixTests/NIOThreadPoolTest.swift
  Tests/NIOPosixTests/TestUtils.swift
  Tests/NIOPosixTests/ThreadTest.swift
Labels: 🔼 needs-minor-version-bump

#2270 address additional NIOLockedValueBox review comments
  Sources/NIOConcurrencyHelpers/NIOLockedValueBox.swift
  Tests/NIOConcurrencyHelpersTests/NIOConcurrencyHelpersTests.swift
Labels: needs-no-version-bump

#2272 Update allocation limits
  docker/docker-compose.1804.54.yaml
  docker/docker-compose.2004.55.yaml
  docker/docker-compose.2004.56.yaml
  docker/docker-compose.2204.57.yaml
Labels: needs-no-version-bump

#2267 Raise minimum supported Swift version from 5.4 to 5.5
  CONTRIBUTING.md
  IntegrationTests/tests_02_syscall_wrappers/defines.sh
  Package@swift-5.4.swift
  README.md
  SECURITY.md
  Sources/NIOWebSocket/Base64.swift
  Tests/LinuxMain.swift
  docker/Dockerfile
  docker/docker-compose.2204.57.yaml
  scripts/generate_linux_tests.rb
Labels: 🔼 needs-minor-version-bump

#2273 Move ISSUE_TEMPLATE.md to ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: needs-no-version-bump
