Repository apple/swift-nio, pull requests merged in 2022-06, with the labels that each got.

#2141 NIOCore: adjust labels for `inet_{ntop,pton}` on Windows
  Sources/NIOCore/Interfaces.swift
Labels: patch-version-bump-only

#2149 Adopt `Sendable` in `Codec.swift` and `SingleStepByteToMessageDecoder.swift`
  Sources/NIOCore/Codec.swift
  Sources/NIOCore/SingleStepByteToMessageDecoder.swift
Labels: 🔼 needs-minor-version-bump

#2162 [docs] Fix docc warning about missing symbol
  Sources/NIOCore/AsyncAwaitSupport.swift
Labels: patch-version-bump-only

#2152 NIOCore: adjust socket address handling on Windows
  Sources/NIOCore/SocketAddresses.swift
Labels: patch-version-bump-only

#2156 NIOCore: add explicit type cast for Windows compatibility
  Sources/NIOCore/Interfaces.swift
Labels: patch-version-bump-only

#2158 NIOCore: import the C library interfaces
  Sources/NIOCore/SocketAddresses.swift
Labels: patch-version-bump-only

#2163 NIOCore: remove reference to `in_addr_t` on Windows
  Sources/NIOCore/SocketAddresses.swift
Labels: patch-version-bump-only

#2165 NIOCore: duplicate the NIODevice implementation on Windows
  Sources/NIOCore/Interfaces.swift
Labels: patch-version-bump-only

#2166 NIOPosix: re-export C library on Windows to match
  Sources/NIOPosix/System.swift
Labels: patch-version-bump-only

#2169 Add support for translating subnet prefixes to masks
  Sources/NIOCore/Interfaces.swift
  Sources/NIOCore/SocketAddresses.swift
  Tests/NIOPosixTests/SocketAddressTest+XCTest.swift
  Tests/NIOPosixTests/SocketAddressTest.swift
Labels: patch-version-bump-only

#2150 NIOCore: extract and modify POSIX flag constants
  Sources/NIOCore/FileHandle.swift
Labels: patch-version-bump-only

#2135 Remove `@preconcurrency` from internal `EventLoopFuture` methods
  Sources/NIOCore/EventLoopFuture.swift
  Sources/NIOCore/NIOSendable.swift
  docker/docker-compose.1804.54.yaml
  docker/docker-compose.2004.55.yaml
  docker/docker-compose.2004.56.yaml
  docker/docker-compose.2004.57.yaml
  docker/docker-compose.2004.main.yaml
Labels: 🔼 needs-minor-version-bump

#2168 NIOPosix: add additional imports and typealiases on Windows
  Sources/NIOPosix/BSDSocketAPIWindows.swift
Labels: patch-version-bump-only

#2173 NIOPosix: use wrapper function for duplicating file descriptor
  Sources/NIOPosix/Bootstrap.swift
Labels: patch-version-bump-only

#2174 NIOPosix: shuffle typealias location
  Sources/NIOPosix/BSDSocketAPIWindows.swift
  Sources/NIOPosix/System.swift
Labels: patch-version-bump-only

#2172 NIOPosix: remove unused alias for function
  Sources/NIOPosix/System.swift
Labels: patch-version-bump-only

#2171 NIOPosix: silence some deprecation warnings on Windows
  Sources/NIOPosix/System.swift
Labels: patch-version-bump-only

#2180 NIOPosix: use typealias instead of C name
  Sources/NIOPosix/PendingWritesManager.swift
  Sources/NIOPosix/Socket.swift
Labels: patch-version-bump-only

#2177 NIOPosix: use internal enumeration for GAI resolver
  Sources/NIOPosix/Bootstrap.swift
  Sources/NIOPosix/GetaddrinfoResolver.swift
  Tests/NIOPosixTests/GetAddrInfoResolverTest.swift
  Tests/NIOPosixTests/TestUtils.swift
Labels: patch-version-bump-only

#2181 NIOPosix: reorganise ECN constants, define for Windows
  Sources/NIOPosix/System.swift
Labels: patch-version-bump-only

#2179 NIOPosix: port file validation to Windows
  Sources/NIOPosix/Bootstrap.swift
Labels: patch-version-bump-only

#2182 NIOPosix: reorganise packet info constants
  Sources/NIOPosix/System.swift
Labels: patch-version-bump-only

#2183 NIOPosix: adjust precondition for Windows
  Sources/NIOPosix/DatagramVectorReadManager.swift
Labels: patch-version-bump-only

#2186 Use 5.7 nightlies
  docker/docker-compose.2004.57.yaml
Labels: needs-no-version-bump

#2193 Use correct alloc limits for 5.7
  docker/docker-compose.2004.57.yaml
Labels: needs-no-version-bump

#2191 Provide conversion APIs between TimeAmount and Swift.Duration
  Package.swift
  Sources/_NIOBeta/TimeAmount+Duration.swift
  Tests/LinuxMain.swift
  Tests/NIOBetaTests/TimeAmount+DurationTests+XCTest.swift
  Tests/NIOBetaTests/TimeAmount+DurationTests.swift
Labels: 🔼 needs-minor-version-bump

#2194 NIOPosix: disable `timespec` extension on Windows
  Sources/NIOPosix/SelectorGeneric.swift
Labels: patch-version-bump-only

#2195 Adopt `Sendable` in `NIOEmbedded`
  Sources/NIOEmbedded/Embedded.swift
Labels: 🔼 needs-minor-version-bump

#2199 Adopt `Sendable` in `NIOTestUtils`
  Sources/NIOTestUtils/ByteToMessageDecoderVerifier.swift
  Sources/NIOTestUtils/EventCounterHandler.swift
  Sources/NIOTestUtils/NIOHTTP1TestServer.swift
Labels: 🔼 needs-minor-version-bump

#2203 Adopt `Sendable` in `NIOFoundationCompat`
  Sources/NIOFoundationCompat/ByteBuffer-foundation.swift
Labels: 🔼 needs-minor-version-bump

#2202 Adopt `Sendable` in `NIOTLS`
  Sources/NIOTLS/ApplicationProtocolNegotiationHandler.swift
  Sources/NIOTLS/SNIHandler.swift
  Sources/NIOTLS/TLSEvents.swift
Labels: 🔼 needs-minor-version-bump

#2206 Adopt `noasync` for `ThreadSpecificVariable`
  Sources/NIOPosix/Thread.swift
Labels: 🔼 needs-minor-version-bump

#2208 Adopt `Sendable` for types in `NIOPosix`
  Sources/NIOPosix/Bootstrap.swift
  Sources/NIOPosix/HappyEyeballs.swift
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
  Sources/NIOPosix/NIOThreadPool.swift
  Sources/NIOPosix/NonBlockingFileIO.swift
  Sources/NIOPosix/Thread.swift
Labels: 🔼 needs-minor-version-bump

#2210 Adopt `Sendable` for `NIOThreadPool`
  Sources/NIOPosix/NIOThreadPool.swift
Labels: 🔼 needs-minor-version-bump
