Repository apple/swift-nio, pull requests merged in 2023-03, with the labels that each got.

#2376 Fix memory binding.
  Sources/NIOPosix/Pool.swift
Labels: patch-version-bump-only

#2382 Lower the max segment count in tests
  Tests/NIOPosixTests/DatagramChannelTests.swift
Labels: needs-no-version-bump

#2383 Rebuild the channel when retrying testWriteBufferAtGSOSegmentCountLimit
  Tests/NIOPosixTests/DatagramChannelTests.swift
Labels: needs-no-version-bump

#2379 Remove redundant availability guards
  Tests/NIOPosixTests/EventLoopTest.swift
Labels: needs-no-version-bump

#2381 mark syncShutdownGracefully noasync
  Sources/NIOCore/EventLoop.swift
  Sources/NIOPosix/NIOThreadPool.swift
  Tests/NIOPosixTests/NIOThreadPoolTest+XCTest.swift
  Tests/NIOPosixTests/NIOThreadPoolTest.swift
  Tests/NIOPosixTests/XCTest+AsyncAwait.swift
Labels: 🔼 needs-minor-version-bump

#2385 Add support for UDP_GRO
  Sources/CNIOLinux/include/CNIOLinux.h
  Sources/CNIOLinux/shim.c
  Sources/NIOCore/BSDSocketAPI.swift
  Sources/NIOCore/ChannelOption.swift
  Sources/NIOCore/Utilities.swift
  Sources/NIOPosix/BSDSocketAPIPosix.swift
  Sources/NIOPosix/BSDSocketAPIWindows.swift
  Sources/NIOPosix/Socket.swift
  Sources/NIOPosix/SocketChannel.swift
  Tests/NIOPosixTests/DatagramChannelTests+XCTest.swift
  Tests/NIOPosixTests/DatagramChannelTests.swift
Labels: 🔼 needs-minor-version-bump

#2386 Rework the `NIOAsyncSequenceProducer` tests to rely less on timings
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncSequenceTests.swift
  Tests/NIOCoreTests/AsyncSequences/NIOThrowingAsyncSequenceTests.swift
Labels: needs-no-version-bump

#2378 Buffer pool for message headers and addresses.
  Sources/NIOPosix/PendingDatagramWritesManager.swift
  Sources/NIOPosix/Pool.swift
  Sources/NIOPosix/SelectableEventLoop.swift
  Sources/NIOPosix/SocketChannel.swift
  Tests/NIOPosixTests/PendingDatagramWritesManagerTests.swift
Labels: patch-version-bump-only

#2387 Allow UDP GRO tests to fail in some circumstances
  Package.swift
  Sources/CNIOLinux/include/CNIOLinux.h
  Sources/CNIOLinux/shim.c
  Tests/NIOPosixTests/DatagramChannelTests.swift
Labels: patch-version-bump-only

#2389 Work around the SwiftPM layout change.
  IntegrationTests/tests_02_syscall_wrappers/defines.sh
  IntegrationTests/tests_02_syscall_wrappers/test_01_syscall_wrapper_fast.sh
  IntegrationTests/tests_02_syscall_wrappers/test_02_unacceptable_errnos.sh
  IntegrationTests/tests_02_syscall_wrappers/test_03_unacceptable_read_errnos.sh
Labels: needs-no-version-bump
