Repository apple/swift-nio, pull requests merged in 2023-04, with the labels that each got.

#2396 Update links in NIO docs index
  Sources/NIO/Docs.docc/index.md
Labels: needs-no-version-bump

#2399 Throw `CancellationError` if `NIOThrowingAsyncSequenceProducer.AsyncIterator.next()` is cancelled instead of returning `nil`
  Sources/NIOCore/AsyncSequences/NIOAsyncSequenceProducer.swift
  Sources/NIOCore/AsyncSequences/NIOThrowingAsyncSequenceProducer.swift
  Tests/NIOCoreTests/AsyncSequences/NIOThrowingAsyncSequenceTests.swift
Labels: 🔼 needs-minor-version-bump

#2397 Land `NIOAsyncChannel` as SPI
  Package.swift
  Sources/NIOCore/AsyncChannel/AsyncChannel.swift
  Sources/NIOCore/AsyncChannel/AsyncChannelInboundStream.swift
  Sources/NIOCore/AsyncChannel/AsyncChannelInboundStreamChannelHandler.swift
  Sources/NIOCore/AsyncChannel/AsyncChannelOutboundWriter.swift
  Sources/NIOCore/AsyncChannel/AsyncChannelOutboundWriterHandler.swift
  Sources/NIOCore/AsyncChannel/CloseRatchet.swift
  Tests/NIOCoreTests/AsyncChannel/AsyncChannelTests.swift
  Tests/NIOCoreTests/XCTest+AsyncAwait.swift
Labels: 🔼 needs-minor-version-bump

#2400 Clean up and regression check the docs.
  Sources/NIO/Docs.docc/index.md
  Sources/NIOCore/AsyncAwaitSupport.swift
  Sources/NIOCore/AsyncSequences/NIOAsyncSequenceProducer.swift
  Sources/NIOCore/AsyncSequences/NIOThrowingAsyncSequenceProducer.swift
  Sources/NIOCore/ByteBuffer-views.swift
  Sources/NIOCore/Docs.docc/index.md
  Sources/NIOCore/EventLoopFuture.swift
  Sources/NIOCore/NIOLoopBound.swift
  Sources/NIOCore/Utilities.swift
  docker/docker-compose.2004.55.yaml
  docker/docker-compose.2004.56.yaml
  docker/docker-compose.2204.57.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.main.yaml
  docker/docker-compose.yaml
  scripts/check-docs.sh
Labels: needs-no-version-bump

#2401 Throw `CancellationError` instead of returning `nil` during early cancellation.
  Sources/NIOCore/AsyncSequences/NIOAsyncSequenceProducer.swift
  Sources/NIOCore/AsyncSequences/NIOThrowingAsyncSequenceProducer.swift
  Sources/NIOPerformanceTester/NIOAsyncSequenceProducerBenchmark.swift
  Tests/NIOCoreTests/AsyncSequences/NIOThrowingAsyncSequenceTests.swift
Labels: 🔼 needs-minor-version-bump

#2405 Fix broken docs.
  Sources/NIOCore/AsyncSequences/NIOThrowingAsyncSequenceProducer.swift
Labels: needs-no-version-bump

#2402 Handle reentrant reads in ALPNHandler
  Package.swift
  Sources/NIOTLS/ApplicationProtocolNegotiationHandler.swift
  Tests/NIOTLSTests/ApplicationProtocolNegotiationHandlerTests+XCTest.swift
  Tests/NIOTLSTests/ApplicationProtocolNegotiationHandlerTests.swift
Labels: patch-version-bump-only

#2407 Close accepted FDs if we fail to create Socket
  Sources/NIOPosix/ServerSocket.swift
Labels: patch-version-bump-only

#2408 Don't have channels stop reading on errors they tolerate.
  Sources/NIOPosix/BaseSocketChannel.swift
  Tests/NIOPosixTests/SALChannelTests.swift
  Tests/NIOPosixTests/SocketChannelTest.swift
  Tests/NIOPosixTests/SyscallAbstractionLayer.swift
Labels: patch-version-bump-only

#2409 Avoid double-closing on fcntl failures
  Sources/NIOPosix/ServerSocket.swift
  Sources/NIOPosix/SocketProtocols.swift
Labels: needs-no-version-bump

#2411 Extend the integration test harness to track FDs
  IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/include/atomic-counter.h
  IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/src/atomic-counter.c
  IntegrationTests/allocation-counter-tests-framework/template/HookedFunctionsDoHook/Sources/HookedFunctions/include/hooked-functions.h
  IntegrationTests/allocation-counter-tests-framework/template/HookedFunctionsDoHook/Sources/HookedFunctions/src/hooked-functions-darwin.c
  IntegrationTests/allocation-counter-tests-framework/template/HookedFunctionsDoHook/Sources/HookedFunctions/src/hooked-functions-unix.c
  IntegrationTests/allocation-counter-tests-framework/template/Sources/bootstrapDoHook/main.c
  IntegrationTests/allocation-counter-tests-framework/template/scaffolding.swift
  IntegrationTests/tests_04_performance/test_01_allocation_counts.sh
  IntegrationTests/tests_04_performance/test_01_resources/test_1000_rst_connections.swift
Labels: needs-no-version-bump

#2412 AsyncChannelBootstrapTests bind to 0 instead
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
Labels: needs-no-version-bump

#2413 Bind to port 0 in a few more places
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
Labels: needs-no-version-bump

#2414 Handle close(output) in the pipeline handler.
  Sources/NIOHTTP1/HTTPServerPipelineHandler.swift
  Tests/NIOHTTP1Tests/HTTPServerPipelineHandlerTest.swift
Labels: patch-version-bump-only

#2415 NIOThrowingAsyncSequenceProducer throws when cancelled
  Sources/NIOCore/AsyncSequences/NIOThrowingAsyncSequenceProducer.swift
  Tests/NIOCoreTests/AsyncSequences/NIOThrowingAsyncSequenceTests.swift
Labels: patch-version-bump-only
