Repository apple/swift-nio, pull requests merged in 2023-11, with the labels that each got.

#2586 Fix spelling of retroactive guard
  Sources/NIOFoundationCompat/ByteBuffer-foundation.swift
Labels: patch-version-bump-only

#2587 Fix reordering/reentrancy bug in `NIOAsyncWriter` + `NIOAsyncChannel`
  Sources/NIOCore/AsyncSequences/NIOAsyncWriter.swift
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncWriterTests.swift
Labels: patch-version-bump-only

#2584 Fixing an issue with CNIOSHA1 missing an #include for the BYTE_ORDER define.
  Sources/CNIOSHA1/c_nio_sha1.c
  Sources/CNIOSHA1/include/CNIOSHA1.h
  Sources/CNIOSHA1/update_and_patch_sha1.sh
Labels: patch-version-bump-only

#2589 Add `withInboundOutboud` to `NIOAsyncChannel` and deprecate deinit ba…
  Benchmarks/Benchmarks/NIOPosixBenchmarks/TCPEchoAsyncChannel.swift
  Sources/NIOCore/AsyncChannel/AsyncChannel.swift
  Sources/NIOCore/AsyncChannel/AsyncChannelInboundStream.swift
  Sources/NIOCore/AsyncChannel/AsyncChannelInboundStreamChannelHandler.swift
  Sources/NIOCore/AsyncChannel/AsyncChannelOutboundWriter.swift
  Sources/NIOCore/AsyncChannel/AsyncChannelOutboundWriterHandler.swift
  Sources/NIOCore/AsyncChannel/CloseRatchet.swift
  Sources/NIOCore/AsyncSequences/NIOAsyncSequenceProducer.swift
  Sources/NIOCore/AsyncSequences/NIOAsyncWriter.swift
  Sources/NIOCore/AsyncSequences/NIOThrowingAsyncSequenceProducer.swift
  Sources/NIOCore/Docs.docc/swift-concurrency.md
  Sources/NIOPerformanceTester/NIOAsyncSequenceProducerBenchmark.swift
  Sources/NIOPerformanceTester/NIOAsyncWriterSingleWritesBenchmark.swift
  Sources/NIOTCPEchoClient/Client.swift
  Sources/NIOTCPEchoServer/Server.swift
  Tests/NIOCoreTests/AsyncChannel/AsyncChannelTests.swift
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncSequenceTests.swift
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncWriterTests.swift
  Tests/NIOCoreTests/AsyncSequences/NIOThrowingAsyncSequenceTests.swift
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
Labels: 🔼 needs-minor-version-bump

#2592 Add `closeOnDeinit` to the `NIOAsyncChannel` init
  Benchmarks/Benchmarks/NIOPosixBenchmarks/TCPEchoAsyncChannel.swift
  Sources/NIOCore/AsyncChannel/AsyncChannel.swift
  Sources/NIOCore/AsyncChannel/AsyncChannelInboundStream.swift
  Sources/NIOCore/AsyncChannel/AsyncChannelOutboundWriter.swift
  Sources/NIOCore/Docs.docc/swift-concurrency.md
  Sources/NIOPosix/Bootstrap.swift
  Sources/NIOTCPEchoClient/Client.swift
  Sources/NIOTCPEchoServer/Server.swift
  Sources/NIOWebSocketClient/Client.swift
  Sources/NIOWebSocketServer/Server.swift
  Tests/NIOCoreTests/AsyncChannel/AsyncChannelTests.swift
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
Labels: 🔼 needs-minor-version-bump

#2596 Add missing availability guards in tests
  Tests/NIOCoreTests/AsyncChannel/AsyncChannelInboundStreamTests.swift
  Tests/NIOCoreTests/AsyncChannel/AsyncChannelOutboundWriterTests.swift
  Tests/NIOCoreTests/AsyncChannel/AsyncChannelTests.swift
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncSequenceTests.swift
  Tests/NIOCoreTests/AsyncSequences/NIOThrowingAsyncSequenceTests.swift
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
  Tests/NIOPosixTests/SerialExecutorTests.swift
Labels: patch-version-bump-only

#2602 Update APNSwift Repository Link in README.md
  README.md
Labels: needs-no-version-bump

#2595 Changes to support building with Musl
  IntegrationTests/tests_02_syscall_wrappers/defines.sh
  IntegrationTests/tests_05_assertions/defines.sh
  Package.swift
  Sources/CNIOLinux/shim.c
  Sources/NIOCore/ChannelOption.swift
  Sources/NIOCore/IO.swift
  Sources/NIOPosix/BSDSocketAPICommon.swift
  Sources/NIOPosix/SocketProtocols.swift
  Sources/NIOPosix/System.swift
Labels: patch-version-bump-only

#2601 Add tests to validate the behaviour when requests/response content-length headers are wrong in HTTP1
  Tests/NIOHTTP1Tests/ContentLengthTests.swift
Labels: needs-no-version-bump
