Repository apple/swift-nio, pull requests merged in 2023-06, with the labels that each got.

#2437 Add NIOAsyncChannel based connect methods to ClientBootstrap
  Sources/NIOCore/Docs.docc/swift-concurrency.md
  Sources/NIOPosix/Bootstrap.swift
  Sources/NIOPosix/HappyEyeballs.swift
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
  Tests/NIOPosixTests/HappyEyeballsTest.swift
Labels: 🔼 needs-minor-version-bump

#2440 Adopt the Swift CoC
  CODE_OF_CONDUCT.md
Labels: needs-no-version-bump

#2445 Update RediStack URL in README.md
  README.md
Labels: needs-no-version-bump

#2443 Align ServerBootstrap bind methods with the initializer style
  Sources/NIOCore/AsyncChannel/AsyncChannel.swift
  Sources/NIOCore/AsyncChannel/AsyncChannelInboundStream.swift
  Sources/NIOCore/AsyncChannel/AsyncChannelInboundStreamChannelHandler.swift
  Sources/NIOCore/ChannelHandler.swift
  Sources/NIOPosix/Bootstrap.swift
  Tests/NIOCoreTests/AsyncChannel/AsyncChannelTests.swift
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
  docker/docker-compose.2204.main.yaml
Labels: 🔼 needs-minor-version-bump

#2449 Add support for Musl libc
  Sources/NIOConcurrencyHelpers/NIOLock.swift
  Sources/NIOConcurrencyHelpers/atomics.swift
  Sources/NIOConcurrencyHelpers/lock.swift
  Sources/NIOCore/BSDSocketAPI.swift
  Sources/NIOCore/ByteBuffer-core.swift
  Sources/NIOCore/FileHandle.swift
  Sources/NIOCore/FileRegion.swift
  Sources/NIOCore/Interfaces.swift
  Sources/NIOCore/SocketAddresses.swift
  Sources/NIOCore/SocketOptionProvider.swift
  Sources/NIOCore/SystemCallHelpers.swift
  Sources/NIOCore/Utilities.swift
  Sources/NIOPosix/BSDSocketAPICommon.swift
  Sources/NIOPosix/DatagramVectorReadManager.swift
  Sources/NIOPosix/Linux.swift
  Sources/NIOPosix/PendingDatagramWritesManager.swift
  Sources/NIOPosix/Socket.swift
  Sources/NIOPosix/System.swift
  Sources/NIOPosix/ThreadPosix.swift
  Sources/_NIODataStructures/Heap.swift
Labels: patch-version-bump-only

#2451 Correct a few Musl additions from #2449 for Android, plus error if libc not found
  .mailmap
  CONTRIBUTORS.txt
  IntegrationTests/allocation-counter-tests-framework/template/scaffolding.swift
  Sources/NIOConcurrencyHelpers/NIOLock.swift
  Sources/NIOConcurrencyHelpers/atomics.swift
  Sources/NIOConcurrencyHelpers/lock.swift
  Sources/NIOCore/BSDSocketAPI.swift
  Sources/NIOCore/ByteBuffer-core.swift
  Sources/NIOCore/FileHandle.swift
  Sources/NIOCore/FileRegion.swift
  Sources/NIOCore/IO.swift
  Sources/NIOCore/Interfaces.swift
  Sources/NIOCore/SocketAddresses.swift
  Sources/NIOCore/SocketOptionProvider.swift
  Sources/NIOCore/SystemCallHelpers.swift
  Sources/NIOCore/Utilities.swift
  Sources/NIOPosix/BSDSocketAPICommon.swift
  Sources/NIOPosix/System.swift
  Sources/_NIODataStructures/Heap.swift
  Tests/NIOConcurrencyHelpersTests/NIOConcurrencyHelpersTests.swift
  Tests/NIOPosixTests/HappyEyeballsTest.swift
Labels: patch-version-bump-only

#2454 Update mailmap to unify my (Gwynne's) email addresses
  .mailmap
  CONTRIBUTORS.txt
Labels: needs-no-version-bump

#2455 Fix several minor typos in comments found in various files
  Sources/NIOCore/ByteBuffer-int.swift
  Sources/NIOCore/ChannelHandler.swift
  Sources/NIOCore/ChannelOption.swift
  Sources/NIOCore/ChannelPipeline.swift
  Sources/NIOCore/Codec.swift
  Sources/NIOCore/NIOAny.swift
  Sources/NIOCore/Utilities.swift
Labels: needs-no-version-bump

#2456 Allocations regressed in 5.9
  docker/docker-compose.2204.59.yaml
Labels: needs-no-version-bump
