Repository apple/swift-nio, pull requests merged in 2023-10, with the labels that each got.

#2524 Bump minimum Swift version to 5.7
  CONTRIBUTING.md
  IntegrationTests/tests_02_syscall_wrappers/defines.sh
  Package.swift
  README.md
  SECURITY.md
  Sources/NIOCore/AsyncChannel/AsyncChannelInboundStream.swift
  Sources/NIOCore/AsyncChannel/AsyncChannelOutboundWriter.swift
  Sources/NIOCore/ChannelHandlers.swift
  Sources/NIOCore/ChannelPipeline.swift
  Sources/NIOCore/Codec.swift
  Sources/NIOCore/EventLoop.swift
  Sources/NIOCore/EventLoopFuture.swift
  Sources/NIOCore/SingleStepByteToMessageDecoder.swift
  Sources/NIOCore/UniversalBootstrapSupport.swift
  Sources/NIOHTTP1/HTTPPipelineSetup.swift
  Sources/NIOPosix/Bootstrap.swift
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
  Sources/NIOPosix/NIOThreadPool.swift
  Sources/NIOPosix/NonBlockingFileIO.swift
  Sources/NIOPosix/Thread.swift
  Sources/NIOWebSocket/NIOWebSocketServerUpgrader.swift
  Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift
  docker/docker-compose.2204.510.yaml
  docker/docker-compose.2204.59.yaml
Labels: 🔼 needs-minor-version-bump

#2527 Breaking SPI(AsyncChannel): Align back pressure naming
  Sources/NIOCore/AsyncChannel/AsyncChannel.swift
  Sources/NIOCore/AsyncChannel/AsyncChannelInboundStream.swift
  Sources/NIOPosix/Bootstrap.swift
  Tests/NIOCoreTests/AsyncChannel/AsyncChannelTests.swift
Labels: 🔼 needs-minor-version-bump

#2528 SPI(AsyncChannel): Make `NIOAsyncChannel` a struct
  Sources/NIOCore/AsyncChannel/AsyncChannel.swift
Labels: 🔼 needs-minor-version-bump

#2531 Tolerate empty HTTP response body parts
  Sources/NIOHTTP1/HTTPEncoder.swift
  Tests/NIOHTTP1Tests/HTTPServerClientTest.swift
Labels: patch-version-bump-only

#2529 SPI(AsyncChannel): Update the concurrency documentation
  Sources/NIOCore/Docs.docc/swift-concurrency.md
Labels: needs-no-version-bump

#2526 Introduce new typed `HTTPClientUpgrader` and `WebSocketClientUpgrader`
  Sources/NIOHTTP1/HTTPTypedPipelineSetup.swift
  Sources/NIOHTTP1/NIOTypedHTTPClientUpgradeHandler.swift
  Sources/NIOHTTP1/NIOTypedHTTPClientUpgraderStateMachine.swift
  Sources/NIOHTTP1/NIOTypedHTTPServerUpgradeHandler.swift
  Sources/NIOWebSocket/NIOWebSocketClientUpgrader.swift
  Sources/NIOWebSocketClient/Client.swift
  Sources/NIOWebSocketClient/main.swift
  Tests/NIOHTTP1Tests/HTTPClientUpgradeTests.swift
  Tests/NIOWebSocketTests/WebSocketClientEndToEndTests.swift
Labels: 🔼 needs-minor-version-bump

#2538 Add customization point for scheduling `ExecutorJob`s on `EventLoop`s
  Benchmarks/Benchmarks/NIOPosixBenchmarks/Benchmarks.swift
  Benchmarks/Benchmarks/NIOPosixBenchmarks/TCPEcho.swift
  Benchmarks/Benchmarks/NIOPosixBenchmarks/TCPEchoAsyncChannel.swift
  Benchmarks/Thresholds/5.10/NIOPosixBenchmarks.TCPEchoAsyncChannel.p90.json
  Benchmarks/Thresholds/5.9/NIOPosixBenchmarks.TCPEchoAsyncChannel.p90.json
  Benchmarks/Thresholds/main/NIOPosixBenchmarks.TCPEchoAsyncChannel.p90.json
  Sources/NIOCore/EventLoop+SerialExecutor.swift
  Sources/NIOCore/EventLoop.swift
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
  Sources/NIOPosix/SelectableEventLoop.swift
Labels: 🔼 needs-minor-version-bump

#2544 perf tests: reset BB indices after every iteration
  Sources/NIOPerformanceTester/ByteBufferWriteMultipleBenchmarks.swift
Labels: needs-no-version-bump

#2543 Fix overflow
  Sources/NIOCore/EventLoop.swift
  Tests/NIOCoreTests/TimeAmountTests.swift
Labels: patch-version-bump-only

#2547 Call `NIOAsyncWriterSinkDelegate` outside of the lock
  Benchmarks/Thresholds/5.10/NIOPosixBenchmarks.TCPEchoAsyncChannel.p90.json
  Benchmarks/Thresholds/5.9/NIOPosixBenchmarks.TCPEchoAsyncChannel.p90.json
  Benchmarks/Thresholds/main/NIOPosixBenchmarks.TCPEchoAsyncChannel.p90.json
  Sources/NIOCore/AsyncChannel/AsyncChannelOutboundWriterHandler.swift
  Sources/NIOCore/AsyncSequences/NIOAsyncWriter.swift
  Tests/NIOCoreTests/AsyncChannel/AsyncChannelTests.swift
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncWriterTests.swift
Labels: patch-version-bump-only

#2542 Add jitter support to recurring tasks
  Sources/NIOCore/EventLoop.swift
  Tests/NIOPosixTests/EventLoopTest.swift
Labels: 🔼 needs-minor-version-bump

#2552 Fix flaky `testRemovesAllHTTPRelatedHandlersAfterUpgrade` test
  Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift
Labels: needs-no-version-bump

#2556 Fix `Sendable` conformance for `Lock`
  Sources/NIOConcurrencyHelpers/lock.swift
Labels: patch-version-bump-only

#2554 Remove `NIOProtocolNegotiationResult`
  Sources/NIOCore/ChannelHandler.swift
  Sources/NIOTLS/NIOTypedApplicationProtocolNegotiationHandler.swift
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
  Tests/NIOTLSTests/NIOTypedApplicationProtocolNegotiationHandlerTests.swift
Labels: 🔼 needs-minor-version-bump

#2549 Add docs for the async NIO APIs
  Benchmarks/Benchmarks/NIOPosixBenchmarks/TCPEchoAsyncChannel.swift
  Sources/NIOCore/AsyncChannel/AsyncChannel.swift
  Sources/NIOCore/AsyncChannel/AsyncChannelOutboundWriter.swift
  Sources/NIOHTTP1/NIOTypedHTTPClientUpgradeHandler.swift
  Sources/NIOTCPEchoClient/Client.swift
  Sources/NIOTCPEchoServer/Server.swift
  Sources/NIOWebSocketClient/Client.swift
  Sources/NIOWebSocketServer/Server.swift
  Tests/NIOCoreTests/AsyncChannel/AsyncChannelTests.swift
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
  docs/public-async-nio-apis.md
Labels: 🔼 needs-minor-version-bump

#2548 Remove SPI from `NIOAsyncChannel` and new bootstrap methods
  Benchmarks/Benchmarks/NIOPosixBenchmarks/TCPEchoAsyncChannel.swift
  Sources/NIOCore/AsyncChannel/AsyncChannel.swift
  Sources/NIOCore/AsyncChannel/AsyncChannelInboundStream.swift
  Sources/NIOCore/AsyncChannel/AsyncChannelOutboundWriter.swift
  Sources/NIOCore/Docs.docc/swift-concurrency.md
  Sources/NIOHTTP1/HTTPTypedPipelineSetup.swift
  Sources/NIOHTTP1/NIOTypedHTTPClientUpgradeHandler.swift
  Sources/NIOHTTP1/NIOTypedHTTPServerUpgradeHandler.swift
  Sources/NIOPosix/Bootstrap.swift
  Sources/NIOPosix/RawSocketBootstrap.swift
  Sources/NIOTCPEchoClient/Client.swift
  Sources/NIOTCPEchoServer/Server.swift
  Sources/NIOTLS/NIOTypedApplicationProtocolNegotiationHandler.swift
  Sources/NIOWebSocket/NIOWebSocketClientUpgrader.swift
  Sources/NIOWebSocket/NIOWebSocketServerUpgrader.swift
  Sources/NIOWebSocketClient/Client.swift
  Sources/NIOWebSocketServer/Server.swift
  Tests/NIOCoreTests/AsyncChannel/AsyncChannelInboundStreamTests.swift
  Tests/NIOCoreTests/AsyncChannel/AsyncChannelOutboundWriterTests.swift
  Tests/NIOCoreTests/AsyncChannel/AsyncChannelTests.swift
  Tests/NIOHTTP1Tests/HTTPClientUpgradeTests.swift
  Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
  Tests/NIOTLSTests/NIOTypedApplicationProtocolNegotiationHandlerTests.swift
  Tests/NIOWebSocketTests/WebSocketClientEndToEndTests.swift
  Tests/NIOWebSocketTests/WebSocketServerEndToEndTests.swift
  docs/public-async-nio-apis.md
Labels: 🔼 needs-minor-version-bump

#2550 Avoid terminating when a precondition is not met in HTTPServerPipelineHandler
  Sources/NIOHTTP1/HTTPServerPipelineHandler.swift
  Tests/NIOHTTP1Tests/HTTPServerPipelineHandlerTest.swift
Labels: patch-version-bump-only

#2557 Fix flakiness in testDelayedUpgradeBehaviour
  Tests/NIOHTTP1Tests/HTTPClientUpgradeTests.swift
  Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift
Labels: needs-no-version-bump

#2562 NonBlockingFileIO: tolerate chunk handlers from other ELs
  Sources/NIOPosix/NonBlockingFileIO.swift
  Tests/NIOPosixTests/NonBlockingFileIOTest.swift
Labels: patch-version-bump-only

#2563 Support disabling body aggregation in NIOHTTP1TestServer
  Sources/NIOTestUtils/NIOHTTP1TestServer.swift
  Tests/NIOTestUtilsTests/NIOHTTP1TestServerTest.swift
Labels: 🔼 needs-minor-version-bump

#2567 Add autogenerated files from VSCode to .gitignore
  .gitignore
Labels: needs-no-version-bump

#2569 Mark retroactive conformances appropriately.
  Sources/NIOFoundationCompat/ByteBuffer-foundation.swift
Labels: patch-version-bump-only

#2572 Mention file length in bytes in `readFileSize` explicitly
  Sources/NIOPosix/NonBlockingFileIO.swift
Labels: needs-no-version-bump

#2537 Fix thread-safety issues in TCPThroughputBenchmark
  Sources/NIOPerformanceTester/TCPThroughputBenchmark.swift
Labels: needs-no-version-bump

#2566 Add async version of NIOThreadPool.runIfActive
  Sources/NIOPosix/NIOThreadPool.swift
  Tests/NIOPosixTests/NIOThreadPoolTest.swift
Labels: 🔼 needs-minor-version-bump

#2575 Fix concurrency doc APIs
  Sources/NIOCore/Docs.docc/swift-concurrency.md
Labels: needs-no-version-bump

#2579 Back out new typed HTTP protocol upgrader
  Sources/NIOHTTP1/HTTPTypedPipelineSetup.swift
  Sources/NIOHTTP1/NIOTypedHTTPClientUpgradeHandler.swift
  Sources/NIOHTTP1/NIOTypedHTTPClientUpgraderStateMachine.swift
  Sources/NIOHTTP1/NIOTypedHTTPServerUpgradeHandler.swift
  Sources/NIOHTTP1/NIOTypedHTTPServerUpgraderStateMachine.swift
  Sources/NIOTCPEchoClient/Client.swift
  Sources/NIOTCPEchoServer/Server.swift
  Sources/NIOWebSocket/NIOWebSocketClientUpgrader.swift
  Sources/NIOWebSocket/NIOWebSocketServerUpgrader.swift
  Sources/NIOWebSocketClient/Client.swift
  Sources/NIOWebSocketServer/Server.swift
  Tests/NIOHTTP1Tests/HTTPClientUpgradeTests.swift
  Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift
  Tests/NIOWebSocketTests/WebSocketClientEndToEndTests.swift
  Tests/NIOWebSocketTests/WebSocketServerEndToEndTests.swift
Labels: 🔼 needs-minor-version-bump

#2580 Fix exclusive access violation in `NIOAsyncChannelOutboundWriterHandler`
  Sources/NIOCore/AsyncChannel/AsyncChannelOutboundWriterHandler.swift
  Tests/NIOCoreTests/AsyncChannel/AsyncChannelTests.swift
Labels: patch-version-bump-only
