Repository apple/swift-nio, pull requests merged in 2023-08, with the labels that each got.

#2489 Fix leaked promise in `NIOTypedApplicationProtocolNegotiationHandler`
  Sources/NIOTLS/NIOTypedApplicationProtocolNegotiationHandler.swift
  Sources/NIOTLS/ProtocolNegotiationHandlerStateMachine.swift
  Tests/NIOTLSTests/NIOTypedApplicationProtocolNegotiationHandlerTests.swift
Labels: patch-version-bump-only

#2497 Avoid using deinit to fulfil the protocol negotiation promise
  Sources/NIOTLS/NIOTypedApplicationProtocolNegotiationHandler.swift
  Sources/NIOTLS/ProtocolNegotiationHandlerStateMachine.swift
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
  Tests/NIOTLSTests/NIOTypedApplicationProtocolNegotiationHandlerTests.swift
Labels: patch-version-bump-only

#2496 EventLoopFuture/Promise: only Sendable if Value is Sendable
  Sources/NIOCore/EventLoopFuture.swift
Labels: 🔼 needs-minor-version-bump

#2500 match casing of reference links to the casing of the actual referenced declaration/module
  Sources/NIO/Docs.docc/index.md
Labels: needs-no-version-bump

#2502 Update nightly allocation limits
  docker/docker-compose.2204.main.yaml
Labels: needs-no-version-bump

#2475 Adding ByteBuffer.hexDump in xxd and hexdump -C formats
  Sources/NIOCore/ByteBuffer-conversions.swift
  Sources/NIOCore/ByteBuffer-hexdump.swift
  Tests/NIOCoreTests/ByteBufferTest.swift
Labels: 🔼 needs-minor-version-bump

#2499 Docs: explain the basic safe usage of ByteBuffer
  Sources/NIOCore/ByteBuffer-core.swift
Labels: needs-no-version-bump

#2503 Make the initializers of NIOThreadPoolError public
  Sources/NIOPosix/NIOThreadPool.swift
Labels: 🔼 needs-minor-version-bump

#2508 Support users opting-out of us setting framing headers.
  Sources/NIOHTTP1/HTTPEncoder.swift
  Sources/NIOHTTP1/HTTPPipelineSetup.swift
  Tests/NIOHTTP1Tests/HTTPRequestEncoderTest.swift
  Tests/NIOHTTP1Tests/HTTPResponseEncoderTest.swift
Labels: 🔼 needs-minor-version-bump
