Repository apple/swift-nio, pull requests merged in 2023-07, with the labels that each got.

#2459 Make `NIO[Throwing]AsyncSequenceProducer.Source` `Sendable`
  Sources/NIOCore/AsyncSequences/NIOAsyncSequenceProducer.swift
  Sources/NIOCore/AsyncSequences/NIOThrowingAsyncSequenceProducer.swift
Labels: 🔼 needs-minor-version-bump

#2458 Async support NIOPipeBootstrap
  Sources/NIOCrashTester/CrashTests+System.swift
  Sources/NIOCrashTester/OutputGrepper.swift
  Sources/NIOHTTP1Server/main.swift
  Sources/NIOPosix/Bootstrap.swift
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
  Tests/NIOPosixTests/BootstrapTest.swift
  Tests/NIOPosixTests/PipeChannelTest.swift
  Tests/NIOPosixTests/TestUtils.swift
Labels: 🔼 needs-minor-version-bump

#2460 Async methods for `NIORawSocketBootstrap`
  Sources/NIOPosix/RawSocketBootstrap.swift
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
Labels: needs-no-version-bump

#2477 Throw SocketAddressError (cf. fatalError) in SocketAddress.convert for unknown address family
  Sources/NIOPosix/BaseSocket.swift
  Sources/NIOPosix/DatagramVectorReadManager.swift
  Sources/NIOPosix/SocketChannel.swift
  Tests/NIOPosixTests/SocketAddressTest.swift
Labels: patch-version-bump-only

#2476 Skip TCP_NODELAY on sockets that NIO doesn't explicitly support
  Sources/NIOPosix/BaseSocket.swift
  Tests/NIOPosixTests/ChannelTests.swift
Labels: patch-version-bump-only

#2474 WIP: Reduce the amount of bootstrap async methods
  Sources/NIOCore/AsyncChannel/AsyncChannel.swift
  Sources/NIOCore/AsyncChannel/AsyncChannelInboundStream.swift
  Sources/NIOCore/AsyncChannel/AsyncChannelInboundStreamChannelHandler.swift
  Sources/NIOCore/ChannelHandler.swift
  Sources/NIOPosix/Bootstrap.swift
  Sources/NIOPosix/RawSocketBootstrap.swift
  Sources/NIOTLS/ApplicationProtocolNegotiationHandler.swift
  Sources/NIOTLS/NIOTypedApplicationProtocolNegotiationHandler.swift
  Sources/NIOTLS/ProtocolNegotiationHandlerStateMachine.swift
  Tests/NIOCoreTests/AsyncChannel/AsyncChannelTests.swift
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
  Tests/NIOTLSTests/NIOTypedApplicationProtocolNegotiationHandlerTests.swift
Labels: 🔼 needs-minor-version-bump

#2481 update contributor email address
  .mailmap
  CONTRIBUTORS.txt
Labels: needs-no-version-bump

#2471 NIOSingletons: Use NIO in easy mode
  Package.swift
  Sources/NIOCore/GlobalSingletons.swift
  Sources/NIOCrashTester/CrashTests+EventLoop.swift
  Sources/NIOHTTP1Server/main.swift
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
  Sources/NIOPosix/NIOThreadPool.swift
  Sources/NIOPosix/PosixSingletons.swift
  Tests/NIOSingletonsTests/GlobalSingletonsTests.swift
Labels: 🔼 needs-minor-version-bump

#2487 Fix 5.9 and nightly allocation limits (#2485)
  IntegrationTests/tests_04_performance/test_01_resources/shared.swift
  docker/docker-compose.2004.56.yaml
  docker/docker-compose.2204.57.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.59.yaml
  docker/docker-compose.2204.main.yaml
Labels: needs-no-version-bump

#2463 Add async TCP echo example
  Package.swift
  Sources/NIOTCPEchoClient/Client.swift
  Sources/NIOTCPEchoClient/README.md
  Sources/NIOTCPEchoServer/README.md
  Sources/NIOTCPEchoServer/Server.swift
Labels: needs-no-version-bump

#2483 Rename the `waitForFinalResult()` methods and provide an `ELF` convenience
  Sources/NIOCore/ChannelHandler.swift
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
Labels: 🔼 needs-minor-version-bump

#2486 Don't lose or delay writes before channelActive
  Sources/NIOPosix/BaseSocket.swift
  Sources/NIOPosix/BaseSocketChannel.swift
  Sources/NIOPosix/Bootstrap.swift
  Tests/NIOPosixTests/ChannelTests.swift
  Tests/NIOPosixTests/SALChannelTests.swift
  Tests/NIOPosixTests/SyscallAbstractionLayer.swift
Labels: patch-version-bump-only

#2394 Make System.coreCount aware of cgroup2
  Sources/NIOCore/Linux.swift
  Sources/NIOCore/Utilities.swift
  Tests/NIOCoreTests/LinuxTest.swift
Labels: patch-version-bump-only

#2388 Initial PoC of Custom Actor Executor support
  Sources/NIOCore/ActorExecutor.swift
  Sources/NIOCore/EventLoop.swift
  Sources/NIOEmbedded/AsyncTestingEventLoop.swift
  Sources/NIOEmbedded/Embedded.swift
  Sources/NIOPosix/SelectableEventLoop.swift
  Tests/NIOPosixTests/SerialExecutorTests.swift
Labels: 🔼 needs-minor-version-bump
