Repository apple/swift-nio, pull requests merged in 2023-05, with the labels that each got.

#2418 Add CustomDebugStringConvertible conformance to ByteBuffer
  Sources/NIOCore/ByteBuffer-core.swift
Labels: 🔼 needs-minor-version-bump

#2419 Add unprocessedBytes property on NIOSingleStepByteToMessageProcessor
  Sources/NIOCore/SingleStepByteToMessageDecoder.swift
  Tests/NIOCoreTests/SingleStepByteToMessageDecoderTest.swift
Labels: 🔼 needs-minor-version-bump

#2417 addition of assertSuccess() and assertFailure() on EventLoopFuture
  Sources/NIOCore/EventLoopFuture.swift
  Tests/NIOPosixTests/EventLoopFutureTest.swift
Labels: 🔼 needs-minor-version-bump

#2421 Tolerate sending data after close(mode: .output)
  Sources/NIOHTTP1/HTTPServerPipelineHandler.swift
  Tests/NIOHTTP1Tests/HTTPServerPipelineHandlerTest.swift
Labels: patch-version-bump-only

#2430 Update `update-alloc-limits-...` script
  dev/update-alloc-limits-to-last-completed-ci-build
Labels: needs-no-version-bump

#2429 `Embedded`: `getOption(ChannelOptions.allowRemoteHalfClosure)` should not `fatalError`
  Sources/NIOEmbedded/AsyncTestingChannel.swift
  Sources/NIOEmbedded/Embedded.swift
  Tests/NIOEmbeddedTests/AsyncTestingChannelTests.swift
  Tests/NIOEmbeddedTests/EmbeddedChannelTest.swift
  docker/docker-compose.2004.56.yaml
  docker/docker-compose.2204.57.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.59.yaml
  docker/docker-compose.2204.main.yaml
Labels: 🔼 needs-minor-version-bump

#2433 Add test coverage of WebSocketMaskingKey.random()
  Tests/NIOWebSocketTests/WebSocketMaskingKeyTests.swift
Labels: needs-no-version-bump

#2431 Fix flaky test in NIOAsyncWriter
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncWriterTests.swift
  docker/docker-compose.2204.main.yaml
Labels: needs-no-version-bump

#2436 Fix happy eyeballs races with custom resolver
  Sources/NIOPosix/HappyEyeballs.swift
  Tests/NIOPosixTests/HappyEyeballsTest.swift
Labels: patch-version-bump-only
