Repository apple/swift-nio, pull requests merged in 2023-02, with the labels that each got.

#2361 Remove unused array
  Sources/NIOPosix/PendingDatagramWritesManager.swift
Labels: patch-version-bump-only

#2360 Add UDP performance tests
  Sources/NIOPerformanceTester/UDPBenchmark.swift
  Sources/NIOPerformanceTester/main.swift
Labels: needs-no-version-bump

#2358 Pool buffers for ivecs and storage refs in the event loop.
  Sources/NIOPosix/BaseStreamSocketChannel.swift
  Sources/NIOPosix/PendingDatagramWritesManager.swift
  Sources/NIOPosix/PendingWritesManager.swift
  Sources/NIOPosix/Pool.swift
  Sources/NIOPosix/SelectableEventLoop.swift
  Sources/NIOPosix/SocketChannel.swift
  Tests/NIOPosixTests/ChannelTests.swift
  Tests/NIOPosixTests/PendingDatagramWritesManagerTests.swift
Labels: patch-version-bump-only

#2363 Make PooledBuffer safer.
  Sources/NIOPosix/PendingDatagramWritesManager.swift
  Sources/NIOPosix/PendingWritesManager.swift
  Sources/NIOPosix/Pool.swift
  Sources/NIOPosix/SelectableEventLoop.swift
Labels: patch-version-bump-only

#2365 NIOAsyncWriter: Provide a fast path for single element writes
  Sources/NIOCore/AsyncSequences/NIOAsyncWriter.swift
Labels: 🔼 needs-minor-version-bump

#2366 Clarify on EL semantics
  Sources/NIOCore/EventLoop.swift
Labels: needs-no-version-bump

#2367 TCP channel throughput benchmark.
  Sources/NIOPerformanceTester/TCPThroughputBenchmark.swift
  Sources/NIOPerformanceTester/main.swift
Labels: needs-no-version-bump

#2368 Add availability requirements to TCPThroughputBenchmark
  Sources/NIOPerformanceTester/TCPThroughputBenchmark.swift
  Sources/NIOPerformanceTester/main.swift
Labels: needs-no-version-bump

#2373 Don't retain a task when all we want is a time
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
  Sources/NIOPosix/SelectableEventLoop.swift
  Tests/NIOPosixTests/EventLoopTest+XCTest.swift
  Tests/NIOPosixTests/EventLoopTest.swift
Labels: patch-version-bump-only

#2362 Add a pooled recv buffer allocator
  Sources/NIOCore/RecvByteBufferAllocator.swift
  Sources/NIOPosix/BaseSocketChannel.swift
  Sources/NIOPosix/BaseStreamSocketChannel.swift
  Sources/NIOPosix/PooledRecvBufferAllocator.swift
  Sources/NIOPosix/SocketChannel.swift
  Tests/LinuxMain.swift
  Tests/NIOPosixTests/PooledRecvBufferAllocatorTests+XCTest.swift
  Tests/NIOPosixTests/PooledRecvBufferAllocatorTests.swift
  dev/update-alloc-limits-to-last-completed-ci-build
  docker/docker-compose.2004.55.yaml
  docker/docker-compose.2004.56.yaml
  docker/docker-compose.2204.57.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.main.yaml
Labels: 🔼 needs-minor-version-bump

#2374 Make our time types transparent
  Sources/NIOCore/EventLoop.swift
Labels: patch-version-bump-only

#2372 Add support for UDP_SEGMENT
  Sources/CNIOLinux/include/CNIOLinux.h
  Sources/CNIOLinux/shim.c
  Sources/NIOCore/BSDSocketAPI.swift
  Sources/NIOCore/ChannelOption.swift
  Sources/NIOCore/Utilities.swift
  Sources/NIOPosix/BSDSocketAPIPosix.swift
  Sources/NIOPosix/BSDSocketAPIWindows.swift
  Sources/NIOPosix/Socket.swift
  Sources/NIOPosix/SocketChannel.swift
  Sources/NIOPosix/SocketProtocols.swift
  Tests/NIOPosixTests/DatagramChannelTests+XCTest.swift
  Tests/NIOPosixTests/DatagramChannelTests.swift
Labels: 🔼 needs-minor-version-bump

#2370 OnLoopSendable: Sendable containers if on EventLoop
  Sources/NIOCore/NIOLoopBound.swift
  Sources/NIOCrashTester/CrashTestSuites.swift
  Sources/NIOCrashTester/CrashTests+LoopBound.swift
  Tests/LinuxMain.swift
  Tests/NIOPosixTests/NIOLoopBoundTests+XCTest.swift
  Tests/NIOPosixTests/NIOLoopBoundTests.swift
Labels: 🔼 needs-minor-version-bump
