Repository apple/swift-nio, pull requests merged in 2023-01, with the labels that each got.

#2341 Allow writing and reading empty datagrams
  Sources/NIOPosix/SocketChannel.swift
  Tests/NIOPosixTests/DatagramChannelTests+XCTest.swift
  Tests/NIOPosixTests/DatagramChannelTests.swift
Labels: patch-version-bump-only

#2337 Fix main nightly CI
  IntegrationTests/tests_02_syscall_wrappers/test_02_unacceptable_errnos.sh
  IntegrationTests/tests_02_syscall_wrappers/test_03_unacceptable_read_errnos.sh
  IntegrationTests/tests_05_assertions/test_01_syscall_wrapper_fast.sh
  Sources/NIOCrashTester/main.swift
  docker/docker-compose.2004.main.yaml
Labels: needs-no-version-bump

#2347 Avoid actually allocating a giant buffer
  Tests/NIOCoreTests/ByteBufferTest.swift
Labels: needs-no-version-bump

#2345 Implement `remoteAddress0` and `localAddress0` on `EmbeddedChannel`
  Sources/NIOEmbedded/Embedded.swift
  Tests/NIOEmbeddedTests/EmbeddedChannelTest+XCTest.swift
  Tests/NIOEmbeddedTests/EmbeddedChannelTest.swift
Labels: patch-version-bump-only

#2346 Prepare mmsghdr structure properly.
  Sources/NIOPosix/PendingDatagramWritesManager.swift
  Tests/NIOPosixTests/PendingDatagramWritesManagerTests.swift
Labels: patch-version-bump-only

#2348 Avoid integer literals that won't fit.
  Tests/NIOCoreTests/ByteBufferTest.swift
Labels: needs-no-version-bump

#2349 Tail allocate mutex and a generic value using ManagedBuffer
  Sources/NIOConcurrencyHelpers/NIOLock.swift
  Sources/NIOConcurrencyHelpers/NIOLockedValueBox.swift
  docker/docker-compose.2004.55.yaml
  docker/docker-compose.2004.56.yaml
  docker/docker-compose.2004.main.yaml
  docker/docker-compose.2204.57.yaml
Labels: patch-version-bump-only

#2311 Special case EventLoopPromise.succeed() when Value is Void
  Sources/NIOCore/EventLoopFuture.swift
Labels: 🔼 needs-minor-version-bump

#2352 Lift alloc counter Package.swift to 5.1 and add platforms
  IntegrationTests/allocation-counter-tests-framework/run-allocation-counter.sh
Labels: needs-no-version-bump

#2353 Point docs to Swift Package Index
  README.md
  docs/public-api.md
Labels: needs-no-version-bump

#2355 Fix flaky testTaskCancel_whenStreaming_andNotSuspended
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncSequenceTests.swift
Labels: needs-no-version-bump
