Repository apple/swift-nio, pull requests merged in 2024-09, with the labels that each got.

#2857 Fix global concurrency hook integration test
  Sources/NIOCrashTester/CrashTests+EventLoop.swift
  Sources/NIOPosix/PosixSingletons+ConcurrencyTakeOver.swift
Labels: semver/patch

#2850 Update release.yml
  .github/release.yml
Labels: semver/none

#2865 Make `assumeIsolated` work with SerialExecutors that are backed by EventLoops
  Sources/NIOCore/EventLoop+SerialExecutor.swift
  Tests/NIOPosixTests/SerialExecutorTests.swift
Labels: semver/patch

#2864 Making ByteBuffer's description more useful
  Sources/NIOCore/ByteBuffer-core.swift
  Sources/NIOCore/ByteBuffer-hexdump.swift
  Tests/NIOCoreTests/ByteBufferTest.swift
  Tests/NIOCoreTests/NIOAnyDebugTest.swift
Labels: semver/minor

#2870 [CI] License header support `.in` and `.cmake` files
  scripts/check-license-header.sh
Labels: semver/none

#2869 Include nanoseconds in assertion of timestamp for NIOFileSystem tests
  Tests/NIOFileSystemIntegrationTests/FileHandleTests.swift
Labels: semver/none

#2872 Correct the link of sswg-security at SECURITY.md
  SECURITY.md
Labels: semver/none

#2866 Improving `description` and adding `debugDescription` to `NIOAny`
  Sources/NIOCore/NIOAny.swift
  Tests/NIOCoreTests/NIOAnyDebugTest.swift
Labels: semver/patch

#2871 Issue-2752 - Make FileChunk sendable
  Sources/NIOFileSystem/FileChunks.swift
Labels: semver/patch

#2495 Make `ByteBuffer.debugDescription` suitable for structural display
  Sources/NIOCore/ByteBuffer-core.swift
Labels: semver/patch

#2873 Speculative fix for flakey AsyncTestingEventLoop test
  Tests/NIOEmbeddedTests/AsyncTestingEventLoopTests.swift
Labels: semver/none

#2671 Add support for WASILibc
  Package.swift
  Sources/CNIOSHA1/c_nio_sha1.c
  Sources/CNIOWASI/CNIOWASI.c
  Sources/CNIOWASI/include/CNIOWASI.h
  Sources/NIOConcurrencyHelpers/NIOLock.swift
  Sources/NIOConcurrencyHelpers/atomics.swift
  Sources/NIOConcurrencyHelpers/lock.swift
  Sources/NIOCore/AsyncAwaitSupport.swift
  Sources/NIOCore/BSDSocketAPI.swift
  Sources/NIOCore/ByteBuffer-aux.swift
  Sources/NIOCore/ByteBuffer-conversions.swift
  Sources/NIOCore/ByteBuffer-core.swift
  Sources/NIOCore/Channel.swift
  Sources/NIOCore/ConvenienceOptionSupport.swift
  Sources/NIOCore/DispatchQueue+WithFuture.swift
  Sources/NIOCore/EventLoop.swift
  Sources/NIOCore/EventLoopFuture.swift
  Sources/NIOCore/FileHandle.swift
  Sources/NIOCore/FileRegion.swift
  Sources/NIOCore/GlobalSingletons.swift
  Sources/NIOCore/IO.swift
  Sources/NIOCore/Interfaces.swift
  Sources/NIOCore/MulticastChannel.swift
  Sources/NIOCore/SocketAddresses.swift
  Sources/NIOCore/SocketOptionProvider.swift
  Sources/NIOCore/SystemCallHelpers.swift
  Sources/NIOCore/Utilities.swift
  Sources/NIOEmbedded/AsyncTestingChannel.swift
  Sources/NIOEmbedded/AsyncTestingEventLoop.swift
  Sources/NIOEmbedded/Embedded.swift
  Sources/NIOPosix/GetaddrinfoResolver.swift
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
  Sources/NIOPosix/NIOThreadPool.swift
  Sources/_NIODataStructures/Heap.swift
Labels: semver/patch

#2881 NIOSingleStepByteToMessageDecoder reentrancy safety
  Sources/NIOCore/SingleStepByteToMessageDecoder.swift
  Tests/NIOCoreTests/SingleStepByteToMessageDecoderTest.swift
Labels: semver/patch

#2879 Adopt `NIOThrowingAsyncSequenceProducer`
  Sources/NIOFileSystem/DirectoryEntries.swift
  Sources/NIOFileSystem/FileChunks.swift
  Sources/NIOFileSystem/Internal/BufferedOrAnyStream.swift
  Tests/NIOFileSystemIntegrationTests/FileHandleTests.swift
Labels: semver/patch

#2882 ci: Install shellcheck if not present in CI runner
  .github/workflows/soundness.yml
Labels: semver/none

#2883 ci: Use ${GITHUB_BASE_REF} as treeish for checking API break
  .github/workflows/soundness.yml
Labels: semver/none

#2745 Issue-2734 - Clamp buffer to maximum upon large write operation
  Sources/NIOCore/ByteBuffer-core.swift
  Sources/NIOCore/Codec.swift
  Tests/NIOCoreTests/ByteBufferTest.swift
Labels: semver/patch

#2891 Expose UDP_MAX_SEGMENTS via System
  Sources/CNIOLinux/include/CNIOLinux.h
  Sources/CNIOLinux/shim.c
  Sources/NIOCore/Utilities.swift
  Tests/NIOPosixTests/DatagramChannelTests.swift
Labels: semver/minor

#2890 Add concrete description for `EmbeddedEventLoop`
  Sources/NIOEmbedded/Embedded.swift
Labels: semver/patch

#2884 ci: Refer to nested reusable workflows using remote variant
  .github/workflows/benchmarks.yml
  .github/workflows/cxx_interop.yml
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  .github/workflows/scheduled.yml
  .github/workflows/unit_tests.yml
Labels: semver/none

#2849 Add new ChannelOption to get the amount of buffered outbound data in the Channel
  Sources/NIOCore/BSDSocketAPI.swift
  Sources/NIOCore/ChannelOption.swift
  Sources/NIOEmbedded/AsyncTestingChannel.swift
  Sources/NIOEmbedded/Embedded.swift
  Sources/NIOPosix/BaseStreamSocketChannel.swift
  Sources/NIOPosix/PendingDatagramWritesManager.swift
  Sources/NIOPosix/PendingWritesManager.swift
  Sources/NIOPosix/SocketChannel.swift
  Tests/NIOEmbeddedTests/AsyncTestingChannelTests.swift
  Tests/NIOEmbeddedTests/EmbeddedChannelTest.swift
  Tests/NIOPosixTests/ChannelTests.swift
  Tests/NIOPosixTests/DatagramChannelTests.swift
  Tests/NIOPosixTests/PendingDatagramWritesManagerTests.swift
Labels: semver/minor

#2885 [CI] Fix pull request label workflow
  .github/actions/pull_request_semver_label_checker/action.yml
Labels: semver/none

#2782 Add an `AcceptBackoffHandler` to the async server bootstraps
  Sources/NIOCore/ChannelHandlers.swift
  Sources/NIOPosix/Bootstrap.swift
  Tests/NIOPosixTests/AcceptBackoffHandlerTest.swift
Labels: semver/minor

#2898 Work around a type checking error when using the Static Linux SDK
  Sources/NIOPosix/PosixSingletons+ConcurrencyTakeOver.swift
Labels: semver/patch

#2837 Issue-2748 - Add ByteBuffer Hex init & write
  Sources/NIOCore/ByteBuffer-aux.swift
  Sources/NIOCore/ByteBuffer-conversions.swift
  Sources/NIOCore/ByteBuffer-hex.swift
  Tests/NIOCoreTests/ByteBufferTest.swift
Labels: semver/minor
