Repository apple/swift-nio, pull requests merged in 2024-04, with the labels that each got.

#2697 Add a helper for setting or cascading optional promises
  Sources/NIOCore/EventLoopFuture.swift
  Tests/NIOPosixTests/EventLoopFutureTest.swift
Labels: 🔼 needs-minor-version-bump

#2699 Add support for `SWIFTCI_USE_LOCAL_DEPS` convention
  Package.swift
Labels: needs-no-version-bump

#2695 Add privacy manifest
  .PrivacyInfo.xcprivacy
  Package.swift
  Sources/NIOFileSystem/PrivacyInfo.xcprivacy
  Sources/NIOPosix/PrivacyInfo.xcprivacy
Labels: patch-version-bump-only

#2704 Tolerate IPv6 address resolution failure
  Tests/NIOPosixTests/DatagramChannelTests.swift
Labels: needs-no-version-bump

#2703 Retain a ref to NIOAsyncWriter until channel active
  Sources/NIOCore/AsyncChannel/AsyncChannelOutboundWriter.swift
  Sources/NIOCore/AsyncChannel/AsyncChannelOutboundWriterHandler.swift
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
  Tests/NIOPosixTests/NIOThreadPoolTest.swift
  Tests/NIOPosixTests/XCTest+AsyncAwait.swift
Labels: patch-version-bump-only

#2706 Remove surplus Sendable requirements from FileSystem with methods
  Sources/NIOFileSystem/BufferedWriter.swift
  Sources/NIOFileSystem/FileHandleProtocol.swift
  Sources/NIOFileSystem/FileSystem.swift
  Sources/NIOFileSystem/FileSystemProtocol.swift
  Sources/NIOFileSystem/Internal/Cancellation.swift
Labels: patch-version-bump-only

#2707 Add `ByteBuffer` support to `BufferedWriter`
  Sources/NIOFileSystem/BufferedWriter.swift
  Tests/NIOFileSystemIntegrationTests/BufferedWriterTests.swift
Labels: 🔼 needs-minor-version-bump

#2708 Add 'withTemporaryDirectory'
  Sources/NIOFileSystem/Docs.docc/Extensions/FileSystemProtocol.md
  Sources/NIOFileSystem/FileSystemProtocol.swift
  Tests/NIOFileSystemIntegrationTests/FileSystemTests.swift
Labels: 🔼 needs-minor-version-bump

#2709 Replace 'R' with 'ReturnType'
  Sources/NIOFileSystem/BufferedWriter.swift
  Sources/NIOFileSystem/FileHandleProtocol.swift
  Sources/NIOFileSystem/FileSystem.swift
  Sources/NIOFileSystem/FileSystemProtocol.swift
Labels: 🔼 needs-minor-version-bump

#2710 concurrency takeover safe for 6.0
  Sources/NIOPosix/PosixSingletons+ConcurrencyTakeOver.swift
Labels: patch-version-bump-only
