Repository apple/swift-nio, pull requests merged in 2024-11, with the labels that each got.

#2963 Fix leaking technique
  Sources/NIOPosix/PosixSingletons.swift
Labels: semver/patch

#2968 Remove sendable checking from NIOLock and NIOLockedValueBox
  Sources/NIOConcurrencyHelpers/NIOLock.swift
  Sources/NIOConcurrencyHelpers/NIOLockedValueBox.swift
Labels: semver/patch

#2970 Fix SemVer major label check
  .github/actions/pull_request_semver_label_checker/action.yml
Labels: semver/none

#2756 Close channel during upgrade, if client closes input
  Sources/NIOHTTP1/NIOTypedHTTPServerUpgradeHandler.swift
  Sources/NIOHTTP1/NIOTypedHTTPServerUpgraderStateMachine.swift
  Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift
Labels: semver/patch

#2972 unify scheduled and main yamls
  .github/workflows/main.yml
  .github/workflows/scheduled.yml
Labels: semver/none

#2976 remove unused Swift 6 language mode workflow
  .github/workflows/pull_request.yml
Labels: semver/none

#2974 Swift 6ify NIOHTTP1Server demo
  Sources/NIOHTTP1Server/main.swift
Labels: semver/none

#2971 Add WebSocketFrame.reservedBits OptionSet
  Sources/NIOWebSocket/WebSocketFrame.swift
  Tests/NIOWebSocketTests/WebSocketMaskingKeyTests.swift
Labels: semver/minor

#2964 Use condition variable in NIOThreadPool
  Sources/NIOPosix/NIOThreadPool.swift
Labels: semver/patch

#2979 Better handle ECONNRESET on connected datagram sockets.
  Sources/NIOPosix/BaseSocketChannel.swift
  Sources/NIOPosix/PipeChannel.swift
  Sources/NIOPosix/SelectableChannel.swift
  Sources/NIOPosix/SelectableEventLoop.swift
  Sources/NIOPosix/SelectorEpoll.swift
  Sources/NIOPosix/SelectorGeneric.swift
  Sources/NIOPosix/SelectorKqueue.swift
  Sources/NIOPosix/SocketChannel.swift
  Tests/NIOPosixTests/DatagramChannelTests.swift
  Tests/NIOPosixTests/SALChannelTests.swift
  Tests/NIOPosixTests/SelectorTest.swift
  Tests/NIOPosixTests/SyscallAbstractionLayer.swift
Labels: semver/patch

#2975 tests: Remove asserts on the value of local Vsock CID
  .github/workflows/pull_request.yml
  Sources/NIOPosix/VsockAddress.swift
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
  Tests/NIOPosixTests/EchoServerClientTest.swift
  Tests/NIOPosixTests/TestUtils.swift
  Tests/NIOPosixTests/VsockAddressTest.swift
Labels: semver/none

#2981 Backport: BaseSocketChannel flushNow IONotificationState changes (#2954)
  Sources/NIOPosix/BaseSocketChannel.swift
  Tests/NIOPosixTests/SALChannelTests.swift
Labels: semver/patch

#2982 Backport: Add new protocol for ChannelHandler to get buffered bytes in the channel handler (#2918)
  Sources/NIOCore/ChannelHandler.swift
  Sources/NIOCore/ChannelPipeline.swift
  Tests/NIOPosixTests/ChannelPipelineTest.swift
Labels: semver/minor

#2983 Backport: Fix broken swift format link (#2948)
  CONTRIBUTING.md
Labels: semver/none

#2987 Add back alloc limits script with JSON mode
  dev/alloc-limits-from-test-output
Labels: semver/none

#2988 Backport: Remove unused dockerfiles and allocation limit scripts (#2957)
  dev/alloc-limits-from-test-output
  dev/update-alloc-limits-to-last-completed-ci-build
  docker/Dockerfile
  docker/docker-compose.2204.510.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.59.yaml
  docker/docker-compose.2204.main.yaml
  docker/docker-compose.2204.nightly-6.0.yaml
  docker/docker-compose.yaml
Labels: semver/none

#2989 Fix leaking technique (#2963)
  Sources/NIOPosix/PosixSingletons.swift
Labels: semver/patch

#2990 Backport: Improve docs around running act for formatting (#2965)
  CONTRIBUTING.md
Labels: semver/none

#2973 Add ByteBuffer methods getUTF8ValidatedString and readUTF8ValidatedString
  Sources/NIOCore/ByteBuffer-aux.swift
  Tests/NIOCoreTests/ByteBufferTest.swift
Labels: semver/minor

#2985 EventLoopFuture.waitSpinningRunLoop()
  Sources/NIOFoundationCompat/WaitSpinningRunLoop.swift
  Tests/NIOFoundationCompatTests/WaitSpinningRunLoopTests.swift
Labels: semver/minor

#2992 Backport: Remove sendable checking from NIOLock and NIOLockedValueBox (#2968)
  Sources/NIOConcurrencyHelpers/NIOLock.swift
  Sources/NIOConcurrencyHelpers/NIOLockedValueBox.swift
Labels: semver/patch

#2984 give common blocking functions a clear name
  Sources/NIOCore/EventLoopFuture.swift
  Sources/NIOCore/SystemCallHelpers.swift
  Sources/NIOPosix/BSDSocketAPICommon.swift
  Sources/NIOPosix/BaseSocket.swift
  Sources/NIOPosix/IO.swift
  Sources/NIOPosix/Linux.swift
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
  Sources/NIOPosix/NIOThreadPool.swift
  Sources/NIOPosix/SelectableEventLoop.swift
  Sources/NIOPosix/SelectorEpoll.swift
  Sources/NIOPosix/SelectorGeneric.swift
  Sources/NIOPosix/SelectorKqueue.swift
  Sources/NIOPosix/System.swift
  Sources/NIOPosix/Thread.swift
Labels: semver/patch

#2995 fix warnings: syncShutdownGracefully not available in async contexts
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
  Tests/NIOPosixTests/SerialExecutorTests.swift
Labels: semver/none

#2996 Only toggle production state when above/below watermark
  Sources/NIOCore/AsyncSequences/NIOAsyncSequenceProducerStrategies.swift
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncSequenceProducer+HighLowWatermarkBackPressureStrategyTests.swift
Labels: semver/patch

#2997 Only toggle production state when above/below watermark (#2996)
  Sources/NIOCore/AsyncSequences/NIOAsyncSequenceProducerStrategies.swift
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncSequenceProducer+HighLowWatermarkBackPressureStrategyTests.swift
Labels: semver/patch

#2598 Make NIOFileDescriptor/FileRegion/IOData Sendable & soft-deprecated
  Sources/NIOCore/ChannelInvoker.swift
  Sources/NIOCore/FileHandle.swift
  Sources/NIOCore/FileRegion.swift
  Sources/NIOCore/IOData.swift
  Sources/NIOCore/Linux.swift
  Sources/NIOCrashTester/OutputGrepper.swift
  Sources/NIOHTTP1Server/main.swift
  Sources/NIOPosix/Bootstrap.swift
  Sources/NIOPosix/NonBlockingFileIO.swift
  Sources/NIOPosix/PendingWritesManager.swift
  Sources/NIOPosix/PipeChannel.swift
  Sources/NIOPosix/PipePair.swift
  Sources/NIOPosix/SelectorEpoll.swift
  Sources/NIOPosix/SelectorGeneric.swift
  Sources/NIOPosix/SelectorKqueue.swift
  Sources/NIOPosix/SelectorUring.swift
  Tests/NIOCoreTests/BaseObjectsTest.swift
  Tests/NIOCoreTests/NIOAnyDebugTest.swift
  Tests/NIOCoreTests/XCTest+Extensions.swift
  Tests/NIOEmbeddedTests/EmbeddedChannelTest.swift
  Tests/NIOHTTP1Tests/HTTPServerClientTest.swift
  Tests/NIOPosixTests/BootstrapTest.swift
  Tests/NIOPosixTests/ChannelPipelineTest.swift
  Tests/NIOPosixTests/ChannelTests.swift
  Tests/NIOPosixTests/FileRegionTest.swift
  Tests/NIOPosixTests/NIOFileHandleTest.swift
  Tests/NIOPosixTests/NonBlockingFileIOTest.swift
  Tests/NIOPosixTests/TestUtils.swift
Labels: semver/minor

#2999 Add Cxx interop swift settings to CI
  scripts/check-cxx-interop-compatibility.sh
Labels: semver/none

#2994 fix almost all Sendable warnings
  Sources/NIOCore/ChannelPipeline.swift
  Sources/NIOFileSystem/Internal/BufferedStream.swift
  Sources/NIOHTTP1/HTTPServerPipelineHandler.swift
  Sources/NIOHTTP1/HTTPServerUpgradeHandler.swift
  Sources/NIOHTTP1/NIOHTTPClientUpgradeHandler.swift
  Sources/NIOHTTP1/NIOTypedHTTPClientUpgradeHandler.swift
  Sources/NIOHTTP1/NIOTypedHTTPServerUpgradeHandler.swift
  Sources/NIOHTTP1Server/main.swift
  Sources/NIOPosix/Bootstrap.swift
  Sources/NIOTLS/ApplicationProtocolNegotiationHandler.swift
  Sources/NIOTLS/NIOTypedApplicationProtocolNegotiationHandler.swift
  Sources/NIOTestUtils/NIOHTTP1TestServer.swift
  Sources/NIOWebSocket/WebSocketProtocolErrorHandler.swift
  Tests/NIOEmbeddedTests/EmbeddedChannelTest.swift
  Tests/NIOHTTP1Tests/HTTPClientUpgradeTests.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
  Tests/NIOHTTP1Tests/HTTPServerClientTest.swift
  Tests/NIOHTTP1Tests/HTTPServerPipelineHandlerTest.swift
  Tests/NIOPosixTests/ChannelNotificationTest.swift
  Tests/NIOPosixTests/ChannelPipelineTest.swift
  Tests/NIOPosixTests/ChannelTests.swift
  Tests/NIOPosixTests/EchoServerClientTest.swift
  Tests/NIOPosixTests/EventLoopTest.swift
  Tests/NIOPosixTests/IdleStateHandlerTest.swift
  Tests/NIOPosixTests/NIOThreadPoolTest.swift
  Tests/NIOPosixTests/SocketChannelTest.swift
  Tests/NIOPosixTests/StreamChannelsTest.swift
Labels: semver/minor

#2480 deprecate NIOEventLoopGroupProvider.createNew
  Sources/NIOCore/Docs.docc/index.md
  Sources/NIOCore/EventLoop.swift
Labels: semver/minor

#1839 ByteBuffer: one fewer allocs to go to Data
  Sources/NIOFoundationCompat/ByteBuffer-foundation.swift
Labels: semver/patch

#2998 Update documentation comments
  CONTRIBUTING.md
  Package.swift
  README.md
  Sources/NIOFileSystem/CopyStrategy.swift
  Sources/NIOFileSystem/FileSystem.swift
  Sources/NIOFileSystem/Internal/ParallelDirCopy.swift
  Sources/NIOPosix/NIOThreadPool.swift
Labels: semver/none

#3002 Cxx interop CI appends swiftSettings
  scripts/check-cxx-interop-compatibility.sh
Labels: semver/none

#3000 fix remaining warnings & enable -warnings-as-errors in CI
  .github/workflows/main.yml
  Sources/NIOFoundationCompat/ByteBuffer-foundation.swift
  Tests/NIOPosixTests/EchoServerClientTest.swift
  Tests/NIOPosixTests/NIOThreadPoolTest.swift
  Tests/NIOPosixTests/SALEventLoopTests.swift
  Tests/NIOPosixTests/TestUtils.swift
Labels: semver/none

#3003 Prevent crash in Happy Eyeballs Resolver
  Sources/NIOPosix/HappyEyeballs.swift
  Tests/NIOPosixTests/HappyEyeballsTest.swift
Labels: semver/patch

#3004 Backport: Prevent crash in Happy Eyeballs Resolver (#3003)
  Sources/NIOPosix/HappyEyeballs.swift
  Tests/NIOPosixTests/HappyEyeballsTest.swift
Labels: semver/patch

#3001 Remove noasync from NIOFileHandle
  Sources/NIOCore/FileHandle.swift
Labels: semver/patch

#3006 Avoid converting array holding existentials
  IntegrationTests/tests_04_performance/Thresholds/5.10.json
  IntegrationTests/tests_04_performance/Thresholds/5.9.json
  IntegrationTests/tests_04_performance/Thresholds/6.0.json
  IntegrationTests/tests_04_performance/Thresholds/nightly-6.0.json
  IntegrationTests/tests_04_performance/Thresholds/nightly-main.json
  Sources/NIOCore/ChannelPipeline.swift
Labels: semver/patch

#3007 Aligning semantic version label check name
  .github/workflows/pull_request_label.yml
Labels: semver/none
