Repository apple/swift-nio, pull requests merged in 2024-01, with the labels that each got.

#2564 allow setting MTELG.singleton as Swift Concurrency executor
  Sources/NIOCrashTester/CrashTests+EventLoop.swift
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
  Sources/NIOPosix/PosixSingletons+ConcurrencyTakeOver.swift
  Sources/NIOPosix/SelectableEventLoop.swift
  Sources/NIOTCPEchoClient/Client.swift
  Sources/NIOTCPEchoServer/Server.swift
  Sources/NIOWebSocketClient/Client.swift
  Sources/NIOWebSocketServer/Server.swift
Labels: 🔼 needs-minor-version-bump

#2619 Fix the broken performance test binary
  Sources/NIOPerformanceTester/NIOAsyncWriterSingleWritesBenchmark.swift
Labels: needs-no-version-bump

#2620 Suppress the performance checker warning by being sneaky
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
Labels: patch-version-bump-only

#2621 Fix broken tests
  IntegrationTests/allocation-counter-tests-framework/run-allocation-counter.sh
  IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Package.swift
  IntegrationTests/allocation-counter-tests-framework/template/HookedFunctionsDoHook/Package.swift
  IntegrationTests/allocation-counter-tests-framework/template/HookedFunctionsDoNotHook/Package.swift
  IntegrationTests/tests_05_assertions/defines.sh
  Sources/NIOCrashTester/CrashTests+EventLoop.swift
  Tests/NIOCoreTests/AsyncSequences/NIOThrowingAsyncSequenceTests.swift
  dev/make-single-file-spm
Labels: needs-no-version-bump

#2624 Add additional guards in tests for mocking
  Tests/NIOFileSystemIntegrationTests/FileHandleTests.swift
  Tests/NIOFileSystemIntegrationTests/FileSystemTests.swift
  Tests/NIOFileSystemIntegrationTests/XCTestExtensions.swift
  Tests/NIOFileSystemTests/FileHandleTests.swift
  Tests/NIOFileSystemTests/FileSystemErrorTests.swift
  Tests/NIOFileSystemTests/Internal/Concurrency Primitives/BufferedStreamTests.swift
  Tests/NIOFileSystemTests/Internal/Concurrency Primitives/IOExecutorTests.swift
  Tests/NIOFileSystemTests/Internal/MockingInfrastructure.swift
  Tests/NIOFileSystemTests/Internal/SyscallTests.swift
  Tests/NIOFileSystemTests/XCTestExtensions.swift
Labels: needs-no-version-bump

#2626 Avoid overflow in tests where Int is 32-bit
  Tests/NIOFileSystemIntegrationTests/FileSystemTests.swift
Labels: needs-no-version-bump

#2625 [arch] Add arm64_32 to the 32-bit platform check
  Sources/NIOCore/ByteBuffer-int.swift
  Sources/NIOWebSocket/WebSocketFrameEncoder.swift
  Tests/NIOCoreTests/ByteBufferTest.swift
Labels: patch-version-bump-only

#2628 More changes to support building with Musl.
  Sources/CNIOLinux/shim.c
  Sources/NIOFileSystem/FileInfo.swift
  Sources/NIOFileSystem/FileSystem.swift
  Sources/NIOFileSystem/FileSystemError+Syscall.swift
  Sources/NIOFileSystem/FileType.swift
  Sources/NIOFileSystem/Internal/Concurrency Primitives/ThreadPosix.swift
  Sources/NIOFileSystem/Internal/System Calls/CInterop.swift
  Sources/NIOFileSystem/Internal/System Calls/Errno.swift
  Sources/NIOFileSystem/Internal/System Calls/FileDescriptor+Syscalls.swift
  Sources/NIOFileSystem/Internal/System Calls/Mocking.swift
  Sources/NIOFileSystem/Internal/System Calls/Syscall.swift
  Sources/NIOFileSystem/Internal/System Calls/Syscalls.swift
  Sources/NIOFileSystem/Internal/SystemFileHandle.swift
Labels: patch-version-bump-only

#2627 Avoid renameat2 on Android
  Sources/NIOFileSystem/Internal/System Calls/Syscall.swift
  Sources/NIOFileSystem/Internal/System Calls/Syscalls.swift
Labels: patch-version-bump-only
