Repository apple/swift-nio, pull requests merged in 2024-12, with the labels that each got.

#3009 Use the new Android overlay in the tests and update some Bionic declarations
  Sources/NIOFileSystem/Internal/System Calls/Syscalls.swift
  Sources/NIOPosix/System.swift
  Tests/NIOConcurrencyHelpersTests/NIOConcurrencyHelpersTests.swift
  Tests/NIOCoreTests/XCTest+Extensions.swift
  Tests/NIOEmbeddedTests/TestUtils.swift
  Tests/NIOFileSystemTests/FileInfoTests.swift
  Tests/NIOFileSystemTests/FileTypeTests.swift
Labels: semver/patch

#3014 Revert `fastRebase` implementation
  Sources/NIOCore/ByteBuffer-aux.swift
  Sources/NIOCore/ByteBuffer-core.swift
  Sources/NIOCore/ByteBuffer-int.swift
  Sources/NIOCore/PointerHelpers.swift
  Sources/NIOPosix/ControlMessage.swift
  Sources/NIOPosix/PointerHelpers.swift
Labels: semver/patch

#3013 Introduce JSON matrix workflow
  .github/workflows/benchmarks.yml
  .github/workflows/cxx_interop.yml
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  .github/workflows/swift_test_matrix.yml
  .github/workflows/unit_tests.yml
  scripts/generate_matrix.sh
Labels: semver/none

#3016 Matrix workflows refer to main branch
  .github/workflows/benchmarks.yml
  .github/workflows/cxx_interop.yml
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  .github/workflows/unit_tests.yml
Labels: semver/none

#3017 Re-usable workflows curl scripts
  .github/workflows/benchmarks.yml
  .github/workflows/cxx_interop.yml
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  .github/workflows/unit_tests.yml
Labels: semver/none

#3018 GHA: Separate matrix input handling
  .github/workflows/swift_load_test_matrix.yml
  .github/workflows/swift_test_matrix.yml
Labels: semver/none

#3015 Add EventLoop.now API for getting the current time
  Sources/NIOCore/EventLoop.swift
  Sources/NIOEmbedded/AsyncTestingEventLoop.swift
  Sources/NIOEmbedded/Embedded.swift
  Sources/NIOPosix/SelectableEventLoop.swift
  Tests/NIOEmbeddedTests/AsyncTestingEventLoopTests.swift
  Tests/NIOEmbeddedTests/EmbeddedEventLoopTest.swift
  Tests/NIOPosixTests/EventLoopTest.swift
Labels: semver/minor

#3023 Remove outdated documentation
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
Labels: semver/none

#3022 Deprecate not-actually-public Base64 APIs
  Sources/NIOCore/ByteBuffer-aux.swift
  Sources/NIOWebSocket/NIOWebSocketClientUpgrader.swift
  Sources/NIOWebSocket/NIOWebSocketServerUpgrader.swift
  Sources/_NIOBase64/Base64.swift
  Tests/NIOBase64Tests/Base64Test.swift
Labels: semver/patch

#3024 rename top matrix workflow object 'swift'->'config'
  .github/workflows/swift_test_matrix.yml
  scripts/generate_matrix.sh
Labels: semver/none

#3026 Fix new warnings
  Sources/NIOAsyncAwaitDemo/AsyncChannelIO.swift
  Sources/NIOPosix/Bootstrap.swift
  Tests/NIOEmbeddedTests/AsyncTestingChannelTests.swift
  Tests/NIOHTTP1Tests/HTTPClientUpgradeTests.swift
  Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
  Tests/NIOPosixTests/NIOScheduledCallbackTests.swift
  Tests/NIOPosixTests/RawSocketBootstrapTests.swift
  Tests/NIOPosixTests/SocketChannelTest.swift
  Tests/NIOPosixTests/UniversalBootstrapSupportTest.swift
  Tests/NIOWebSocketTests/WebSocketClientEndToEndTests.swift
Labels: semver/patch

#3025 Remove now unneeded fts_open bitcast for Android
  Sources/NIOFileSystem/Internal/System Calls/Syscall.swift
Labels: semver/patch

#3027 fix bogus "unleakable promise leaked" error message (#2855)
  Sources/NIOCore/EventLoopFuture.swift
Labels: semver/patch

#3021 Enable MemberImportVisibility check on all targets
  Package.swift
Labels: semver/none

#3028 Revert "Enable MemberImportVisibility check on all targets"
  Package.swift
Labels: semver/none

#2969 Add isolated views to EventLoop, Promise, and Future
  Sources/NIOCore/AsyncChannel/AsyncChannelHandler.swift
  Sources/NIOCore/ChannelHandlers.swift
  Sources/NIOCore/ChannelPipeline.swift
  Sources/NIOCore/Codec.swift
  Sources/NIOCore/Docs.docc/loops-futures-concurrency.md
  Sources/NIOCore/EventLoopFuture+AssumeIsolated.swift
  Sources/NIOEmbedded/Embedded.swift
  Tests/NIOPosixTests/EventLoopFutureIsolatedTests.swift
Labels: semver/minor

#3031 Fix now-racy scheduled callback tests
  Tests/NIOPosixTests/NIOScheduledCallbackTests.swift
Labels: semver/none

#3030 Get NIOEmbedded clean under strict concurrency
  IntegrationTests/tests_04_performance/Thresholds/5.10.json
  IntegrationTests/tests_04_performance/Thresholds/5.9.json
  IntegrationTests/tests_04_performance/Thresholds/6.0.json
  IntegrationTests/tests_04_performance/Thresholds/nightly-6.0.json
  IntegrationTests/tests_04_performance/Thresholds/nightly-main.json
  Package.swift
  Sources/NIOEmbedded/AsyncTestingChannel.swift
  Sources/NIOEmbedded/AsyncTestingEventLoop.swift
  Sources/NIOEmbedded/Embedded.swift
  Tests/NIOEmbeddedTests/AsyncTestingChannelTests.swift
  Tests/NIOEmbeddedTests/AsyncTestingEventLoopTests.swift
  Tests/NIOEmbeddedTests/EmbeddedChannelTest.swift
  Tests/NIOEmbeddedTests/EmbeddedEventLoopTest.swift
  Tests/NIOEmbeddedTests/TestUtils.swift
Labels: semver/minor

#3029 Enable MemberImportVisibility check - attempt 2
  Package.swift
  Sources/NIOCrashTester/CrashTests+Strict.swift
  Sources/NIOCrashTester/CrashTests+System.swift
  Sources/NIOMulticastChat/main.swift
  Sources/NIOPosix/BaseSocket.swift
  Sources/NIOPosix/Bootstrap.swift
  Sources/NIOPosix/DatagramVectorReadManager.swift
  Sources/NIOPosix/NonBlockingFileIO.swift
  Sources/NIOPosix/PendingDatagramWritesManager.swift
  Sources/NIOPosix/PendingWritesManager.swift
  Sources/NIOPosix/SelectorEpoll.swift
  Sources/NIOPosix/Socket.swift
  Sources/NIOPosix/SocketChannel.swift
  Tests/NIOFileSystemTests/FileInfoTests.swift
  Tests/NIOFileSystemTests/Internal/SyscallTests.swift
  Tests/NIOPosixTests/BlockingIOThreadPoolTest.swift
  Tests/NIOPosixTests/ControlMessageTests.swift
  Tests/NIOPosixTests/NIOThreadPoolTest.swift
  Tests/NIOPosixTests/NonBlockingFileIOTest.swift
  Tests/NIOPosixTests/PendingDatagramWritesManagerTests.swift
  Tests/NIOPosixTests/SocketAddressTest.swift
  Tests/NIOPosixTests/SocketOptionProviderTest.swift
  Tests/NIOPosixTests/StreamChannelsTest.swift
  Tests/NIOPosixTests/SyscallAbstractionLayer.swift
  Tests/NIOPosixTests/SystemTest.swift
  Tests/NIOPosixTests/ThreadTest.swift
Labels: semver/patch

#3032 Wait for `closeFuture` instead of close promise in `NIOAsyncChannel`'s `executeThenClose`
  Sources/NIOCore/AsyncChannel/AsyncChannel.swift
  Sources/NIOCore/Channel.swift
Labels: semver/patch

#3033 Import Android instead for NIOEmbedded
  Sources/NIOEmbedded/Embedded.swift
Labels: semver/patch

#3035 Update release.yml and label action
  .github/actions/pull_request_semver_label_checker/action.yml
  .github/release.yml
Labels: semver/none

#3036 Fix flaky test testTasksScheduledDuringShutdownAreAutomaticallyCancel…
  Tests/NIOEmbeddedTests/AsyncTestingEventLoopTests.swift
Labels: semver/none
