Repository apple/swift-nio, pull requests merged in 2024-06, with the labels that each got.

#2735 Add API for setting last accessed and last modified file times
  Sources/CNIOLinux/include/CNIOLinux.h
  Sources/CNIOLinux/shim.c
  Sources/NIOFileSystem/FileHandle.swift
  Sources/NIOFileSystem/FileHandleProtocol.swift
  Sources/NIOFileSystem/FileInfo.swift
  Sources/NIOFileSystem/FileSystemError+Syscall.swift
  Sources/NIOFileSystem/Internal/System Calls/Syscall.swift
  Sources/NIOFileSystem/Internal/System Calls/Syscalls.swift
  Sources/NIOFileSystem/Internal/SystemFileHandle.swift
  Tests/NIOFileSystemIntegrationTests/FileHandleTests.swift
  Tests/NIOFileSystemTests/FileSystemErrorTests.swift
  Tests/NIOFileSystemTests/Internal/SyscallTests.swift
Labels: 🔼 needs-minor-version-bump

#2739 Update availability guard on tests
  Tests/NIOFileSystemIntegrationTests/FileHandleTests.swift
Labels: needs-no-version-bump

#2737 304 Not Modified Broken with Response Compression Enabled
  Sources/NIOHTTP1/HTTPTypes.swift
  Tests/NIOHTTP1Tests/HTTPResponseEncoderTest.swift
Labels: patch-version-bump-only

#2741 Silence warning about missing include in macOS builds
  Sources/CNIOLinux/include/CNIOLinux.h
Labels: patch-version-bump-only

#2746 convert the NIOFileSystem example code to a Snippet
  Snippets/NIOFileSystemTour.swift
  Sources/NIOFileSystem/Docs.docc/NIOFileSystem.md
  scripts/soundness.sh
Labels: needs-no-version-bump

#2744 Throw an appropriate error from the writer when the channel closed
  Sources/NIOCore/AsyncChannel/AsyncChannelOutboundWriterHandler.swift
  Tests/NIOCoreTests/AsyncChannel/AsyncChannelTests.swift
Labels: patch-version-bump-only

#2753 NIOSendableBox: allow off-loop initialisation iff Value is Sendable
  Sources/NIOCore/NIOLoopBound.swift
  Tests/NIOPosixTests/NIOLoopBoundTests.swift
Labels: 🔼 needs-minor-version-bump
