Repository apple/swift-nio, pull requests merged in 2024-03, with the labels that each got.

#2661 Migrate to `syncOperations` in more places
  Sources/NIOAsyncAwaitDemo/main.swift
  Sources/NIOChatServer/main.swift
  Sources/NIOCore/AsyncAwaitSupport.swift
  Sources/NIOCore/ChannelPipeline.swift
  Sources/NIOCrashTester/OutputGrepper.swift
  Sources/NIOEchoServer/main.swift
  Sources/NIOHTTP1/HTTPServerUpgradeHandler.swift
  Sources/NIOHTTP1/NIOTypedHTTPServerUpgradeHandler.swift
  Sources/NIOPerformanceTester/TCPThroughputBenchmark.swift
  Sources/NIOPerformanceTester/WebSocketFrameDecoderBenchmark.swift
  Sources/NIOPerformanceTester/WebSocketFrameEncoderBenchmark.swift
  Tests/NIOHTTP1Tests/HTTPDecoderLengthTest.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
  Tests/NIOHTTP1Tests/HTTPRequestEncoderTest.swift
  Tests/NIOHTTP1Tests/HTTPResponseEncoderTest.swift
  Tests/NIOHTTP1Tests/HTTPServerPipelineHandlerTest.swift
  Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift
  Tests/NIOHTTP1Tests/HTTPTest.swift
  Tests/NIOHTTP1Tests/NIOHTTPObjectAggregatorTest.swift
  Tests/NIOPosixTests/BootstrapTest.swift
  Tests/NIOPosixTests/ChannelPipelineTest.swift
  Tests/NIOPosixTests/CodecTest.swift
  Tests/NIOPosixTests/IdleStateHandlerTest.swift
  Tests/NIOTLSTests/ApplicationProtocolNegotiationHandlerTests.swift
  Tests/NIOTLSTests/NIOTypedApplicationProtocolNegotiationHandlerTests.swift
  Tests/NIOTLSTests/SNIHandlerTests.swift
  Tests/NIOWebSocketTests/WebSocketClientEndToEndTests.swift
  Tests/NIOWebSocketTests/WebSocketFrameDecoderTest.swift
  Tests/NIOWebSocketTests/WebSocketFrameEncoderTest.swift
  Tests/NIOWebSocketTests/WebSocketServerEndToEndTests.swift
  docker/docker-compose.2204.main.yaml
Labels: 🔼 needs-minor-version-bump

#2645 Track `execute()` and `enqueue()` tasks separately from scheduled tasks.
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
  Sources/NIOPosix/SelectableEventLoop.swift
  Tests/NIOPosixTests/EventLoopTest.swift
  docker/docker-compose.2204.510.yaml
  docker/docker-compose.2204.57.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.59.yaml
  docker/docker-compose.2204.main.yaml
Labels: 🔼 needs-minor-version-bump

#2673 Fix memory allocations counters on macOS.
  IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Package.swift
Labels: needs-no-version-bump

#2675 Raise minimum Swift version to 5.8
  Benchmarks/Thresholds/5.7/NIOPosixBenchmarks.TCPEcho.p90.json
  Package.swift
  README.md
  Sources/NIOCore/TimeAmount+Duration.swift
  Tests/NIOCoreTests/TimeAmount+DurationTests.swift
  Tests/NIOPosixTests/SocketAddressTest.swift
  docker/docker-compose.2204.510.yaml
  docker/docker-compose.2204.57.yaml
  docker/docker-compose.2204.59.yaml
Labels: 🔼 needs-minor-version-bump

#2676 Expose `NIOThreadPool.numberOfThreads` publicly.
  Sources/NIOPosix/NIOThreadPool.swift
Labels: 🔼 needs-minor-version-bump

#2677 Prevent BufferedWriter from producing empty files
  Sources/NIOFileSystem/BufferedWriter.swift
  Tests/NIOFileSystemIntegrationTests/BufferedWriterTests.swift
Labels: 🔼 needs-minor-version-bump

#2680 Update issue template link in SECURITY.md
  SECURITY.md
Labels: needs-no-version-bump

#2683 Underscore the NIOFileSystem module
  .spi.yml
  Package.swift
  Sources/NIOFileSystem/BufferedWriter.swift
  Sources/NIOFileSystem/Docs.docc/Extensions/DirectoryFileHandleProtocol.md
  Sources/NIOFileSystem/Docs.docc/Extensions/FileHandleProtocol.md
  Sources/NIOFileSystem/Docs.docc/Extensions/FileSystemProtocol.md
  Sources/NIOFileSystem/Docs.docc/Extensions/ReadableFileHandleProtocol.md
  Sources/NIOFileSystem/Docs.docc/Extensions/WritableFileHandleProtocol.md
  Sources/NIOFileSystem/Docs.docc/NIOFileSystem.md
  Sources/NIOFileSystem/FileHandleProtocol.swift
  Sources/NIOFileSystemFoundationCompat/Date+FileInfo.swift
  Tests/NIOFileSystemFoundationCompatTests/FileSystemFoundationCompatTests.swift
  Tests/NIOFileSystemIntegrationTests/BufferedReaderTests.swift
  Tests/NIOFileSystemIntegrationTests/BufferedWriterTests.swift
  Tests/NIOFileSystemIntegrationTests/ConvenienceTests.swift
  Tests/NIOFileSystemIntegrationTests/FileHandleTests.swift
  Tests/NIOFileSystemIntegrationTests/FileSystemTests+SPI.swift
  Tests/NIOFileSystemIntegrationTests/FileSystemTests.swift
  Tests/NIOFileSystemIntegrationTests/XCTestExtensions.swift
  Tests/NIOFileSystemTests/ByteCountTests.swift
  Tests/NIOFileSystemTests/DirectoryEntriesTests.swift
  Tests/NIOFileSystemTests/FileChunksTests.swift
  Tests/NIOFileSystemTests/FileHandleTests.swift
  Tests/NIOFileSystemTests/FileInfoTests.swift
  Tests/NIOFileSystemTests/FileOpenOptionsTests.swift
  Tests/NIOFileSystemTests/FileSystemErrorTests.swift
  Tests/NIOFileSystemTests/FileTypeTests.swift
  Tests/NIOFileSystemTests/Internal/CancellationTests.swift
  Tests/NIOFileSystemTests/Internal/Concurrency Primitives/BufferedStreamTests.swift
  Tests/NIOFileSystemTests/Internal/Concurrency Primitives/IOExecutorTests.swift
  Tests/NIOFileSystemTests/Internal/MockingInfrastructure.swift
  Tests/NIOFileSystemTests/Internal/SyscallTests.swift
  Tests/NIOFileSystemTests/XCTestExtensions.swift
Labels: 🔼 needs-minor-version-bump

#2682 Handle 'atomically' created files more gracefully when detached
  Sources/NIOFileSystem/FileSystemError+Syscall.swift
  Sources/NIOFileSystem/Internal/System Calls/Syscall.swift
  Sources/NIOFileSystem/Internal/System Calls/Syscalls.swift
  Sources/NIOFileSystem/Internal/SystemFileHandle.swift
  Tests/NIOFileSystemIntegrationTests/FileSystemTests.swift
  Tests/NIOFileSystemTests/FileSystemErrorTests.swift
  Tests/NIOFileSystemTests/Internal/SyscallTests.swift
Labels: patch-version-bump-only

#2687 Remove DispatchGroup and replace with condvar
  Sources/NIOPosix/NIOThreadPool.swift
Labels: patch-version-bump-only

#2688 Change BufferedReader.read(while:) signature
  Sources/NIOFileSystem/BufferedReader.swift
  Tests/NIOFileSystemIntegrationTests/BufferedReaderTests.swift
Labels: 🔼 needs-minor-version-bump

#2689 Add a NIOFileSystem shim
  Package.swift
  Sources/_NIOFileSystemExported/Exports.swift
Labels: 🔼 needs-minor-version-bump

#2690 Remove temp directories after tests
  Tests/NIOFileSystemIntegrationTests/FileHandleTests.swift
Labels: needs-no-version-bump

#2679 Add cancellation to NIOThreadPool's async runIfActive
  Sources/NIOPosix/NIOThreadPool.swift
  Tests/NIOPosixTests/NIOThreadPoolTest.swift
  Tests/NIOPosixTests/NonBlockingFileIOTest.swift
Labels: patch-version-bump-only

#2691 Clarify Client/Server column headers
  README.md
Labels: needs-no-version-bump

#2692 Use NIOThreadPool in NIOFileSystem
  Package.swift
  Sources/NIOFileSystem/DirectoryEntries.swift
  Sources/NIOFileSystem/FileChunks.swift
  Sources/NIOFileSystem/FileSystem.swift
  Sources/NIOFileSystem/Internal/Concurrency Primitives/IOExecutor.swift
  Sources/NIOFileSystem/Internal/Concurrency Primitives/Thread.swift
  Sources/NIOFileSystem/Internal/Concurrency Primitives/ThreadPosix.swift
  Sources/NIOFileSystem/Internal/SystemFileHandle.swift
  Tests/NIOFileSystemIntegrationTests/FileHandleTests.swift
  Tests/NIOFileSystemTests/FileHandleTests.swift
  Tests/NIOFileSystemTests/Internal/Concurrency Primitives/IOExecutorTests.swift
Labels: patch-version-bump-only

#2693 Added file and line to NIOAsyncWriterError description
  Sources/NIOCore/AsyncSequences/NIOAsyncWriter.swift
Labels: 🔼 needs-minor-version-bump

#2608 Add delegate for collecting eventloop tick metrics
  Sources/NIOPosix/LinuxCPUSet.swift
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
  Sources/NIOPosix/SelectableEventLoop.swift
  Tests/NIOPosixTests/EventLoopMetricsDelegateTests.swift
  Tests/NIOPosixTests/EventLoopTest.swift
  Tests/NIOPosixTests/SyscallAbstractionLayer.swift
Labels: 🔼 needs-minor-version-bump
