Repository apple/swift-nio, pull requests merged in 2024-10, with the labels that each got.

#2867 Add functions for reading and writing length-prefixed data with customizable encodings for the length
  Sources/NIOCore/ByteBuffer-binaryEncodedLengthPrefix.swift
  Sources/NIOCore/ByteBuffer-quicBinaryEncodingStrategy.swift
  Sources/NIOCore/Docs.docc/ByteBuffer-lengthPrefix.md
  Sources/NIOCore/Docs.docc/index.md
  Tests/NIOCoreTests/ByteBufferBinaryEncodedLengthPrefixTests.swift
  Tests/NIOCoreTests/ByteBufferQUICBinaryEncodingStrategyTests.swift
Labels: semver/minor

#2901 ConditionLock deallocs its pthread_cond_t in more cases
  Sources/NIOConcurrencyHelpers/lock.swift
Labels: semver/patch

#2759 Add EventLoop APIs for simpler scheduling of callbacks
  Benchmarks/Benchmarks/NIOPosixBenchmarks/Benchmarks.swift
  Sources/NIOCore/EventLoop.swift
  Sources/NIOCore/NIOScheduledCallback.swift
  Sources/NIOEmbedded/AsyncTestingEventLoop.swift
  Sources/NIOEmbedded/Embedded.swift
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
  Sources/NIOPosix/SelectableEventLoop.swift
  Sources/_NIODataStructures/Heap.swift
  Sources/_NIODataStructures/PriorityQueue.swift
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
  Tests/NIOPosixTests/NIOScheduledCallbackTests.swift
Labels: semver/minor

#2905 A DatagramChannelTest now waits for writes
  Tests/NIOPosixTests/DatagramChannelTests.swift
Labels: semver/patch

#2904 Make ByteBufferQUICBinaryEncodingStrategyTests compatible with 32-bit systems
  Tests/NIOCoreTests/ByteBufferQUICBinaryEncodingStrategyTests.swift
Labels: semver/none

#2907 Fix broken link to swift-server performance documentation
  docs/advanced-performance-analysis.md
Labels: semver/none

#2909 Add convenience conformances to `ByteCount`
  Sources/NIOFileSystem/ByteCount.swift
  Tests/NIOFileSystemTests/ByteCountTests.swift
Labels: semver/minor

#2911 Throw error when the max read amount is greater than `ByteBuffer` can tolerate
  Sources/NIOFileSystem/ByteCount.swift
  Sources/NIOFileSystem/FileHandleProtocol.swift
  Tests/NIOFileSystemIntegrationTests/FileSystemTests.swift
Labels: semver/patch

#2912 Add `removeHandler(context: ChannelHandlerContext)` to SynchronousOperations of ChannelPipeline
  Sources/NIOCore/ChannelPipeline.swift
  Tests/NIOPosixTests/ChannelPipelineTest.swift
Labels: semver/minor

#2914 [NIOFileSystem] Provide an API to specify allowing unlimited sized reads
  Sources/NIOFileSystem/ByteCount.swift
  Sources/NIOFileSystem/FileHandleProtocol.swift
  Tests/NIOFileSystemIntegrationTests/FileSystemTests.swift
  Tests/NIOFileSystemIntegrationTests/XCTestExtensions.swift
  Tests/NIOFileSystemTests/ByteCountTests.swift
Labels: semver/minor

#2913 [CI] Switch to reusable soundness
  .github/actions/pull_request_semver_label_checker/action.yml
  .github/workflows/benchmarks.yml
  .github/workflows/cxx_interop.yml
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  .github/workflows/scheduled.yml
  .github/workflows/soundness.yml
  .github/workflows/swift_6_language_mode.yml
  .github/workflows/swift_matrix.yml
  .github/workflows/unit_tests.yml
  scripts/check-broken-symlinks.sh
  scripts/check-cxx-interop-compatibility.sh
  scripts/check-docs.sh
  scripts/check-license-header.sh
  scripts/check-matrix-job.sh
  scripts/check-swift-format.sh
  scripts/check-unacceptable-language.sh
  scripts/check_no_api_breakages.sh
  scripts/cxx-interop-compatibility.sh
Labels: semver/none

#2915 [CI] Fix unit test yaml file
  .github/workflows/unit_tests.yml
Labels: semver/none

#2916 [CI] Add back matrix CI script
  scripts/check-matrix-job.sh
Labels: semver/none

#2919 Re-add CXX compat check script
  scripts/check-cxx-interop-compatibility.sh
Labels: semver/none

#2920 [CI] Migrate to Swift 6.0 and drop 5.8
  .github/workflows/benchmarks.yml
  .github/workflows/cxx_interop.yml
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  .github/workflows/scheduled.yml
  .github/workflows/swift_6_language_mode.yml
  .github/workflows/swift_matrix.yml
  .github/workflows/unit_tests.yml
  scripts/check-matrix-job.sh
Labels: semver/none

#2917 Adopt NIOThrowingAsyncSequenceProducer 2nd try
  Sources/NIOFileSystem/DirectoryEntries.swift
  Sources/NIOFileSystem/FileChunks.swift
  Sources/NIOFileSystem/Internal/BufferedOrAnyStream.swift
  Tests/NIOFileSystemIntegrationTests/FileHandleTests.swift
Labels: semver/patch

#2927 Disable semver-label-check locally
  .github/actions/pull_request_semver_label_checker/action.yml
Labels: semver/none

#2928 Disable semver label check locally
  .github/actions/pull_request_semver_label_checker/action.yml
Labels: semver/none

#2925 [CI] Fix python lint
  .github/workflows/pull_request.yml
  .github/workflows/scheduled.yml
  Benchmarks/Thresholds/6.0/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
  Benchmarks/Thresholds/6.0/NIOPosixBenchmarks.TCPEcho.p90.json
  Benchmarks/Thresholds/6.0/NIOPosixBenchmarks.TCPEchoAsyncChannel.p90.json
  dev/stackdiff-dtrace.py
Labels: semver/none

#2931 Add future wait benchmark to catch memory leaks
  Benchmarks/Benchmarks/NIOCoreBenchmarks/Benchmarks.swift
  Benchmarks/Thresholds/5.10/NIOCoreBenchmarks.WaitOnPromise.p90.json
  Benchmarks/Thresholds/5.8/NIOCoreBenchmarks.WaitOnPromise.p90.json
  Benchmarks/Thresholds/5.9/NIOCoreBenchmarks.WaitOnPromise.p90.json
Labels: semver/patch

#2924 Drop support for Swift 5.8
  .github/workflows/main.yml
  Benchmarks/Thresholds/5.8/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
  Benchmarks/Thresholds/5.8/NIOPosixBenchmarks.TCPEcho.p90.json
  CONTRIBUTING.md
  Package.swift
  README.md
  Sources/NIOCore/EventLoop+SerialExecutor.swift
  Sources/NIOCore/EventLoop.swift
  Sources/NIOCore/NIOScheduledCallback.swift
  Sources/NIOEmbedded/AsyncTestingEventLoop.swift
  Sources/NIOEmbedded/Embedded.swift
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
  Sources/NIOPosix/PosixSingletons+ConcurrencyTakeOver.swift
  Sources/NIOPosix/SelectableEventLoop.swift
  Sources/NIOTCPEchoClient/Client.swift
  Sources/NIOTCPEchoServer/Server.swift
  Tests/NIOPosixTests/SerialExecutorTests.swift
Labels: semver/minor

#2932 clean up 5.8 thresholds
  Benchmarks/Thresholds/5.8/NIOCoreBenchmarks.WaitOnPromise.p90.json
Labels: semver/none

#2654 Fix `EventLoopFuture` and `EventLoopPromise` under strict concurrency checking
  Sources/NIOCore/AsyncAwaitSupport.swift
  Sources/NIOCore/ChannelPipeline.swift
  Sources/NIOCore/DispatchQueue+WithFuture.swift
  Sources/NIOCore/Docs.docc/index.md
  Sources/NIOCore/Docs.docc/loops-futures-concurrency.md
  Sources/NIOCore/EventLoop+Deprecated.swift
  Sources/NIOCore/EventLoop.swift
  Sources/NIOCore/EventLoopFuture+Deprecated.swift
  Sources/NIOCore/EventLoopFuture+WithEventLoop.swift
  Sources/NIOCore/EventLoopFuture.swift
  Sources/NIOCore/NIOScheduledCallback.swift
  Sources/NIOEmbedded/AsyncTestingEventLoop.swift
  Sources/NIOEmbedded/Embedded.swift
  Tests/NIOCoreTests/AsyncChannel/AsyncChannelTests.swift
  Tests/NIOPosixTests/EventLoopFutureTest.swift
  Tests/NIOPosixTests/NonBlockingFileIOTest.swift
Labels: semver/minor

#2935 Fix Windows build break.
  Sources/NIOConcurrencyHelpers/lock.swift
Labels: semver/patch

#2923 Provide APIs to read file into more data types
  Package.swift
  Sources/NIOFileSystem/Array+FileSystem.swift
  Sources/NIOFileSystem/ArraySlice+FileSystem.swift
  Sources/NIOFileSystemFoundationCompat/Data+FileSystem.swift
  Tests/NIOFileSystemFoundationCompatTests/FileSystemFoundationCompatTests.swift
  Tests/NIOFileSystemIntegrationTests/FileSystemTests.swift
Labels: semver/minor

#2937 Fix withConnectedSocket in async mode
  Sources/NIOPosix/Bootstrap.swift
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
Labels: semver/patch

#2929 [CI] Add Windows matrix build
  .github/workflows/swift_matrix.yml
  .github/workflows/unit_tests.yml
  scripts/check-matrix-job.ps1
Labels: semver/none

#2939 [CI] Small adjustments to the Windows actions
  .github/workflows/swift_matrix.yml
  .github/workflows/unit_tests.yml
Labels: semver/none

#2940 [CI] Enable benchmarks & cxx Windows CI
  .github/workflows/benchmarks.yml
  .github/workflows/cxx_interop.yml
  .github/workflows/swift_matrix.yml
Labels: semver/none

#2941 [CI] Fix the Windows 6.0 check name
  .github/workflows/swift_matrix.yml
Labels: semver/none

#2944 NIOPosix on Darwin: inherit main thread QoS
  Sources/NIOPosix/ThreadPosix.swift
Labels: semver/patch

#2945 workaround Xcode 15.4 bug with swift build --arch x86_64 --arch arm64
  Sources/NIOCore/NIOScheduledCallback.swift
Labels: semver/patch

#2946 Checkout any submodules when running Actions
  .github/workflows/swift_6_language_mode.yml
  .github/workflows/swift_matrix.yml
Labels: semver/none

#2947 Issue-2900 - Add VisionOS support
  Package.swift
  Sources/NIOFileSystem/BufferedReader.swift
  Sources/NIOFileSystem/BufferedWriter.swift
  Sources/NIOFileSystem/ByteBuffer+FileSystem.swift
  Sources/NIOFileSystem/ByteCount.swift
  Sources/NIOFileSystem/Convenience.swift
  Sources/NIOFileSystem/DirectoryEntries.swift
  Sources/NIOFileSystem/DirectoryEntry.swift
  Sources/NIOFileSystem/Exports.swift
  Sources/NIOFileSystem/FileChunks.swift
  Sources/NIOFileSystem/FileHandle.swift
  Sources/NIOFileSystem/FileHandleProtocol.swift
  Sources/NIOFileSystem/FileInfo.swift
  Sources/NIOFileSystem/FileSystem.swift
  Sources/NIOFileSystem/FileSystemError+Syscall.swift
  Sources/NIOFileSystem/FileSystemError.swift
  Sources/NIOFileSystem/FileSystemProtocol.swift
  Sources/NIOFileSystem/FileType.swift
  Sources/NIOFileSystem/Internal/BufferedOrAnyStream.swift
  Sources/NIOFileSystem/Internal/BufferedStream.swift
  Sources/NIOFileSystem/Internal/Cancellation.swift
  Sources/NIOFileSystem/Internal/Concurrency Primitives/UnsafeTransfer.swift
  Sources/NIOFileSystem/Internal/ParallelDirCopy.swift
  Sources/NIOFileSystem/Internal/String+UnsafeUnititializedCapacity.swift
  Sources/NIOFileSystem/Internal/System Calls/CInterop.swift
  Sources/NIOFileSystem/Internal/System Calls/Errno.swift
  Sources/NIOFileSystem/Internal/System Calls/FileDescriptor+Syscalls.swift
  Sources/NIOFileSystem/Internal/System Calls/Mocking.swift
  Sources/NIOFileSystem/Internal/System Calls/Syscall.swift
  Sources/NIOFileSystem/Internal/System Calls/Syscalls.swift
  Sources/NIOFileSystem/Internal/SystemFileHandle.swift
  Sources/NIOFileSystem/Internal/Utilities.swift
  Sources/NIOFileSystem/OpenOptions.swift
  Sources/NIOFileSystemFoundationCompat/Date+FileInfo.swift
  Tests/NIOFileSystemFoundationCompatTests/FileSystemFoundationCompatTests.swift
  Tests/NIOFileSystemIntegrationTests/BufferedReaderTests.swift
  Tests/NIOFileSystemIntegrationTests/BufferedWriterTests.swift
  Tests/NIOFileSystemIntegrationTests/ConvenienceTests.swift
  Tests/NIOFileSystemIntegrationTests/FileHandleTests.swift
  Tests/NIOFileSystemIntegrationTests/FileSystemTests+SPI.swift
  Tests/NIOFileSystemIntegrationTests/FileSystemTests.swift
  Tests/NIOFileSystemIntegrationTests/XCTestExtensions.swift
  Tests/NIOFileSystemTests/ByteCountTests.swift
  Tests/NIOFileSystemTests/DirectoryEntriesTests.swift
  Tests/NIOFileSystemTests/FileChunksTests.swift
  Tests/NIOFileSystemTests/FileHandleTests.swift
  Tests/NIOFileSystemTests/FileInfoTests.swift
  Tests/NIOFileSystemTests/FileOpenOptionsTests.swift
  Tests/NIOFileSystemTests/FileSystemErrorTests.swift
  Tests/NIOFileSystemTests/FileTypeTests.swift
  Tests/NIOFileSystemTests/Internal/CancellationTests.swift
  Tests/NIOFileSystemTests/Internal/Concurrency Primitives/BufferedStreamTests.swift
  Tests/NIOFileSystemTests/Internal/MockingInfrastructure.swift
  Tests/NIOFileSystemTests/Internal/SyscallTests.swift
  Tests/NIOFileSystemTests/XCTestExtensions.swift
Labels: semver/patch

#2951 EmbeddedEventLoop/Channel: check correct thread
  Sources/NIOEmbedded/Embedded.swift
  Sources/NIOPosix/Thread.swift
  Tests/NIOCoreTests/DispatchQueue+WithFutureTest.swift
  Tests/NIOPosixTests/EventLoopFutureTest.swift
  Tests/NIOPosixTests/NIOScheduledCallbackTests.swift
Labels: semver/patch

#2952 Fix `NIOAsyncSequenceProducer` watermark strategy.
  Sources/NIOCore/AsyncSequences/NIOAsyncSequenceProducerStrategies.swift
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncSequenceProducer+HighLowWatermarkBackPressureStrategyTests.swift
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncSequenceTests.swift
Labels: semver/patch

#2953 Handle Sendability of RemovableChannelHandler
  Sources/NIOCore/AsyncAwaitSupport.swift
  Sources/NIOCore/ChannelPipeline.swift
  Sources/NIOHTTP1/HTTPServerUpgradeHandler.swift
  Sources/NIOHTTP1/NIOHTTPClientUpgradeHandler.swift
  Sources/NIOTLS/ApplicationProtocolNegotiationHandler.swift
  Sources/NIOTLS/NIOTypedApplicationProtocolNegotiationHandler.swift
  Sources/NIOTLS/SNIHandler.swift
  Tests/NIOCoreTests/AsyncChannel/AsyncChannelTests.swift
  Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift
  Tests/NIOPosixTests/AcceptBackoffHandlerTest.swift
  Tests/NIOPosixTests/ChannelPipelineTest.swift
  Tests/NIOPosixTests/CodecTest.swift
  Tests/NIOPosixTests/MulticastTest.swift
Labels: semver/minor

#2955 Clean up Sendability for ChannelInvoker
  Sources/NIOCore/AsyncAwaitSupport.swift
  Sources/NIOCore/Channel.swift
  Sources/NIOCore/ChannelInvoker.swift
  Sources/NIOCore/ChannelPipeline.swift
  Sources/NIOCore/Docs.docc/swift-concurrency.md
  Sources/NIOCore/NIOAny.swift
  Sources/NIOEmbedded/AsyncTestingChannel.swift
  Sources/NIOEmbedded/Embedded.swift
  Sources/NIOPerformanceTester/main.swift
  Sources/NIOPosix/SocketChannel.swift
  Sources/NIOTestUtils/NIOHTTP1TestServer.swift
  Tests/NIOCoreTests/AsyncChannel/AsyncChannelTests.swift
  Tests/NIOEmbeddedTests/AsyncTestingChannelTests.swift
  Tests/NIOEmbeddedTests/EmbeddedChannelTest.swift
  Tests/NIOHTTP1Tests/HTTPServerClientTest.swift
  Tests/NIOHTTP1Tests/HTTPServerPipelineHandlerTest.swift
  Tests/NIOHTTP1Tests/HTTPServerProtocolErrorHandlerTest.swift
  Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift
  Tests/NIOPosixTests/BootstrapTest.swift
  Tests/NIOPosixTests/ChannelPipelineTest.swift
  Tests/NIOPosixTests/ChannelTests.swift
  Tests/NIOPosixTests/CodecTest.swift
  Tests/NIOPosixTests/DatagramChannelTests.swift
  Tests/NIOPosixTests/EchoServerClientTest.swift
  Tests/NIOPosixTests/EventLoopTest.swift
  Tests/NIOPosixTests/FileRegionTest.swift
  Tests/NIOPosixTests/IdleStateHandlerTest.swift
  Tests/NIOPosixTests/UniversalBootstrapSupportTest.swift
  Tests/NIOTestUtilsTests/NIOHTTP1TestServerTest.swift
Labels: semver/minor

#2948 Fix broken swift format link
  CONTRIBUTING.md
Labels: semver/none

#2957 Remove unused dockerfiles and allocation limit scripts
  dev/alloc-limits-from-test-output
  dev/update-alloc-limits-to-last-completed-ci-build
  docker/Dockerfile
  docker/docker-compose.2204.510.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.59.yaml
  docker/docker-compose.2204.main.yaml
  docker/docker-compose.2204.nightly-6.0.yaml
  docker/docker-compose.yaml
Labels: semver/none

#2959 Complete NIOCore strict concurrency
  Package.swift
  Sources/NIOCore/BSDSocketAPI.swift
  Tests/NIOCoreTests/AsyncChannel/AsyncChannelTests.swift
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncSequenceTests.swift
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncWriterTests.swift
  Tests/NIOCoreTests/AsyncSequences/NIOThrowingAsyncSequenceTests.swift
  Tests/NIOCoreTests/ByteBufferTest.swift
  Tests/NIOCoreTests/ChannelOptionStorageTest.swift
  Tests/NIOCoreTests/DispatchQueue+WithFutureTest.swift
  Tests/NIOCoreTests/NIOCloseOnErrorHandlerTest.swift
  Tests/NIOCoreTests/XCTest+Extensions.swift
Labels: semver/minor
