Repository apple/swift-nio, pull requests merged in 2024-08, with the labels that each got.

#2824 Fix failing build for test
  Tests/NIOPosixTests/StreamChannelsTest.swift
Labels: semver/none

#2604 Fix typo in comment in WebSocketErrorCodes.swift
  Sources/NIOWebSocket/WebSocketErrorCodes.swift
Labels: semver/none

#2822 [CI] Add a scheduled workflow for tests and benchmarks
  .github/actions/pull_request_semver_label_checker/action.yml
  .github/workflows/pull_request_label.yml
  .github/workflows/scheduled.yml
Labels: semver/none

#2827 [CI] Fix label check
  .github/actions/pull_request_semver_label_checker/action.yml
  .github/workflows/pull_request_label.yml
Labels: semver/none

#2830 Update wording from `ubuntu` to `Ubuntu` at README.md
  README.md
Labels: semver/none

#2832 Adopt strict concurrency and Sendable in NIOConcurrencyHelpers
  Package.swift
  Sources/NIOConcurrencyHelpers/NIOAtomic.swift
  Sources/NIOConcurrencyHelpers/atomics.swift
Labels: semver/minor

#2833 Update the triggers for the Semantic Version label check
  .github/workflows/pull_request_label.yml
Labels: semver/none

#2829 Add `.editorconfig` file
  .editorconfig
  .licenseignore
Labels: semver/none

#2835 Adopt strict concurrency in _NIODataStructures
  Package.swift
  Sources/_NIODataStructures/_TinyArray.swift
Labels: semver/minor

#2836 Fix text availability
  Tests/NIOFileSystemIntegrationTests/FileSystemTests.swift
Labels: semver/none

#2838 Adopt strict concurrency in _NIOBase64
  Package.swift
  Sources/_NIOBase64/Base64.swift
Labels: semver/patch

#2840 Strict concurrency the early tests
  Package.swift
  Tests/NIOConcurrencyHelpersTests/NIOConcurrencyHelpersTests.swift
Labels: semver/none

#2841 Remove symlinks from resources
  .PrivacyInfo.xcprivacy
  Sources/NIOFileSystem/PrivacyInfo.xcprivacy
  Sources/NIOPosix/PrivacyInfo.xcprivacy
Labels: semver/patch

#2842 Fix `NIOFileSystem` flaky tests
  Tests/NIOFileSystemIntegrationTests/FileHandleTests.swift
Labels: semver/none

#2843 Improve testTasksScheduledDuringShutdownAreAutomaticallyCancelled
  Tests/NIOEmbeddedTests/AsyncTestingEventLoopTests.swift
Labels: semver/none

#2839 Align benchmark scaling and minimum samples
  Benchmarks/Benchmarks/NIOCoreBenchmarks/Benchmarks.swift
  Benchmarks/Benchmarks/NIOPosixBenchmarks/Benchmarks.swift
  Benchmarks/Thresholds/5.10/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
  Benchmarks/Thresholds/5.10/NIOPosixBenchmarks.TCPEcho.p90.json
  Benchmarks/Thresholds/5.10/NIOPosixBenchmarks.TCPEchoAsyncChannel.p90.json
  Benchmarks/Thresholds/5.8/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
  Benchmarks/Thresholds/5.8/NIOPosixBenchmarks.TCPEcho.p90.json
  Benchmarks/Thresholds/5.9/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
  Benchmarks/Thresholds/5.9/NIOPosixBenchmarks.TCPEcho.p90.json
  Benchmarks/Thresholds/5.9/NIOPosixBenchmarks.TCPEchoAsyncChannel.p90.json
  Benchmarks/Thresholds/nightly-6.0/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
  Benchmarks/Thresholds/nightly-6.0/NIOPosixBenchmarks.TCPEcho.p90.json
  Benchmarks/Thresholds/nightly-6.0/NIOPosixBenchmarks.TCPEchoAsyncChannel.p90.json
  Benchmarks/Thresholds/nightly-main/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
  Benchmarks/Thresholds/nightly-main/NIOPosixBenchmarks.TCPEcho.p90.json
  Benchmarks/Thresholds/nightly-main/NIOPosixBenchmarks.TCPEchoAsyncChannel.p90.json
Labels: semver/none

#2845 Explain why TSV isn't Sendable.
  Sources/NIOPosix/Thread.swift
Labels: semver/none

#2847 [CI] Don't persist git credentials in CI
  .github/workflows/pull_request_label.yml
  .github/workflows/soundness.yml
  .github/workflows/swift_6_language_mode.yml
  .github/workflows/swift_matrix.yml
Labels: semver/none

#2848 [CI] Mark the workspace as safe for the matrix job
  .github/workflows/swift_matrix.yml
Labels: semver/none

#2854 Pin DocC to below 1.4
  Package.swift
Labels: semver/none

#2831 Provide documentation and context information for NIOTooManyBytesError
  Sources/NIOCore/AsyncAwaitSupport.swift
  Tests/NIOCoreTests/AsyncSequenceTests.swift
Labels: semver/minor

#2851 [CI] Make container images configurable in soundness and matrix jobs …
  .github/workflows/soundness.yml
  .github/workflows/swift_matrix.yml
  Package.swift
  scripts/check-docs.sh
Labels: semver/none
