Repository apple/swift-nio, pull requests merged in 2024-07, with the labels that each got.

#2760 [GHA] Introduce the first GitHub Action
  .github/workflows/pull_requests.yml
Labels: needs-no-version-bump

#2763 [GHA] Add API breaking check
  .github/workflows/pull_requests.yml
Labels: needs-no-version-bump

#2764 [GHA] Documentation check
  .github/workflows/pull_requests.yml
  Sources/NIOCore/AsyncAwaitSupport.swift
  Sources/NIOCore/AsyncChannel/AsyncChannel.swift
  Sources/NIOCore/EventLoop.swift
  Sources/NIOFileSystem/FileSystem.swift
Labels: needs-no-version-bump

#2767 [GHA] Create reusable workflow
  .github/workflows/pull_request.yml
  .github/workflows/reusable_pull_request.yml
Labels: needs-no-version-bump

#2765 Pre-box some errors to reduce allocations
  Sources/NIOCore/AsyncChannel/AsyncChannelOutboundWriterHandler.swift
  Sources/NIOCore/Channel.swift
  Sources/NIOCore/ChannelPipeline.swift
  Sources/NIOCore/DeadChannel.swift
  Sources/NIOCore/EventLoop.swift
  Sources/NIOPosix/BSDSocketAPIPosix.swift
  Sources/NIOPosix/BaseSocketChannel.swift
  Sources/NIOPosix/BaseStreamSocketChannel.swift
  Sources/NIOPosix/Bootstrap.swift
  Sources/NIOPosix/Errors+Any.swift
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
  Sources/NIOPosix/PendingDatagramWritesManager.swift
  Sources/NIOPosix/PipeChannel.swift
  Sources/NIOPosix/PipePair.swift
  Sources/NIOPosix/SelectableEventLoop.swift
  Sources/NIOPosix/SelectorGeneric.swift
  Sources/NIOPosix/SelectorKqueue.swift
  Sources/NIOPosix/SocketChannel.swift
  docker/docker-compose.2204.510.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.59.yaml
Labels: patch-version-bump-only

#2766 [GHA] Unacceptable language check
  .github/workflows/reusable_pull_request.yml
  IntegrationTests/run-tests.sh
  IntegrationTests/tests_01_http/defines.sh
  IntegrationTests/tests_01_http/test_08_survive_signals.sh
  IntegrationTests/tests_01_http/test_10_connection_drop_in_body_ok.sh
  IntegrationTests/tests_01_http/test_13_http_pipelining.sh
  IntegrationTests/tests_01_http/test_18_close_with_no_keepalive.sh
  IntegrationTests/tests_01_http/test_19_connection_drop_while_waiting_for_response_uds.sh
  IntegrationTests/tests_01_http/test_20_connection_drop_while_waiting_for_response_tcp.sh
  IntegrationTests/tests_01_http/test_21_connection_reset_tcp.sh
  NOTICE.txt
  README.md
  Sources/CNIOAtomics/src/cpp_magic.h
  Sources/CNIOLinux/shim.c
  Sources/CNIOSHA1/update_and_patch_sha1.sh
  Sources/NIO/Docs.docc/index.md
  Sources/NIOCore/SystemCallHelpers.swift
  Sources/NIOPosix/System.swift
  Tests/NIOPosixTests/ChannelTests.swift
  scripts/nio-diagnose
  scripts/soundness.sh
  scripts/unacceptable_language_check.sh
Labels: needs-no-version-bump

#2768 Avoid creating a yield ID counter per async writer
  Sources/NIOCore/AsyncSequences/NIOAsyncWriter.swift
Labels: patch-version-bump-only

#2774 Add benchmark for creating NIOAsyncChannel
  Benchmarks/Benchmarks/NIOCoreBenchmarks/Benchmarks.swift
  Benchmarks/Package.swift
  Benchmarks/Thresholds/5.10/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
  Benchmarks/Thresholds/5.8/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
  Benchmarks/Thresholds/5.9/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
  Benchmarks/Thresholds/main/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
Labels: needs-no-version-bump

#2776 [GHA] Move docs check to script
  .github/workflows/reusable_pull_request.yml
  scripts/check-unacceptable-language.sh
Labels: needs-no-version-bump

#2780 [GHA] Benchmark job
  .github/workflows/pull_request.yml
  .github/workflows/reusable_pull_request.yml
  Benchmarks/Thresholds/nightly-main/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
  Benchmarks/Thresholds/nightly-main/NIOPosixBenchmarks.TCPEcho.p90.json
  Benchmarks/Thresholds/nightly-main/NIOPosixBenchmarks.TCPEchoAsyncChannel.p90.json
  Benchmarks/Thresholds/nightly-next/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
  Benchmarks/Thresholds/nightly-next/NIOPosixBenchmarks.TCPEcho.p90.json
  Benchmarks/Thresholds/nightly-next/NIOPosixBenchmarks.TCPEchoAsyncChannel.p90.json
Labels: needs-no-version-bump

#2785 [GHA] Download the scripts to make workflow reusable
  .github/workflows/reusable_pull_request.yml
Labels: needs-no-version-bump

#2775 HTTPPart Documentation Clarification
  Sources/NIOHTTP1/HTTPTypes.swift
Labels: needs-no-version-bump

#2781 [GHA] Add license header check
  .github/workflows/pull_request.yml
  .github/workflows/reusable_pull_request.yml
  .licenseignore
  Benchmarks/Package.swift
  scripts/check-license-header.sh
Labels: needs-no-version-bump

#2787 [GHA] Broken symlink and format check
  .github/workflows/pull_request.yml
  .github/workflows/reusable_pull_request.yml
  scripts/check-broken-symlinks.sh
Labels: needs-no-version-bump

#2789 [GHA] Introduce reusable matrix workflow
  .github/workflows/pull_request.yml
  .github/workflows/pull_request_soundness.yml
  .github/workflows/pull_request_swift_matrix.yml
  scripts/check-matrix-job.sh
  scripts/soundness.sh
Labels: needs-no-version-bump

#2790 [GHA] Cxx interoperability compatibility and integration tests check
  .github/workflows/pull_request.yml
  Benchmarks/Thresholds/nightly-6.0/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
  Benchmarks/Thresholds/nightly-6.0/NIOPosixBenchmarks.TCPEcho.p90.json
  Benchmarks/Thresholds/nightly-6.0/NIOPosixBenchmarks.TCPEchoAsyncChannel.p90.json
  IntegrationTests/tests_04_performance/Thresholds/5.10.json
  IntegrationTests/tests_04_performance/Thresholds/5.8.json
  IntegrationTests/tests_04_performance/Thresholds/5.9.json
  IntegrationTests/tests_04_performance/Thresholds/nightly-6.0.json
  IntegrationTests/tests_04_performance/Thresholds/nightly-main.json
  IntegrationTests/tests_04_performance/test_01_allocation_counts.sh
  docker/docker-compose.2204.nightly-6.0.yaml
  scripts/check-cxx-interop-compatibility.sh
  scripts/check-docs.sh
Labels: needs-no-version-bump

#2786 Add manual control to NIOLockedValueBox
  Benchmarks/Thresholds/5.10/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
  Benchmarks/Thresholds/5.8/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
  Benchmarks/Thresholds/5.9/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
  Benchmarks/Thresholds/nightly-6.0/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
  Benchmarks/Thresholds/nightly-main/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
  Sources/NIOConcurrencyHelpers/NIOLockedValueBox.swift
  Sources/NIOCore/AsyncSequences/NIOAsyncWriter.swift
  Sources/NIOCore/AsyncSequences/NIOThrowingAsyncSequenceProducer.swift
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncSequenceTests.swift
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncWriterTests.swift
  Tests/NIOCoreTests/AsyncSequences/NIOThrowingAsyncSequenceTests.swift
Labels: 🔼 needs-minor-version-bump

#2793 Disable warnings as errors on Swift 6 and main
  .github/workflows/pull_request.yml
  IntegrationTests/tests_04_performance/Thresholds/nightly-6.0.json
  IntegrationTests/tests_04_performance/Thresholds/nightly-main.json
Labels: needs-no-version-bump

#2797 [GHA] Only format Swift files that are in Git index
  .github/workflows/pull_request_soundness.yml
Labels: needs-no-version-bump

#2784 Use the new Android overlay and Bionic module from Swift 6
  Sources/NIOConcurrencyHelpers/NIOLock.swift
  Sources/NIOConcurrencyHelpers/atomics.swift
  Sources/NIOConcurrencyHelpers/lock.swift
  Sources/NIOCore/BSDSocketAPI.swift
  Sources/NIOCore/ByteBuffer-core.swift
  Sources/NIOCore/FileHandle.swift
  Sources/NIOCore/FileRegion.swift
  Sources/NIOCore/GlobalSingletons.swift
  Sources/NIOCore/IO.swift
  Sources/NIOCore/Interfaces.swift
  Sources/NIOCore/SocketAddresses.swift
  Sources/NIOCore/SocketOptionProvider.swift
  Sources/NIOCore/SystemCallHelpers.swift
  Sources/NIOCore/Utilities.swift
  Sources/NIOFileSystem/FileInfo.swift
  Sources/NIOFileSystem/FileSystem.swift
  Sources/NIOFileSystem/FileType.swift
  Sources/NIOFileSystem/Internal/System Calls/CInterop.swift
  Sources/NIOFileSystem/Internal/System Calls/Errno.swift
  Sources/NIOFileSystem/Internal/System Calls/FileDescriptor+Syscalls.swift
  Sources/NIOFileSystem/Internal/System Calls/Mocking.swift
  Sources/NIOFileSystem/Internal/System Calls/Syscall.swift
  Sources/NIOFileSystem/Internal/System Calls/Syscalls.swift
  Sources/NIOFileSystem/Internal/SystemFileHandle.swift
  Sources/NIOPosix/Linux.swift
  Sources/NIOPosix/SocketProtocols.swift
  Sources/NIOPosix/System.swift
  Sources/_NIODataStructures/Heap.swift
  Tests/NIOConcurrencyHelpersTests/NIOConcurrencyHelpersTests.swift
  Tests/NIOFileSystemIntegrationTests/FileHandleTests.swift
  Tests/NIOFileSystemTests/FileInfoTests.swift
  Tests/NIOFileSystemTests/Internal/SyscallTests.swift
  Tests/NIOPosixTests/HappyEyeballsTest.swift
Labels: patch-version-bump-only

#2802 Change `unsafeDownCast` to `as!`
  Sources/NIOConcurrencyHelpers/NIOLock.swift
  Sources/NIOPosix/Pool.swift
Labels: patch-version-bump-only

#2808 Fix compose file used in update-benchmark-thresholds script
  dev/update-benchmark-thresholds.sh
Labels: semver/none

#2810 Make testInstantTCPConnectionResetThrowsError more reliable
  Tests/NIOPosixTests/SocketChannelTest.swift
Labels: semver/none

#2800 Better align shutdown semantics of testing event loops
  IntegrationTests/tests_04_performance/Thresholds/5.10.json
  IntegrationTests/tests_04_performance/Thresholds/5.8.json
  IntegrationTests/tests_04_performance/Thresholds/5.9.json
  IntegrationTests/tests_04_performance/Thresholds/nightly-6.0.json
  IntegrationTests/tests_04_performance/Thresholds/nightly-main.json
  Sources/NIOEmbedded/AsyncTestingEventLoop.swift
  Sources/NIOEmbedded/Embedded.swift
  Tests/NIOEmbeddedTests/AsyncTestingEventLoopTests.swift
  Tests/NIOEmbeddedTests/EmbeddedChannelTest.swift
  Tests/NIOEmbeddedTests/EmbeddedEventLoopTest.swift
  Tests/NIOPosixTests/XCTest+AsyncAwait.swift
  docker/docker-compose.2204.510.yaml
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.59.yaml
  docker/docker-compose.2204.main.yaml
  docker/docker-compose.2204.nightly-6.0.yaml
Labels: semver/patch

#2809 [CI] Add `shellcheck` and fix up warnings
  .github/workflows/soundness.yml
  IntegrationTests/allocation-counter-tests-framework/run-allocation-counter.sh
  IntegrationTests/plugin_junit_xml.sh
  IntegrationTests/run-single-test.sh
  IntegrationTests/run-tests.sh
  IntegrationTests/test_functions.sh
  IntegrationTests/tests_01_http/defines.sh
  IntegrationTests/tests_01_http/test_01_get_file.sh
  IntegrationTests/tests_01_http/test_02_get_random_bytes.sh
  IntegrationTests/tests_01_http/test_03_post_random_bytes.sh
  IntegrationTests/tests_01_http/test_04_keep_alive_works.sh
  IntegrationTests/tests_01_http/test_05_repeated_reqs_work.sh
  IntegrationTests/tests_01_http/test_06_http_1.0.sh
  IntegrationTests/tests_01_http/test_07_headers_work.sh
  IntegrationTests/tests_01_http/test_08_survive_signals.sh
  IntegrationTests/tests_01_http/test_09_curl_happy_with_trailers.sh
  IntegrationTests/tests_01_http/test_10_connection_drop_in_body_ok.sh
  IntegrationTests/tests_01_http/test_11_res_body_streaming.sh
  IntegrationTests/tests_01_http/test_12_headers_too_large.sh
  IntegrationTests/tests_01_http/test_13_http_pipelining.sh
  IntegrationTests/tests_01_http/test_14_strict_mode_assertion.sh
  IntegrationTests/tests_01_http/test_15_post_in_chunked_encoding.sh
  IntegrationTests/tests_01_http/test_16_tcp_client_ip.sh
  IntegrationTests/tests_01_http/test_17_serve_massive_sparse_file.sh
  IntegrationTests/tests_01_http/test_18_close_with_no_keepalive.sh
  IntegrationTests/tests_01_http/test_19_connection_drop_while_waiting_for_response_uds.sh
  IntegrationTests/tests_01_http/test_20_connection_drop_while_waiting_for_response_tcp.sh
  IntegrationTests/tests_01_http/test_21_connection_reset_tcp.sh
  IntegrationTests/tests_01_http/test_22_http_1.0_keep_alive.sh
  IntegrationTests/tests_01_http/test_23_repeated_reqs_with_half_closure.sh
  IntegrationTests/tests_01_http/test_24_http_over_stdio.sh
  IntegrationTests/tests_02_syscall_wrappers/defines.sh
  IntegrationTests/tests_02_syscall_wrappers/test_01_syscall_wrapper_fast.sh
  IntegrationTests/tests_02_syscall_wrappers/test_02_unacceptable_errnos.sh
  IntegrationTests/tests_02_syscall_wrappers/test_03_unacceptable_read_errnos.sh
  IntegrationTests/tests_03_debug_binary_checks/defines.sh
  IntegrationTests/tests_03_debug_binary_checks/test_01_check_we_do_not_link_Foundation.sh
  IntegrationTests/tests_03_debug_binary_checks/test_02_expected_crashes_work.sh
  IntegrationTests/tests_04_performance/test_01_allocation_counts.sh
  IntegrationTests/tests_05_assertions/defines.sh
  IntegrationTests/tests_05_assertions/test_01_syscall_wrapper_fast.sh
  Sources/CNIOLLHTTP/update_and_patch_llhttp.sh
  Sources/CNIOSHA1/update_and_patch_sha1.sh
  dev/update-benchmark-thresholds.sh
  scripts/check-docs.sh
  scripts/check-license-header.sh
  scripts/check-matrix-job.sh
  scripts/check-swift-format.sh
  scripts/check_no_api_breakages.sh
  scripts/cxx-interop-compatibility.sh
  scripts/generate_contributors_list.sh
  scripts/integration_tests.sh
  scripts/soundness.sh
Labels: semver/none

#2811 [CI] Fix docs check
  .github/workflows/soundness.yml
  scripts/check-docs.sh
Labels: semver/none

#2812 [CI] Add Swift 6 language mode workflow
  .github/workflows/pull_request.yml
  .github/workflows/soundness.yml
  .github/workflows/swift_6_language_mode.yml
  .github/workflows/swift_matrix.yml
Labels: semver/none

#2817 Fix test compilation on non-macOS Darwin platforms
  Tests/NIOEmbeddedTests/AsyncTestingEventLoopTests.swift
Labels: semver/none

#2816 ChannelOption: Allow types to be accessed with leading dot syntax
  IntegrationTests/tests_04_performance/test_01_resources/shared.swift
  IntegrationTests/tests_04_performance/test_01_resources/test_1000_autoReadGetAndSet.swift
  IntegrationTests/tests_04_performance/test_01_resources/test_1000_autoReadGetAndSet_sync.swift
  IntegrationTests/tests_04_performance/test_01_resources/test_1000_tcpconnections.swift
  IntegrationTests/tests_04_performance/test_01_resources/test_1000_udp_reqs.swift
  IntegrationTests/tests_04_performance/test_01_resources/test_ping_pong_1000_reqs_1_conn.swift
  Sources/NIOChatClient/main.swift
  Sources/NIOChatServer/main.swift
  Sources/NIOCore/ChannelOption.swift
  Sources/NIOCore/ConvenienceOptionSupport.swift
  Sources/NIOCrashTester/OutputGrepper.swift
  Sources/NIOEchoClient/main.swift
  Sources/NIOEchoServer/main.swift
  Sources/NIOHTTP1Client/main.swift
  Sources/NIOHTTP1Server/main.swift
  Sources/NIOMulticastChat/main.swift
  Sources/NIOPerformanceTester/UDPBenchmark.swift
  Sources/NIOPerformanceTester/main.swift
  Sources/NIOPosix/BaseSocketChannel.swift
  Sources/NIOPosix/Bootstrap.swift
  Sources/NIOPosix/VsockAddress.swift
  Sources/NIOTCPEchoServer/Server.swift
  Sources/NIOTestUtils/NIOHTTP1TestServer.swift
  Sources/NIOUDPEchoClient/main.swift
  Sources/NIOUDPEchoServer/main.swift
  Sources/NIOWebSocketServer/Server.swift
  Tests/NIOCoreTests/ChannelOptionStorageTest.swift
  Tests/NIOEmbeddedTests/AsyncTestingChannelTests.swift
  Tests/NIOEmbeddedTests/EmbeddedChannelTest.swift
  Tests/NIOHTTP1Tests/HTTPServerClientTest.swift
  Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift
  Tests/NIOPosixTests/AcceptBackoffHandlerTest.swift
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
  Tests/NIOPosixTests/BootstrapTest.swift
  Tests/NIOPosixTests/ChannelNotificationTest.swift
  Tests/NIOPosixTests/ChannelTests.swift
  Tests/NIOPosixTests/DatagramChannelTests.swift
  Tests/NIOPosixTests/EchoServerClientTest.swift
  Tests/NIOPosixTests/EventLoopTest.swift
  Tests/NIOPosixTests/FileRegionTest.swift
  Tests/NIOPosixTests/IdleStateHandlerTest.swift
  Tests/NIOPosixTests/MulticastTest.swift
  Tests/NIOPosixTests/PipeChannelTest.swift
  Tests/NIOPosixTests/RawSocketBootstrapTests.swift
  Tests/NIOPosixTests/SALChannelTests.swift
  Tests/NIOPosixTests/SelectorTest.swift
  Tests/NIOPosixTests/SocketChannelTest.swift
  Tests/NIOPosixTests/StreamChannelsTest.swift
  Tests/NIOPosixTests/TestUtils.swift
  Tests/NIOPosixTests/UniversalBootstrapSupportTest.swift
  Tests/NIOPosixTests/VsockAddressTest.swift
  Tests/NIOTestUtilsTests/NIOHTTP1TestServerTest.swift
Labels: semver/minor

#2714 Make EventLoopPromise conform to Equatable
  Sources/NIOCore/EventLoopFuture.swift
  Tests/NIOPosixTests/EventLoopFutureTest.swift
Labels: semver/minor

#2814 [CI] Add action and workflow to check for semver label
  .github/actions/pull_request_semver_label_checker.yml
  .github/workflows/pull_request_label.yml
Labels: semver/none
