Repository apple/swift-nio, pull requests merged in 2024-05, with the labels that each got.

#2719 clean up @retroactive conformances
  Sources/NIOFoundationCompat/ByteBuffer-foundation.swift
Labels: patch-version-bump-only

#2721 Update PosixSingletons+ConcurrencyTakeOver.swift
  Sources/NIOPosix/PosixSingletons+ConcurrencyTakeOver.swift
Labels: needs-no-version-bump

#2716 Exclude unused privacy manifests.
  Package.swift
Labels: needs-no-version-bump

#2724 Fix race in TCPThroughputBenchmark
  Sources/NIOPerformanceTester/TCPThroughputBenchmark.swift
Labels: needs-no-version-bump

#2725 testSimpleMPTCP should not fail for ENOPROTOOPT
  Tests/NIOPosixTests/SocketChannelTest.swift
Labels: needs-no-version-bump

#2726 Remove storage indirection for FileSystemError
  Sources/NIOFileSystem/FileSystemError.swift
  Tests/NIOFileSystemTests/FileSystemErrorTests.swift
Labels: patch-version-bump-only

#2731 Improve rename error
  Sources/NIOFileSystem/FileSystem.swift
  Sources/NIOFileSystem/FileSystemError+Syscall.swift
  Sources/NIOFileSystem/Internal/SystemFileHandle.swift
  Tests/NIOFileSystemTests/FileSystemErrorTests.swift
Labels: patch-version-bump-only

#2730 Add a version of 'write' for 'ByteBuffer'
  Sources/NIOFileSystem/Docs.docc/Extensions/WritableFileHandleProtocol.md
  Sources/NIOFileSystem/FileHandleProtocol.swift
  Tests/NIOFileSystemIntegrationTests/FileHandleTests.swift
Labels: 🔼 needs-minor-version-bump

#2715 Release file handles back to caller on failure to take ownership
  Sources/NIOPosix/Bootstrap.swift
  Tests/NIOPosixTests/BootstrapTest.swift
Labels: patch-version-bump-only

#2733 Add a fallback path if renameat2 fails
  Sources/NIOFileSystem/Internal/SystemFileHandle.swift
  Tests/NIOFileSystemIntegrationTests/FileHandleTests.swift
Labels: patch-version-bump-only
