Repository apple/swift-nio, pull requests merged in 2025-09, with the labels that each got.

#3363 Add a NIOFilePath based NIOFileSystem
  .spi.yml
  Package.swift
  Snippets/NIOFileSystemTour.swift
  Sources/NIO/Docs.docc/index.md
  Sources/NIOFileSystem/Array+FileSystem.swift
  Sources/NIOFileSystem/ArraySlice+FileSystem.swift
  Sources/NIOFileSystem/BufferedReader.swift
  Sources/NIOFileSystem/BufferedWriter.swift
  Sources/NIOFileSystem/ByteBuffer+FileSystem.swift
  Sources/NIOFileSystem/Convenience.swift
  Sources/NIOFileSystem/DirectoryEntries.swift
  Sources/NIOFileSystem/DirectoryEntry.swift
  Sources/NIOFileSystem/Docs.docc/Extensions/DirectoryFileHandleProtocol.md
  Sources/NIOFileSystem/Docs.docc/Extensions/FileHandleProtocol.md
  Sources/NIOFileSystem/Docs.docc/Extensions/FileSystemProtocol.md
  Sources/NIOFileSystem/Docs.docc/Extensions/ReadableFileHandleProtocol.md
  Sources/NIOFileSystem/Docs.docc/Extensions/WritableFileHandleProtocol.md
  Sources/NIOFileSystem/Docs.docc/index.md
  Sources/NIOFileSystem/FileChunks.swift
  Sources/NIOFileSystem/FileHandleProtocol.swift
  Sources/NIOFileSystem/FileSystem.swift
  Sources/NIOFileSystem/FileSystemProtocol+FilePath.swift
  Sources/NIOFileSystem/FileSystemProtocol.swift
  Sources/NIOFileSystem/Internal/BufferedOrAnyStream.swift
  Sources/NIOFileSystem/Internal/ParallelDirCopy.swift
  Sources/NIOFileSystem/Internal/ParallelRemoval.swift
  Sources/NIOFileSystem/NIOFileSystemSendableMetatype.swift
  Sources/NIOFileSystem/OpenOptions.swift
  Sources/NIOFileSystem/String+FileSystem.swift
  Sources/NIOFileSystemFoundationCompat/Data+FileSystem.swift
  Sources/NIOFileSystemFoundationCompat/Date+FileInfo.swift
  Sources/_NIOFileSystemExported/Exports.swift
  Tests/NIOFileSystemFoundationCompatTests/FileSystemFoundationCompatTests.swift
  Tests/NIOFileSystemIntegrationTests/BufferedReaderTests.swift
  Tests/NIOFileSystemIntegrationTests/BufferedWriterTests.swift
  Tests/NIOFileSystemIntegrationTests/ConvenienceTests.swift
  Tests/NIOFileSystemIntegrationTests/FileHandleTests.swift
  Tests/NIOFileSystemIntegrationTests/FileSystemTests+SPI.swift
  Tests/NIOFileSystemIntegrationTests/FileSystemTests.swift
  Tests/NIOFileSystemIntegrationTests/XCTestExtensions.swift
  Tests/NIOFileSystemTests/ByteCountTests.swift
  Tests/NIOFileSystemTests/DirectoryEntriesTests.swift
  Tests/NIOFileSystemTests/FileChunksTests.swift
  Tests/NIOFileSystemTests/FileHandleTests.swift
  Tests/NIOFileSystemTests/FileInfoTests.swift
  Tests/NIOFileSystemTests/FileOpenOptionsTests.swift
  Tests/NIOFileSystemTests/FilePathTests.swift
  Tests/NIOFileSystemTests/FileSystemErrorTests.swift
  Tests/NIOFileSystemTests/FileTypeTests.swift
  Tests/NIOFileSystemTests/Internal/CancellationTests.swift
  Tests/NIOFileSystemTests/Internal/Concurrency Primitives/BufferedStreamTests.swift
  Tests/NIOFileSystemTests/Internal/MockingInfrastructure.swift
  Tests/NIOFileSystemTests/Internal/SyscallTests.swift
  Tests/NIOFileSystemTests/XCTestExtensions.swift
Labels: 🆕 semver/minor

#3365 [Windows] Sleep instead of WSAPoll, if no outstanding IO
  Sources/NIOPosix/SelectorWSAPoll.swift
Labels: 🔨 semver/patch

#3364 [Windows] Reimplement pwrite
  Sources/NIOPosix/IO.swift
  Sources/NIOPosix/NonBlockingFileIO.swift
  Sources/NIOPosix/System.swift
  Sources/NIOPosix/Windows.swift
Labels: 🔨 semver/patch

#3366 [Windows] Ensure WSAStartup is correctly called.
  Sources/CNIOWindows/WSAStartup.c
  Sources/NIOCore/SocketAddresses.swift
Labels: 🔨 semver/patch

#3370 Remove NIOFileSystem from products
  Package.swift
  Snippets/NIOFileSystemTour.swift
Labels: 🔨 semver/patch

#3374 Update CI scripts for 6.2
  .github/workflows/benchmarks.yml
  .github/workflows/cxx_interop.yml
  .github/workflows/macos_tests.yml
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  .github/workflows/release_builds.yml
  .github/workflows/unit_tests.yml
  Benchmarks/Thresholds/6.2/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
  Benchmarks/Thresholds/6.2/NIOPosixBenchmarks.TCPEcho.p90.json
  Benchmarks/Thresholds/6.2/NIOPosixBenchmarks.TCPEchoAsyncChannel.p90.json
  IntegrationTests/tests_04_performance/Thresholds/6.2.json
  scripts/check-matrix-job.sh
  scripts/generate_matrix.sh
Labels: semver/none
