Repository apple/swift-nio, pull requests merged in 2025-05, with the labels that each got.

#3229 Replace almost all public static lets with computed vars
  Sources/NIOCore/BSDSocketAPI.swift
  Sources/NIOCore/ByteBuffer-hex.swift
  Sources/NIOCore/EventLoop.swift
  Sources/NIOCore/FileHandle.swift
  Sources/NIOCore/IPProtocol.swift
  Sources/NIOCore/IntegerTypes.swift
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOHTTP1/HTTPTypes.swift
  Sources/NIOPosix/BSDSocketAPICommon.swift
  Sources/NIOPosix/IntegerTypes.swift
  Sources/NIOPosix/NonBlockingFileIO.swift
  Sources/NIOPosix/VsockAddress.swift
  Sources/NIOWebSocket/WebSocketOpcode.swift
  Sources/_NIOBase64/Base64.swift
Labels: semver/none

#3227 Removed Docker references as repo moved to Github actions
  CONTRIBUTING.md
  README.md
  dev/update-benchmark-thresholds.sh
Labels: semver/none

#3232 Update SECURITY.md
  SECURITY.md
Labels: semver/none

#3230 Make ChannelError and NIOConnectionError conform to CustomStringConvertible
  Sources/NIOCore/Channel.swift
  Sources/NIOPosix/HappyEyeballs.swift
Labels: 🆕 semver/minor

#3228 Drop Swift 5.9
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  Benchmarks/Package.swift
  Benchmarks/Thresholds/5.9/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
  Benchmarks/Thresholds/5.9/NIOCoreBenchmarks.WaitOnPromise.p90.json
  Benchmarks/Thresholds/5.9/NIOPosixBenchmarks.TCPEcho.p90.json
  Benchmarks/Thresholds/5.9/NIOPosixBenchmarks.TCPEchoAsyncChannel.p90.json
  IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Package.swift
  IntegrationTests/allocation-counter-tests-framework/template/HookedFunctionsDoHook/Package.swift
  IntegrationTests/allocation-counter-tests-framework/template/HookedFunctionsDoNotHook/Package.swift
  IntegrationTests/tests_04_performance/Thresholds/5.9.json
  Package.swift
  README.md
  Sources/NIOEmbedded/AsyncTestingChannel.swift
  Sources/NIOHTTP1/HTTPTypedPipelineSetup.swift
  Sources/NIOHTTP1/NIOTypedHTTPClientUpgradeHandler.swift
  Sources/NIOHTTP1/NIOTypedHTTPClientUpgraderStateMachine.swift
  Sources/NIOHTTP1/NIOTypedHTTPServerUpgradeHandler.swift
  Sources/NIOHTTP1/NIOTypedHTTPServerUpgraderStateMachine.swift
  Sources/NIOPosix/SelectableEventLoop.swift
  Sources/NIOWebSocket/NIOWebSocketClientUpgrader.swift
  Sources/NIOWebSocket/NIOWebSocketServerUpgrader.swift
  Sources/NIOWebSocketClient/Client.swift
  Sources/NIOWebSocketServer/Server.swift
  Tests/NIOConcurrencyHelpersTests/NIOConcurrencyHelpersTests.swift
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncWriterTests.swift
  Tests/NIOFileSystemIntegrationTests/FileSystemTests.swift
  Tests/NIOHTTP1Tests/HTTPClientUpgradeTests.swift
  Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift
  Tests/NIOWebSocketTests/WebSocketClientEndToEndTests.swift
  Tests/NIOWebSocketTests/WebSocketServerEndToEndTests.swift
Labels: 🆕 semver/minor

#3220 Update Array+FileSystem.swift to add visionOS
  Sources/NIOCore/ByteBuffer-aux.swift
  Sources/NIOFileSystem/Array+FileSystem.swift
  Sources/NIOFileSystem/ArraySlice+FileSystem.swift
  Sources/NIOFileSystem/IOStrategy.swift
  Sources/NIOFileSystemFoundationCompat/Data+FileSystem.swift
  Tests/NIOCoreTests/ByteBufferTest.swift
Labels: 🔨 semver/patch

#3231 Remove assertions on PWM failAll and closeOutbound
  Sources/NIOPosix/BaseStreamSocketChannel.swift
  Sources/NIOPosix/PendingWritesManager.swift
  Tests/NIOPosixTests/StreamChannelsTest.swift
Labels: 🔨 semver/patch

#3233 Disable Swift 5.9 CI jobs by default
  .github/workflows/benchmarks.yml
  .github/workflows/cxx_interop.yml
  .github/workflows/swift_matrix.yml
  .github/workflows/unit_tests.yml
  scripts/generate_matrix.sh
Labels: semver/none

#3234 Enable visionOS xcodebuilds by default in CI
  .github/workflows/macos_tests.yml
Labels: semver/none

#3235 Revert "Enable visionOS xcodebuilds by default in CI"
  .github/workflows/macos_tests.yml
Labels: semver/none

#3236 Macos setup command
  .github/workflows/macos_tests.yml
Labels: semver/none

#3237 Update check-matrix-job.sh to default swift commands
  scripts/check-matrix-job.sh
Labels: semver/none

#3240 Update macos_tests.yml to limit run time to 30 minutes
  .github/workflows/macos_tests.yml
Labels: semver/none

#3242 Remove default setup command for Xcode 16.2
  .github/workflows/macos_tests.yml
Labels: semver/none

#3244 Revert "Remove default setup command for Xcode 16.2 (#3242)"
  .github/workflows/macos_tests.yml
Labels: semver/none

#3245 Revert "Print the swift version in Linux matrix jobs"
  .github/workflows/swift_test_matrix.yml
Labels: semver/none

#3247 Execute swift --version in shared workflows
  .github/workflows/benchmarks.yml
  .github/workflows/cxx_interop.yml
  .github/workflows/unit_tests.yml
Labels: semver/none

#3250 Update the matrix nightly-next to point to 6.2
  scripts/generate_matrix.sh
Labels: semver/none

#3243 `NIOThrowingAsyncSequenceProducer` make more funcs `@inlinable`
  Sources/NIOCore/AsyncSequences/NIOThrowingAsyncSequenceProducer.swift
Labels: 🔨 semver/patch

#3249 Handle different ThreadDestructor signatures between Android NDK 27 and NDK 28
  Sources/NIOPosix/ThreadPosix.swift
Labels: 🔨 semver/patch

#3258 Benchmarks workflow prints diff when changes found
  .github/workflows/benchmarks.yml
  dev/thresholds-from-benchmark-output.sh
  scripts/check_benchmark_thresholds.sh
Labels: semver/none

#3259 a couple grammar fixes
  Sources/NIOCore/EventLoopFuture.swift
  Sources/NIOPerformanceTester/UDPBenchmark.swift
  Tests/NIOPosixTests/ChannelTests.swift
Labels: semver/none

#3254 Embedded channels should set local and remote address always
  Sources/NIOEmbedded/AsyncTestingChannel.swift
  Sources/NIOEmbedded/Embedded.swift
  Tests/NIOEmbeddedTests/AsyncTestingChannelTests.swift
  Tests/NIOEmbeddedTests/EmbeddedChannelTest.swift
Labels: 🔨 semver/patch
