Repository apple/swift-nio, pull requests merged in 2025-04, with the labels that each got.

#3163 macOS CI pools
  .github/workflows/macos_tests.yml
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#3166 Update install_static_sdk.sh to cope with versions with no patch
  scripts/install_static_sdk.sh
Labels: semver/none

#3161 Strict concurrency for websocket client/server demo and async demo
  Package.swift
  Sources/NIOAsyncAwaitDemo/AsyncChannelIO.swift
  Sources/NIOAsyncAwaitDemo/FullRequestResponse.swift
Labels: semver/none

#3168 Document supported versions consistently
  README.md
Labels: semver/none

#3171 Add support for Xcode 16.3
  .github/workflows/macos_tests.yml
Labels: semver/none

#3173 Improve alloc tests failure messages
  IntegrationTests/test_functions.sh
  IntegrationTests/tests_04_performance/test_01_allocation_counts.sh
Labels: 🔨 semver/patch

#3176 uncomment visionOS CI tasks
  .github/workflows/macos_tests.yml
Labels: semver/none

#3169 Strict concurrency for NIOHTTP1Tests
  Package.swift
  Tests/NIOHTTP1Tests/HTTPClientUpgradeTests.swift
  Tests/NIOHTTP1Tests/HTTPDecoderLengthTest.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
  Tests/NIOHTTP1Tests/HTTPServerClientTest.swift
  Tests/NIOHTTP1Tests/HTTPServerPipelineHandlerTest.swift
  Tests/NIOHTTP1Tests/HTTPServerProtocolErrorHandlerTest.swift
  Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift
  Tests/NIOHTTP1Tests/HTTPTest.swift
  Tests/NIOPosixTests/TestUtils.swift
Labels: semver/none

#3187 Update nightly main benchmark thresholds
  Benchmarks/Thresholds/nightly-main/NIOPosixBenchmarks.TCPEchoAsyncChannel.p90.json
Labels: semver/none

#3181 Ignore return value of signal() on Android
  Sources/NIOCrashTester/main.swift
Labels: semver/none

#3183 Strict concurrency for NIOPosix BootstrapTest
  Tests/NIOPosixTests/BootstrapTest.swift
Labels: semver/none

#3185 Strict concurrency NIOPosix EventLoopTest
  Tests/NIOPosixTests/EventLoopTest.swift
Labels: semver/none

#3186 Static SDK installation script improvements
  .github/workflows/static_sdk.yml
  scripts/install_static_sdk.sh
  scripts/install_swift_prerequisites.sh
Labels: semver/none

#3190 Strict concurrency for NIOPosix SelectorTest
  Tests/NIOPosixTests/SelectorTest.swift
Labels: semver/none

#3188 Strict concurrency for NIOPosix NonBlockingFileIOTest
  Tests/NIOPosixTests/NonBlockingFileIOTest.swift
Labels: semver/none

#3178 Add perf test for EL as SerialExecutor
  Benchmarks/Benchmarks/NIOPosixBenchmarks/Benchmarks.swift
  Benchmarks/Package.swift
Labels: semver/none

#3191 Strict concurrency for NIOPosix ChannelTests
  Tests/NIOPosixTests/ChannelTests.swift
  Tests/NIOPosixTests/DatagramChannelTests.swift
Labels: semver/none

#3179 Expose the event loop from the loop bound boxes
  Sources/NIOCore/NIOLoopBound.swift
Labels: 🆕 semver/minor

#3192 Remove unchecked from SelectorTest
  Tests/NIOPosixTests/SelectorTest.swift
Labels: semver/none

#3193 Strict concurrency for NIOPosixTests, EL and ELF
  Tests/NIOPosixTests/EventLoopFutureTest.swift
  Tests/NIOPosixTests/EventLoopTest.swift
Labels: semver/none

#3174 Add More Peek API Variants for ByteBuffer
  Sources/NIOCore/ByteBuffer-core.swift
  Sources/NIOCore/ByteBuffer-lengthPrefix.swift
  Sources/NIOFoundationCompat/ByteBuffer-foundation.swift
  Sources/NIOWebSocket/WebSocketErrorCodes.swift
  Tests/NIOCoreTests/ByteBufferLengthPrefixTests.swift
  Tests/NIOCoreTests/ByteBufferTest.swift
  Tests/NIOWebSocketTests/ByteBufferWebSocketTests.swift
Labels: 🆕 semver/minor

#3196 Add and enable Swift 6.1 workflows
  .github/workflows/benchmarks.yml
  .github/workflows/cxx_interop.yml
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  .github/workflows/unit_tests.yml
  Benchmarks/Thresholds/6.1/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
  Benchmarks/Thresholds/6.1/NIOPosixBenchmarks.TCPEcho.p90.json
  Benchmarks/Thresholds/6.1/NIOPosixBenchmarks.TCPEchoAsyncChannel.p90.json
  IntegrationTests/tests_04_performance/Thresholds/6.1.json
  scripts/generate_matrix.sh
Labels: semver/none

#3201 Update matrix job script for 6.1
  scripts/check-matrix-job.sh
Labels: semver/none

#3198 Add Tests for WebSocketErrorCode Get, Read and Write APIs in ByteBuffer
  Tests/NIOWebSocketTests/ByteBufferWebSocketTests.swift
Labels: semver/none

#3199 Strict concurrency for a handful more NIOPosixTests
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
  Tests/NIOPosixTests/BlockingIOThreadPoolTest.swift
  Tests/NIOPosixTests/ChannelNotificationTest.swift
  Tests/NIOPosixTests/CodecTest.swift
  Tests/NIOPosixTests/DatagramChannelTests.swift
  Tests/NIOPosixTests/EventLoopFutureTest.swift
  Tests/NIOPosixTests/FileRegionTest.swift
  Tests/NIOPosixTests/HappyEyeballsTest.swift
  Tests/NIOPosixTests/IdleStateHandlerTest.swift
  Tests/NIOPosixTests/MulticastTest.swift
  Tests/NIOPosixTests/NIOThreadPoolTest.swift
  Tests/NIOPosixTests/PendingDatagramWritesManagerTests.swift
  Tests/NIOPosixTests/PipeChannelTest.swift
  Tests/NIOPosixTests/SocketChannelTest.swift
  Tests/NIOPosixTests/TestUtils.swift
  Tests/NIOPosixTests/UniversalBootstrapSupportTest.swift
Labels: semver/none

#3208 Swift concurrency for NIOWebSocketTests
  Package.swift
  Sources/NIOWebSocket/NIOWebSocketClientUpgrader.swift
  Tests/NIOWebSocketTests/WebSocketClientEndToEndTests.swift
  Tests/NIOWebSocketTests/WebSocketFrameDecoderTest.swift
  Tests/NIOWebSocketTests/WebSocketServerEndToEndTests.swift
Labels: 🆕 semver/minor

#3206 Strict concurrency for NIOTestUtilsTests
  Package.swift
  Tests/NIOTestUtilsTests/NIOHTTP1TestServerTest.swift
Labels: semver/none

#3207 Strict concurrency for NIOTLSTests
  Package.swift
  Tests/NIOTLSTests/ApplicationProtocolNegotiationHandlerTests.swift
  Tests/NIOTLSTests/NIOTypedApplicationProtocolNegotiationHandlerTests.swift
Labels: semver/none

#3205 Strict concurrency for SAL tests
  Tests/NIOPosixTests/SALChannelTests.swift
  Tests/NIOPosixTests/SALEventLoopTests.swift
  Tests/NIOPosixTests/SyscallAbstractionLayer.swift
  Tests/NIOPosixTests/SyscallAbstractionLayerContext.swift
Labels: semver/none

#3211 Enable strict concurrency for NIOPosixTests
  Package.swift
  Tests/NIOPosixTests/DatagramChannelTests.swift
  Tests/NIOPosixTests/EventLoopFutureTest.swift
Labels: semver/none

#3210 Add errorCaught to NIOTypedHTTPClientUpgradeHandler
  Sources/NIOHTTP1/NIOTypedHTTPClientUpgradeHandler.swift
  Tests/NIOHTTP1Tests/HTTPClientUpgradeTests.swift
Labels: 🔨 semver/patch

#3212 Clarify test server error code
  Sources/NIOTestUtils/NIOHTTP1TestServer.swift
  Tests/NIOTestUtilsTests/NIOHTTP1TestServerTest.swift
Labels: 🔨 semver/patch

#3217 Fix ByteBufferTests when compiling with Swift 6 but running on macOS 14.
  Tests/NIOCoreTests/ByteBufferTest.swift
Labels: semver/none

#3216 Update LLHTTP and apply patch to support C++ interop
  .licenseignore
  Sources/CNIOLLHTTP/LICENSE
  Sources/CNIOLLHTTP/c_nio_api.c
  Sources/CNIOLLHTTP/c_nio_http.c
  Sources/CNIOLLHTTP/c_nio_llhttp.c
  Sources/CNIOLLHTTP/include/c_nio_llhttp.h
  Sources/CNIOLLHTTP/update_and_patch_llhttp.sh
  Tests/NIOHTTP1Tests/HTTPClientUpgradeTests.swift
  Tests/NIOHTTP1Tests/HTTPDecoderLengthTest.swift
  Tests/NIOHTTP1Tests/HTTPDecoderTest.swift
Labels: 🔨 semver/patch

#3224 Fix compiler issues on 5.10 x86 Ubuntu Noble.
  Sources/NIOCore/AsyncChannel/AsyncChannel.swift
  Sources/NIOCore/NIOLoopBound.swift
Labels: 🔨 semver/patch

#3148 BaseStreamSocketChannel half-close allows outstanding writes to complete
  Sources/NIOPosix/BaseSocketChannel.swift
  Sources/NIOPosix/BaseStreamSocketChannel.swift
  Sources/NIOPosix/PendingDatagramWritesManager.swift
  Sources/NIOPosix/PendingWritesManager.swift
  Tests/NIOPosixTests/ChannelTests.swift
  Tests/NIOPosixTests/PendingDatagramWritesManagerTests.swift
  Tests/NIOPosixTests/StreamChannelsTest.swift
Labels: 🔨 semver/patch
