Repository apple/swift-nio, pull requests merged in 2025-06, with the labels that each got.

#3267 Add Xcode 26 beta 1 to macOS CI
  .github/workflows/macos_tests.yml
Labels: semver/none

#3263 Add `scheduleCallback` APIs to `NIOIsolatedEventLoop`
  Sources/NIOCore/EventLoop.swift
  Sources/NIOCore/EventLoopFuture+AssumeIsolated.swift
  Sources/NIOCore/NIOScheduledCallback.swift
  Tests/NIOPosixTests/NIOScheduledCallbackTests.swift
Labels: 🆕 semver/minor

#3270 Fixed issue with macOS CI when overrides are being used.
  .github/workflows/macos_tests.yml
Labels: semver/none

#3276 Fix API documentation links in README.md
  README.md
Labels: semver/none

#3277 Support for 64-bit timespec seconds on 32-bit platforms
  Sources/NIOConcurrencyHelpers/lock.swift
  Sources/NIOPosix/SelectorGeneric.swift
Labels: 🔨 semver/patch
