Repository apple/swift-nio, pull requests merged in 2025-01, with the labels that each got.

#3041 Print alloc-limits-from-test-output usage when no args
  dev/alloc-limits-from-test-output
Labels: semver/none

#3043 Support concurrency take over in 6.2
  Sources/NIOPosix/PosixSingletons+ConcurrencyTakeOver.swift
Labels: 🔨 semver/patch

#3034 Add Sendability annotations on SocketOptionProvider
  Sources/NIOCore/SocketOptionProvider.swift
  Sources/NIOPosix/BaseSocketChannel+SocketOptionProvider.swift
Labels: 🆕 semver/minor

#3050 unchecked Sendable for the Channels
  Sources/NIOPosix/BaseSocketChannel.swift
  Sources/NIOPosix/BaseStreamSocketChannel.swift
  Sources/NIOPosix/PipeChannel.swift
  Sources/NIOPosix/SocketChannel.swift
Labels: 🔨 semver/patch

#3053 Add channel initializer closure to NIOAsyncTestingChannel.init
  Sources/NIOEmbedded/AsyncTestingChannel.swift
  Tests/NIOEmbeddedTests/AsyncTestingChannelTests.swift
Labels: 🆕 semver/minor

#3055 Avoid abstraction overheads on isolated ELF
  IntegrationTests/tests_04_performance/Thresholds/5.10.json
  IntegrationTests/tests_04_performance/Thresholds/5.9.json
  IntegrationTests/tests_04_performance/Thresholds/6.0.json
  IntegrationTests/tests_04_performance/Thresholds/nightly-6.0.json
  IntegrationTests/tests_04_performance/Thresholds/nightly-main.json
  Sources/NIOCore/EventLoopFuture+AssumeIsolated.swift
  Sources/NIOCore/EventLoopFuture.swift
Labels: 🔨 semver/patch

#3058 Clarify docs on EventLoopFuture/assumeIsolatedUnsafeUnchecked
  Sources/NIOCore/EventLoopFuture+AssumeIsolated.swift
Labels: semver/none

#3057 Fix compiling on 6.1
  Package.swift
  Sources/NIOCore/EventLoop.swift
  Sources/NIOCore/FileRegion.swift
  Sources/NIOEmbedded/AsyncTestingEventLoop.swift
  Sources/NIOHTTP1/HTTPDecoder.swift
  Sources/NIOPosix/DatagramVectorReadManager.swift
  Sources/NIOPosix/PendingDatagramWritesManager.swift
  Sources/NIOPosix/SelectableEventLoop.swift
  Sources/NIOPosix/SelectorKqueue.swift
  Tests/NIOPosixTests/HappyEyeballsTest.swift
  Tests/NIOPosixTests/MulticastTest.swift
  Tests/NIOPosixTests/PendingDatagramWritesManagerTests.swift
Labels: 🆕 semver/minor

#3059 Remove unnecessary 'FIXME' comment
  Tests/NIOCoreTests/AsyncSequences/NIOAsyncWriterTests.swift
Labels: semver/none

#3051 Clean up sendability in the bootstraps
  IntegrationTests/tests_04_performance/Thresholds/5.10.json
  IntegrationTests/tests_04_performance/Thresholds/5.9.json
  IntegrationTests/tests_04_performance/Thresholds/6.0.json
  IntegrationTests/tests_04_performance/Thresholds/nightly-6.0.json
  IntegrationTests/tests_04_performance/Thresholds/nightly-main.json
  Sources/NIOPosix/Bootstrap.swift
  dev/malloc-aggregation.d
  dev/stackdiff-dtrace.py
Labels: 🔨 semver/patch

#3060 Add some trivial Sendable annotations
  Sources/NIOCore/ChannelOption.swift
  Sources/NIOPosix/BSDSocketAPICommon.swift
  Sources/NIOPosix/IntegerTypes.swift
Labels: 🆕 semver/minor

#3040 Fix WebSocketProtocolErrorHandler sending the close frame with appropriate masking key
  Sources/NIOWebSocket/NIOWebSocketClientUpgrader.swift
  Sources/NIOWebSocket/NIOWebSocketServerUpgrader.swift
  Sources/NIOWebSocket/WebSocketProtocolErrorHandler.swift
  Tests/NIOWebSocketTests/WebSocketClientEndToEndTests.swift
Labels: 🆕 semver/minor

#3048 feat: Add `String(contentsOf: FilePath ...)`
  Sources/NIOFileSystem/String+FileSystem.swift
  Tests/NIOFileSystemIntegrationTests/ConvenienceTests.swift
Labels: 🆕 semver/minor

#3046 feat: NIO.TimeAmount(string:) and TimeAmount.description
  .gitignore
  Sources/NIOCore/EventLoop.swift
  Tests/NIOCoreTests/TimeAmountTests.swift
Labels: 🆕 semver/minor

#3068 Add allocation counter tests for isolated EL operations
  IntegrationTests/tests_04_performance/Thresholds/5.10.json
  IntegrationTests/tests_04_performance/Thresholds/5.9.json
  IntegrationTests/tests_04_performance/Thresholds/6.0.json
  IntegrationTests/tests_04_performance/Thresholds/nightly-6.0.json
  IntegrationTests/tests_04_performance/Thresholds/nightly-main.json
  IntegrationTests/tests_04_performance/test_01_resources/test_assume_isolated_scheduling_10000_executions.swift
  IntegrationTests/tests_04_performance/test_01_resources/test_flat_schedule_10000_tasks.swift
  IntegrationTests/tests_04_performance/test_01_resources/test_flat_schedule_assume_isolated_10000_tasks.swift
  IntegrationTests/tests_04_performance/test_01_resources/test_schedule_assume_isolated_10000_tasks.swift
  IntegrationTests/tests_04_performance/test_01_resources/test_schedule_with_deadline_10000_tasks.swift
  IntegrationTests/tests_04_performance/test_01_resources/test_schedule_with_deadline_assume_isolated_10000_tasks.swift
  IntegrationTests/tests_04_performance/test_01_resources/test_submit_10000_tasks.swift
  IntegrationTests/tests_04_performance/test_01_resources/test_submit_assume_isolated_10000_tasks.swift
Labels: semver/none

#3069 Improve coverage of isolated views
  Tests/NIOPosixTests/EventLoopFutureIsolatedTests.swift
Labels: semver/none

#3070 Move Isolated EL operations to EL protocol
  IntegrationTests/tests_04_performance/Thresholds/5.10.json
  IntegrationTests/tests_04_performance/Thresholds/5.9.json
  IntegrationTests/tests_04_performance/Thresholds/6.0.json
  IntegrationTests/tests_04_performance/Thresholds/nightly-6.0.json
  IntegrationTests/tests_04_performance/Thresholds/nightly-main.json
  Sources/NIOCore/EventLoop.swift
  Sources/NIOCore/EventLoopFuture+AssumeIsolated.swift
Labels: 🔨 semver/patch

#3072 Ensure we test the isolated fallback methods
  Tests/NIOPosixTests/EventLoopFutureIsolatedTests.swift
Labels: semver/none

#3063 Improve HTTPHeaders description performance
  IntegrationTests/tests_01_http/test_07_headers_work.sh
  Sources/NIOHTTP1/HTTPTypes.swift
  Sources/NIOPerformanceTester/main.swift
  Tests/NIOHTTP1Tests/HTTPHeadersTest.swift
Labels: 🔨 semver/patch

#3073 Fast-path isolated view for EmbeddedEventLoop
  Sources/NIOEmbedded/Embedded.swift
Labels: 🔨 semver/patch

#3074 Enable optimized Isolated view path for AsyncTestingEL
  Sources/NIOEmbedded/AsyncTestingEventLoop.swift
Labels: 🔨 semver/patch

#3076 Update nightly CI pipelines to 6.1 instead of 6.0
  .github/workflows/unit_tests.yml
  scripts/generate_matrix.sh
Labels: 🔨 semver/patch

#3078 more 6.0 nightly to 6.1 nightly CI changes
  .github/workflows/benchmarks.yml
  .github/workflows/cxx_interop.yml
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  Benchmarks/Thresholds/nightly-6.1/NIOCoreBenchmarks.NIOAsyncChannel.init.p90.json
  Benchmarks/Thresholds/nightly-6.1/NIOPosixBenchmarks.TCPEcho.p90.json
  Benchmarks/Thresholds/nightly-6.1/NIOPosixBenchmarks.TCPEchoAsyncChannel.p90.json
  IntegrationTests/tests_04_performance/Thresholds/nightly-6.1.json
  scripts/check-matrix-job.ps1
  scripts/check-matrix-job.sh
Labels: semver/none

#3080 check-matrix-job.sh should tolerate unset 6.1 vars
  scripts/check-matrix-job.ps1
  scripts/check-matrix-job.sh
Labels: semver/none

#3079 Improve `flatScheduleTask`
  IntegrationTests/tests_04_performance/Thresholds/5.10.json
  IntegrationTests/tests_04_performance/Thresholds/5.9.json
  IntegrationTests/tests_04_performance/Thresholds/6.0.json
  IntegrationTests/tests_04_performance/Thresholds/nightly-6.1.json
  IntegrationTests/tests_04_performance/Thresholds/nightly-main.json
  Sources/NIOCore/EventLoop.swift
  Sources/NIOCore/EventLoopFuture+AssumeIsolated.swift
Labels: 🔨 semver/patch

#3062 Fix the HappyEyeballsResolver and core Bootstraps under strict concurrency
  Benchmarks/Thresholds/5.10/NIOPosixBenchmarks.TCPEcho.p90.json
  Benchmarks/Thresholds/5.9/NIOPosixBenchmarks.TCPEcho.p90.json
  Benchmarks/Thresholds/6.0/NIOPosixBenchmarks.TCPEcho.p90.json
  Benchmarks/Thresholds/nightly-6.1/NIOPosixBenchmarks.TCPEcho.p90.json
  Benchmarks/Thresholds/nightly-main/NIOPosixBenchmarks.TCPEcho.p90.json
  Sources/NIOPosix/Bootstrap.swift
  Sources/NIOPosix/GetaddrinfoResolver.swift
  Sources/NIOPosix/HappyEyeballs.swift
  Tests/NIOPosixTests/HappyEyeballsTest.swift
Labels: 🆕 semver/minor

#3081 Clean up Sendability in Thread and ThreadPool
  Sources/NIOPosix/LinuxCPUSet.swift
  Sources/NIOPosix/NIOThreadPool.swift
  Sources/NIOPosix/Thread.swift
  Sources/NIOPosix/ThreadPosix.swift
Labels: 🆕 semver/minor

#3082 Make NonBlockingFileIO strict-concurrency clean
  Sources/NIOPosix/NonBlockingFileIO.swift
Labels: 🆕 semver/minor

#3083 Sendability clean up for RawSocketBootstrap
  Sources/NIOPosix/RawSocketBootstrap.swift
Labels: 🔨 semver/patch

#3084 Strict concurrency for SelectableEventLoop & MTELG
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
  Sources/NIOPosix/SelectableEventLoop.swift
Labels: 🔨 semver/patch

#3085 Add Sendable annotations to SelectorGeneric
  Sources/NIOPosix/SelectorGeneric.swift
Labels: 🔨 semver/patch

#3086 Remove accidental static var
  Sources/NIOPosix/Socket.swift
Labels: 🔨 semver/patch

#3088 Add simple Sendable conformance to AsyncSequenceFromIterator
  Sources/NIOCore/AsyncAwaitSupport.swift
Labels: 🔨 semver/patch

#3087 Add Sendable annotations to the syscall wrappers
  Sources/NIOPosix/System.swift
Labels: 🔨 semver/patch

#3089 Avoid using stderr explicitly
  Sources/NIOPosix/SelectableEventLoop.swift
Labels: 🔨 semver/patch

#3090 Make NIOPosix strict-concurrency clean
  Package.swift
  Sources/NIOPosix/GetaddrinfoResolver.swift
  Sources/NIOPosix/SelectableEventLoop.swift
Labels: 🔨 semver/patch

#3067 `NIOFileSystem`: Try ${TMPDIR} first for temporary directory
  Sources/NIOFileSystem/FileSystem.swift
  Tests/NIOFileSystemIntegrationTests/FileSystemTests.swift
Labels: 🔨 semver/patch

#3092 undo Xcode 13 GM workaround
  Sources/NIOCore/ByteBuffer-core.swift
Labels: 🔨 semver/patch

#3094 Update the legacy CI matrix for 6.1 nightly
  .github/workflows/swift_matrix.yml
Labels: semver/none
