Repository apple/swift-nio, pull requests merged in 2025-03, with the labels that each got.

#3122 Update re-usable workflows to use nightly_next
  .github/workflows/benchmarks.yml
  .github/workflows/cxx_interop.yml
  .github/workflows/unit_tests.yml
Labels: semver/none

#3125 Populate CI env var in swift_test_matrix.yml
  .github/workflows/swift_test_matrix.yml
Labels: semver/none

#3128 NIOSingletons docs: Clarify the set once-ness
  Sources/NIOCore/GlobalSingletons.swift
Labels: semver/none

#3129 Remove side effect from assertion in IPHeaderRemoverHandler
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
Labels: semver/none

#3132 Enable strict concurrency checking for NIOHTTP1Server
  Package.swift
  Sources/NIOHTTP1Client/main.swift
  Sources/NIOHTTP1Server/main.swift
Labels: 🔨 semver/patch

#3131 Enable strict concurrency checking for NIOHTTP1Client
  Package.swift
Labels: 🔨 semver/patch

#3127 Enable strict concurrency checking for NIOWebSocket
  Package.swift
  Sources/NIOWebSocket/NIOWebSocketClientUpgrader.swift
  Sources/NIOWebSocket/NIOWebSocketServerUpgrader.swift
  Sources/NIOWebSocket/WebSocketOpcode.swift
Labels: 🆕 semver/minor

#3130 Enable strict concurrency checking for NIOTestUtils
  Package.swift
  Sources/NIOTestUtils/NIOHTTP1TestServer.swift
Labels: 🔨 semver/patch

#3133 Delete Thresholds/nightly-6.1 symlinks
  Benchmarks/Thresholds/nightly-6.1
  IntegrationTests/tests_04_performance/Thresholds/nightly-6.1.json
Labels: semver/none

#3134 Only apply standard swift settings on valid targets
  Package.swift
Labels: semver/none

#3019 A re-usable static SDK compilation workflow
  .github/workflows/main.yml
  .github/workflows/static_sdk.yml
  .github/workflows/swift_load_test_matrix.yml
  .github/workflows/swift_test_matrix.yml
  scripts/install_static_sdk.sh
Labels: semver/none

#3137 Downgrade NIOHTTP1TestServer handleChannel failure
  Sources/NIOTestUtils/NIOHTTP1TestServer.swift
Labels: 🔨 semver/patch

#3140 Add a missing import to CNIOLinux
  Tests/NIOPosixTests/ChannelPipelineTest.swift
Labels: semver/none

#3141 Experimental macOS CI
  .github/workflows/macos_tests.yml
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#3143 Remove macOS CI shim
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#3142 Make static SDK curl for setup script
  .github/workflows/pull_request.yml
  .github/workflows/static_sdk.yml
  .github/workflows/swift_test_matrix.yml
  scripts/install_static_sdk.sh
Labels: semver/none

#3145 install jq, use correct quotes
  .github/workflows/cmake_tests.yml
Labels: semver/none

#3150 Update macOS CI workflow
  .github/workflows/macos_tests.yml
  .github/workflows/main.yml
Labels: semver/none

#3153 always @preconcurrency import Glibc/Musl/Android/Bionic/WASILibc
  Sources/NIOConcurrencyHelpers/NIOLock.swift
  Sources/NIOConcurrencyHelpers/atomics.swift
  Sources/NIOConcurrencyHelpers/lock.swift
  Sources/NIOCore/BSDSocketAPI.swift
  Sources/NIOCore/ByteBuffer-core.swift
  Sources/NIOCore/EventLoop.swift
  Sources/NIOCore/FileHandle.swift
  Sources/NIOCore/FileRegion.swift
  Sources/NIOCore/GlobalSingletons.swift
  Sources/NIOCore/IO.swift
  Sources/NIOCore/Interfaces.swift
  Sources/NIOCore/SocketAddresses.swift
  Sources/NIOCore/SocketOptionProvider.swift
  Sources/NIOCore/SystemCallHelpers.swift
  Sources/NIOCore/Utilities.swift
  Sources/NIOEmbedded/Embedded.swift
  Sources/NIOFileSystem/FileInfo.swift
  Sources/NIOFileSystem/FileSystem.swift
  Sources/NIOFileSystem/FileSystemError+Syscall.swift
  Sources/NIOFileSystem/FileType.swift
  Sources/NIOFileSystem/Internal/System Calls/CInterop.swift
  Sources/NIOFileSystem/Internal/System Calls/Errno.swift
  Sources/NIOFileSystem/Internal/System Calls/FileDescriptor+Syscalls.swift
  Sources/NIOFileSystem/Internal/System Calls/Mocking.swift
  Sources/NIOFileSystem/Internal/System Calls/Syscall.swift
  Sources/NIOFileSystem/Internal/System Calls/Syscalls.swift
  Sources/NIOFileSystem/Internal/SystemFileHandle.swift
  Sources/NIOPosix/System.swift
  Sources/NIOPosix/VsockAddress.swift
  Sources/_NIODataStructures/Heap.swift
Labels: 🔨 semver/patch

#3151 A script for updating benchmark thresholds from CI output
  dev/thresholds-from-benchmark-output.sh
Labels: semver/none

#3121 Changed NIOAsyncChannel.executeThenClose to accept actor-isolated par…
  Sources/NIOCore/AsyncChannel/AsyncChannel.swift
  Tests/NIOCoreTests/AsyncChannel/AsyncChannelTests.swift
Labels: 🆕 semver/minor

#3156 fix: Fix NIOCore build for wasm targets
  Sources/NIOCore/FileHandle.swift
Labels: 🔨 semver/patch

#3157 Add peekInteger API to ByteBuffer
  Sources/NIOCore/ByteBuffer-int.swift
  Tests/NIOCoreTests/ByteBufferTest.swift
Labels: 🆕 semver/minor

#3155 Use overflow addition in tests to avoid compilation failures
  Tests/NIOPosixTests/NonBlockingFileIOTest.swift
Labels: semver/none

#3160 Add Peek API variants for ByteBuffer
  Sources/NIOCore/ByteBuffer-aux.swift
  Tests/NIOCoreTests/ByteBufferTest.swift
Labels: 🆕 semver/minor

#3162 Separate build and test steps in `macos_tests.yml`
  .github/workflows/macos_tests.yml
Labels: semver/none
