Repository apple/swift-nio, pull requests merged in 2025-08, with the labels that each got.

#3330 Don't double-initialize Pipe Bootstraps
  Sources/NIOPosix/Bootstrap.swift
  Tests/NIOPosixTests/BootstrapTest.swift
Labels: 🔨 semver/patch

#3308 Support options on AsyncTestingChannel and EmbeddedChannel
  Sources/NIOEmbedded/AsyncTestingChannel.swift
  Sources/NIOEmbedded/Embedded.swift
  Tests/NIOEmbeddedTests/AsyncTestingChannelTests.swift
  Tests/NIOEmbeddedTests/EmbeddedChannelTest.swift
Labels: 🆕 semver/minor

#3337 [Windows] Ensure ssize_t and socklen_t are available
  Sources/CNIOWindows/include/CNIOWindows.h
  Sources/NIOPosix/NonBlockingFileIO.swift
  Sources/NIOPosix/PipePair.swift
  Sources/NIOPosix/SocketProtocols.swift
Labels: 🔨 semver/patch

#3336 [Windows] Add msghdr extension for Windows
  Sources/NIOPosix/BSDSocketAPIPosix.swift
  Sources/NIOPosix/BSDSocketAPIWindows.swift
  Sources/NIOPosix/DatagramVectorReadManager.swift
  Sources/NIOPosix/PendingDatagramWritesManager.swift
  Sources/NIOPosix/Socket.swift
  Tests/NIOPosixTests/ChannelTests.swift
  Tests/NIOPosixTests/SystemTest.swift
Labels: 🔨 semver/patch

#3333 Update FilePath references to NIOFilePath
  Snippets/NIOFileSystemTour.swift
  Sources/NIOFileSystem/Array+FileSystem.swift
  Sources/NIOFileSystem/ArraySlice+FileSystem.swift
  Sources/NIOFileSystem/ByteBuffer+FileSystem.swift
  Sources/NIOFileSystem/Convenience.swift
  Sources/NIOFileSystem/DirectoryEntry.swift
  Sources/NIOFileSystem/Docs.docc/Extensions/DirectoryFileHandleProtocol.md
  Sources/NIOFileSystem/Docs.docc/Extensions/FileSystemProtocol.md
  Sources/NIOFileSystem/FileHandle.swift
  Sources/NIOFileSystem/FileHandleProtocol.swift
  Sources/NIOFileSystem/FileSystem.swift
  Sources/NIOFileSystem/FileSystemProtocol+FilePath.swift
  Sources/NIOFileSystem/FileSystemProtocol.swift
  Sources/NIOFileSystem/Internal/SystemFileHandle.swift
  Sources/NIOFileSystem/OpenOptions.swift
  Sources/NIOFileSystem/String+FileSystem.swift
  Sources/NIOFileSystemFoundationCompat/Data+FileSystem.swift
  Tests/NIOFileSystemFoundationCompatTests/FileSystemFoundationCompatTests.swift
  Tests/NIOFileSystemIntegrationTests/FileHandleTests.swift
  Tests/NIOFileSystemIntegrationTests/FileSystemTests.swift
Labels: ⚠️ semver/major

#3338 [Windows] Ensure NIOHTTP1 compiles
  Sources/NIOHTTP1/HTTPDecoder.swift
Labels: 🔨 semver/patch

#3339 Drop all server response parts after an invalid header
  Sources/NIOHTTP1/HTTPHeaderValidator.swift
  Tests/NIOHTTP1Tests/HTTPHeaderValidationTests.swift
Labels: 🔨 semver/patch

#3344 [Windows] Make SelectableEventLoop compile
  Sources/CNIOWindows/include/CNIOWindows.h
  Sources/CNIOWindows/shim.c
  Sources/NIOPosix/Windows.swift
Labels: 🔨 semver/patch

#3345 [Windows] Fix deprecation warnings in NIOCore
  Sources/NIOCore/GlobalSingletons.swift
  Sources/NIOCore/IO.swift
  Sources/NIOCore/SystemCallHelpers.swift
  Sources/NIOCore/Utilities.swift
Labels: 🔨 semver/patch

#3351 [Windows] Fix getenv warnings in NIOPosix and NIOEmbedded
  Sources/NIOCore/Utilities.swift
  Sources/NIOEmbedded/Embedded.swift
  Sources/NIOPosix/SelectableEventLoop.swift
Labels: 🔨 semver/patch

#3352 [Windows] `dup` is deprecated on Windows, use `_dup` instead
  Sources/NIOPosix/System.swift
Labels: 🔨 semver/patch

#3353 [Windows] Add shims to make string from `GetLastError` using `FormatMessage`
  Sources/CNIOWindows/include/CNIOWindows.h
  Sources/CNIOWindows/shim.c
  Sources/NIOPosix/Windows.swift
Labels: 🔨 semver/patch

#3355 Use path based deps in the alloc counter framework
  IntegrationTests/allocation-counter-tests-framework/run-allocation-counter.sh
  IntegrationTests/allocation-counter-tests-framework/template/HookedFunctionsDoHook/Package.swift
  IntegrationTests/allocation-counter-tests-framework/template/HookedFunctionsDoNotHook/Package.swift
Labels: semver/none

#3356 [Windows] Allow `_SelectorBackendProtocol` to work with Windows Handles
  Sources/NIOPosix/SelectorGeneric.swift
Labels: 🔨 semver/patch

#3357 [Windows] Use recv instead of read
  Sources/NIOPosix/BSDSocketAPIWindows.swift
  Sources/NIOPosix/Socket.swift
  Sources/NIOPosix/Windows.swift
Labels: 🔨 semver/patch

#3358 [Windows] Disable Pipelines for now (fatalError)
  Sources/NIOPosix/Bootstrap.swift
  Sources/NIOPosix/PipePair.swift
  Sources/NIOPosix/Windows.swift
Labels: 🔨 semver/patch
