Repository apple/swift-nio, pull requests merged in 2025-07, with the labels that each got.

#3283 Functions that return values should return those values
  Sources/CNIOLinux/shim.c
Labels: 🔨 semver/patch

#3285 Make use of symlink to latest Xcode beta
  .github/workflows/macos_tests.yml
Labels: semver/none

#3287 Add diffing to the stackdiff tool
  dev/stackdiff/Sources/stackdiff/StackFormatter.swift
  dev/stackdiff/Sources/stackdiff/Stackdiff+Diff.swift
  dev/stackdiff/Sources/stackdiff/Stackdiff.swift
Labels: semver/none

#3293 Add DocC docs for running alloc tests and debugging them
  README.md
  Sources/NIO/Docs.docc/Articles/Debugging Allocation Regressions.md
  Sources/NIO/Docs.docc/Articles/Running Alloction Counting Tests.md
  Sources/NIO/Docs.docc/index.md
Labels: semver/none

#3113 Add bpftrace allocations script
  .licenseignore
  dev/malloc-aggregation.bt
  docs/debugging-allocations.md
Labels: semver/none

#3298 Run update_and_patch_llhttp.sh script to update to 9.3.0
  Sources/CNIOLLHTTP/c_nio_llhttp.c
  Sources/CNIOLLHTTP/include/c_nio_llhttp.h
Labels: 🔨 semver/patch

#3299 ensure <stddef.h> is not imported within extern "C"
  Sources/CNIOLLHTTP/include/c_nio_llhttp.h
  Sources/CNIOLLHTTP/update_and_patch_llhttp.sh
Labels: 🔨 semver/patch

#3301 inEventLoop benchmark
  Sources/NIOPerformanceTester/TCPThroughputBenchmark.swift
  Sources/NIOPerformanceTester/main.swift
Labels: semver/none

#3302 improve inEventLoop checks
  Package.swift
  Sources/CNIOPosix/event_loop_id.c
  Sources/CNIOPosix/include/CNIOPosix.h
  Sources/NIOCore/ByteBuffer-int.swift
  Sources/NIOFileSystem/ByteCount.swift
  Sources/NIOPosix/IntegerBitPacking.swift
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
  Sources/NIOPosix/SelectableEventLoop.swift
  Sources/NIOWebSocket/WebSocketFrameEncoder.swift
  Tests/NIOCoreTests/ByteBufferTest.swift
  Tests/NIOPosixTests/EventLoopTest.swift
Labels: 🔨 semver/patch

#3303 Wrap closures stored in the CallbackList
  IntegrationTests/tests_04_performance/Thresholds/5.10.json
  IntegrationTests/tests_04_performance/Thresholds/6.0.json
  IntegrationTests/tests_04_performance/Thresholds/6.1.json
  IntegrationTests/tests_04_performance/Thresholds/nightly-main.json
  IntegrationTests/tests_04_performance/Thresholds/nightly-next.json
  Sources/NIOCore/EventLoopFuture.swift
  docs/workarounds.md
Labels: 🔨 semver/patch

#3296 Structured Concurrency compliant MTELG create/shutdown
  NOTICE.txt
  Sources/NIOPosix/MultiThreadedEventLoopGroup.swift
  Sources/NIOPosix/StructuredConcurrencyHelpers.swift
  Tests/NIOPosixTests/EventLoopTest.swift
Labels: 🆕 semver/minor

#3307 Pick visionOS version for Xcode 16.2
  .github/workflows/macos_tests.yml
Labels: semver/none

#3309 Call channel initializer when using async methods on pipe bootstrap
  Sources/NIOPosix/Bootstrap.swift
  Tests/NIOPosixTests/AsyncChannelBootstrapTests.swift
Labels: 🔨 semver/patch

#3310 Remove Foundation import
  Package.swift
Labels: 🔨 semver/patch

#3311 Fixes a small mistake in the NIOTCPEchoServer README file
  Sources/NIOTCPEchoServer/README.md
Labels: semver/none

#3314 CMake Updater: Output difference in expectations
  scripts/update-cmake-lists.sh
Labels: semver/none

#3315 Fix docc
  Sources/NIOPosix/Bootstrap.swift
Labels: semver/none

#3319 [Windows] Ensure NIOEmbedded compiles
  Sources/NIOEmbedded/Embedded.swift
Labels: 🔨 semver/patch

#3321 Enable release mode builds for pull requests
  .github/workflows/release_builds.yml
Labels: semver/none

#3325 Do not run windows nightly CI by default
  .github/workflows/release_builds.yml
  .github/workflows/unit_tests.yml
Labels: semver/none
