Repository apple/swift-nio, pull requests merged in 2025-02, with the labels that each got.

#3095 Opt _NIOConcurrency into Strict Concurrency
  Package.swift
Labels: semver/none

#3096 Opt NIOFoundationCompat into strict concurrency
  Package.swift
Labels: semver/none

#3099 Clean up concurrency in NIOEchoClient
  Package.swift
  Sources/NIOEchoClient/main.swift
Labels: semver/none

#3101 Add strict concurrency to NIOUDPEchoServer
  Package.swift
  Sources/NIOUDPEchoServer/main.swift
Labels: semver/none

#3100 Lock in strict concurrency in NIOEchoServer
  Package.swift
Labels: semver/none

#3102 Update NIOUDPEchoClient for strict concurrency
  Package.swift
  Sources/NIOUDPEchoClient/main.swift
Labels: semver/none

#3104 Strict concurrency for the chat examples
  Package.swift
  Sources/NIOChatClient/main.swift
  Sources/NIOMulticastChat/main.swift
Labels: semver/none

#3105 Strict concurrency enablement for some test targets
  Package.swift
Labels: semver/none

#3098 Make _NIOFileSystem strict concurrency compatible
  Package.swift
  Sources/NIOCore/AsyncSequences/NIOAsyncSequenceProducer.swift
  Sources/NIOFileSystem/DirectoryEntries.swift
  Sources/NIOFileSystem/Internal/BufferedOrAnyStream.swift
  Sources/NIOFileSystem/Internal/BufferedStream.swift
Labels: 🆕 semver/minor

#3065 Add ChannelPipeline.SynchronousOperations.Position
  Sources/NIOCore/ChannelPipeline.swift
  Sources/NIOHTTP1/HTTPPipelineSetup.swift
  Tests/NIOPosixTests/ChannelPipelineTest.swift
Labels: 🆕 semver/minor

#3107 Make the FileSystem world strict concurrency clean
  Package.swift
  Tests/NIOFileSystemIntegrationTests/FileSystemTests.swift
Labels: semver/none

#3108 document known Structured Concurrency violations
  Sources/NIOCore/AsyncAwaitSupport.swift
Labels: semver/none

#3112 Enable strict concurrency checking for NIOTLS
  Package.swift
  Sources/NIOTLS/NIOTypedApplicationProtocolNegotiationHandler.swift
Labels: 🔨 semver/patch

#3117 Add more methods to work with Isolated futures
  Sources/NIOCore/EventLoop.swift
  Sources/NIOCore/EventLoopFuture+AssumeIsolated.swift
  Sources/NIOCore/EventLoopFuture.swift
  Tests/NIOPosixTests/EventLoopFutureIsolatedTests.swift
  Tests/NIOPosixTests/EventLoopFutureTest.swift
Labels: 🆕 semver/minor

#3118 Simplify Windows matrix command invocation
  .github/workflows/swift_test_matrix.yml
Labels: semver/none

#3116 Make isolated execute on async testing eventloop actually run
  Sources/NIOEmbedded/AsyncTestingEventLoop.swift
  Tests/NIOPosixTests/EventLoopFutureIsolatedTests.swift
Labels: 🔨 semver/patch

#3115 Enable strict concurrency checking for NIOHTTP1
  Package.swift
  Sources/NIOHTTP1/HTTPPipelineSetup.swift
  Sources/NIOHTTP1/HTTPServerUpgradeHandler.swift
  Sources/NIOHTTP1/HTTPTypedPipelineSetup.swift
  Sources/NIOHTTP1/NIOHTTPClientUpgradeHandler.swift
  Sources/NIOHTTP1/NIOTypedHTTPClientUpgradeHandler.swift
  Sources/NIOHTTP1/NIOTypedHTTPServerUpgradeHandler.swift
  Sources/NIOHTTP1/NIOTypedHTTPServerUpgraderStateMachine.swift
  Tests/NIOHTTP1Tests/HTTPClientUpgradeTests.swift
  Tests/NIOWebSocketTests/WebSocketClientEndToEndTests.swift
Labels: 🆕 semver/minor

#3119 Equatable SocketAddressError
  Sources/NIOCore/SocketAddresses.swift
Labels: 🆕 semver/minor

#3120 Update generate matrix stript to use nightly_next
  scripts/generate_matrix.sh
Labels: semver/none

#3123 Expose GITHUB_ACTIONS env var to docker containers
  .github/workflows/swift_test_matrix.yml
Labels: semver/none
